### ISSUE TITLE
ACTIVATION_REQUIRED while testing composer networks

### ISSUE THREAD

**Issue by abhi201191** [hyperledger/caliper#101]
While testing composer basic-sample-network, getting this error at peer:
[mychannel][aa9c533b] failed to invoke chaincode name:"basic-sample-network" , error: transaction returned with failure: Error: The current identity, with the name 'admin' and the identifier '01899e04161a3a6d64670504fa122e55818295352929b6a616333a3739fde3f2', must be activated (ACTIVATION_REQUIRED)

**Comment by ski2per** [comment]
I have the same issue when running composer test

**Comment by haojun** [comment]
@nklincoln Do you have any suggestions for this issue?

**Comment by vyalla** [comment]
I am also getting the similar error while running "composer network ping ...".
Composer version: 0.19.13
Fabric version: 1.2
Node version: 8.11.3

**Comment by panyu4** [comment]
@vyalla , it looks you should use fabric 1.1.0
