### ISSUE TITLE
Negative send rate can be observed in reports

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#1044]
In some instances it is possible to observe a negative send rate in the reports.

This appears to occur in short round durations, and a quick set of logging in the report generation side (within getResultValues) reveals that there may be any issue in the txUpdate phase, since:

```
results.getFirstCreateTime() 1602161955354
results.getLastCreateTime()  1602161954519
```

At no point should the last create time be less than the first create time.

**Comment by aklenik** [comment]
I think this is the problem:
https://github.com/hyperledger/caliper/blob/363a6ddf34f084dbd9a54cdc08e21413d521f843/packages/caliper-core/lib/common/core/transaction-statistics-collector.js#L330-L334
`firstCreateTime` is calculated from `firstFinishTime` during stat merge 😅

**Comment by nklincoln** [comment]
confirmed above, by locally fixing code and re-running
