### ISSUE TITLE
Is it possible to run Caliper on Windows 10?

### ISSUE THREAD

**Issue by jamievaravara** [hyperledger/caliper#108]
The question is the same as the title.

Is it possible to run Caliper on Windows 10?

**Comment by haojun** [comment]
Never tried it. But i think it's possible if all dependencies can be installed successfully.

**Comment by bitpeng** [comment]
@haojun, I work hard to try to run caliper on my MacBook Pro but unfortunately failed. It's wise to seek help, is it possible to run caliper on MacBook and which Linux distributions they are written in？thanks！
