### ISSUE TITLE
How to add an organization in hyperledger caliper?

### ISSUE THREAD

**Issue by s1119858711** [hyperledger/caliper#1084]
Hello.EveryOne.

I had sucessfully run caliper-benchmark/../config_solo.
So,it show follow:

| Name     | Succ | Fail | Send Rate (TPS) | Max Latency (s) | Min Latency (s) | Avg Latency (s) | Throughput (TPS) |

|----------|------|------|-----------------|-----------------|-----------------|-----------------|------------------|

| open     | 1000 | 0    | 30.5            | 1.68            | 0.25            | 0.63            | 30.2             |

|----------|------|------|-----------------|-----------------|-----------------|-----------------|------------------|

| query    | 1000 | 0    | 100.3           | 0.06            | 0.01            | 0.01            | 100.1            |

|----------|------|------|-----------------|-----------------|-----------------|-----------------|------------------|

| transfer | 50   | 0    | 5.3             | 0.31            | 0.09            | 0.20            | 5.2              |

+----------+------+------+-----------------+-----------------+-----------------+-----------------+------------------+

Yeah,But I want to add an orgnazaition to it.(with 2 peers like others)

How could I do ?

Thank you very much

**Comment by nklincoln** [comment]
This appears to be a question on network configuration, if so (and the samples hosted in https://github.com/hyperledger/caliper-benchmarks/ are not sufficient) then the best source of information here would be a direct Hyperledger Fabric resource.

I would direct you to:
- https://hyperledger-fabric.readthedocs.io/en/latest/tutorials.html
- https://chat.hyperledger.org/channel/fabric-questions

**Comment by s1119858711** [comment]
Yeah　Thank you.
I'm going to learn as you said.
