### ISSUE TITLE
I have a question. the result of caliper test in multiple machines and single machine are same

### ISSUE THREAD

**Issue by hehui0316** [hyperledger/caliper#1096]
multiple machines
two machines node1: peer0org1 peer1org1 1 orderer
                       node2: peer0org2 peer1org2
 single machine peer0org1 peer1org1 peer0org2 peer1org2 1 orderer

**Comment by nklincoln** [comment]
what benchmark did you run?

For general questions, please use the Rocket chat forum: https://chat.hyperledger.org/channel/caliper

GitHub issues are for tracking bugs and enhancements
