### ISSUE TITLE
Improve caliper to support long time testing

### ISSUE THREAD

**Issue by haojun** [hyperledger/caliper#110]
Now txns statuses are stored in internal arrays and exchanged between processes via messages or zookeeper. Some people may want to start a long time testing such as testing 24 hours with a sending rate of 10000 tps. That may cause performance issues for caliper itself. So the mechanism of txns statuses storing and exchanging should be improved to meet the needs of long timing testing.

**Comment by nklincoln** [comment]
closing due to:
- ability to use Prometheus as a txn store
- no longer building an array of Promises to wait on
