### ISSUE TITLE
How to pass the "value" argument/parameter of a payable function of a contract for Ethereum Caliper test?

### ISSUE THREAD

**Issue by nachikettapas** [hyperledger/caliper#1106]
I have a payable function for which I am trying to write a benchmark test. I am not sure as to how to pass the value parameter. For example:
````
instance.deposit(myData, {value: 100, from: myAccount});
````
I have the following code which verifies the value passed in the call.
````
function announce(...) public payable
{
        ...       
        //Check if the commitment parameter matches the commitment sent to the contract.
        require(msg.value == _commitment, "The announcement didn't receive the commitment.");
       ...
}
````
How do I write a test case for this? I am trying to extend the simple contract example to generate test parameters.
https://github.com/hyperledger/caliper-benchmarks/tree/master/benchmarks/scenario/simple

**Comment by nklincoln** [comment]
closed by #1122
