### ISSUE TITLE
Some of the documentation for 0.4.2 are out of date in the code examples

### ISSUE THREAD

**Issue by RosieMurphy0** [hyperledger/caliper#1107]
Some the code blocks in the 0.4.2 version are out of date and still showing code that is relevant to previous versions and won't work for 0.4.2. The explanations around the code blocks have been updated with the latest changes but code blocks need to be updated to. 

Notably in https://hyperledger.github.io/caliper/v0.4.2/bench-config/ the example code block is out of date.

**Comment by jsoni3** [comment]
Is there an estimated timeframe on when the documentation will be updated? I am kinda stuck at a standstill for setting up and testing out the Hyperledger Caliper-CLI.

**Comment by davidkel** [comment]
The code block in bench-config has now been updated
