### ISSUE TITLE
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: EOF

### ISSUE THREAD

**Issue by EG-easy** [hyperledger/caliper#112]
Hi!
After creating channel, i have some problem...
How can I solve this problem?

$ node benchmark/simple/main.js
TAP version 13
# #######Caliper Test######
docker-compose -f network/fabric-v11/2-org-2-peer/docker-compose.yaml up -d
Creating orderer.example.com            ... done
Creating couchdb.peer0.org1.example.com ... done
Creating ca.org1.example.com            ... done
Creating couchdb.peer0.org2.example.com ... done
Creating ca.org2.example.com            ... done
Creating couchdb.peer1.org1.example.com ... done
Creating couchdb.peer1.org2.example.com ... done
Creating peer0.org1.example.com         ... done
Creating peer0.org2.example.com         ... done
Creating peer1.org2.example.com         ... done
Creating peer1.org1.example.com         ... done
# create mychannel......
ok 1 created mychannel successfully
# Sleep 5s......
# Join channel......
# join mychannel
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: EOF
    at new createStatusError (/Users/shizuka/caliper2/caliper/node_modules/grpc/src/client.js:64:15)
    at /Users/shizuka/caliper2/caliper/node_modules/grpc/src/client.js:583:15
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: EOF
    at new createStatusError (/Users/shizuka/caliper2/caliper/node_modules/grpc/src/client.js:64:15)
    at /Users/shizuka/caliper2/caliper/node_modules/grpc/src/client.js:583:15
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: EOF
    at new createStatusError (/Users/shizuka/caliper2/caliper/node_modules/grpc/src/client.js:64:15)
    at /Users/shizuka/caliper2/caliper/node_modules/grpc/src/client.js:583:15
not ok 2 TypeError: Cannot read property 'stack' of undefined
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [TypeError: Cannot read property 'stack' of undefined]
    at: process.onetime (/Users/shizuka/caliper2/caliper/node_modules/tape-promise/node_modules/onetime/index.js:22:12)
    stack: |-
      TypeError: Cannot read property 'stack' of undefined
          at channels.reduce.then.catch (/Users/shizuka/caliper2/caliper/src/fabric/join-channel.js:216:56)
          at <anonymous>
  ...

1..2
# tests 2
# pass  1
# fail  1

**Comment by aklenik** [comment]
@EG-easy In my experience, this kind of error originates from a CouchDB access error. Based on your logs, you start the entire network (quite a number of containers) on a single machine. 

This results in scarce resources for the containers, and connection failures between a peer and its CouchDB instance. Try to look at a peer and CouchDB container log to see the exact cause. 

Try a smaller network (1 peer per org), or a "stronger" (virtual)machine, or distribute your network on different machines.

**Comment by EG-easy** [comment]
Thnak you!!
i solved this problem as below after all.

1. docker-compose -f network/fabric-v11/2-org-2-peer/docker-compose.yaml up -d in another shell
2. remove "start": "docker-compose -f network/fabric-v11/2-org-2-peer/docker-compose.yaml up -d", from config.json 
3. node benchmark/simple/main.js

**Comment by ArvonHuang** [comment]
I change my linux user to root and it works, I don't know why.
