### ISSUE TITLE
The record-rate controller in documentation's samples doesn't work.

### ISSUE THREAD

**Issue by chasecheese** [hyperledger/caliper#1131]
Try to use record-rate in Caliper v0.4.2 testing fabric, but get errors.
## Context

I wrote the config according to the samples in doc, but it doesn't work. I'm testing fabric using caliperv0.4.2
## Actual Behavior

I get errors:

## Possible Fix

Would you please update the part of doc? How to use record-rate and replay-rate in v0.4.2.
## Steps to Reproduce

1. wrote the benchmarkconfig.yaml
```
test:
    name: basic-contract-benchmark
    description: test benchmark
    workers:
      type: local
      number: 4
    rounds:
      - label: 50TpsAsset
        description: Read asset benchmark
        txDuration: 10

        rateControl: {
          "type": "record-rate",
          "opts": {
            "rateController": {
              "type": "fixed-rate",
              "opts": {"tps" : 100}
            },
            "pathTemplate": "../tx_records_client<C>_round<R>.txt",
            "outputFormat": "TEXT",
            "logEnd": true
          }
        }
        workload:
          module: workload/readAsset.js
          arguments:
            assets: 10
            contractId: basic
```
2.run caliper `npx caliper launch manager  --caliper-workspace ./ --caliper-networkconfig ./networks/networkConfig.yaml --caliper-benchconfig ./benchmarks/benchmarkconfig.yaml --caliper-flow-only-test --caliper-fabric-gateway-enabled`
3.get error:
![image](https://user-images.githubusercontent.com/51473567/112867889-024aba00-90ee-11eb-912b-368d0636fd56.png)
## Your Environment

* Version used: Caliper v0.4.2(installed via npm) fabirc2.0.0
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version : Ubuntu20.04/16.04 amd64

**Comment by davidkel** [comment]
This looks like a bug in the RecordRate implementation, specifically this line in the constructor
```
        this.rateController = new RateControl(testMessage, stats, workerIndex,);
```
It's passing back the original test message where as it should be creating a new TestMessage instance based on `this.options.rateController`
