### ISSUE TITLE
Error: Benchmark failed with error code 5 at Function.handler

### ISSUE THREAD

**Issue by OierAM** [hyperledger/caliper#1133]
2021.04.15-10:15:00.032 info  [caliper] [cli-launch-master]     Set workspace path: /home/oamezua/Caliper/caliper-benchmarks
2021.04.15-10:15:00.033 info  [caliper] [cli-launch-master]     Set benchmark configuration path: /home/oamezua/Caliper/caliper-benchmarks/benchmarks/scenario/simple/config.yaml
2021.04.15-10:15:00.033 info  [caliper] [cli-launch-master]     Set network configuration path: /home/oamezua/Caliper/caliper-benchmarks/networks/fabric/fabric-v1.4.0/2org1peergoleveldb/fabric-go.yaml
2021.04.15-10:15:00.033 info  [caliper] [cli-launch-master]     Set SUT type: fabric
2021.04.15-10:15:00.035 info  [caliper] [benchmark-validator]   No observer specified, will default to `none`
2021.04.15-10:15:00.035 info  [caliper] [caliper-engine]        Starting benchmark flow
2021.04.15-10:15:00.037 info  [caliper] [adapters/fabric]       Initializing standard adaptor compatible with installed SDK: 2.2.5
2021.04.15-10:15:00.343 info  [caliper] [caliper-utils]         Executing command: cd .; export FABRIC_VERSION=1.4.0;export FABRIC_CA_VERSION=1.4.0;docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb/docker-compose.yaml up -d;sleep 3s
Creating network "2org1peergoleveldb_default" with the default driver
Creating orderer.example.com ... 
Creating ca.org2.example.com ... 
Creating ca.org1.example.com ... 
Creating orderer.example.com ... done
Creating peer0.org1.example.com ... 
Creating peer0.org2.example.com ... 
Creating ca.org2.example.com    ... done
Creating ca.org1.example.com    ... done
Creating peer0.org2.example.com ... done
Creating peer0.org1.example.com ... done
2021.04.15-10:15:10.447 info  [caliper] [caliper-engine]        Executed start command in 10.105 seconds
2021.04.15-10:15:10.448 info  [caliper] [adapters/fabric]       Fabric SDK version: 1.4.7; TLS: none
2021.04.15-10:15:11.039 info  [caliper] [adapters/fabric]       Org1's registrar enrolled successfully
2021.04.15-10:15:11.207 info  [caliper] [adapters/fabric]       Org2's registrar enrolled successfully
2021.04.15-10:15:11.215 info  [caliper] [adapters/fabric]       Org1's admin's materials are successfully loaded
2021.04.15-10:15:11.220 info  [caliper] [adapters/fabric]       Org2's admin's materials are successfully loaded
2021.04.15-10:15:11.226 info  [caliper] [adapters/fabric]       client0.org1.example.com's materials are successfully loaded
2021.04.15-10:15:11.232 info  [caliper] [adapters/fabric]       client0.org2.example.com's materials are successfully loaded
2021.04.15-10:15:11.233 info  [caliper] [adapters/fabric]       Channel 'mychannel' definiton being retrieved from file
2021.04.15-10:15:11.270 info  [caliper] [adapters/fabric]       Channel 'mychannel' successfully created
2021.04.15-10:15:11.271 info  [caliper] [adapters/fabric]       Sleeping 5s...
2021.04.15-10:15:16.409 info  [caliper] [adapters/fabric]       Org1's peers successfully joined mychannel: peer0.org1.example.com
2021.04.15-10:15:16.534 info  [caliper] [adapters/fabric]       Org2's peers successfully joined mychannel: peer0.org2.example.com
2021.04.15-10:15:16.535 info  [caliper] [adapters/fabric]       Sleeping 5s...
2021.04.15-10:15:21.536 info  [caliper] [caliper-engine]        Executed "init" step in 11.087 seconds
2021.04.15-10:15:21.538 info  [caliper] [adapters/fabric]       Installing chaincodes for mychannel...
2021.04.15-10:15:21.585 info  [caliper] [adapters/fabric]       marbles@v0 successfully installed on Org1's peers: peer0.org1.example.com
2021.04.15-10:15:21.597 info  [caliper] [adapters/fabric]       marbles@v0 successfully installed on Org2's peers: peer0.org2.example.com
2021.04.15-10:15:21.621 info  [caliper] [adapters/fabric]       drm@v0 successfully installed on Org1's peers: peer0.org1.example.com
2021.04.15-10:15:21.630 info  [caliper] [adapters/fabric]       drm@v0 successfully installed on Org2's peers: peer0.org2.example.com
2021.04.15-10:15:21.653 info  [caliper] [adapters/fabric]       simple@v0 successfully installed on Org1's peers: peer0.org1.example.com
2021.04.15-10:15:21.661 info  [caliper] [adapters/fabric]       simple@v0 successfully installed on Org2's peers: peer0.org2.example.com
2021.04.15-10:15:21.687 info  [caliper] [adapters/fabric]       smallbank@v0 successfully installed on Org1's peers: peer0.org1.example.com
2021.04.15-10:15:21.694 info  [caliper] [adapters/fabric]       smallbank@v0 successfully installed on Org2's peers: peer0.org2.example.com
2021.04.15-10:15:21.695 info  [caliper] [adapters/fabric]       Instantiating marbles@v0 in mychannel. This might take some time...
2021.04.15-10:15:22.924 error [caliper] [caliper-engine]        **Error** while performing "install" step: Error: Invalid endorsement for marbles@v0 in mychannel from peer0.org1.example.com: error starting container: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "/chaincode/input/src/fabric/samples/marbles/go/marbles.go:110:2: cannot find package "github.com/hyperledger/fabric/core/chaincode/shim" in any of:
        /usr/local/go/src/github.com/hyperledger/fabric/core/chaincode/shim (from $GOROOT)
        /chaincode/input/src/github.com/hyperledger/fabric/core/chaincode/shim (from $GOPATH)
        /go/src/github.com/hyperledger/fabric/core/chaincode/shim
/chaincode/input/src/fabric/samples/marbles/go/marbles.go:111:2: cannot find package "github.com/hyperledger/fabric/protos/peer" in any of:
        /usr/local/go/src/github.com/hyperledger/fabric/protos/peer (from $GOROOT)
        /chaincode/input/src/github.com/hyperledger/fabric/protos/peer (from $GOPATH)
        /go/src/github.com/hyperledger/fabric/protos/peer
"
2021.04.15-10:15:22.925 info  [caliper] [caliper-engine]        Executed "install" step in 1.389 seconds
2021.04.15-10:15:22.925 info  [caliper] [caliper-utils]         Executing command: cd .; docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb/docker-compose.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*
The FABRIC_CA_VERSION variable is not set. Defaulting to a blank string.
The FABRIC_VERSION variable is not set. Defaulting to a blank string.
Stopping peer0.org2.example.com ... 
Stopping peer0.org1.example.com ... 
Stopping ca.org1.example.com    ... 
Stopping orderer.example.com    ... 
Stopping ca.org2.example.com    ... 
Stopping peer0.org2.example.com ... done
Stopping peer0.org1.example.com ... done
Stopping orderer.example.com    ... done
Stopping ca.org2.example.com    ... done
Stopping ca.org1.example.com    ... done
Removing peer0.org2.example.com ... 
Removing peer0.org1.example.com ... 
Removing ca.org1.example.com    ... 
Removing orderer.example.com    ... 
Removing ca.org2.example.com    ... 
Removing orderer.example.com    ... done
Removing ca.org1.example.com    ... done
Removing ca.org2.example.com    ... done
Removing peer0.org2.example.com ... done
Removing peer0.org1.example.com ... done
Removing network 2org1peergoleveldb_default
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
2021.04.15-10:15:34.915 info  [caliper] [caliper-engine]        Executed end command in 11.99 seconds
2021.04.15-10:15:34.915 **error** [caliper] [cli-launch-master]     Benchmark failed with error code 5

**Comment by OierAM** [comment]
- Version used: v0.3.0
- Operating System and version: ubuntu 20.04

**Comment by feickertm** [comment]
I am having the exact same problem. @OierAM have you managed to fix it?

**Comment by davidkel** [comment]
This appears to be around using the caliper-benchmarks repo and as this repo requires a complete overhaul it's not surprising that things aren't working now

**Comment by davidkel** [comment]
Issue about the marbles Go chaincode raised here https://github.com/hyperledger/caliper-benchmarks/issues/155 as it's this that is causing the problems

**Comment by davidkel** [comment]
closing as created appropriate issue in appropriate repo
