### ISSUE TITLE
[Integrating Ethereum] Error while performing "init" step: Error: connection not open on send()

### ISSUE THREAD

**Issue by pooja239** [hyperledger/caliper#1139]
I am trying to set up a private Ethereum network and test it with Caliper. I couldn't achieve that with existing sample networks and my network. I got an error when I launch the benchmark on the sample network in this repository.

## Context
2021.04.29-00:33:28.666 error [caliper] [caliper-engine] 	Error while performing "init" step: Error: connection not open on send()

## Steps to Reproduce
I cloned the Caliper repository.

Then executed the following commands.
npm init -y
npm install --only=prod
@hyperledger/caliper-cli@0.4.0
npx caliper bind
--caliper-bind-sut ethereum:1.2.1
caliper launch manager     --caliper-workspace .     --caliper-benchconfig benchmarks/scenario/simple/config.yaml     --caliper-networkconfig networks/ethereum/1node-clique/networkconfig.json

The error I got when I run above commands:

#8 exporting to image
#8 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#8 exporting layers 0.1s done
#8 writing image sha256:f20280ba56026d16b4762741f42f2b874e9294b9c7d8af3847497b9831a97ae7
#8 writing image sha256:f20280ba56026d16b4762741f42f2b874e9294b9c7d8af3847497b9831a97ae7 done
#8 naming to docker.io/library/caliper-ethereum-clique done
#8 DONE 0.1s
Successfully built f20280ba56026d16b4762741f42f2b874e9294b9c7d8af3847497b9831a97ae7
Image for service node was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating ethereum_clique ... 
Creating ethereum_clique ... done
2021.04.29-00:33:28.654 info  [caliper] [caliper-engine] 	Executed start command in 76.324 seconds
2021.04.29-00:33:28.666 error [caliper] [caliper-engine] 	Error while performing "init" step: Error: connection not open on send()
2021.04.29-00:33:28.667 info  [caliper] [caliper-engine] 	Executed "init" step in 0.01 seconds
2021.04.29-00:33:28.667 info  [caliper] [caliper-utils] 	Executing command: cd .; docker-compose -f ./networks/ethereum/1node-clique/docker-compose.yml down
Removing ethereum_clique ... 
Removing ethereum_clique ... done
Removing network 1node-clique_default
2021.04.29-00:33:30.153 info  [caliper] [caliper-engine] 	Executed end command in 1.486 seconds
2021.04.29-00:33:30.154 error [caliper] [cli-launch-manager] 	Benchmark failed with error code 4
Usage:
 caliper launch manager --caliper-bind-sut fabric:1.4 [other options]

Options:
  --help, -h           Show usage information  [boolean]
  --version            Show version information  [boolean]
  --caliper-bind-sut   The name and version of the platform to bind to  [string]
  --caliper-bind-cwd   The working directory for performing the SDK install  [string]
  --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
  --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]

Error: Benchmark failed with error code 4
    at Function.handler (/usr/local/lib/node_modules/@hyperledger/caliper-cli/lib/launch/lib/launchManager.js:70:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Pooja:caliper-benchmarks pooja$ pwd
/Users/pooja/Desktop/caliper/caliper-benchmarks

## Existing issues

https://github.com/hyperledger/caliper/issues/1024

It was closed and no solution was provided. 

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

##Requested networkconfig.json configuration

{
    "caliper": {
        "blockchain": "ethereum",
        "command" : {
            "start": "docker-compose -f ./networks/ethereum/1node-clique/docker-compose.yml up -d && sleep 60s",
            "end" : "docker-compose -f ./networks/ethereum/1node-clique/docker-compose.yml down"
          }
    },
    "ethereum": {
        "url": "ws://localhost:8546",
        "contractDeployerAddress": "0xc0A8e4D217eB85b812aeb1226fAb6F588943C2C2",
        "contractDeployerAddressPassword": "password",
        "fromAddress": "0xc0A8e4D217eB85b812aeb1226fAb6F588943C2C2",
        "fromAddressPassword": "password",
        "transactionConfirmationBlocks": 2,
        "contracts": {
            "simple": {
                "path": "./src/ethereum/simple/simple.json",
                "estimateGas": true,
                "gas": {
                    "query": 100000,
                    "transfer": 70000
                }
            }
        }
    }
}

**Comment by nklincoln** [comment]
looks to be in the build pipeline too, it is possible a dependency has changed - @shemnon - are you aware of any likely candidate changes here?

**Comment by pooja239** [comment]
hi @shemnon , can you please help me resolving this issue?

**Comment by aklenik** [comment]
@pooja239 I usually received this error when the Ethereum node wasn't ready to accept connections yet. Try increasing the sleep time in the start command, or check the logs of the Ethereum node for any other error.

**Comment by ws4583** [comment]
@pooja239 I had the same issue, and I finally found that some Geth commands are outdated.
In docker-compose.yml, I changed some flags in commands
--minerthread --etherebase --wsaddr --wsorigin --wsapi --gasprice
to
--miner.thread --miner.etherebase --ws.addr --ws.origins --ws.api --miner.gasprice
and it worked!
I hope this can help you.

**Comment by pooja239** [comment]
@ws4583 thanks for sharing this.  I realized this and already fixed the issue.
However, I am observing that caliper fails to start the network.  Quick workaround is to bring up the network and then start caliper.

**Comment by WeiYun0912** [comment]
> @ws4583 thanks for sharing this. I realized this and already fixed the issue. However, I am observing that caliper fails to start the network. Quick workaround is to bring up the network and then start caliper.

Hello, I have the same problem, I google for a long time and still can't solve it, can you tell me how you solved it?

Thank you.

**Comment by aklenik** [comment]
@WeiYun0912 The `connection not open on send()` error only indicates that Caliper cannot communicate with the Ethereum node. Make sure that the node started correctly and it's ready to accept connections (examine its logs).

**Comment by WeiYun0912** [comment]
> @WeiYun0912 The `connection not open on send()` error only indicates that Caliper cannot communicate with the Ethereum node. Make sure that the node started correctly and it's ready to accept connections (examine its logs).

okey, thank you!! 
I will try it.
