### ISSUE TITLE
Using percpu_usage.length can cause invalid CPU statistics

### ISSUE THREAD

**Issue by RobertDiebels** [hyperledger/caliper#114]
**Issue**
See the [docker documentation](https://docs.docker.com/engine/api/v1.37/#operation/ContainerStats):

"If either precpu_stats.online_cpus or cpu_stats.online_cpus is nil then for compatibility with older daemons the length of the corresponding cpu_usage.percpu_usage array should be used."

Relevant code in caliper: https://github.com/hyperledger/caliper/blob/56fbd8892e4ebe165977673c33c5829fd6805a72/src/comm/monitor-docker.js#L218

**Extra information**
I'd like to note that when falling back on `percpu_usage.length` it might be that you can have a total of 4 cores and only 2 are in use. So the `percpu_usage` Array might look like this: `[34782342, 358734, 0, 0]` in that case using `percpu_usage.length` will be invalid. 
Since you'd always be looking at the maximum amount of cores that could be used. Instead of the amount of cores that are actually used.

**Solution**
Replace line 218 with:
```
self.stats[id].cpu_percent.push(cpuDelta / sysDelta * MonitorDocker.coresInUse(stat.cpu_stats) * 100.0);
```
and add the following methods to the class:
```
    static coresInUse(cpu_stats) {
        return cpu_stats.online_cpus || MonitorDocker.findCoresInUse(cpu_stats.cpu_usage.percpu_usage || []);
    }

    static findCoresInUse(percpu_usage) {
        percpu_usage = percpu_usage.filter((coreUsage) => {
            if (coreUsage > 0) {
                return (coreUsage)
            }
        });
        return percpu_usage.length;
    }
```

**Comment by haojun** [comment]
@RobertDiebels , thanks for pointing out this  issue. Would you like to submit a PR?

**Comment by RobertDiebels** [comment]
@haojun I'd love to contribute to Caliper I just don't have the time to do so right now. I've tested the solution above in a fork and it's worked so far. If you'd like you can just take that bit of code and add it.
