### ISSUE TITLE
can't catch the error of commitTimeOut , because of the unit is not uniform

### ISSUE THREAD

**Issue by workhard-12** [hyperledger/caliper#1141]
When we submit a tx , the unit of "commitTimeOut" should be seconds ,  but the caliper use milliseconds.

**Comment by workhard-12** [comment]
packages\caliper-fabric\lib\connector-versions\v2\FabricGateway.js
- async _createGatewayWithIdentity(mspId, aliasName, wallet) 
- constructor(connectorConfiguration, workerIndex, bcType)

**Comment by davidkel** [comment]
This is mainly a documentation issue as internally the code actually considers this to be seconds not milliseconds, however the default value of 60000 is assuming to be 60 seconds so the default value should change

**Comment by davidkel** [comment]
Docs have been updated and code base has changed the default from 60,000 to 60. In the mean time you can override the default with
```
--caliper-fabric-timeout-invokeorquery 60
```
when you launch caliper
