### ISSUE TITLE
FabricCAClientService.js

### ISSUE THREAD

**Issue by Elhamshammar** [hyperledger/caliper#1155]
I am a new to caliper 
I would like to benchmark my network
Fabric sdk 2.1
Caliper 0.4.0

Once I launch  master command it showed me the following error

error: [FabricCAClientService.js]: Failed to enroll admin, error:%o message=Calling enrollment endpoint failed with error [Error: Client network socket disconnected before secure TLS connection was established], stack=Error: Calling enrollment endpoint failed with error [Error: Client network socket disconnected before secure TLS connection was established]

**Comment by davidkel** [comment]
duplicate of #1154
