### ISSUE TITLE
Failed connecting client to a Network Gateway with error: Error: extension not supported

### ISSUE THREAD

**Issue by Xeryus01** [hyperledger/caliper#1169]
I got error while trying to benchmark hyperledger fabric 2.1 by using hyperledger caliper v0.4.2. I benchmark the existing network in my server, but i always got same error like in this post [https://stackoverflow.com/questions/69762835/connecting-client-to-a-network-gateway-error](https://stackoverflow.com/questions/69762835/connecting-client-to-a-network-gateway-erro). I run the benchmark with command `npx caliper launch manager --caliper-workspace ~/caliper-benchmarks --caliper-networkconfig  networks/fabric/1/fabric-javascript-solo-samples.yaml --caliper-benchconfig benchmarks/scenario/simple/test/config.yaml --caliper-flow-only-test --caliper-fabric-gateway-enabled`
I've restarted and changed the keystore filename in network configuration, but still got the same problem. All of my configuration and the caliper logs is in this link [https://stackoverflow.com/questions/69762835/connecting-client-to-a-network-gateway-error](https://stackoverflow.com/questions/69762835/connecting-client-to-a-network-gateway-erro).

**Comment by davidkel** [comment]
I've commented on your stackoverflow which is a more appropriate place for this rather than a github issue as this doesn't appear to be a problem with caliper.
