### ISSUE TITLE
test fabric1.2

### ISSUE THREAD

**Issue by yqcong** [hyperledger/caliper#1173]
Hi，I have modified the source code of fabric1.4. I want to know whether the performance of the modified fabric has been improved. Can I use caliper0.2 to test the fabric platform I modified? @aklenik @nklincoln

**Comment by davidkel** [comment]
@yqcong why would you not want to use caliper 0.4.2 ?

**Comment by yqcong** [comment]
I need to reproduce a paper, which is based on  @fabric1.2，but I did not find any reference documents about first-network@davidkel，I want to know whether caliper0.2 supports first-network network testing.

**Comment by davidkel** [comment]
caliper 0.4.2 can work with any existing fabric 1.4 network, I have no idea about caliper 0.2 sorry. I would suggest you use caliper 0.4.2 to benchmark your network.

**Comment by yqcong** [comment]
Thank you, but caplier0.4.2 does not seem to support fabric1.2 network@davidkel

**Comment by davidkel** [comment]
But you said you had modified the 1.4 source code, not the 1.2 code base

**Comment by yqcong** [comment]
Yes，1.4  has been solved
