### ISSUE TITLE
 Error[caliper]: failed to connect to all addresses

### ISSUE THREAD

**Issue by wafa-elshibani** [hyperledger/caliper#1182]
I want to use Hyperledger Caliper to test my running chaincode. the chain code depoyed useing composer 0.20. my network fabric sdk is 1.2.0.

## network_config file 
name: Fabric
version: "1.0"
mutual-tls: false

caliper:
  blockchain: fabric
  
info:
  Version: 1.2.0
  Size: 1 Org with 3Peer
  Orderer: Solo
  Distribution: 3 Hosts
  StateDB: CouchDB

clients:
  client0.org1.example.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
          path: /tmp/hfc-cvs/org1
      clientPrivateKey:
        path: caliper-benchmarks/networks/fabric/LLR/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/key.pem
      clientSignedCert:
        path: caliper-benchmarks/networks/fabric/LLR/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem

channels:
  mychannel:
    created: true

    orderers:
    - orderer.example.com
    peers:
      peer0.org1.example.com:
        eventSource: true
      peer1.org1.example.com:
        eventSource: true
      peer2.org1.example.com:
        eventSource: true
    chaincodes:
      - id: land-registry
        version: "0.0.2-deploy.12"
        language: golang
        path: fabric/api/LLR/go
    

organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    - peer1.org1.example.com
    - peer2.org1.example.com
    certificateAuthorities:
    - ca.example.com
    adminPrivateKey:
      path: caliper-benchmarks/networks/fabric/LLR/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/key.pem
    signedCert:
      path: caliper-benchmarks/networks/fabric/LLR/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem

orderers:
  orderer.example.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
    tlsCACerts:
      path: caliper-benchmarks/networks/fabric/LLR/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: caliper-benchmarks/networks/fabric/LLR/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer1.org1.example.com:
    url: grpcs://<IP address of host2>:8051
    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: caliper-benchmarks/networks/fabric/LLR/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

  peer2.org1.example.com:
    url: grpcs://<IP address of host3>:9051
    grpcOptions:
      ssl-target-name-override: peer2.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: caliper-benchmarks/networks/fabric/LLR/crypto-config/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

certificateAuthorities:
  ca.example.com:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: caliper-benchmarks/networks/fabric/LLR/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

    registrar:
    - enrollId: admin
      enrollSecret: adminpw

  

## result
##but when running  caliper i had the following errors:
2021.12.05-16:07:54.655 info  [caliper] [cli-launch-master]     Set workspace path: /home/sysadmin/caliperForComposer
2021.12.05-16:07:54.661 info  [caliper] [cli-launch-master]     Set benchmark configuration path: /home/sysadmin/caliperForComposer/caliper-benchmarks/benchmarks/scenario/simple/LLR/config.yaml
2021.12.05-16:07:54.662 info  [caliper] [cli-launch-master]     Set network configuration path: /home/sysadmin/caliperForComposer/caliper-benchmarks/networks/fabric/LLR/network-config.yaml
2021.12.05-16:07:54.663 info  [caliper] [cli-launch-master]     Set SUT type: fabric
2021.12.05-16:07:54.668 info  [caliper] [benchmark-validator]   No observer specified, will default to `none`
2021.12.05-16:07:54.669 info  [caliper] [caliper-engine]        Starting benchmark flow
2021.12.05-16:07:55.509 info  [caliper] [adapters/fabric]       Initializing standard adaptor compatible with installed SDK: 1.4.8
2021.12.05-16:07:56.168 info  [caliper] [caliper-engine]        Network configuration attribute "caliper.command.start" is not present, skipping start command
2021.12.05-16:07:56.170 info  [caliper] [adapters/fabric]       Fabric SDK version: 1.4.8; TLS: server
2021.12.05-16:07:56.484 warn  [caliper] [adapters/fabric]       Org1's registrar's materials found locally in file system key-value stores. Make sure it is the right one!
2021.12.05-16:07:56.492 info  [caliper] [adapters/fabric]       Org1's admin's materials are successfully loaded
2021.12.05-16:07:56.516 info  [caliper] [adapters/fabric]       client0.org1.example.com's materials are successfully loaded
2021.12.05-16:07:56.518 info  [caliper] [adapters/fabric]       Channel 'mychannel' is configured as created, skipping creation
E1205 16:07:56.545989248   26606 ssl_transport_security.cc:1245] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
E1205 16:07:56.553800645   26606 ssl_transport_security.cc:1245] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
E1205 16:07:56.559680739   26606 ssl_transport_security.cc:1245] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
2021.12.05-16:07:56.560 error [caliper] [adapters/fabric]       The following errors occurred while querying mychannel information from Org1's peers:
        - Couldn't query mychannel information from peer0.org1.example.com: 14 UNAVAILABLE: failed to connect to all addresses
        - Couldn't query mychannel information from peer1.org1.example.com: 14 UNAVAILABLE: failed to connect to all addresses
        - Couldn't query mychannel information from peer2.org1.example.com: 14 UNAVAILABLE: failed to connect to all addresses
2021.12.05-16:07:56.567 error [caliper] [caliper-engine]        Error while performing "init" step: Error: Couldn't query mychannel information from Org1's peers
2021.12.05-16:07:56.568 info  [caliper] [caliper-engine]        Executed "init" step in 0.398 seconds
2021.12.05-16:07:56.570 info  [caliper] [caliper-engine]        Network configuration attribute "caliper.command.end" is not present, skipping end command
2021.12.05-16:07:56.571 error [caliper] [cli-launch-master]     Benchmark failed with error code

**Comment by aklenik** [comment]
@wafa-elshibani Caliper does not support HL Composer anymore (since it's deprecated), so you should try writing a vanilla Fabric chaincode instead and deploy it directly on Fabric.

Also, please double-check the peer addresses in your network configuration (and it would help if you formatted the network configuration in the issue using triple backticks that preserve indentation).

**Comment by wafa-elshibani** [comment]
> @wafa-elshibani Caliper does not support HL Composer anymore (since it's deprecated), so you should try writing a vanilla Fabric chaincode instead and deploy it directly on Fabric.
> 
> Also, please double-check the peer addresses in your network configuration (and it would help if you formatted the network configuration in the issue using triple backticks that preserve indentation).

Can i create new simple chaincode and deployed on my network to test the network with out effecting on the previous chaincode?

**Comment by aklenik** [comment]
@wafa-elshibani I think that's completely doable if you have access to the Fabric nodes. Simply choose another chaincode ID and it won't interfere with the existing one. And then you can use on of the Fabric connectors to interact with the new chaincode.

I'm closing this issue for now, since it pertains to Composer.
