### ISSUE TITLE
error when integrate caliper with fabric SDK 2.4

### ISSUE THREAD

**Issue by Sympathy189** [hyperledger/caliper#1185]
I am receiving this error when starting running caliper with fabric 2.4 with the fabric-samples sample using test-nerwork.

I received an error in installation and I couldn't fix it. I need some one to solve this:

2021.12.13-01:35:24.814 +0300 info [cli-launch-manager] Set workspace path: /Users/testfolder/caliper-workspace
2021.12.13-01:35:24.814 +0300 info [cli-launch-manager] Set benchmark configuration path: /Users/testfolder/caliper-workspace/benchmarks/assetCCBenchmark.yaml
2021.12.13-01:35:24.814 +0300 info [cli-launch-manager] Set network configuration path: /Users/testfolder/caliper-workspace/networks/networkConfig.yaml
2021.12.13-01:35:24.814 +0300 info [cli-launch-manager] Set SUT type: fabric
2021.12.13-01:35:24.847 +0300 info [benchmark-validator] No observer specified, will default to `none`
2021.12.13-01:35:24.847 +0300 info [caliper-engine] Starting benchmark flow
2021.12.13-01:35:25.364 +0300 info [fabric-connector] Initializing gateway connector compatible with installed SDK: 2.2.3
2021.12.13-01:35:25.370 +0300 error [cli-launch-manager] Unexpected error during benchmark execution: Error: path property does not point to a file that exists for clientSignedCert for name User1 in organization Org1MSP

**Comment by aklenik** [comment]
Could please provide the details of your network configuration file? It looks like a path error when setting the certs for User1@Org1

**Comment by rbadrana** [comment]
caliper:
    blockchain: fabric
    sutOptions :
       mutualTls: true

channels:
  - channelName: mychannel
    contracts:
    - id: orgtmp
      
organizations:
  - mspid: Org1MSP
    identities:
      certificates:
      - name: 'client0.org1.example.com'
        clientPrivateKey:
          path: '../caliper/networks/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk'
        clientSignedCert:
          path: '../caliper/networks/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem'
    connectionProfile:
      path: '../caliper/networks/crypto-config/connection-profiles/connection-profile.yaml'
      discover: false

  - mspid: Org2MSP
    identities:
      certificates:
      - name: 'client0.org2.example.com'
        clientPrivateKey:
          path: '../networks/crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/priv_sk'
        clientSignedCert:
          path: '../networks/crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/signcerts/cert.pem'
    connectionProfile:
      path: '../networks/crypto-config/connection-profiles/connection-profile.yaml'
      discover: false

  - mspid: Org3MSP
    identities:
      certificates:
      - name: 'client0.org3.example.com'
        clientPrivateKey:
          path: '../networks/crypto-config/peerOrganizations/org3.example.com/users/User1@org3.example.com/msp/keystore/priv_sk'
        clientSignedCert:
          path: '../networks/crypto-config/peerOrganizations/org3.example.com/users/User1@org3.example.com/msp/signcerts/cert.pem'
    connectionProfile:
      path: '../networks/crypto-config/connection-profiles/connection-profile.yaml'
      discover: false

**Comment by davidkel** [comment]
@rbadrana relative paths can be tricky and you may not have got it correct. You could try absolute paths instead or better still embed the certificates directly into the network config using the `pem` property rather than the path property, see https://hyperledger.github.io/caliper/v0.4.2/fabric-config/new/ for details

**Comment by Sympathy189** [comment]
I tried several times to copy the exact path but nothing works. I have changed the SDK to 2.3 and it works. I think it is a compatibility issue. Thanks
