### ISSUE TITLE
Support automatic register and enrolment of identities in the new network configuration for fabric

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper#1212]
### Please share the technical limitation of Caliper that you encountered.

The legacy fabric network configuration supported the ability to register and enroll an identity for use within a benchmark. The new network configuration format doesn't support that option currently. 
This issue is being created as a point of discussion to see if there is a good argument to include this capability over alternatives such as using fabric-ca-client yourself to generate the crypto material in preparation for running a benchmark

### Please detail your feature idea that could alleviate the limitation.

TBD

**Comment by aklenik** [comment]
Since we're moving away from the SUT deploy/init features, I'd say that creating new identities is not the responsibility of Caliper. Users can generate crypto materials and wallets offline and reference those in the network configuration.
