### ISSUE TITLE
Caliper documentation has a Monitors and Observers section but it ony talks about Monitors

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper#1213]
### Which Caliper version are you using?

v0.4.2

### Which Node.JS version are you using?

v10

### Which operating system are you using?

Ubuntu 18.04

### Please provide some context for your error. For example, when did the error occur? What were you trying to achieve, and how?

Documentation issue, are there such things as observers and can they be configured ?

### What was the observed incorrect behavior?

Incorrect documentation

### Please provide the error logs and their surroundings.

```text
n/a
```

**Comment by aklenik** [comment]
There were two options for the manager service to receive progress reports from workers: directly via update messages and pulling metrics from a Prometheus server. The latter seemed unstable, so I think it was removed (maybe just from the documentation). I think 😅
