### ISSUE TITLE
Unknown rate control type linear-rate

### ISSUE THREAD

**Issue by Miraczpp** [hyperledger/caliper#123]
Info: client 104362 start test runFixedNumber():opening accounts
***** { type: 'linear-rate',
  opts: { startingTps: 500, finishingTps: 5000 } }
Client 104362: error Error: Unknown rate control type linear-rate
    at new RateControl (/opt/caliper/src/comm/rate-control/rateControl.js:49:19)
    at runFixedNumber (/opt/caliper/src/comm/client/local-client.js:89:23)
    at blockchain.getContext.then (/opt/caliper/src/comm/client/local-client.js:180:20)
    at <anonymous>

**Comment by aklenik** [comment]
@Miraczpp Based on the line numbers in the error, you didn't pull the latest version of Caliper.
The latest version [contains](https://github.com/hyperledger/caliper/blob/6131f4fca8881d9bb2f3a0fdc829b7df7036659e/src/comm/rate-control/rateControl.js#L58) the `linear-rate` controller:
```
case 'linear-rate': {
            const LinearRateController = require('./linearRate.js');
            this.controller = new LinearRateController(blockchain, rateControl.opts);
            break;
        }
```

**Comment by panyu4** [comment]
As this issue is not existed in latest version, I'm closing it.
