### ISSUE TITLE
[client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: TCP Read failed at new createStatusError

### ISSUE THREAD

**Issue by nktuan286** [hyperledger/caliper#127]
I have two servers. One is using to build app service and the other is using to build hyperledger fabric network. When i request from app service to blockchain network then sometime i have some problem like below:

[client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: TCP Read failed
    at new createStatusError (/home/user/server/node_modules/fabric-client/node_modules/grpc/src/client.js:64:15)
    at /home/user/server/node_modules/fabric-client/node_modules/grpc/src/client.js:583:15

[Orderer.js]: sendBroadcast - on error: "Error: 14 UNAVAILABLE: TCP Read failed\n    at createStatusError (/home/user/server/node_modules/fabric-client/node_modules/grpc/src/client.js:64:15)\n   at ClientDuplexStream._emitStatusIfDone (/home/user/server/node_modules/fabric-client/node_modules/grpc/src/client.js:270:19)\n    at ClientDuplexStream._receiveStatus (/home/user/server/node_modules/fabric-client/node_modules/grpc/src/client.js:248:8)\n    at /home/user/server/node_modules/fabric-client/node_modules/grpc/src/client.js:804:12".

Is anyone know to solved this issue. Thanks so much. (sorry for my bad english)

**Comment by aklenik** [comment]
@nktuan286 I experienced this issue when the Fabric network was overloaded, so basically the used resources are not enough. Did you run every node on the same machine? 

Some options to "push down" the system requirements (during development time):
- Decrease the TPS rate while you are developing/testing on a local network
- Use only one organization, with one peer and one CA, and solo orderer (adjust the chaincode policy to 1-of-1)
- If it's possible, avoid CouchDB, unless you need the rich query functionality 

Hope these tips help.

**Comment by nktuan286** [comment]
@aklenik Thanks for your help. 
I assume that this issue is not Fabric network was overload.
My local network is OK but this error occurs on Azure.
Currently i running one CA, one Order and one Peer (every node running on a virtual machine on Azure).
Sometime i request to peer then occurs error but try again (one or two more time) then it success

**Comment by aklenik** [comment]
Take a look at the peer/orderer logs. My guess is that it is some kind of transient connection failure between the nodes. 

Anyway, these errors are returned by the Fabric SDK, which receives the error from the Fabric network, so it's not originating from inside Caliper. Can you share some details about your setup? Type/number of VMs, network speed, transaction rate, the complexity of  the chaincode?

**Comment by nktuan286** [comment]
@aklenik Thanks so much. I will try to fix it.

**Comment by panyu4** [comment]
Since the errors are not originating from inside Caliper, I'm closing this issue.

**Comment by Adibla** [comment]
> I have two servers. One is using to build app service and the other is using to build hyperledger fabric network. When i request from app service to blockchain network then sometime i have some problem like below:
> 
> [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: TCP Read failed
> at new createStatusError (/home/user/server/node_modules/fabric-client/node_modules/grpc/src/client.js:64:15)
> at /home/user/server/node_modules/fabric-client/node_modules/grpc/src/client.js:583:15
> 
> [Orderer.js]: sendBroadcast - on error: "Error: 14 UNAVAILABLE: TCP Read failed\n at createStatusError (/home/user/server/node_modules/fabric-client/node_modules/grpc/src/client.js:64:15)\n at ClientDuplexStream._emitStatusIfDone (/home/user/server/node_modules/fabric-client/node_modules/grpc/src/client.js:270:19)\n at ClientDuplexStream._receiveStatus (/home/user/server/node_modules/fabric-client/node_modules/grpc/src/client.js:248:8)\n at /home/user/server/node_modules/fabric-client/node_modules/grpc/src/client.js:804:12".
> 
> Is anyone know to solved this issue. Thanks so much. (sorry for my bad english)

I've the same problem, in a managed service (as you) At the end, did you have resolve your issue?
