### ISSUE TITLE
Error: Invoke stoped. Unfinished number never decrease

### ISSUE THREAD

**Issue by JulienGuo** [hyperledger/caliper#130]
the log always:
[Transaction Info] - Submitted: 20000 Succ: 18736 Fail:0 Unfinished:1264
[Transaction Info] - Submitted: 20000 Succ: 18736 Fail:0 Unfinished:1264
[Transaction Info] - Submitted: 20000 Succ: 18736 Fail:0 Unfinished:1264
[Transaction Info] - Submitted: 20000 Succ: 18736 Fail:0 Unfinished:1264
[Transaction Info] - Submitted: 20000 Succ: 18736 Fail:0 Unfinished:1264
[Transaction Info] - Submitted: 20000 Succ: 18736 Fail:0 Unfinished:1264
[Transaction Info] - Submitted: 20000 Succ: 18736 Fail:0 Unfinished:1264
[Transaction Info] - Submitted: 20000 Succ: 18736 Fail:0 Unfinished:1264
[Transaction Info] - Submitted: 20000 Succ: 18736 Fail:0 Unfinished:1264
[Transaction Info] - Submitted: 20000 Succ: 18736 Fail:0 Unfinished:1264
[Transaction Info] - Submitted: 20000 Succ: 18736 Fail:0 Unfinished:1264
[Transaction Info] - Submitted: 20000 Succ: 18736 Fail:0 Unfinished:1264
[Transaction Info] - Submitted: 20000 Succ: 18736 Fail:0 Unfinished:1264
[Transaction Info] - Submitted: 20000 Succ: 18736 Fail:0 Unfinished:1264
[Transaction Info] - Submitted: 20000 Succ: 18736 Fail:0 Unfinished:1264
[Transaction Info] - Submitted: 20000 Succ: 18736 Fail:0 Unfinished:1264
[Transaction Info] - Submitted: 20000 Succ: 18736 Fail:0 Unfinished:1264

**Comment by JulienGuo** [comment]
I changed the timeout of invoke, it is very long. please don't use a const value to be timeout

**Comment by nklincoln** [comment]
Ah - OK, so there was a regression in the Composer plugin where a callback was introduced in the main framework but was unfortunately missed in the Composer transactions. The transactions (smart contract invocations) were being run, but the fact that they had run was not being registered and so the test never finished.

To my knowledge this has now been fixed with a recent PR, so if you were to update to the latest code base you should be good to go.

**Comment by JulienGuo** [comment]
@nklincoln This is the fabric thing and it has nothing to do with composer

**Comment by abhi201191** [comment]
Facing this same issue. @JulienGuo any luck in this?

**Comment by modood** [comment]
Facing this same issue. @JulienGuo any luck in this?

**Comment by zsh122958** [comment]
@JulienGuo Can you share your experience?I had a problem submitting the transaction
Thank you very much for your help

**Comment by aklenik** [comment]
@abhi201191 @modood @zsh122958 Any luck with the issue?
