### ISSUE TITLE
Change the invoke timeout from a constant value to a variable value , and make the value related to sleep time.

### ISSUE THREAD

**Issue by JulienGuo** [hyperledger/caliper#131]

**Comment by JulienGuo** [comment]
@nklincoln @haojun

**Comment by nklincoln** [comment]
@JulienGuo - could you expand on this issue description please?

**Comment by JulienGuo** [comment]
The timeout of tx is set at https://github.com/hyperledger/caliper/blob/master/benchmark/simple/open.js 
Line     
return bc.invokeSmartContract(contx, 'simple', 'v0', {verb: 'open', account: newAcc, money: initMoney}, 30);
timeout is 30s, it is a constant value
Sometimes , I need set txNumber as a big number like 100,000, then some txs be executed early , timeout should  be a few seconds , some txs be executed very later , and because of backlog tx timeout is long, maybe the tx start early ,but end later, so  timeout should be long.  So, I want change timeout to a variable value.

**Comment by nklincoln** [comment]
@JulienGuo - would the intention be to have a single "high" value set for a test run, or for the value to change through the tests?

If the former, then the change could be made to the test file, with a new argument being passed into the test and used locally for the duration. For instance, in the `init` function, `args.timeout` could be bound to a variable to use in the test, with the corresponding change being made to the test runner specification to provide the argument and a value.

**Comment by JulienGuo** [comment]
@nklincoln If I set a single "high" value, if I execute some invokes, maybe them would be error ,  but I should be waiting too long , then  the avg latency would be low. If all the success invokes have been executed complete,  what I can see is the console log never change , just print same log every second. Description: https://github.com/hyperledger/caliper/issues/130

**Comment by zsh122958** [comment]
@JulienGuo  可以帮我解决这个问题么？  invokeSmartContract（） 发送request请求没有响应

**Comment by feihujiang** [comment]
@JulienGuo Only the successful transactions are used for computing the avg latency, so setting a single "high" value would not affect the avg latency. We have submitted one PR(#215 ) with feedback rate controller to balance the high sending rate with  backend throughput. To avoid the high sending rate per client you would use zookeeper client  mode.  We also submitted one PRs with file mode(#286 ) to reduce the time consume.

**Comment by aklenik** [comment]
@JulienGuo Additionally, the timeouts in the example benchmarks are just, well, examples. You can implement any logic to determine the timeout for the individual transactions. This is up to the user, whatever he/she sets, Caliper will enforce that timeout during the transaction life-cycle.

These examples are not production-ready applications, just simple user modules that demonstrate the Caliper API. So IMO it's kind of pointless to polish them till perfection.

**Comment by aklenik** [comment]
Closing it due to inactivity
