### ISSUE TITLE
Prepare the release of Caliper 0.5.0

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper#1333]
- [x] Update the change log (include a script to help generate)
- [x] change 0.5.0-unstable to 0.5.0 to publish official npm and docker components
- [ ] change 0.5.0 to 0.5.1-unstable in prep for next release
- [x] copy vNext dir to 0.5.0 dir in docs, rename 'main' references to 0.5.0 add 0.5.0 to dropdown for docs
- [x] create pre-release entry in the github release section

The main branch of caliper-benchmarks should work with 0.4.2 and 0.5.0 and it would be much better for 0.4.2 users to use main branch so at this time I don't think caliper-benchmarks should be tagged there is still some work required to document use of the new peer gateway in caliper benchmarks plus there are still some broken aspects of caliper-benchmarks that need to be fixed first.

**Comment by SamYuan1990** [comment]
Cool!
