### ISSUE TITLE
npm install grpc@1.10.1  ERR

### ISSUE THREAD

**Issue by gongchuanhua** [hyperledger/caliper#136]
`
[root@llhl178 caliper]# npm install grpc@1.10.1
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ECONNREFUSED: request to https://registry.npmjs.org/decamelize failed, reason: connect ECONNREFUSED 104.18.96.96:443
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

> grpc@1.10.1 install /opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Pre-built binaries not installable for grpc@1.10.1 and node@8.11.3 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Hit error EACCES: permission denied, mkdir '/opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/node' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/build'
gyp ERR! System Linux 4.17.6-1.el7.elrepo.x86_64
gyp ERR! command "/usr/local/node-v8.11.3-linux-x64/bin/node" "/usr/local/node-v8.11.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc"
gyp ERR! cwd /opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/node-v8.11.3-linux-x64/bin/node /usr/local/node-v8.11.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.17.6-1.el7.elrepo.x86_64
node-pre-gyp ERR! command "/usr/local/node-v8.11.3-linux-x64/bin/node" "/opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc
node-pre-gyp ERR! node -v v8.11.3
node-pre-gyp ERR! node-pre-gyp -v v0.7.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/node-v8.11.3-linux-x64/bin/node /usr/local/node-v8.11.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.10.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-18T03_01_41_563Z-debug.log
`

**Comment by bitpeng** [comment]
try to run :  `npm i grpc@1.10.1 --unsafe-perm`

**Comment by panyu4** [comment]
@gongchuanhua  it may be a permission problem. Try to run : sudo npm install grpc@1.10.1 , or switch to another user and run: sudo npm install grpc@1.10.1

**Comment by aklenik** [comment]
My experience is that it's simpler to install local packages as a non-root user. Way less headache (and no need for root privileges anyway):
```
git clone https://github.com/hyperledger/caliper.git
cd caliper
npm install
npm install grpc@1.10.1 fabric-ca-client@1.1.0 fabric-client@1.1.0
```

**Comment by gongchuanhua** [comment]
thanks ,It Works!

**Comment by ishandutta2007** [comment]
I needed to downgrade node from 10.12 to 8.11

    node -v

v10.12.0

    npm install -g n
    n 8.11.1
    mode -v

v8.11.1

**Comment by Hdezhkam** [comment]
npm install firebase --force

**Comment by aklenik** [comment]
For anyone struggling with global installs or grpc/node versions, check out the Dockerfile for Caliper for the non-root global install approach: https://github.com/hyperledger/caliper/blob/master/packages/caliper-publish/caliper.Dockerfile

For installing on node 10.x LTS, check out the binding file for the necessary environment and install settings: https://github.com/hyperledger/caliper/blob/master/packages/caliper-cli/lib/lib/config.yaml#L18
