### ISSUE TITLE
Remove unused dependency from caliper-fabric package

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper#1365]
In the caliper-fabric package the dependency `@hapi/joi` is listed but isn't required anymore

**Comment by davidkel** [comment]
This might be a good test of the node module caching in the build, so maybe leave until that is implemented

**Comment by ggold7046** [comment]
I'm new to blockchain. Can anybody guide me how to solve this issue ?

**Comment by Sayalikukkar** [comment]
Hello @davidkel , I would like to contribute on this. Can i start working on this?

**Comment by psankhe28** [comment]
@davidkel Can I work on this issue?

**Comment by davidkel** [comment]
@psankhe28 sure, do you want me to assign it to you ?

**Comment by davidkel** [comment]
Merged ready for 0.5.1 release
