### ISSUE TITLE
Migrate the publish step to Github Actions

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper#1369]
This will require help from the Hyperledger Foundation as they own the npm and docker push secrets, As part of this we will need to also disable the azure pipelines publish to ensure only one build pipeline performs the publish step
This is dependent on #1368 being completed first

**Comment by davidkel** [comment]
FYI:
OK. Here are the ones you need (and have): DOCKERHUB_ORG, DOCKERHUB_TOKEN, DOCKERHUB_USERNAME, NPM_TOKEN 
Here is how :iroha: uses them: https://github.com/hyperledger/iroha/blob/9af9a2f64008a5224c17440c681894b758de4b35/.github/workflows/iroha2-push-nightly.yml

Also note that to be consistent we should still perform the unit test runs before doing a merge as this is what the azure pipelines currently does. There is an issue under the optimize theme that covers looking into why this was done (I don't know but @aklenik may know) see #1380

**Comment by CaptainIRS** [comment]
I think the tokens haven't been added to the repository yet as the workflow failed in the main branch due to the missing NPM_TOKEN variable.
