### ISSUE TITLE
generator integration tests fail (but the build doesn't notice a failure) because it's bound to fabric 2.2

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper#1377]
The generator tests rely on using the non gateway fabric:1.4 binding because it uses the ability to create channels. We need to change the generator binding from 2.2 to 1.4 to fix this, ie

change run.sh in the generator tests from
```
${CALL_METHOD} bind --caliper-bind-sut fabric:2.2
```
to
```
${CALL_METHOD} bind --caliper-bind-sut fabric:1.4
```

**Comment by Swastyy** [comment]
Hi @davidkel , can I work on this?
