### ISSUE TITLE
Extract hard-coded constants to configurable variables

### ISSUE THREAD

**Issue by aklenik** [hyperledger/caliper#138]
Currently, some values are hard-coded, e.g., the timeout for chaincode instantiation (#137). A proper configuration support should be added to Caliper. 

The two aspects:
1. The library: I propose `nconf`, the Fabric SDK uses it, and wrote an elegant wrapper class for it (reusing this wrapper class without introducing the SDK as a constant dependency is another question).
1. The conventions: I propose a naming convention like in Fabric, since Caliper also has some major submodules. For example, the current `OVERWRITE_GOPATH` setting could be something like
`CALIPER_FABRIC_OVERWRITEGOPATH` 

@haojun Opinions?

**Comment by haojun** [comment]
@panyu4 @jiangyaoguo

**Comment by aklenik** [comment]
Implemented by PR #202
