### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by wanghairong1109** [hyperledger/caliper#1386]
### Please share the technical limitation of Caliper that you encountered.

2022.06.22-12:36:58.964 error [caliper] [fiscoBcosApi.js] 	Compiling error: 
/sources/TextEvidence.sol:3:1: Error: Source file requires different compiler version (current compiler is 0.4.25+commit.59dbf8f1.Linux.g++ - note that nightly builds are considered to be strictly less than the released version
pragma solidity >=0.6.0 <0.7.0;

### Please detail your feature idea that could alleviate the limitation.

2022.06.22-12:36:58.964 error [caliper] [fiscoBcosApi.js] 	Compiling error: 
/sources/TextEvidence.sol:3:1: Error: Source file requires different compiler version (current compiler is 0.4.25+commit.59dbf8f1.Linux.g++ - note that nightly builds are considered to be strictly less than the released version
pragma solidity >=0.6.0 <0.7.0;

**Comment by davidkel** [comment]
Closing as fisco-bcos is unsupported (and removed from future versions of caliper). Available as is only now in 0.5.0 and below
