### ISSUE TITLE
Support multiple orderers

### ISSUE THREAD

**Issue by pplam** [hyperledger/caliper#139]
For `fabric` benchmark, only 1 `orderer` can be specified in `fabric.json`. This make all traffic go to 1 `orderer` and the test result is not really correct. Could you please implement the feature that support multiple `orderer` sooner?

**Comment by pplam** [comment]
Got it, so i need to do some hacking on `caliper` and keep looking forward to this feature. Thanks

**Comment by aklenik** [comment]
If you need the feature right away, then yes :) But I'm working on the issue, hopefully, it will be ready soon.

**Comment by pplam** [comment]
That's great, I've done my job with some other monitor tools and if the feature is ready, I may use it later. Thanks again.

**Comment by cao0507** [comment]
> That's great, I've done my job with some other monitor tools and if the feature is ready, I may use it later. Thanks again.

What monitor tools have you find?

**Comment by cao0507** [comment]
@aklenik Hello，does caliper support multiple orderers now?

**Comment by aklenik** [comment]
@cao0507 There will be a work-in-progress PR soon (hopefully within a day or two), and you can start playing around with the new features.

**Comment by samlee1203** [comment]
is it ready now? I am also looking for caliper's fabric testing on multiple orderers (not solo).

**Comment by rohitkhatri** [comment]
Is there any workaround to test this on multiple orderer until It's added?

**Comment by aklenik** [comment]
@samlee1203 @rohitkhatri Check out PR #296 and the corresponding documentation. It's not merged yet, and every feedback is welcome!

**Comment by aklenik** [comment]
Resolved by PR #296
