### ISSUE TITLE
Signed-off-by: Tezas-6174 <jamdade.2@iitj.ac.in>

### ISSUE THREAD

**Issue by sarahmaya771** [hyperledger/caliper#1399]
Signed-off-by: Tezas-6174 <jamdade.2@iitj.ac.in>

- Fixes #1377.
- Changed the generator binding from 2.2 to 1.4 in ``run.sh`` in generator-tests of ``caliper-test-integration`` package.

__Originally posted by @Tezas-6174 in https://github.com/hyperledger/caliper/pull/1391__

**Comment by Tezas-6174** [comment]
What's the issue with this?
