### ISSUE TITLE
Monitor disk r/w rate

### ISSUE THREAD

**Issue by pplam** [hyperledger/caliper#140]
When performing a large transaction benchmark on `fabric`, I got very high `Traffic In/Out` for each `peer` and the specified `orderer` of `1.1 GB ~ 2.5 GB` from the statistic result but nothing about the disk read/write rate of these nodes. Is it possible to monitor the hard disk read/write rate of each node?

**Comment by haojun** [comment]
@pplam I'm 100% not sure, but @jiangyaoguo we can investigate on it.

**Comment by aklenik** [comment]
Resolved by PR #237
