### ISSUE TITLE
Error in Register Tx event in fabric sdk node js 

### ISSUE THREAD

**Issue by WaedSaleh** [hyperledger/caliper#141]
When I register transaction event, I get this error 

node:31526) UnhandledPromiseRejectionWarning: Error: There was a problem with the eventhub ::Error: 14 UNAVAILABLE: EOF
    at eh.registerTxEvent (/home/waedjabareen/blockchain-explorer/app/query.js:266:12)
    at closer (/home/waedjabareen/blockchain-explorer/node_modules/fabric-client/lib/EventHub.js:441:5)
    at EventHub._closeAllCallbacks (/home/waedjabareen/blockchain-explorer/node_modules/fabric-client/lib/EventHub.js:451:3)
    at EventHub._disconnect (/home/waedjabareen/blockchain-explorer/node_modules/fabric-client/lib/EventHub.js:387:8)
    at ClientDuplexStream.<anonymous> (/home/waedjabareen/blockchain-explorer/node_modules/fabric-client/lib/EventHub.js:358:10)
    at emitOne (events.js:116:13)
    at ClientDuplexStream.emit (events.js:211:7)
    at ClientDuplexStream._emitStatusIfDone (/home/waedjabareen/blockchain-explorer/node_modules/grpc/src/client.js:271:12)
    at ClientDuplexStream._receiveStatus (/home/waedjabareen/blockchain-explorer/node_modules/grpc/src/client.js:248:8)
    at /home/waedjabareen/blockchain-explorer/node_modules/grpc/src/client.js:804:12
(node:31526) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31526) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

And here is the code 
var registerTxEvent = function (transactionID, channelName, peer,org) {
	var client = helper.getClientForOrg(org);
	var channel = helper.getChannelForOrg(org, channelName);
	var target = buildTarget(peer, org);
	let eh = client.newEventHub();
    eh.setPeerAddr('grpc://localhost:8051');
	eh.connect();
	var promises = [];
	console.log(peer);
	
  
    let txPromise = new Promise((resolve, reject) => {
        let handle = setTimeout(() => {
			console.log('start app');
           eh.disconnect();
			resolve({event_status : 'TIMEOUT'});
        }, 30000);
		console.log('start register tx');
        eh.registerTxEvent(transactionID, (tx, code) => {
            clearTimeout(handle);
            eh.unregisterTxEvent(transactionID);
            //eh.disconnect();

           		// now let the application know what happened
				var return_status = {event_status : code, tx_id : transactionID};
				if (code !== 'VALID') {
					console.error('The transaction was invalid, code = ' + code);
				//	resolve(return_status).catch(error => 	reject(new Error('There was a problem with the eventhub ::'+err)));// we could use reject(new Error('Problem with the tranaction, event status ::'+code));
				} else {
					console.log('The transaction has been committed on peer ' + eh._endpoint.addr);
				//	resolve(return_status).catch(error => 	reject(new Error('There was a problem with the eventhub ::'+err))) ;
				}
			}, (err) => {
				//this is the callback if something goes wrong with the event registration or processing
				reject(new Error('There was a problem with the eventhub ::'+err));
			});
       
	});

	promises.push(txPromise);
	return Promise.all(promises);
	
	}

**Comment by aklenik** [comment]
@WaedSaleh I'm not sure that this should be a Caliper issue :) Nevertheless, this (Fabric SDK) error indicates that the event hub connection was terminated for some reason (network issues, overloaded peers, etc.).

**Comment by aklenik** [comment]
Since this is `blockchain-explorer`-related, I'm closing the issue.
