### ISSUE TITLE
Caliper with Raft Consensus Algo

### ISSUE THREAD

**Issue by AlbshriAdel** [hyperledger/caliper#1449]
### Which Caliper version are you using?

latest

### Which Node.JS version are you using?

v18.3.0

### Which operating system are you using?

Ubuntu 20.04

### Please provide some context for your error. For example, when did the error occur? What were you trying to achieve, and how?

I tried to use the Caliper benchmark with Quorum by using the latest Ethereum as SUT, which has worked perfectly with consensus algorithms supported by Quorum networks such as Istanbul and qbft. However, an error message appeared when I tried to use raft as a consensus algorithm, as shown below in fig 6. Therefore, I tried all possible solutions, but unfortunately, all attempts failed. If anyone has faced the same issue or has any suggestions to overcome this issue, I would appreciate that.

Figure 1. shows the docker process status, which indicates 4 nodes running.
![docker process status](https://user-images.githubusercontent.com/84684367/191792402-0e5b757d-c59c-4130-86d8-775c5e8a1f58.PNG)

Figure 2. shows the networking config file.
![networking config file](https://user-images.githubusercontent.com/84684367/191792462-0c55220a-fb5f-4802-93c8-117010a5c69a.PNG)

Figure 3. shows the benchmarkConfig file.
![benchmark config file](https://user-images.githubusercontent.com/84684367/191792512-8a8d3723-066b-4b6a-a070-1217ffa812b9.PNG)

Figure 4. shows the results of the Caliper benchmark when I used qbft as the consensus algorithm.
![results of the caliper](https://user-images.githubusercontent.com/84684367/191792625-ac6ed4ae-4a83-4642-9bd0-7a492ae151f7.PNG)

Figure 5. shows the block explorer, which presents that Caliper had Successfully sent all transactions 
![block explorer](https://user-images.githubusercontent.com/84684367/191792648-93c42b62-f0ee-4135-ba1e-d4ce67835fae.PNG)

Figure 6. shows the message error when I used raft. 
![error](https://user-images.githubusercontent.com/84684367/191792703-c6f937fc-053e-42c1-ac5b-4be2063ba2c1.PNG)

### What was the observed incorrect behavior?

An error message appeared when I tried to use raft as a consensus algorithm, as shown below in fig 6.

### Please provide the error logs and their surroundings.

```text
2022.09.22-15:42:59.335 info  [caliper] [cli-launch-manager]    Set workspace path: /root
2022.09.22-15:42:59.336 info  [caliper] [cli-launch-manager]    Set benchmark configuration path: /root/benchmark/benchconfig.yaml
2022.09.22-15:42:59.336 info  [caliper] [cli-launch-manager]    Set network configuration path: /root/quorum-test-network/networkconfig.json
2022.09.22-15:42:59.336 info  [caliper] [cli-launch-manager]    Set SUT type: ethereum
2022.09.22-15:42:59.625 info  [caliper] [benchmark-validator]   No observer specified, will default to `none`
2022.09.22-15:42:59.625 info  [caliper] [caliper-engine]        Starting benchmark flow
2022.09.22-15:42:59.626 info  [caliper] [caliper-utils]         Executing command: cd ./; echo start benchmark
start benchmark
2022.09.22-15:42:59.650 info  [caliper] [caliper-engine]        Executed start command in 0.024 seconds
2022.09.22-15:42:59.660 info  [caliper] [caliper-engine]        Executed "init" step in 0 seconds
2022.09.22-15:42:59.661 info  [caliper] [ethereum-connector]    Creating contracts...
/root/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6
    if (!val) throw new Error(msg || 'Assertion failed');
              ^

Error: Number can only safely store up to 53 bits
    at assert (/root/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/root/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:506:7)
    at Object.hexToNumber (/root/node_modules/web3-utils/src/utils.js:239:24)
    at Object.outputBlockFormatter [as outputFormatter] (/root/node_modules/web3-core-helpers/src/formatters.js:301:29)
    at Subscription._formatOutput (/root/node_modules/web3-core-subscriptions/src/subscription.js:122:84)
    at /root/node_modules/web3-core-subscriptions/src/subscription.js:263:44
    at Array.forEach (<anonymous>)
    at Object.callback (/root/node_modules/web3-core-subscriptions/src/subscription.js:262:28)
    at requestManagerNotification (/root/node_modules/web3-core-requestmanager/src/index.js:103:65)
    at /root/node_modules/web3-providers-ws/src/index.js:122:25
    at Array.forEach (<anonymous>)
    at /root/node_modules/web3-providers-ws/src/index.js:120:45
    at Array.forEach (<anonymous>)
    at WebsocketProvider.connection.onmessage (/root/node_modules/web3-providers-ws/src/index.js:104:36)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/root/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/root/node_modules/@web3-js/websocket/lib/W3CWebSocket.js:234:14)
```

**Comment by aakzubaidi** [comment]
I have the same issue. Is there any solution to this?

**Comment by AlbshriAdel** [comment]
Any suggestion regarding this issue?

**Comment by aakzubaidi** [comment]
Try the following, which should resolve the issue:

'''sh
npm install web3@v4.0.1-alpha.1
'''

**Comment by AlbshriAdel** [comment]
I appreciate your response. Upon trying your suggestion, I found that it worked perfectly. Once again, thank you.
