### ISSUE TITLE
I can't run any samples example

### ISSUE THREAD

**Issue by ml16a6a** [hyperledger/caliper#145]
Can any one help me, I'm trying to run the first example "basic-sample-network" and I got this error. Did I miss something ?
 
<img width="993" alt="screen shot 2018-07-28 at 08 35 24" src="https://user-images.githubusercontent.com/40967156/43354289-60ea1848-9241-11e8-91f5-9dbd50cc5043.png">

**Comment by aklenik** [comment]
@ml16a6a By default, docker compose names the docker network based on the directory name that contains the compose.yaml file. Some versions remove the `-` symbols, some don't. Try modifying this line (and for every other peer) to `- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=2-org-1-peer_default`

**Comment by ml16a6a** [comment]
@aklenik Thanks, it works now
