### ISSUE TITLE
fixed-load documentation states `startingTps`, code states `startTps`

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper#1471]
There is also an issue on caliper-benchmarks as the examples there also state `startingTps` when it needs to be `startTps`

or we change the code to match the documentation and caliper-benchmarks

**Comment by vinayakjaas** [comment]
Hi @davidkel, I'd like to take on this task. I'm eager to tackle the issue. Could you please assign it to me?

**Comment by davidkel** [comment]
Fix sumitted and merged.
