### ISSUE TITLE
fabric no using TLS ! how to using caliper?

### ISSUE THREAD

**Issue by gantleman** [hyperledger/caliper#150]
node benchmark/simple/main.js -c yourconfig.json -n yournetwork.json
report create-channel.js TLS path error~

**Comment by nklincoln** [comment]
... can you expand on the above issue please? What were you trying to achieve, what did you do, etc

**Comment by houqinghui** [comment]
@gantleman TLS is the way that fabric support ，you can refer to [https://hyperledger-fabric.readthedocs.io/en/release-1.4/enable_tls.html]，or you can use the default tls network config file or the defautl no tls network config file.

**Comment by aklenik** [comment]
@gantleman Any progress on the issue? The network examples have been reworked, for both TLS and no-TLS.
