### ISSUE TITLE
Does it support fabric2.5.3?

### ISSUE THREAD

**Issue by bajiang1** [hyperledger/caliper#1505]
my hyperlegerfabric version is 2.5.3，does it support？

**Comment by davidkel** [comment]
Version 0.5.0 can work with hyperledger fabric 2.5.3. The bind option selects a client sdk to use to interact with hyperledger fabric. See https://hyperledger.github.io/caliper/v0.5.0/fabric-config/new/#installing-dependencies
for information regarding binding, but in reality you can bind with `fabric:1.4`, `fabric:2.2` or `fabric:2.4`. I would recommend using `fabric:2.4` with your version of hyperledger fabric, unless your workload requires a specific caliper capability that is only available in `fabric:2.2`. There is no reason these days to bind the `fabric:1.4`

**Comment by davidkel** [comment]
Also I would highly recommend reading
https://hyperledger-fabric.readthedocs.io/en/release-2.5/performance.html as well as https://www.hyperledger.org/blog/2023/02/16/benchmarking-hyperledger-fabric-2-5-performance

**Comment by davidkel** [comment]
see #1464 which would hopefully avoid this confusion in the future

**Comment by davidkel** [comment]
New version of caliper published and will default to the new docs which addresses this issue.
