### ISSUE TITLE
Bug: Error Occurs When Running Documentation Locally

### ISSUE THREAD

**Issue by vinayakjaas** [hyperledger/caliper#1525]
### Which Caliper version are you using?

v0.5.0

### Which Node.JS version are you using?

v20.10.0

### Which operating system are you using?

Windows 11

### Please provide some context for your error. For example, when did the error occur? What were you trying to achieve, and how?

When: The error occurred while I was attempting to run the documentation locally.
What I was trying to achieve: I was trying to run the documentation locally to ensure its correctness and appearance before making some correction.
How: I followed the instructions provided in the project's README or documentation to run the documentation locally, typically using a command like bundle exec jekyll serve.

### What was the observed incorrect behavior?

 The documentation failed to render or display properly when attempting to run it locally. Instead of seeing the expected documentation pages, an error occurred during the rendering process, preventing the documentation from being viewed as intended.

### Please provide the error logs and their surroundings.

```text
<internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require': cannot load such file -- rexml/parsers/baseparser (LoadError)
        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/kramdown-1.17.0/lib/kramdown/parser/html.rb:10:in `<top (required)>'
```

**Comment by davidkel** [comment]
Closing as resolved, many thanks for the contribution
