### ISSUE TITLE
Handshake fad wileith fatal error

### ISSUE THREAD

**Issue by gantleman** [hyperledger/caliper#153]
sur@ubuntu:~/caliper$ node benchmark/simple/main.js -c config.json -n fabric.json
TAP version 13
# #######Caliper Test######
docker-compose -f network/fabric/simplenetwork/docker-compose.yaml up -d
Creating network "simplenetwork_default" with the default driver
Creating simplenetwork_ca_1   ... done
Creating simplenetwork_peer_1   ... done
Creating ca_peerOrg1            ... done
Creating ca_peerOrg2            ... done
Creating orderer.example.com  ... done
Creating peer0.org1.example.com ... done
Creating peer0.org2.example.com ... done
Creating peer1.org1.example.com ... done
Creating peer1.org2.example.com ... done
# create mychannel......
E0803 00:23:46.331521753   39650 ssl_transport_security.cc:989] Handshake fad wileith fatal error SSL_ERROR_SSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed.
E0803 00:23:47.379271451   39650 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed.
E0803 00:23:49.187643994   39650 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed.
error: [Remote.js]: Error: Failed to connect before the deadline
error: [Orderer.js]: Orderer grpcs://localhost:7050 has an error Error: Failed to connect before the deadline 
not ok 1 Failed to create channels Error: Failed to connect before the deadline at checkState (/home/sur/caliper/node_modules/grpc/src/client.js:838:16)
  ---
    operator: fail
    at: channels.reduce.then.then.catch (/home/sur/caliper/src/fabric/create-channel.js:159:19)
    stack: |-
      Error: Failed to create channels Error: Failed to connect before the deadline
          at checkState (/home/sur/caliper/node_modules/grpc/src/client.js:838:16)
          at Test.assert [as _assert] (/home/sur/caliper/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/home/sur/caliper/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/home/sur/caliper/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/home/sur/caliper/node_modules/tape/lib/test.js:76:32)
          at channels.reduce.then.then.catch (/home/sur/caliper/src/fabric/create-channel.js:159:19)
          at process._tickCallback (internal/process/next_tick.js:68:7)
  ...
fabric.init() failed, Error: Fabric: Create channel failed
    at channels.reduce.then.then.catch (/home/sur/caliper/src/fabric/create-channel.js:160:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
unexpected error, Error: Fabric: Create channel failed
    at channels.reduce.then.then.catch (/home/sur/caliper/src/fabric/create-channel.js:160:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
docker-compose -f network/fabric/simplenetwork/docker-compose.yaml down;docker rm $(docker ps -aq);docker rmi $(docker images dev* -q)
Stopping peer1.org2.example.com ... done
Stopping peer1.org1.example.com ... done
Stopping peer0.org1.example.com ... done
Stopping peer0.org2.example.com ... done
Stopping ca_peerOrg2            ... done
Stopping orderer.example.com    ... done
Stopping ca_peerOrg1            ... done
Stopping simplenetwork_ca_1     ... done
Removing peer1.org2.example.com ... done
Removing peer1.org1.example.com ... done
Removing peer0.org1.example.com ... done
Removing peer0.org2.example.com ... done
Removing ca_peerOrg2            ... done
Removing orderer.example.com    ... done
Removing ca_peerOrg1            ... done
Removing simplenetwork_peer_1   ... done
Removing simplenetwork_ca_1     ... done
Removing network simplenetwork_default
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images

1..1
# tests 1
# pass  0
# fail  1

sur@ubuntu:~/caliper$

**Comment by stanly-johnson** [comment]
I have the same issue. Any solutions?

**Comment by kaiknight** [comment]
Hi same issue here.
I've this issue in Ubuntu 16.04 when connecting through NodeJS SDK.
The issue doesn't occur when submitting transaction through peer command in cli container.
It doesn't occur in OSX either when connecting through NodeJS SDK.
Any workaround?

**Comment by anchit93** [comment]
Hello @kaiknight , 
I am also facing the same issue while trying to setup my network using Node SDK on my Ubuntu VMs.
I am facing it while creating a common channel and joining my orgs. I also tried running my JS file with sudo permission but still facing the same issue. I would really appreciate if you can assist me in solving this issue.

**Comment by gantleman** [comment]
> Hi same issue here.
> I've this issue in Ubuntu 16.04 when connecting through NodeJS SDK.
> The issue doesn't occur when submitting transaction through peer command in cli container.
> It doesn't occur in OSX either when connecting through NodeJS SDK.
> Any workaround?

thank you, have already been solved

**Comment by gantleman** [comment]
> Hi same issue here.
> I've this issue in Ubuntu 16.04 when connecting through NodeJS SDK.
> The issue doesn't occur when submitting transaction through peer command in cli container.
> It doesn't occur in OSX either when connecting through NodeJS SDK.
> Any workaround?

@kaiknight thank you, have already been solved

**Comment by Macaret** [comment]
I have the same issue... when trying to invoke from the NodeJS app. Any help?

**Comment by aklenik** [comment]
@anchit93 @Macaret Looks like a connection issue with the orderer. Could you do the following steps?
1. Remove the start and end scripts from the config.
1. Start the docker network manually (execute the removed start script)
1. Wait a few seconds for the network to start
1. Execute the benchmark

If the error is still there, inspect your orderer logs (and post it here as a GitHub gist if you can't figure out the reason for the error)

**Comment by dattajadhav44** [comment]
I have the same error, Can someone please suggest

error: [Remote.js]: Error: Failed to connect before the deadline URL:grpcs://localhost:7050
[2018-11-29 18:23:48.445] [ERROR] Join-Channel - Error: Failed to connect before the deadline URL:grpcs://localhost:7050
    at checkState (/home/djadhav/Desktop/fabric-samples/balance-transfer/node_modules/grpc/src/client.js:720:16)
[2018-11-29 18:23:48.445] [ERROR] Join-Channel - Failed to join all peers to channel. cause:Error: Failed to connect before the deadline URL:grpcs://localhost:7050
(node:7079) UnhandledPromiseRejectionWarning: Error: Failed to join all peers to channel. cause:Error: Failed to connect before the deadline URL:grpcs://localhost:7050
    at Object.joinChannel (/home/djadhav/Desktop/fabric-samples/balance-transfer/app/join-channel.js:101:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:7079) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

**Comment by Macaret** [comment]
> @anchit93 @Macaret Looks like a connection issue with the orderer. Could you do the following steps?
> 
> 1. Remove the start and end scripts from the config.
> 2. Start the docker network manually (execute the removed start script)
> 3. Wait a few seconds for the network to start
> 4. Execute the benchmark
> 
> If the error is still there, inspect your orderer logs (and post it here as a GitHub gist if you can't figure out the reason for the error)

I still have the issue, only on invoke, on query - everything works fine...
Here are the logs from my orderer:

[2018-12-03T12:58:59.843] [ERROR] app - asyncMiddleware Error: Failed to connect before the deadline URL:grpcs://orderer.test.com:7050

```
2018-12-03 12:34:56.225 UTC [localconfig] completeInitialization -> INFO 001 Kafka.Version unset, setting to 0.10.2.0
2018-12-03 12:34:56.237 UTC [orderer/common/server] prettyPrintStruct -> INFO 002 Orderer config values:
	General.LedgerType = "file"
	General.ListenAddress = "0.0.0.0"
	General.ListenPort = 7050
	General.TLS.Enabled = true
	General.TLS.PrivateKey = "/var/hyperledger/orderer/tls/server.key"
	General.TLS.Certificate = "/var/hyperledger/orderer/tls/server.crt"
	General.TLS.RootCAs = [/var/hyperledger/orderer/tls/ca.crt]
	General.TLS.ClientAuthRequired = false
	General.TLS.ClientRootCAs = []
	General.Keepalive.ServerMinInterval = 1m0s
	General.Keepalive.ServerInterval = 2h0m0s
	General.Keepalive.ServerTimeout = 20s
	General.GenesisMethod = "file"
	General.GenesisProfile = "SampleInsecureSolo"
	General.SystemChannel = "test-system-channel-name"
	General.GenesisFile = "/var/hyperledger/orderer/orderer.genesis.block"
	General.Profile.Enabled = false
	General.Profile.Address = "0.0.0.0:6060"
	General.LogLevel = "INFO"
	General.LogFormat = "%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message}"
	General.LocalMSPDir = "/var/hyperledger/orderer/msp"
	General.LocalMSPID = "OrdererMSP"
	General.BCCSP.ProviderName = "SW"
	General.BCCSP.SwOpts.SecLevel = 256
	General.BCCSP.SwOpts.HashFamily = "SHA2"
	General.BCCSP.SwOpts.Ephemeral = false
	General.BCCSP.SwOpts.FileKeystore.KeyStorePath = "/var/hyperledger/orderer/msp/keystore"
	General.BCCSP.SwOpts.DummyKeystore =
	General.BCCSP.PluginOpts =
	General.Authentication.TimeWindow = 15m0s
	FileLedger.Location = "/var/hyperledger/production/orderer"
	FileLedger.Prefix = "hyperledger-fabric-ordererledger"
	RAMLedger.HistorySize = 1000
	Kafka.Retry.ShortInterval = 5s
	Kafka.Retry.ShortTotal = 10m0s
	Kafka.Retry.LongInterval = 5m0s
	Kafka.Retry.LongTotal = 12h0m0s
	Kafka.Retry.NetworkTimeouts.DialTimeout = 10s
	Kafka.Retry.NetworkTimeouts.ReadTimeout = 10s
	Kafka.Retry.NetworkTimeouts.WriteTimeout = 10s
	Kafka.Retry.Metadata.RetryMax = 3
	Kafka.Retry.Metadata.RetryBackoff = 250ms
	Kafka.Retry.Producer.RetryMax = 3
	Kafka.Retry.Producer.RetryBackoff = 100ms
	Kafka.Retry.Consumer.RetryBackoff = 2s
	Kafka.Verbose = false
	Kafka.Version = 0.10.2.0
	Kafka.TLS.Enabled = false
	Kafka.TLS.PrivateKey = ""
	Kafka.TLS.Certificate = ""
	Kafka.TLS.RootCAs = []
	Kafka.TLS.ClientAuthRequired = false
	Kafka.TLS.ClientRootCAs = []
	Kafka.SASLPlain.Enabled = false
	Kafka.SASLPlain.User = ""
	Kafka.SASLPlain.Password = ""
	Kafka.Topic.ReplicationFactor = 3
	Debug.BroadcastTraceDir = ""
	Debug.DeliverTraceDir = ""
2018-12-03 12:34:56.237 UTC [orderer/common/server] initializeServerConfig -> INFO 003 Starting orderer with TLS enabled
2018-12-03 12:34:56.257 UTC [fsblkstorage] newBlockfileMgr -> INFO 004 Getting block information from block storage
2018-12-03 12:34:56.270 UTC [orderer/commmon/multichannel] NewRegistrar -> INFO 005 Starting system channel 'testchainid' with genesis block hash d4c076f5307b417cdd952126560f6b8e8d67143e6f57b69a30ab05f16280eec4 and orderer type solo
2018-12-03 12:34:56.271 UTC [orderer/common/server] Start -> INFO 006 Starting orderer:
 Version: 1.3.0
 Commit SHA: ab0a67a
 Go version: go1.10.4
 OS/Arch: linux/amd64
 Experimental features: false
2018-12-03 12:34:56.271 UTC [orderer/common/server] Start -> INFO 007 Beginning to serve requests
2018-12-03 12:35:02.822 UTC [fsblkstorage] newBlockfileMgr -> INFO 008 Getting block information from block storage
2018-12-03 12:35:02.835 UTC [orderer/commmon/multichannel] newChain -> INFO 009 Created and starting new chain mychannel
2018-12-03 12:35:02.840 UTC [common/deliver] Handle -> WARN 00a Error reading from 10.0.0.36:51508: rpc error: code = Canceled desc = context canceled
2018-12-03 12:35:15.673 UTC [orderer/common/broadcast] Handle -> WARN 00b Error reading from 10.0.0.36:51528: rpc error: code = Canceled desc = context canceled
2018-12-03 12:35:15.673 UTC [common/deliver] Handle -> WARN 00c Error reading from 10.0.0.36:51526: rpc error: code = Canceled desc = context canceled
2018-12-03 12:35:18.728 UTC [common/deliver] Handle -> WARN 00d Error reading from 10.0.0.36:51534: rpc error: code = Canceled desc = context canceled
2018-12-03 12:35:18.728 UTC [orderer/common/broadcast] Handle -> WARN 00e Error reading from 10.0.0.36:51536: rpc error: code = Canceled desc = context canceled
2018-12-03 12:35:46.102 UTC [orderer/common/broadcast] Handle -> WARN 00f Error reading from 10.0.0.36:51576: rpc error: code = Canceled desc = context canceled
2018-12-03 12:41:14.568 UTC [orderer/common/broadcast] Handle -> WARN 010 Error reading from 10.0.0.36:51766: rpc error: code = Canceled desc = context canceled
```

**Comment by raky35** [comment]
Face same issue on Mac at step 11 and 12 https://hyperledger.github.io/composer/latest/tutorials/deploy-to-fabric-multi-org 


 $composer network install --card PeerAdmin@byfn-network-org1 --archiveFile trade-network.bna
⠹ Installing business network. This may take a minute...E0117 21:32:32.532056000 4371604928 ssl_transport_security.cc:989]     Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E0117 21:32:32.532847000 4371604928 ssl_transport_security.cc:989]     Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed. E0117 21:32:32.533437000 4371604928 ssl_transport_security.cc:989]     Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.E0117 21:32:32.534208000 4371604928 ssl_transport_security.cc:989]     Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.E0117 21:32:32.537892000 4371604928 ssl_transport_security.cc:989]     Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E0117 21:32:32.546455000 4371604928 ssl_transport_security.cc:989]     Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.E0117 21:32:32.547008000 4371604928 ssl_transport_security.cc:989]     Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.E0117 21:32:32.547544000 4371604928 ssl_transport_security.cc:989]     Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
⠸ Installing business network. This may take a minute...E0117 21:32:32.658260000 4371604928 ssl_transport_security.cc:989]     Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
E0117 21:32:32.658921000 4371604928 ssl_transport_security.cc:989]     Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.E0117 21:32:32.662836000 4371604928 ssl_transport_security.cc:989]     Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.E0117 21:32:32.664557000 4371604928 ssl_transport_security.cc:989]     Handshake failed with fatal error SSL_ERROR_SSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.
⠴ Installing business

**Comment by nhannamsiu** [comment]
This is compatible problem with grpc on nodejs. Please try downgrading your node to v8 latest, npm rebuild and try again.

**Comment by aklenik** [comment]
@raky35 @Macaret @dattajadhav44 @anchit93 Handshake errors usually occur when the communication protocols don't match on the client and server side. Double check that if your network configuration file uses `grpcs://` and `https://` protocols, then your Fabric network is also configured for TLS (and viceversa).

The example networks were made more robust regarding this error, so make sure you use an up-2-date version of Caliper.

**Comment by simsekgokhan** [comment]
I had the exact same error. These steps fixed it for me:

- Open VirtualBox Manager and select the “default” VM
- Click “Settings”, “Network”, “Advanced”, “Port Forwarding”.
- Create a new rule by clicking the “+” sign on the right and entering the following: Name -> “grpc”, Host Port -> 7050, Guest Port -> 7050
- You can leave the Host IP and Guest IP unspecified.

Thx to: https://developer.ibm.com/opentech/2017/11/29/running-hyperledger-fabric-windows-revised/

**Comment by fady-a-m-ibrahim** [comment]
One of the reasons is using unsuitable node version.
To add the Long Term Support (LTS) subversion of Node.js v8, we can use these commands:
```
curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
source ~/.profile 
nvm ls-remote
nvm install v8.16.0
nvm list
nvm use v8.16.0
node --version
```
