### ISSUE TITLE
Inconsistent URL Slash Display on Documentation Link

### ISSUE THREAD

**Issue by PrathamSikka24** [hyperledger/caliper#1535]
### Which Caliper version are you using?

v0.5.0

### Which Node.JS version are you using?

v18.19.1

### Which operating system are you using?

Ubuntu 22.04.3 LTS(through WSL)

### Please provide some context for your error. For example, when did the error occur? What were you trying to achieve, and how?

![Untitled-2024-03-17-2354](https://github.com/hyperledger/caliper/assets/116445216/1d4b2587-fc86-42ec-9cdc-356ae405a292)
While browsing the Hyperledger Caliper documentation (version 0.5.0), I noticed a discrepancy in the URL path shown in the browser's status bar preview when hovering over the 'Documentation' link.

Objective: I was browsing the documentation.

### What was the observed incorrect behavior?

The status bar URL preview displays an extra slash (i.e., //) in the URL path, which is not consistent with the actual URL path in the address bar, which has a single slash (/). This was observed on the 'Getting Started' page.

### Please provide the error logs and their surroundings.

```text
N/A(Typo in the HTML code that generates the documentation pages.)
```

### Please provide any additional information you deem relevant to the error.

It may seem a little trivial, but it should ideally be corrected for consistency and to adhere to URL standards.

**Comment by PrathamSikka24** [comment]
I've submitted a pull request that addresses this issue: [PR link](https://github.com/hyperledger/caliper/pull/1536)

This PR implements the necessary fix to ensure correct URL formatting in the documentation link, as discussed in this issue. Merging this PR should resolve the issue. 

Thank you for your time and consideration.

**Comment by davidkel** [comment]
@PrathamSikka24  your PR #1532 fixed this and has been merged so will close.

**Comment by PrathamSikka24** [comment]
@davidkel Yes, that sounds good. Looking forward to contributing more.
