### ISSUE TITLE
On the next release of caliper after 0.5.0 we should remove the fisco-bcos logo from the main page

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper#1537]
ie
- update index.html
- delete assets/img/logos/fisco.svg

This is consistent with other connectors still available in older versions of caliper but have since been removed.

**Comment by vinayakjaas** [comment]
@davidkel  can you assign this task to me I am happy to tackle this issue

**Comment by davidkel** [comment]
@vinayakjaas Sorry we can't actually do anything until we release another version of caliper. At this time there is no schedule for that but I suspect it won't be till at least the end of the year. So I don't think it's worth assigning it to you yet.

**Comment by davidkel** [comment]
Due to a security issue in caliper we needed to do a release which included the removal of fisco-bcos. So this was done as part of the release process.
