### ISSUE TITLE
Missing Link: Deploy Hyperledger Caliper

### ISSUE THREAD

**Issue by Mohiit70** [hyperledger/caliper#1550]
The Deploy Hyperledger Caliper link is absent on the Caliper project page, hindering users from accessing deployment guidance. 

link: https://www.hyperledger.org/projects/caliper

**Comment by davidkel** [comment]
@Mohiit70 Already noted this in #1542. Not sure how to get the page updated as yet but I can tell you that the update will remove the Deploy Hyperledger Caliper reference. All information that is available is in the Caliper Documentation, can you explain what detail exactly you need to help you use caliper that isn't there that you thought you might find in the Deploy Hyperledger Caliper section ?

**Comment by davidkel** [comment]
The Deploy link has now been removed from the Caliper project page

**Comment by davidkel** [comment]
@Mohiit70 Any specific issues regarding caliper usage please raise them on github. We are aware for example of the need for documenting remote caliper workers but would be really good to get insight into specific areas that are lacking. 

Closing this issue.
