### ISSUE TITLE
A Tutorial on the use of declaritive workloads

### ISSUE THREAD

**Issue by davidkel** [hyperledger/caliper#1567]
Samples in caliper-benchmarks would also be worth considering

**Comment by anshikavashistha** [comment]
May I work on this issue?
@davidkel

**Comment by Ayush9026** [comment]
@davidkel sir I want to solve this issue.

**Comment by duckling69** [comment]
Hey @davidkel I'd like to work on it

**Comment by davidkel** [comment]
Declarative workloads have been dropped as it's incomplete so no point adding any documentation about it
