### ISSUE TITLE
[Enhancement]: Increase test coverage of fixedRate controller.

### ISSUE THREAD

**Issue by rahat2134** [hyperledger/caliper#1570]
### Please share the technical limitation of Caliper that you encountered.

As per the project `Hyperledger Caliper testability and robustness improvement`. I am suggesting to enhance the test suites of fixedRate controller.

### Please detail your feature idea that could alleviate the limitation.

Adding the more robust test suites.

**Comment by rahat2134** [comment]
@davidkel can assign me this issue if feasible.

**Comment by rahat2134** [comment]
@davidkel can you please assign this issue to me is feasible.

**Comment by rahat2134** [comment]
@davidkel PTAL.

**Comment by Sweetdevil144** [comment]
This PR is a sub-part of #1557 to increase overall test suite coverage for entire `rate-control` directory. Can you refer and link to the same for a clearer view?

**Comment by rahat2134** [comment]
Ya! Thanks for noticing @Sweetdevil144 .
