### ISSUE TITLE
TLS problem

### ISSUE THREAD

**Issue by dzqoo** [hyperledger/caliper#163]
Hello ！
My fabric network is running with tls off and how to test its tps with caliper？
Looking forward your reply ！

**Comment by nklincoln** [comment]
specify a target network that has TLS configured to be 'on'. There are numerous topologies within the `network/fabric` directory that you can pick from - use a docker compose file that is flagged as TLS

**Comment by panyu4** [comment]
Since there are not more activities, it will be closed.
