### ISSUE TITLE
Help using kafka for the ordering node

### ISSUE THREAD

**Issue by jamievaravara** [hyperledger/caliper#171]
I am following [this guide](https://hyperledger-fabric.readthedocs.io/en/release-1.2/kafka.html) to create a orderer that uses kafka. However, I am stuck at point seven, as I cannot find the orderer.yaml file. 
Does anybody know where can I find it?

Is this file located inside of the docker containers created by caliper?
Can I create my own? How can I make caliper consume this file when creating the docker containers?

**Comment by jamievaravara** [comment]
Is this file located inside of the docker containers created by caliper?
Can I create my own? How can I make caliper consume this file when creating the docker containers?

**Comment by aklenik** [comment]
Since the question is not a Caliper issue, I'm closing this thread.
