### ISSUE TITLE
Can you support tronprotocol?

### ISSUE THREAD

**Issue by wangzichichi** [hyperledger/caliper#183]
Hello，I am a block chain development enthusiasts.
Recently, I found tronprotocol support smart contract right now. 
Do you have plan to support tronprotocol in your project?
The tronprotocol url is below:
https://github.com/tronprotocol/java-tron

**Comment by panyu4** [comment]
We have no plan to support tronprotocol.  If you'd like to contribute supporting it,  we appreciate it.

**Comment by aklenik** [comment]
Since the support is not planned in the foreseeable future, I'm closing this thread.
