### ISSUE TITLE
Support for Fabric versions above 1.1

### ISSUE THREAD

**Issue by luigima** [hyperledger/caliper#185]
I am currently working on a Fabric network that leverages private data collections that are only available from Fabric v1.2+. Unfortunately I did not manage to get caliper working with versions above 1.1 yet. Are there any tips or workarounds available? Are there any plans to support newer versions and if so, what is the current state? 

Adjusting the versions of fabric-client and fabric-ca-client while using the correct docker images did not work. I get invalid endorsement system chaincode errors while instantiating.

**Comment by aklenik** [comment]
@luigima I'm almost (~80%) finished with the support for newer versions (and features). As soon as I have a working code-base (with a minimal documentation), I'll drop you the link of the fork here, so you can help the reviewers test it :) Expect it in 2-3 days.

**Comment by luigima** [comment]
This would be awesome! Thank you in advance!

**Comment by jiawanggao** [comment]
@aklenik how to get the code for supporting Fabric v1.2?thanks!

**Comment by aklenik** [comment]
@jiawanggao it's not integrated into Caliper (or a fork) yet, but as soon as I have a working fork, I'll drop the repo url here

**Comment by hurf** [comment]
@aklenik Would create a PR and marked with WIP be better? People can disscuss here instead of looking for other repos.

**Comment by aklenik** [comment]
@hurf Will do that, good idea, but currently, my Fabric adapter implementation is in a sandbox project, but I'll open a WIP PR as soon as it's integrated into my Caliper fork.

**Comment by luigima** [comment]
@aklenik Any news regarding a working fork that I could test?

**Comment by lichanan** [comment]
> @jiawanggao it's not integrated into Caliper (or a fork) yet, but as soon as I have a working fork, I'll drop the repo url here
where is the url?could you publish it here

**Comment by aklenik** [comment]
New releases of Fabric are now supported by both adapter
