### ISSUE TITLE
Sawtooth: BatchBuilderFactory - Custom Batch Builders

### ISSUE THREAD

**Issue by mtrubs** [hyperledger/caliper#189]
I was looking at the `sample` and `smallbank` sawtooth examples. I noticed that they have all their configuration in the `benchmark/*` directories. This is great and isolated. However, there is one file for each in `src/sawtooth/Application/*BatchBuilder.js`.

Is the intention to clone and modify the caliper project vs having a new project with caliper as an npm dependency? I do not see any other way to add a new `BatchBuilder` for specific use cases. I can happily add a `BatchBuilderFactory.register` or something to that end. But thought I would check first before implementing something and issuing a PR.

**Comment by mtrubs** [comment]
here is roughly what i was thinking anyways.

the paths in all the files are still all wonk but it works.

https://github.com/mtrubs/caliper/commit/052e59a42216a43cbde207ff106cf41723914f35

**Comment by feihujiang** [comment]
This was resolved, so closed it.
