### ISSUE TITLE
Refactoring Promise chains to async/await

### ISSUE THREAD

**Issue by aklenik** [hyperledger/caliper#192]
Advantages of the async/await pattern:
1. Makes the code more readable.
1. Results in cleaner error messages and stack traces, simplifying debugging.
1. Simplifies error handling to the traditional try-catch pattern.

Refactoring is required for the following `caliper-core` files:

- [ ] caliper monitor within caliper-core/lib/monitor/*.js
- [ ] caliper zoo client within caliper-zoo-client/cient-orchestrator/zoo-util

**Comment by nklincoln** [comment]
@aklenik - can this be closed now? iirc the promise chains have been eliminated

**Comment by aklenik** [comment]
@aklenik In most of the code-base, yeah. I don't know about the monitoring & reporting components.

**Comment by nklincoln** [comment]
I'll update the description to point to the caliper-core items that still require attention 👍

**Comment by nklincoln** [comment]
closing this as the zoo-client is set to be removed, and we are looking at an overhaul of the monitor to use Prometheus/Grafana instead
