### ISSUE TITLE
Some questions about the endorsement policy.

### ISSUE THREAD

**Issue by cao0507** [hyperledger/caliper#197]
`"endorsement-policy": {                                                   
      "identities": [
        {
          "role": {
            "name": "member",
            "mspId": "Org1MSP"                                                
          }                                                                   
        },
        { 
          "role": {
            "name": "member",                                                 
            "mspId": "Org2MSP"                                                
          }
        },
        { 
          "role": {
            "name": "admin",
            "mspId": "Org1MSP"                                                
          }                                                                   
        }
      ],
      "policy": { "2-of": [{"signed-by": 0}, {"signed-by": 1}]}               
    }`
- Why Org2 don't contain the "admin" role? 
- What's the meaning of "2-of"? Does this mean "AND" or "OR"? And how to express "AND" "OR" "N-OutOf" ?
- And what's the meaning of "signed-by": 0 and "signed-by": 1 ? What is "0" and "1"?

**Comment by cao0507** [comment]
Oh，I have known the answer of these questions. These endorsement policies are the expression of the SDK, and have some differences with the CLI's expressions. I would close this issue.

**Comment by lenoAlex** [comment]
@cao0507 , could you give me a specification about these questions you mentioned above? I am also confused about them. Or any net referred to? thank you.
