### ISSUE TITLE
Docker network default name error

### ISSUE THREAD

**Issue by aklenik** [hyperledger/caliper#198]
## Context

The example `docker-compose` network files don't specify a network name explicitly. The default name is derived from the directory name where the compose file resides. Some versions of `docker-compose` (e.g., `1.22.0`) leave that name as-is (with dashes for example), while older versions (e.g., `1.18.0`) remove the dashes from the directory name. 

The network names set for the peers use the dash-less naming, e.g., `CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=2org1peer_default`, but this network won't exist with newer `docker-compose` versions, because they will create a `2-org-1-peer_default` network.

## Expected Behavior

The benchmark should complete successfully. 

## Actual Behavior

```
ok 3 Installed chaincode marbles successfully in all peers
# Instantiate chaincode......
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error starting container: API error (404): {"message":"network 2org1peer_default not found"}
    
at new createStatusError (/home/klenik/projects/caliper-master/node_modules/grpc/src/client.js:64:15)
    at /home/klenik/projects/caliper-master/node_modules/grpc/src/client.js:583:15
```

## Possible Fix

Newer docker-compose file versions (from 3.5) support explicit network names. But a more backward compatible solution would be to avoid dashes in the directory names containing `docker-compose` files.

## Steps to Reproduce
Make sure you have, for example, the following `docker-compose` version installed:
`docker-compose version 1.22.0, build f46880fe`

In the Caliper directory:
1. `npm install`
2. `npm install grpc@1.10.1 fabric-ca-client@1.1.0 fabric-client@1.1.0`
3. `cd benchmark/marbles`
4. `node main.js -c config-fabric-go.json`

## Your Environment

* Version used: `master@b9d4db2`
* Environment name and version: `Node.js v8.11.4`, `go version go1.10.4 linux/amd64`, `Docker version 18.06.1-ce, build e68fc7a`, `docker-compose version 1.22.0, build f46880fe`
* Operating System and version: Ubuntu 18.04 LTS

**Comment by vamdivd** [comment]
I have the same problem with you. Has the problems be solved?

**Comment by vamdivd** [comment]
I really appreciate it, have a good day :)
