### ISSUE TITLE
Fabric query invocations depend on the block time parameter 

### ISSUE THREAD

**Issue by luigima** [hyperledger/caliper#199]
Queries on the blockchain are typically not sent to the orderer service since no change to the world state is done. Yes, you could do that in order to proof knowledge but in general this is not desired. 
So if I want to query the world state I would simply query the state database in a direct way. In Caliper, however, it seems that a query is endorsed and processed just like write transactions.
   
## Expected Behavior
Benchmarking a query function should be performed instantly without any block time latency.

## Actual Behavior

Query functions are incompleted until a new block is created.
 
## Steps to Reproduce

1. Increase the parameters sufficiently:
- BatchTimeout: 120s 
- MaxMessageCount: 99999
- AbsoluteMaxBytes: 500 MB
- PreferredMaxBytes: 500 MB
3. Create a benchmark that performes queries with a sufficient timeout parameter. The queries will be in a pending state for up to two minutes.

**Comment by aklenik** [comment]
@luigima The query is endorsed (i.e., the transaction is simulated by executing the chaincode), however, it [isn't submitted](https://github.com/hyperledger/caliper/blob/7d70116f83e64dc604319440e84d79a7765c9564/src/fabric/e2eUtils.js#L764) for ordering and committing. 

What example did you run? Note, that the query API can only receive 1 argument for the query function.

**Comment by aklenik** [comment]
@luigima Is this issue still present?
