### ISSUE TITLE
NO_NODE: Exception: NO_NODE[-101]

### ISSUE THREAD

**Issue by kite007** [hyperledger/caliper#201]
NO_NODE: Exception: NO_NODE[-101]

## Context

I am trying to run benchmark with Distributed Clients(using zookeeper).
(my environment)
1. host 1~host 5: Fabric Network
-   host 1: Orderer, Kafka, zookeeper
-   host 2: Peer1
-   host 3: Peer2
-   host 4: Peer3
-   host 5: Peer4
2. host 6: Zookeeper for Caliper (ex: ip 192.168.10.100)
3. host 7: Caliper Clients (clientsPerHosts: 5)
3. host 8: Caliper Clients (clientsPerHosts: 5)

I ran 'npm run starclient -- 192.168.10.100:2181' in terminal#1 and 'node benchmark/fabric/main.js' in terminal#2 on host7.
I ran 'npm run starclient -- 192.168.10.100:2181' in terminal#1 and 'node benchmark/fabric/main.js' in terminal#2 on host8.

Is it right?

I got error messages irregularly in this situation.
NO_NODE: Exception: NO_NODE[-101]
.....

I searched it on google. 
"NO_NODE means that requested node does not exist."
I don't know it. 

Do you guide me how to install and config zookeeper for Caliper? 

For referene, 
I succeeded to run benchmark on distributed clients with only host7 without host8 .
It works well. 

## Actual Behavior

[Transaction Info] - Submitted: 1010 Succ: 1010 Fail:0 Unfinished:0
NO_NODE: Exception: NO_NODE[-101]
    at ConnectionManager.onSocketData (/home/fabric/testformimas/caliper/node_modules/node-zookeeper-client/lib/ConnectionManager.js:570:35)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)

## Your Environment

* Ubuntu 16.04.5 LTS
* Fabric v1.2
* Zookeeper for Caliper : zookeeper-3.4.12
* node v8.11.4
* npm v5.6.0

**Comment by panyu4** [comment]
Now Caliper has not been able to support FabricV1.2. But @aklenik are working on this.  Please look at issue #185.

**Comment by kite007** [comment]
> Now Caliper has not been able to support FabricV1.2. But @aklenik are working on this. Please look at issue #185.

I see. I read caliper readme file. But, I tried to run benchmark for fabric 1.2 and Caliper works well on Fabric 1.2. 
I installed grpc@1.10.1, fabric-ca-client@1.2.2, fabric-client@1.2.2. 

I have only problem to run benchmark on distributed clients installed on multi hosts.

**Comment by kite007** [comment]
> @panyu4 @kite007 Caliper can run against Fabric v1.2 with the 1.2.0 SDK, however, the 1.2 features are not supported (like private collections). But at least you get a nice performance improvement with Fabric 1.2 :)
> 
> As for zookeeper, double check your endpoint addresses and that the hosts can reach eachother.

Thanks to your comment. 

Like your comment, I used Caliper well to run benchmark for Fabric v1.2 without private collection.
I love Caliper! ^^

But, I am so sorry I don't understand your comment for Zookeeper. 
What do you mean "double check your endpoint addresses and that hosts can reach each other."

1. endpoint address
Are these endpoint addresses host7 address(e.g, 192.168.100.17) and host 8 address(e.g, 192.168.100.18)?

2. hosts can reach each other.
Ping work well between host7 and host8.

**Comment by kite007** [comment]
![image](https://user-images.githubusercontent.com/16068648/47625718-36f76780-db6a-11e8-920a-30182345f029.png)

Is it right?
Is it possible?

**Comment by houqinghui** [comment]
@kite007    are there some clients running on the host8, or host8 is just for the zk?

**Comment by kite007** [comment]
> @kite007 are there some clients running on the host8, or host8 is just for the zk?

I executed zookeeper server at host8 only.

**Comment by aklenik** [comment]
@kite007 Maybe [this issue](https://github.com/SOHU-Co/kafka-node/issues/12) can point you to the right direction. Let us know how it goes!

**Comment by kite007** [comment]
> @kite007 Maybe [this issue](https://github.com/SOHU-Co/kafka-node/issues/12) can point you to the right direction. Let us know how it goes!

Thanks for your comment.
I will try again it according to your comment.

**Comment by aklenik** [comment]
@kite007 Did you succeed?
