### ISSUE TITLE
Add unified logging framework

### ISSUE THREAD

**Issue by panyu4** [hyperledger/caliper#207]
## Context

Currently, logging is delegated directly to the console, which mixes the progress messages and the error messages. It would be easier if the console only contained filtered and readable progress/error messages, while log files contained detailed debug/trace messages that can be shared easily as files with the team instead of copying its content into the issue description.
## Possible Fix

The Node SDK created a quite nice logging mechanism utilizing winston, it could be reused in a license-compatible way.

**Comment by panyu4** [comment]
#208

**Comment by aklenik** [comment]
Implemented by PR #208
