### ISSUE TITLE
Move platform dependent properties to the network config files

### ISSUE THREAD

**Issue by aklenik** [hyperledger/caliper#218]
## Context
Currently, every `command.start` and `command.end` scripts in the testing-related config files (`config*.json`) are used to start and stop the DLT network under test. This makes the config files platform dependent (like `config-fabric.json`, `config-iroha.json`, `config-sawtooth.json`), while (almost) every other part is platform-independent. The same goes for the `blockchain` property in these config files. 

## Expected Behavior
The test-related config files shouldn't contain platform-specific information, just testing/round-related settings.

## Possible Fix
The network config files should have a `caliper` section. This section could contain the `start` script, `end` script and blockchain type information. Bonus: this way the network config file will contain the script that starts the appropriate network, making it easier to ensure the consistency between the network and its config.

(The test-related config files can also contain start and end scripts, but these shouldn't be used for platform-specific initialization.)

**Comment by feihujiang** [comment]
This was resolved, close it.
