### ISSUE TITLE
Javascript Linting Required

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#22]
In order help readability of all project code, and to enforce coding consistency for contributors, it would be of great help to add linting rules into the project via eslint.

This will unfortunately require a bit of a code refactor once the rule file is added and enforced, however it will help with code contribution as the project evolves.

**Comment by haojun** [comment]
+1, @feihujiang will help handle it

**Comment by nklincoln** [comment]
I'm happy to initiate this one and start working on it. My proposal would be to:
- add an eslint package dependancy
- add an npm script command to run the lint checker
- introduce a standard javascript linting file
- fix all Composer contributions to resect the linting configuration
- add an eslintignore file with all other files ignored

It would then be possible to address linting considerations in all other files in a systematic way, and once all required linting errors are corrected, we could make this as complete?

A side issue here is that there is looking to be a need for some kind of automated build mechanism for Caliper (Jenkins/Travis) that could automatically run the linting as a build task and prevent any new code being added that does not adhere to the linting rules.

**Comment by feihujiang** [comment]
:+1:

**Comment by haojun** [comment]
Hi @nklincoln, that's great :+1: 
To be honest, @feihujiang and I don't have much time to do it recently. So it would be very helpful if you could take over the work to add support for eslint and CI (travis, maybe) .

**Comment by nklincoln** [comment]
OK -I will start the above, is there a way that you can assign this to me so that nobody else picks it up in the interim?

**Comment by subhodi** [comment]
@nklincoln I can help you with JSlinting. I have done JS linting for Caliper forked REPO with the help of eslint file and [VS code extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint).

**Comment by nklincoln** [comment]
Hi @subhodi - it looks like this issue has now been replaced by #48, which is splitting out the remaining files to be made compatible with the linting.

@haojun - would you like this issue closed off so that #48 can be worked on instead?

**Comment by haojun** [comment]
Closed
