### ISSUE TITLE
Caliper test reports showing inflated values for throughput

### ISSUE THREAD

**Issue by hariharan-avs** [hyperledger/caliper#226]
## Summary
The throughput obtained from test is very high than the provided input.

## Context
The caliper test is run in Sawtooth Nightly (1.1) on AWS

## Expected Behavior
Input 70 tps throughput 70 or lesser tps 

## Actual Behavior
Input 76 tps : throughput 117 and shows fabric docker images which are not used for this test.

## Steps to Reproduce
1. Install Sawtooth 1.1 Nightly on VMs in AWS instance
2. Install caliper on AWS
3. start sawtooth and run caliper tests with respective sawtooth.json rest end points
4. obtain caliper report

[report20181119T092133.zip](https://github.com/hyperledger/caliper/files/2607535/report20181119T092133.zip)

**Comment by houqinghui** [comment]
@hariharan-avs  do you solve your problem? or you can list the detailed log.

**Comment by nklincoln** [comment]
looks to have been fixed in the above ... closing
