### ISSUE TITLE
Support for Fabric versions 1.3

### ISSUE THREAD

**Issue by lenoAlex** [hyperledger/caliper#227]
I am currently working on a Fabric network test that are only available from Fabric v1.3.  Are there any tips or workarounds available? Are there any plans to support newer versions and if so, what is the current state?

Adjusting the versions of fabric-client and fabric-ca-client while using the correct docker images did not work.

**Comment by aklenik** [comment]
@lenoAlex The support for Fabric 1.3 is on the way, sometimes this week (upper bound).

**Comment by lenoAlex** [comment]
@lenoAlex Is there a working fork that I could test? I developed some features base on  Fabric v1.3 and want to get some benchmark.

**Comment by luigima** [comment]
Does the release date for 1.3 support still hold @aklenik?

**Comment by lenoAlex** [comment]
@aklenik Any news regarding the release date for 1.3 support?

**Comment by luigima** [comment]
Reminds me of my issue some weeks ago :P #185

**Comment by aklenik** [comment]
@luigima @lenoAlex The new adapter is basically finished, but I still have to add example benchmarks and networks, plus the documentation of course :) But it's good to know that everyone is anxious to try it, it's a good kind of pressure :P

**Comment by panyu4** [comment]
@lenoAlex @luigima @aklenik currently, caliper is able to support fabric v1.3 by the pr #279 . Pr #296 has tried a new fabric adapter, and after it is merged, you can play with fabric v1.3 by this new adapter.

**Comment by aklenik** [comment]
Both Fabric adapters now support newer Fabric releases
