### ISSUE TITLE
Simplify base configuration for tests using nom scripts

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#229]
It would streamline the user experience by having a set of npm scripts to run in order to install blockchain platform dependancies instead of having to search the docs

## Context
A user must run commands listed in the docs, rather than a simpler `npm run install-deps` script

## Expected Behavior
Life should be easy for a user

## Possible Fix
Add npm scripts and modify the docs to reflect the change

**Comment by aklenik** [comment]
PR #230 resolves this issue
