### ISSUE TITLE
Error while executing the benchmark: Error: Cannot find module 'fabric-ca-client/lib/FabricCAClientImpl.js'

### ISSUE THREAD

**Issue by zcyzhu** [hyperledger/caliper#231]
When I use the command line 
`node benchmark/simple/main.js`
something goes wrong，

`Error while executing the benchmark: Error: Cannot find module 'fabric-ca-client/lib/FabricCAClientImpl.js'`
I have already installed fabric-ca-client

**Comment by MuckT** [comment]
@aklenik I am receiving the same error using the same steps with fabric-ca-client@1.3.0.

**Comment by aklenik** [comment]
@MuckT @zcyzhu The current adapter only supports Fabric up to the 1.2 version (inclusive). The required CA implementation file is probably moved into another directory in 1.3.0.

**Comment by YanLIU0822** [comment]
I  meet the same issue. I solve this issue by uninstalling fabric-ca-client@1.14.0 and installing fabric-ca-client@1.2.0
hope it works for you guys

**Comment by panyu4** [comment]
@zcyzhu , this is caused by the not match fabric SDK and Caliper. Now this problem is resolved by recently pr #279 . So close it.
