### ISSUE TITLE
Fabric chaincode life-cycle handling

### ISSUE THREAD

**Issue by aklenik** [hyperledger/caliper#24]
We ran into the following problem in the `src/fabric/e2eUtils.js invokebycontext()` implementation while load testing Fabric 1.x :

The resolved return value of the [sendTransaction](https://github.com/hyperledger/caliper/blob/fbc8c09f405aac7348929c901be43a69df2fa6d7/src/fabric/e2eUtils.js#L597) call is a `BroadcastResponseObject` which only contains an HTTP ACK from the orderer that it received the Tx successfully. 

If this response arrives and it contains an invalid status code, then we know the Tx ordering will not happen, it was rejected explicitly for some reason. So far so good.

There were times during our load testing when this response did not arrive in time/at all (probably due to network latency reasons). In this case, Caliper marked the Tx as `failed`. However, we received valid event notifications for the Tx, meaning it was successfully committed to the ledger. So this is a false negative result.

I rewrote the life-cycle handling logic in my fork the following way. Note the introduction of the _verified result_ concept.
1. `channel.SendTransactionProposal` call result:
    1. Rejected Promise: Something happened, we terminate the life-cycle early. So this `failed` status is _verified_.
    1. Resolved `ProposalResponseObject`: we received a reply from the endorsing peers:
        1. If any response status is not `200`, there was a chaincode execution error, and the Tx is not endorsed. So this `failed` status is _verified_.
        1. If all responses are valid, but there is a read/write set mismatch, the peers would reject the Tx eventually, so we terminate the life-cycle early. So this `failed` status is _verified_.
        1. Otherwise, we have valid endorsements at this point.

1. Register Tx events Promises and callbacks:
    1. A timeout occurs, resulting in a rejected Promise. We did not get an explicit rejection from the peers. So this fail is _not verified_.
    1. The error callback is invoked from `registerTxEvent`, meaning there was some (probably) connection error with the event hub (it happened during high loads). We did not get an explicit rejection from the peers. So this fail is _not verified_.
    1. The "normal" callback is invoked from `registerTxEvent`. If the returned `code` is not `VALID`, then the Tx was rejected explicitly. So this `failed` status is _verified_.
    1. If the returned `code` is `VALID`, the Tx was committed to the ledger. This commit is a _verified_ result and is also independent of the orderer ACK error in the next section.

1. `channel.sendTransaction` call result:
    1. Rejected Promise: we did not receive an ACK from the orderer for some reason. But this does not mean, that the orderer will not consider the Tx for ordering. So this is _not_ a verified failure.
    1. Resolved `BroadcastResponse` object:
        1. The response status is `SUCCESS`, meaning the orderer will order the Tx. (The `invoke_status.time_order` property name is misleading, this is only the time it took to receive the ACK from the orderer, and not the ordering time itself.)
        1. The response status is not `SUCCESS`, meaning the Tx is explicitly rejected for ordering, resulting in a _verified_ failure. 

1. Wait for all event Promises:
    1. If all Promises resolved successfully, then the Tx is successful in a _verified_ manner.
    1. In case of rejected event Promise, the logic described in section 2. applies to decide whether the failure is verified or not.

1. At this point, the standard life-cycle ends, and the final time for both successful and failed Txs is recorded, also indicating whether the failure is verified or not (note, that the success of a Tx is always explicitly verified by the resolved events).

1. **(Optional Step)** If a failure is not verified, then there is an option to explicitly query the ledger for the given Tx to verify the result. However, a certain amount of sleep time is needed to make sure that the Tx is through its life-cycle and can be queried. 

I would appreciate Your opinions on this logic since as it turns out, writing a robust and reliable client for Fabric is far from trivial!

**Comment by haojun** [comment]
If I understand you correctly, the problem is that a transaction may has been committed even if sendTransaction returns a rejected promise.

A easy way to correct it is ignoring the REQUEST_TIMEOUT error and continuing waiting for all event promises. For other known errors such as SERVICE_UNAVAILABLE, there is no reason to continue, right?

What's your opinion?

BTW: since step 6 is optional, when would it be applied?

**Comment by aklenik** [comment]
Exactly. In my fork, I essentially ignore the orderer response (only log the error). The event results will determine the final status of the transaction. 

Another thought: I use `Promise.All` on the event promises, but `Promise.Any` would be enough I think. If one peer successfully commits the transaction, then every other peer will commit it eventually, so the occasional event hub error of one/some peers should not deem the transaction failed. However, if I want to calculate percentile-based commit times (as discussed by the PSWG), then I need every event notification. 

About step 6: it is a little fuzzy whether this should be performed in the `invokebycontext` function, or as a post-processing step after the round that queries every failed, but not verified transaction. And whether to incorporate that query time somewhere or not. As a first step, I think Caliper should be able to mark such transactions as "verified after the life-cycle" to avoid false negative results and give the option for data analysts to ignore such transaction times during the analysis.

**Comment by haojun** [comment]
It sounds good. Would you please submit the PR? I'll be very happy to review it, thanks.
