### ISSUE TITLE
I am using node benchmark/simple/main.js on caliper, I get an error.

### ISSUE THREAD

**Issue by zcyzhu** [hyperledger/caliper#249]
```
error: [bench-flow.js]: Error: TypeError: Cannot read property 'network' of undefined
    at Object.module.exports.init (/home/zcy/new project/caliper/src/fabric/util.js:140:15)
    at Fabric.init (/home/zcy/new project/caliper/src/fabric/fabric.js:39:14)
    at Blockchain.init (/home/zcy/new project/caliper/src/comm/blockchain.js:66:26)
    at Object.module.exports.run (/home/zcy/new project/caliper/src/comm/bench-flow.js:313:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
This is my environment，
```
zcy@ubuntu:~/new project/caliper$ npm list grpc
caliper@0.1.0 /home/zcy/new project/caliper
├─┬ fabric-client@1.2.0
│ └── grpc@1.10.1  deduped
└── grpc@1.10.1 
```

**Comment by nklincoln** [comment]
based on the existence of #250 - I'm assuming that you have managed to get the benchmark running and so this issue can be closed?

**Comment by houqinghui** [comment]
@zcyzhu  it means that the network config file is not parsed rightly , or the network config file donot have the property 'network'.  first check the newwork config file, if the file is complete, you can run the benchmark again.  
if you have solved the error, please share the way to solve the problem.

**Comment by zcyzhu** [comment]
@nklincoln This failed to test on cd caplier, and my success was tested on cd caliper/benchmark/composer

**Comment by chenshiok** [comment]
I got this error too. Error message:
`ubuntu@ubuntu02:~/caliper/benchmark/simple$ node ./main.js -c config-test.json -n fabric-test.json
info: [bench-flow.js]: ####### Caliper Test ######
error: [bench-flow.js]: Error: TypeError: Cannot read property 'network' of undefined
    at Object.module.exports.init (/home/ubuntu/caliper/src/fabric/util.js:140:15)
    at Fabric.init (/home/ubuntu/caliper/src/fabric/fabric.js:39:14)
    at Blockchain.init (/home/ubuntu/caliper/src/comm/blockchain.js:66:26)
    at Object.module.exports.run (/home/ubuntu/caliper/src/comm/bench-flow.js:313:26)
    at /home/ubuntu/caliper/benchmark/simple/main.js:78:29
    at main (/home/ubuntu/caliper/benchmark/simple/main.js:82:7)
    at Object.<anonymous> (/home/ubuntu/caliper/benchmark/simple/main.js:85:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
`
And my network file:
`{
    "caliper" : {
        "blockchain": "fabric",
        "command" : {
         }
    },
    "fabric": {
        "cryptodir": "network/fabric/config/crypto-config",
        "network" : {
            "orderer" : {
                "url": "grpcs://localhost:7050",
                "mspid": "OrdererMSP",
  ...
`

**Comment by houqinghui** [comment]
@chenshiok you can try the command `node main.js -c config-test.json -n fabric-test.json`, now we change the config file format from json to yaml, you can folk the latest version.

**Comment by zcyzhu** [comment]
![1544059256 1](https://user-images.githubusercontent.com/38487249/49554727-48d1e480-f938-11e8-82ff-5ced07482497.jpg)
There is no fabric-related configuration file in the benchmark/simple file in the latest code I downloaded.

**Comment by houqinghui** [comment]
@zcyzhu  
![image](https://user-images.githubusercontent.com/13465812/49555621-78ceb700-f93b-11e8-85f9-0fdb9ab1b701.png)
now  the network config is moved to other directory.

**Comment by chenshiok** [comment]
@houqinghui Because I already start fabric network, so I set the command empty. And I tried the command "node main.js -c config-test.json -n fabric-test.json", but still not work. Maybe config and network file shoud  convert to yaml?

**Comment by houqinghui** [comment]
@chenshiok we convert the config file from json to jaml at the latest version, you can try the command `node main.js`  to use the default config file.

**Comment by chenshiok** [comment]
@houqinghui My test on fabric 1.2.0, so I installed fabric-client@1.2.0 and fabric-ca-client@1.2.0. I guess  may be the fabric-client version's problem, because fabric-client@1.1.0 is ok.

**Comment by lichanan** [comment]
> @houqinghui My test on fabric 1.2.0, so I installed fabric-client@1.2.0 and fabric-ca-client@1.2.0. I guess may be the fabric-client version's problem, because fabric-client@1.1.0 is ok.
不支持1.2的网络

**Comment by aklenik** [comment]
@chenshiok @lichanan For some unknown reason, the configuration file isn't loaded by the 1.2 SDK. I've worked around this issue, submitting it tonight/tomorrow morning.

**Comment by lichanan** [comment]
> @chenshiok @lichanan For some unknown reason, the configuration file isn't loaded by the 1.2 SDK. I've worked around this issue, submitting it tonight/tomorrow morning.
 it's also dose not work on fabric1.2

**Comment by aklenik** [comment]
PR #260 solves the config load problem for SDK 1.2. @lichanan @chenshiok @zcyzhu Can you confirm this?

**Comment by lichanan** [comment]
> PR #260 solves the config load problem for SDK 1.2. @lichanan @chenshiok @zcyzhu Can you confirm this?

thank you for your contribute,i tried , on Instantiating channel phase ,it's timeout

**Comment by aklenik** [comment]
@lichanan But that means you get past the `network` not found error. Chaincode instantiation timeout can mean an error during the `Init` function of your chaincode. Check the chaincode container logs (before the timeout occurs, because then the container is cleaned up).
