### ISSUE TITLE
I successfully ran node main.js on composer, but the result of the test is this

### ISSUE THREAD

**Issue by zcyzhu** [hyperledger/caliper#250]
![1543926568 1](https://user-images.githubusercontent.com/38487249/49442269-f8f20100-f803-11e8-86be-86e40ab760e9.png)
My cpu share has exceeded 100%!! Why?

What is the difference between dev-peer0.org1.example.co...0.1.0 and peer0.org1.example.com? What do they mean? What does Traffic In and Traffic Out and Disc Read mean? What do the names in docker mean? Why is there a difference between CPU(max) and CPU(avg)? Please explain

**Comment by aklenik** [comment]
@zcyzhu For general questions please use the Rocket.Chat [#caliper](https://chat.hyperledger.org/channel/caliper) channel or the [Caliper mailing list](https://lists.hyperledger.org/g/caliper). GitHub issues should only be raised for confirmed bugs or enhancement suggestions.
