### ISSUE TITLE
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error starting container: Failed to generate platform-specific docker build: Failed to pull hyperledger/fabric-ccenv:arm64-1.1.1-snapshot-feed00ad6:

### ISSUE THREAD

**Issue by Priyanshi52** [hyperledger/caliper#252]
I am running caliper on the following node-
_Name: raspberrypi
Kernel Version: 4.11.2-pi64+
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: aarch64_

and using 

**pesicsasa/fabric-ca:aarch64-1.1.0**
insted of 
hyperledger/fabric-ca:x86_64-1.1.0 image
same for orderer,peer and couchDB.

ok 3 Installed chaincode simple successfully in all peers
# Instantiate chaincode......
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error starting container: Failed to generate platform-specific docker build: Failed to pull hyperledger/fabric-ccenv:arm64-1.1.1-snapshot-feed00ad6: API error (404): {"message":"manifest for hyperledger/fabric-ccenv:arm64-1.1.1-snapshot-feed00ad6 not found"}

    at new createStatusError (/home/caliper-master/node_modules/grpc/src/client.js:64:15)
    at /home/caliper-master/node_modules/grpc/src/client.js:583:15
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error starting container: Failed to generate platform-specific docker build: Failed to pull hyperledger/fabric-ccenv:arm64-1.1.1-snapshot-feed00ad6: API error (404): {"message":"manifest for hyperledger/fabric-ccenv:arm64-1.1.1-snapshot-feed00ad6 not found"}

    at new createStatusError (/home/caliper-master/node_modules/grpc/src/client.js:64:15)
    at /home/caliper-master/node_modules/grpc/src/client.js:583:15
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error starting container: Failed to generate platform-specific docker build: Failed to pull hyperledger/fabric-ccenv:arm64-1.1.1-snapshot-feed00ad6: API error (404): {"message":"manifest for hyperledger/fabric-ccenv:arm64-1.1.1-snapshot-feed00ad6 not found"}

    at new createStatusError (/home/caliper-master/node_modules/grpc/src/client.js:64:15)
    at /home/caliper-master/node_modules/grpc/src/client.js:583:15
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error starting container: Failed to generate platform-specific docker build: Failed to pull hyperledger/fabric-ccenv:arm64-1.1.1-snapshot-feed00ad6: API error (404): {"message":"manifest for hyperledger/fabric-ccenv:arm64-1.1.1-snapshot-feed00ad6 not found"}

    at new createStatusError (/home/caliper-master/node_modules/grpc/src/client.js:64:15)
    at /home/caliper-master/node_modules/grpc/src/client.js:583:15
not ok 4 Failed to instantiate chaincodes, Error: Failed to send instantiate due to error: Error: Failed to send instantiate Proposal or receive valid response. Response null or status is not 200. exiting... at Client.newDefaultKeyValueStore.then.then.then.then (/home/caliper-master/src/fabric/e2eUtils.js:372:19) at <anonymous> at Client.newDefaultKeyValueStore.then.then.then.then.then (/home/caliper-master/src/fabric/e2eUtils.js:385:15) at <anonymous>
  ---
    operator: fail
    at: chaincodes.reduce.then.catch (/home/caliper-master/src/fabric/instantiate-chaincode.js:60:19)
    stack: |-
      Error: Failed to instantiate chaincodes, Error: Failed to send instantiate due to error: Error: Failed to send instantiate Proposal or receive valid response. Response null or status is not 200. exiting...
          at Client.newDefaultKeyValueStore.then.then.then.then (/home/caliper-master/src/fabric/e2eUtils.js:372:19)
          at <anonymous>
          at Client.newDefaultKeyValueStore.then.then.then.then.then (/home/caliper-master/src/fabric/e2eUtils.js:385:15)
          at <anonymous>
          at Test.assert [as _assert] (/home/caliper-master/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/home/caliper-master/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/home/caliper-master/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/home/caliper-master/node_modules/tape/lib/test.js:76:32)
          at chaincodes.reduce.then.catch (/home/caliper-master/src/fabric/instantiate-chaincode.js:60:19)
          at <anonymous>
  ...
fabric.installSmartContract() failed, Error: Fabric: instantiate chaincodes failed
    at chaincodes.reduce.then.catch (/home/caliper-master/src/fabric/instantiate-chaincode.js:61:31)
    at <anonymous>
[Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
unexpected error, Error: Fabric: instantiate chaincodes failed
    at chaincodes.reduce.then.catch (/home/caliper-master/src/fabric/instantiate-chaincode.js:61:31)
    at <anonymous>

**Comment by aklenik** [comment]
@Priyanshi52 This is a Fabric side error while building the docker image for the chaincode. Please consult a Fabric-related channel on how to deploy chaincodes on ARM architectures.

(But it looks like your custom peer containers try to build the chaincode image using the `hyperledger/fabric-ccenv:arm64-1.1.1-snapshot-feed00ad6` which doesn't exist in the Hyperledger docker hub repository (https://hub.docker.com/r/hyperledger/fabric-ccenv/tags/))

**Comment by Priyanshi52** [comment]
@aklenik I have fabric-ccenv image for ARM architecture but I am not able to locate where I need to change from hyperledger/fabric-ccenv to ARM supporting image can you please help me with that.
