### ISSUE TITLE
how to test my own smart contract ?

### ISSUE THREAD

**Issue by lybyyy** [hyperledger/caliper#254]
I had run benchmark simple test with caliper.
Now i want to test my smart contract, it does some auditing work for one column of data, if auditing passed. then broadcast to the network, just a simulation, not on a real network.
My question is: which file should I modify?
* I see the path(./src/contract/fabric/simple) has go version and node.js version smart contract, may i edit one of them, modify the function content in the above file and config file in the path(./benchmark/simple/),then run command( node ./benchmark/simple main.js)?
thanks a lot

**Comment by lybyyy** [comment]
@houqinghui
thank you, I think I may solve the above problem, but only 4 clients run benchmark(i see client number 5 is defined in the file ./benchmark/simple/config.yaml, the document mentioned 1 is for sorting, and 4 is peer client), I modify the 5 to 9 to test 8 clients but it doesn't work... 
If I want to test 8 or even 32 clients, what should I do?

**Comment by houqinghui** [comment]
@lybyyy   there are 5 clients , 1 orderer for sorting and 4 peer in the default config.yaml. if you want to define more peers, you should do the steps below.
 a.	Before the test, you should regenerate the artifacts based on the network topology, for example certificates and private key.

b.	Modify the docker-compose.yaml according to your network topology, which can start the docker containers of the blockchain nodes.

c.	Modify the fabric network configuration file according to your fabric network, furthermore you can define your own chaincode to test your network.

d.	Run caliper to test your blockchain network.

**Comment by panyu4** [comment]
Since it was resolved, it is closing.
