### ISSUE TITLE
Enhancement - Fabric adaptor should not use random target peers

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#255]
The Fabric adaptor distributes load across peers using a Math.random operation, which is non-deterministic and can lead to unbalanced loading across the network for typical (n<100) client numbers

## Context
Target peers are chosen using: `peers[Math.floor(Math.random() * peers.length)];` this could be achieved in a more systematic way though `peers[clientIdx % peers.length]` which would cycle the client connections through the available peers

## Possible Fix
Use `peers[clientIdx % peers.length]` and modify interface where required to enable clientIdx to be passed to getContext()

**Comment by aklenik** [comment]
Resolved by PR #256
