### ISSUE TITLE
config.json  Configuring Txnumber and TPS does not take effect！！！ tx  Background transactions are being executed all the time

### ISSUE THREAD

**Issue by zsh122958** [hyperledger/caliper#271]
"test": {
    "name": "zsh",
    "description" : "This is zshbenchmark for caliper",
    "clients": {
      "type": "local",
      "number": 1
    },
    "rounds": [
      {
        "label" : "SendTransaction",
        "txNumber" : [100],
        "rateControl" : [{"type": "fixed-rate", "opts": {"tps" : 10}}],
        "arguments": { "money": 100 },
        "callback" : "benchmark/zsh_simple/SendTransaction.js"
      },
      {
        "label" : "query",
        "txNumber" : [100],
        "rateControl" : [{"type": "fixed-rate", "opts": {"tps" : 10}}],
        "callback" : "benchmark/zsh_simple/query.js"
      }]
  },

**Comment by zsh122958** [comment]
'use strict';

module.exports.info  = 'account_array';

let account_array = [] ;
let bc,cont;
let initMoney;
module.exports.init = function(blockchain, context, args) {
    if(!args.hasOwnProperty('money')) {
        return Promise.reject(new Error('uchains.SendTransaction - "count" is missed in the arguments'));
    }
initMoney = args.money.toString();
bc = blockchain;
cont = context;
return Promise.resolve();
};



/**
 * Generate string by picking characters from dic variable
 * @param {*} len character to select
 * @returns {String} string generated based on @param number
 */
function randomString(len) {
    len = len || 32;
    let $chars = 'ABCDEFGHJKMNPQRSTWXYZabcdefhijkmnprstwxyz2345678';    /****默认去掉了容易混淆的字符oOLl,9gq,Vv,Uu,I1****/
    let maxPos = $chars.length;
    let pwd = '';
    for (let i = 0; i < len; i++) {
        pwd += $chars.charAt(Math.floor(Math.random() * maxPos));
    }
    return pwd;
}


/**
 * initJson Initializes the number of transactions
 * @returns {String} string generated based on @param number
 */
function initJson(){
    let post_data = {
        'txid': randomString(32),
        'dataHash': randomString(32),
        'data': randomString(32),
        'publicKey': randomString(32),
        'signature': Math.random().toString(32).substr(2),
        'remark':'',
        'appId':Math.random().toString(32).slice(2)
    };
    return post_data;
}

module.exports.run = function() {
    let jsonPoe = initJson();
    account_array.push(jsonPoe);
    return bc.invokeSmartContract(cont, 'uchains', 'v0', {verb: 'account_array', account: jsonPoe,money: initMoney}, 100000);
};

module.exports.end = function() {
    return Promise.resolve();
};

module.exports.account_array = account_array;

**Comment by zsh122958** [comment]
/**
     * Invoke the given chaincode according to the specified options. Multiple transactions will be generated according to the length of args.
     * @param {object} context The Fabric context returned by {getContext}.
     * @param {string} contractID The name of the chaincode.
     * @param {string} contractVer The version of the chaincode.
     * @param {Array} args Array of JSON formatted arguments for transaction(s). Each element containts arguments (including the function name) passing to the chaincode. JSON attribute named transaction_type is used by default to specify the function name. If the attribute does not exist, the first attribute will be used as the function name.
     * @param {number} timeout The timeout to set for the execution in seconds.
     * @return {Promise<object>} The promise for the result of the execution.
     */
    async invokeSmartContract(context, contractID, contractVer, args, timeout) {
        commUtils.log('into invokeSmartContract');
        args.forEach(function(item,index){
            commUtils.log('---------------',item.account+'---'+index);
            try {
                let request = require('sync-request');
                let url ='http://'+restApiUrl+':'+configPort+'/UChains/poe/poe/transaction';
                let res = request('POST', url, {
                    json: item.account
                });
                commUtils.log(JSON.parse(res.getBody('utf8')));
                if (JSON.parse(res.getBody('utf8')).code === '0000') {
                    commUtils.log('    >>>>>body    :',JSON.parse(res.getBody('utf8')));
                    let txid= JSON.parse(res.getBody('utf8')).txid;
                    item.account.txid = txid;
                    commUtils.log(' wait >>>>>>>>>>>>>>>>>>>>>');
                    commUtils.sleep(5000);
                    commUtils.log('    >>>>>txid    :',item.account.txid);
                    return Promise.resolve('SUCCESS');
                } else {
                    commUtils.log('END>>>>>>>>>>>>>>>>>>>>>>>>>');
                    return Promise.resolve('ERRO');
                }
            }
            catch(err) {
                commUtils.log(err);
                let badResult = new TxStatus('artifact');
                badResult.SetStatusFail();
                Promise.resolve(badResult);
            }
        });
        return Promise.resolve();

**Comment by zsh122958** [comment]
![image](https://user-images.githubusercontent.com/44695130/50420045-14828180-086f-11e9-9248-0953971f2e4a.png)
![image](https://user-images.githubusercontent.com/44695130/50420071-45fb4d00-086f-11e9-99c0-1eef3588a0c9.png)

**Comment by zsh122958** [comment]
The number of transactions is set to 100, but the background data is always executing.

**Comment by houqinghui** [comment]
@zsh122958  i donot get your pointtt,  can you run caliper successfully?, if successfully, what does the picture  mean?

**Comment by zsh122958** [comment]
@houqinghui   THANKS,Unexpected stop. Query method not executed.

**Comment by panyu4** [comment]
@zsh122958 , does the simple example run well?

**Comment by panyu4** [comment]
would you please list your version of DLT, NodeJS? @zsh122958

**Comment by zsh122958** [comment]
@panyu4  npm 6.5.0  ,  node v11.4.0 , I suspected that syncsync -request was used to cause the execution program to stop and the node in the background kept sending transactions.

**Comment by panyu4** [comment]
@zsh122958 ， Caliper needs the Node with version 8.*, otherwise, some problems may appear.

**Comment by zsh122958** [comment]
@panyu4 Node v8.9 previously reported an error async function, so we upgraded it

**Comment by panyu4** [comment]
Since it is an inactive issue and the cause(wrong node version and wrong adapter)had been found, it will be closed.
