### ISSUE TITLE
Supporting caliper clients in container for swarm network?

### ISSUE THREAD

**Issue by rupc** [hyperledger/caliper#272]
Suggestions for deployment configuration of caliper clients in docker container.

## Context

Caliper needs to specify each address of peers, orderers, and CAs to communicate in network configuration file. 
When running networks in docker swarm, containers including peers, orderers and CAs can find each other through its container names due to a DNS support from swarm. In contrast, caliper clients should know its IP address to communicate with them.

If caliper clients can also run inside container, the clients can contact other containers by its name, not by its IP address.

This feature is especially important when running large-scale distributed networks with caliper because caliper clients should know a mapping between containers and physical machine that the container runs on. But, creating service in swarm network basically doesn't fix the mapping relationship unless using constraint option.

## Expected Behavior

Running caliper client inside docker container

## Possible Fix

Provide option for running caliper client inside docker container

**Comment by houqinghui** [comment]
@rupc  It is a goog idea, we will think over this idea. If you can contribute  to caliper,  it will be very wonderful.

**Comment by aklenik** [comment]
Caliper is now dockerized 👍
