### ISSUE TITLE
Execution error: No such command: down;docker

### ISSUE THREAD

**Issue by GingerMoon** [hyperledger/caliper#278]
Hi, 
When I execute the following command:
 MINGW64 /c/jsworkspace/caliper/benchmark/simple (master)
$ node main.js

I got the following error:
error: [bench-flow.js]: Unsuccessful command execution. Error code: 1. Terminating signal: null
error: [benchmark/simple/main.js]: Error while executing the benchmark: Error: Command failed: docker-compose -f network/fabric-v1.1/2org1peergoleveldb/docker-compose-tls.yaml down;docker rm $(docker ps -aq);docker rmi $(docker images dev* -q)
No such command: down;docker

**Comment by panyu4** [comment]
@GingerMoon would you please list your docker-compose version?

**Comment by feihujiang** [comment]
@GingerMoon Have you resolved this issue?

**Comment by GingerMoon** [comment]
Really sorry guys for the late response. 
For now I am not working on it and I am closing this ticket.

**Comment by nitrousracer** [comment]
Hello,

May you please revisit this problem? I read that this might arise on docker versions less than 1.6 but mine is my docker version is 2.0.0.3, build: 8858db3 and I am not sure how to fix it.

Thank you.

**Comment by panyu4** [comment]
@nitrousracer have you got docker-compose installed? My version is 1.24.0-rc1 and it works.

**Comment by nitrousracer** [comment]
Yes, I have docker-compose version 1.23.2, I will try to update it and update this thread if it worked.

--
Thank you for your prompt response.

**Comment by aklenik** [comment]
@nitrousracer @panyu4 I think we should keep this discussion in Issue #413 since the OS is different and it might be the issue.
