### ISSUE TITLE
Benchmark return code:  null，后台local-client 一直运行。

### ISSUE THREAD

**Issue by zsh122958** [hyperledger/caliper#280]
Benchmark return code:  null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! caliper@0.1.0 e2e: `node ./scripts/test.js "uchains_simple" "./benchmark/uchains_simple/config.json" "./benchmark/uchains_simple/uchains
.json"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the caliper@0.1.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-04T01_24_06_679Z-debug.log
npm ERR! Test failed.  See above for more details.

**Comment by zsh122958** [comment]
[nohup.txt](https://github.com/hyperledger/caliper/files/2725790/nohup.txt)、
This is the output document.

**Comment by houqinghui** [comment]
@zsh122958  are you sure that you installl the correct version such as nodejs, node-npy? please refer to [https://hyperledger.github.io/caliper/docs/1_Getting_Started.html]

**Comment by panyu4** [comment]
Since it is inactive and a resolution had been given, it is closed.
