### ISSUE TITLE
error: [instantiate-chaincode.js]: Failed to instantiate chaincodes: Error: Failed to send instantiate Proposal or receive valid response. Response null or status is not 200.

### ISSUE THREAD

**Issue by YanLIU0822** [hyperledger/caliper#288]
node benchmark/smallbank/main.js works in my system.
and the I run my own code to test TPS 
it met errors

##  Failed to instantiate chaincodes
info: [create-channel.js]: Creating supplychainchannel...
info: [create-channel.js]: Created supplychainchannel successfully
info: [create-channel.js]: Sleeping 5s...
info: [join-channel.js]: Joining channels...
info: [join-channel.js]: Joining supplychainchannel...
info: [join-channel.js]: Successfully joined crop's peers to supplychainchannel
info: [join-channel.js]: Successfully joined supplychainchannel
info: [install-chaincode.js]: Installing chaincodes...
info: [packager/Node.js]: packaging Node from /home/liuyan/supplychain/chaincode/crop/
info: [install-chaincode.js]: Installed chaincode cc_crop successfully in all peers
info: [instantiate-chaincode.js]: Instantiating chaincodes...
error: [instantiate-chaincode.js]: Failed to instantiate chaincodes: Error: Failed to send instantiate Proposal or receive valid response. Response null or status is not 200.
    at Object.instantiateChaincode (/home/liuyan/caliper/src/adapters/fabric/e2eUtils.js:353:19)
    at <anonymous>
error: [fabric.js]: Fabric chaincode install failed: Error: Failed to send instantiate Proposal or receive valid response. Response null or status is not 200.
    at Object.instantiateChaincode (/home/liuyan/caliper/src/adapters/fabric/e2eUtils.js:353:19)
    at <anonymous>
error: [bench-flow.js]: Error: Error: Failed to send instantiate Proposal or receive valid response. Response null or status is not 200.
    at Object.instantiateChaincode (/home/liuyan/caliper/src/adapters/fabric/e2eUtils.js:353:19)
    at <anonymous>
info: [demo.js]: [Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0

## Environment
* liuyan@liuyan-hp:~/caliper$ npm ls grpc
caliper@0.1.0 /home/liuyan/caliper
├─┬ fabric-client@1.1.0
│ └── grpc@1.10.1 deduped
└── grpc@1.10.1

* liuyan@liuyan-hp:~/caliper$ npm ls fabric-client
caliper@0.1.0 /home/liuyan/caliper
└── fabric-client@1.1.0

* liuyan@liuyan-hp:~/caliper$ npm ls fabric-ca-client
caliper@0.1.0 /home/liuyan/caliper
└── fabric-ca-client@1.1.0

* liuyan@liuyan-hp:/caliper$ node -v
v8.15.0
* liuyan@liuyan-hp:/caliper$ npm -v
6.5.0
* liuyan@liuyan-hp:~/caliper$ node-gyp -v
v3.8.0

I also run npm install

ubuntu 16

**Comment by houqinghui** [comment]
@YanLIU0822 does  `I run my own code to test TPS` mean that you modify the configuratioin file to run the caliper or you want to test your custom network?

**Comment by feihujiang** [comment]
@YanLIU0822 Have you resolved this issue? if not, you can uncomment [this line](https://github.com/hyperledger/caliper/blob/master/src/adapters/fabric/e2eUtils.js#L561), and post the information. We can look into the problem later.

**Comment by panyu4** [comment]
@YanLIU0822 Issue #165 gives one solution. You might take a try.
