### ISSUE TITLE
Stale Block Rate for PoET in Sawtooth

### ISSUE THREAD

**Issue by amiecorso** [hyperledger/caliper#298]
## Context
"Stale blocks" refer to blocks that are published and valid, but do not become part of the longest (or heaviest, etc.) chain in a Proof-of-Work style network (probabilistic finality).  A stale (orphan) block occurs when more than one node manages to publish and broadcast a valid block before receiving a previously published block, leading to a temporary fork.  The stale block rate depends on several factors, such as the target length of the block interval, network latency, block size, and information propagation mechanism.  The higher the rate of stale blocks, the higher the overhead involved in processing and validating them, leading to significant disruption of network throughput.  Additionally, the stale block rate is proportional to the ease with which an adversary could potentially generate a long chain with a <50% share of mining power.  Despite the current intention for Sawtooth to be a permissioned network (and thus the relaxed security assumptions) the stale block rate is a crucial metric for assessing performance and evaluating potential improvements to PoET or making network configuration suggestions.
The following paper has a thorough discussion of stale block rate and other PoW-style considerations: https://eprint.iacr.org/2016/555.pdf
This second paper references the above, and deals directly with PoET - proposing changes that may improve throughput at scale: https://arxiv.org/pdf/1804.00399.pdf

## Expected Behavior
It would be great to incorporate stale block rate as an available metric in Caliper for use with Sawtooth and potential future PoW-style blockchain systems.  Stale block rate would be expressed as the number of stale blocks / total blocks. 

## Actual Behavior
This is not currently available in Caliper.

## Possible Fix
I hope to contribute to the implementation of this feature, as I need it to perform performance evaluation and benchmarking work with Sawtooth.  I would appreciate ideas and guidance from those more familiar with the Caliper core and Sawtooth's event subscription system.  I believe that in order to evaluate the stale rate, it would be necessary to record all block events, keep track of block identities, and finally evaluate how many such blocks were ultimately not part of the longest chain.  

I understand that Caliper involves several layers of abstraction that make it possible to interface with different backend systems, not all of which require stale block rate (for example, Fabric and anything that uses deterministic consensus won't generate stale blocks), so it remains to be considered how to incorporate this option from an architectural standpoint.  A config file flag?

**Comment by amiecorso** [comment]
With some help from researchers at National University Singapore, I realized that calculating the stale block rate can be done by finding 1) all the *valid* blocks that any validator has seen and 2) all the blocks that ended up on the main chain.  Simple scripting can be done to comb the docker container logs for all validators, extracting the valid blocks seen by all nodes and placing them in a set, and then comparing the size of this set to the size of the main chain.  This is currently a layer that is operating outside of Caliper functionality in my workflow.  It seems that to build it into Caliper, which has to accommodate back-end systems that may or may not be running on docker containers, one may need to subscribe to validator events.

**Comment by feihujiang** [comment]
1) How could we make the stale block occur?  how many  validators does the sawtooth blockchain need, how long should we test, and other condition?  2) What's the main chain, how to define the main chain? 3) To the sawtooth, Caliper only tests the docker mode. 4) need to subscribe all of the validators events or just one of validators?

**Comment by nklincoln** [comment]
closing as the sawtooth connector has been removed
