### ISSUE TITLE
channel.generateSignedTransaction is not a function in e2eUtils.js is not a function?

### ISSUE THREAD

**Issue by jmj119** [hyperledger/caliper#300]
Hi all,

I could not pass the below test while having failure report on channel.generateSignedTransaction. Can anyone please share any clue on the root cause?

Thanks,
MJ

mjjeon@swarm06:~/caliper$ sudo node benchmark/simple/main.js -c config-file.yaml
[sudo] password for mjjeon:
info: [bench-flow.js]: ####### Caliper Test #######
info: [bench-flow.js]: Executing command: docker-compose -f network/fabric-v1.1/2org1peergoleveldb/dCreating orderer.example.com ... done
Creating network "2org1peergoleveldb_default" with the default driver
Creating peer0.org2.example.com ... done
Creating orderer.example.com ...
Creating ca.org2.example.com ...
Creating peer0.org1.example.com ...
Creating peer0.org2.example.com ...
info: [create-channel.js]: Creating mychannel...
info: [create-channel.js]: Created mychannel successfully
info: [create-channel.js]: Sleeping 5s...
info: [join-channel.js]: Joining channels...
info: [join-channel.js]: Joining mychannel...
info: [join-channel.js]: Successfully joined peerOrg1's peers to mychannel
info: [join-channel.js]: Successfully joined peerOrg2's peers to mychannel
info: [join-channel.js]: Successfully joined mychannel
info: [install-chaincode.js]: Installing chaincodes...
info: [packager/Node.js]: packaging Node from /home/mjjeon/caliper/src/contract/fabric/marbles-norichquery/node
info: [packager/Node.js]: packaging Node from /home/mjjeon/caliper/src/contract/fabric/marbles-norichquery/node
info: [install-chaincode.js]: Installed chaincode marbles successfully in all peers
info: [packager/Node.js]: packaging Node from /home/mjjeon/caliper/src/contract/fabric/simple/node
info: [packager/Node.js]: packaging Node from /home/mjjeon/caliper/src/contract/fabric/simple/node
info: [install-chaincode.js]: Installed chaincode simple successfully in all peers
info: [instantiate-chaincode.js]: Instantiating chaincodes...
info: [e2eUtils.js]: The chaincode instantiate transaction was valid.
info: [instantiate-chaincode.js]: Instantiated chaincode marbles successfully
info: [e2eUtils.js]: The chaincode instantiate transaction was valid.
info: [instantiate-chaincode.js]: Instantiated chaincode simple successfully
info: [instantiate-chaincode.js]: Sleeping 5s...
info: [bench-flow.js]: Started monitor successfully
info: [bench-flow.js]: ####### Testing 'open' #######
info: [bench-flow.js]: ------ Prepare(file-write) waiting ------
error: [e2eUtils.js]: Failed to send transaction error: TypeError: channel.generateSignedTransaction is not a function
error: [e2eUtils.js]: Failed to send transaction error: TypeError: channel.generateSignedTransaction is not a function
error: [e2eUtils.js]: Failed to send transaction error: TypeError: channel.generateSignedTransaction is not a function
error: [e2eUtils.js]: Failed to send transaction error: TypeError: channel.generateSignedTransaction is not a function
error: [e2eUtils.js]: Failed to send transaction error: TypeError: channel.generateSignedTransaction is not a function

**Comment by houqinghui** [comment]
Can you check the version of fabric-client and fabric-ca-client that have been installed?

**Comment by feihujiang** [comment]
@jmj119 this file mode only supports fabric v1.1 and fabric v1.2.  When using this file mode, please rename the file `src/adapters/fabric/ChannelSignedTransaction.js`  with `Channel.js`  and then replace 
 the original file `node_modules/fabric-client/lib/Channel.js` with the new file `Channel.js`. Please note that it would be better to backup your original file `Channel.js`.

**Comment by feihujiang** [comment]
Since Fabric client does not support the function generateSignedTransaction/sendSignedTransaction in the versions 1.1 and 1.2.

**Comment by jmj119** [comment]
@feihujiang Copying the file works! Thanks all for the comments and help!
