### ISSUE TITLE
Cannot find module 'moment'

### ISSUE THREAD

**Issue by CoreyLin** [hyperledger/caliper#301]
## Context
I installed Caliper from scratch in a server according to official guideline. And the steps are as following:
1.Install dependencies: NodeJS 8.X,node-gyp,docker,docker-compose
2.Gitclone the caliper source code from github to the server
3.Execute command "npm run fabric-deps". And error rised, saying that gcc can not be found.
4.Install gcc
5.Execute command "npm run fabric-deps", and this time it is successful.
So after finishing the above steps, I think the installation of caliper is successful.

Then I ran a simple test by executing command "node benchmark/simple/main.js" to test the basic function. But the following error happened:
Cannot find module 'moment'
![8](https://user-images.githubusercontent.com/12689769/52680583-e9193a80-2f73-11e9-8ed8-8c7d3a180c89.png)

Then I executed "npm run list". Another error arised:
![9](https://user-images.githubusercontent.com/12689769/52680614-0cdc8080-2f74-11e9-819b-842bff87e188.png)

## Expected Behavior
simple benchmark ran successfully and the performance report was reported

## Actual Behavior
Error "Cannot find module 'moment'" happened

@houqinghui could you please help me? Thank you very much.

**Comment by houqinghui** [comment]
@CoreyLin  You should run the command `npm install ` to install all the dependencies.

**Comment by CoreyLin** [comment]
Yes, it is my negligence. After I ran command "npm install", the error disappeared.
Thanks very much for your strong support! 🙂 @houqinghui
