### ISSUE TITLE
grpc,fabric-client,fabric-ca-client installation failed

### ISSUE THREAD

**Issue by CoreyLin** [hyperledger/caliper#302]
## Context
I did the following steps:
1.git clone the caliper source code to my server, then cd caliper folder
2.execute command "npm install". It is successful
![10](https://user-images.githubusercontent.com/12689769/52691315-83d93f80-2f9b-11e9-84db-3064d02b6f74.png)
3.execute command "npm run fabric-v1.1-deps". It is also successful.
![11](https://user-images.githubusercontent.com/12689769/52691331-8cca1100-2f9b-11e9-9667-9fae41696b50.png)
![12](https://user-images.githubusercontent.com/12689769/52691336-905d9800-2f9b-11e9-9426-23a4e2fb5558.png)
4.use npm list to check the installation of grpc, fabric-client,fabric-ca-client. It seems that they are not successfully installed.
![13](https://user-images.githubusercontent.com/12689769/52691488-df0b3200-2f9b-11e9-9579-d395ddef1ca3.png)

## Expected Behavior
grpc, fabric-client,fabric-ca-client are successfully installed

## Actual Behavior
npm list shows nothing

@houqinghui could you please help with this issue? Thank you!

**Comment by CoreyLin** [comment]
After step 1~4, I executed "node benchmark/simple/main.js", and it failed.
Then I installed grpc,fabric-client,fabric-ca-client manually by the following command:
npm install grpc@1.10.1 --unsafe-perm
npm install fabric-ca-client@1.1.0 --unsafe-perm
npm install fabric-client@1.1.0 --unsafe-perm

And then execute "node benchmark/simple/main.js" again. This time, the test is successful, and the test report is generated successfully.
![1](https://user-images.githubusercontent.com/12689769/52692824-f0eed400-2f9f-11e9-926b-03434aa754cd.png)

So this result demonstrated that command "npm run fabric-v1.1-deps" actually didn't install grpc,fabric-client,fabric-ca-client successfully. And there is not any error log.

**Comment by aklenik** [comment]
@CoreyLin The `npm run` script uses the `--no-save` flag, so the packages are not added to the `package.json` file. Probably that's why the `npm ls` command doesn't pick them up. 

But if you execute `ls node_modules/ | grep fabric` then you should see the packages.

**Comment by CoreyLin** [comment]
@aklenik Got it. Thanks. But why "--no-save" flag is used here? In this way, the grpc,fabric-client,fabric-ca-client are not installed. This will directly lead to testing failure.

**Comment by CoreyLin** [comment]
Indeed, the npm install documentation shows that:
--no-save: Prevents saving to dependencies.

But this would require caliper user to manually install grpc,fabric-client,fabric-ca-client. It seems not so reasonable.

**Comment by aklenik** [comment]
Don't forget that Caliper supports multiple blockchain platforms. Installing every dependency of every platform SDK would be confusing/wasteful for the users. So Caliper has some core dependencies (needed by the core code-base) added to the `package.json` and has scripts to install Fabric/Sawtooth/Burrow-specific dependencies. 

The `--no-save` flag is used in these scripts, so they're not added to the `package.json` file after install and we won't commit/push them accidentally :) 

But they're installed and are available during the execution of Caliper.
(N.B. I also don't like this solution, but couldn't come up with a better yet.)

**Comment by CoreyLin** [comment]
OK, I can understand the design thought. The dependencies are categorized to two types: 1.core 2.platform specific. I think it is good.

However, you mentioned "But they're installed and are available during the execution of Caliper.". At least in my server it doesn't work, unless I manually install grpc,fabric-client,fabric-ca-client again...

So maybe in the documentation, this additional manual installation steps should be mentioned so that other users can prevent encountering such problem...

**Comment by aklenik** [comment]
The [Pre-requisites](https://hyperledger.github.io/caliper/docs/1_Getting_Started.html#install-blockchain-sdks) section states, that the additional blockchain SDKs must also be installed, and the platform-specific doc sites detail this install.

So for Fabric, the setup is the following:
```
git clone https://github.com/hyperledger/caliper.git
cd caliper
npm i
npm run fabric-v1.2-deps
```

If these steps work for you, then this issue can be closed.
(The issue of easy install is an other question of course :) )

**Comment by CoreyLin** [comment]
OK, thanks very much. I will close this issue.
