### ISSUE TITLE
Any step to do in advance to run on distribute clients (Could not connect to ZooKeeper)?

### ISSUE THREAD

**Issue by jmj119** [hyperledger/caliper#304]
Hi all,

Here is another test that has failed. I think there would be another work to do to run on distributed clients, which I guess are the source of the problem. Can anyone share how to fix the problem?

Thanks,
MJ

mjjeon@swarm06:~/caliper$ sudo node benchmark/simple/main.js -c config-zookeeper.yaml
info: [bench-flow.js]: ####### Caliper Test #######
info: [bench-flow.js]: Executing command: docker-compose -f network/fabric-v1.1/2org1peergoleveldb/dCreating orderer.example.com ... done
Creating network "2org1peergoleveldb_default" with the default driver
Creating peer0.org2.example.com ... done
Creating ca.org1.example.com ...
Creating ca.org2.example.com ...
Creating peer0.org1.example.com ...
Creating peer0.org2.example.com ...
info: [create-channel.js]: Creating mychannel...
info: [create-channel.js]: Created mychannel successfully
info: [create-channel.js]: Sleeping 5s...
info: [join-channel.js]: Joining channels...
info: [join-channel.js]: Joining organization org1 to channel mychannel...
info: [join-channel.js]: Successfully joined peerOrg1's peers to mychannel
info: [join-channel.js]: Joining organization org2 to channel mychannel...
info: [join-channel.js]: Successfully joined peerOrg2's peers to mychannel
info: [join-channel.js]: Successfully joined mychannel
info: [install-chaincode.js]: installing all chaincodes......
info: [install-chaincode.js]: Installing chaincode drm...
info: [packager/Golang.js]: packaging GOLANG from contract/fabric/drm
info: [install-chaincode.js]: Installing chaincode drm...
info: [packager/Golang.js]: packaging GOLANG from contract/fabric/drm
info: [install-chaincode.js]: Installed chaincode drm successfully in all peers
info: [install-chaincode.js]: Installing chaincode marbles...
info: [packager/Golang.js]: packaging GOLANG from contract/fabric/marbles-norichquery/go
info: [install-chaincode.js]: Installing chaincode marbles...
info: [packager/Golang.js]: packaging GOLANG from contract/fabric/marbles-norichquery/go
info: [install-chaincode.js]: Installed chaincode marbles successfully in all peers
info: [install-chaincode.js]: Installing chaincode simple...
info: [packager/Golang.js]: packaging GOLANG from contract/fabric/simple/go
info: [install-chaincode.js]: Installing chaincode simple...
info: [packager/Golang.js]: packaging GOLANG from contract/fabric/simple/go
info: [install-chaincode.js]: Installed chaincode simple successfully in all peers
info: [install-chaincode.js]: Installing chaincode smallbank...
info: [packager/Golang.js]: packaging GOLANG from contract/fabric/smallbank
info: [install-chaincode.js]: Installing chaincode smallbank...
info: [packager/Golang.js]: packaging GOLANG from contract/fabric/smallbank
info: [install-chaincode.js]: Installed chaincode smallbank successfully in all peers
info: [instantiate-chaincode.js]: Instantiating chaincodes...
info: [e2eUtils.js]: The chaincode instantiate transaction was valid.
info: [instantiate-chaincode.js]: Instantiated chaincode drm successfully
info: [e2eUtils.js]: The chaincode instantiate transaction was valid.
info: [instantiate-chaincode.js]: Instantiated chaincode marbles successfully
info: [e2eUtils.js]: The chaincode instantiate transaction was valid.
info: [instantiate-chaincode.js]: Instantiated chaincode simple successfully
info: [e2eUtils.js]: The chaincode instantiate transaction was valid.
info: [instantiate-chaincode.js]: Instantiated chaincode smallbank successfully
info: [instantiate-chaincode.js]: Sleeping 5s...
info: [client.js]: Connecting to ZooKeeper......
error: [client.js]: Could not connect to ZooKeeper
(node:19892) UnhandledPromiseRejectionWarning: Could not connect to ZooKeeper
(node:19892) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19892) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aklenik** [comment]
@jmj119 Based on the [documentation](https://hyperledger.github.io/caliper/docs/Zookeeper_Client_Design.html), I would check the following things (although I'm not familiar with this feature of Caliper yet):
1. The Zoo clients are started on the remote machines
2. The master (where you start the test) is [properly configured](https://github.com/hyperledger/caliper/blob/master/benchmark/simple/config-zookeeper.yaml) and can access these addresses and ports.

**Comment by aklenik** [comment]
@jmj119 Did you resolve the errors?

**Comment by robiharid** [comment]
> @jmj119 Based on the [documentation](https://hyperledger.github.io/caliper/docs/Zookeeper_Client_Design.html), I would check the following things (although I'm not familiar with this feature of Caliper yet):
> 
> 1. The Zoo clients are started on the remote machines
> 2. The master (where you start the test) is [properly configured](https://github.com/hyperledger/caliper/blob/master/benchmark/simple/config-zookeeper.yaml) and can access these addresses and ports.

I run in the same problem. I am using Azure VMs to deploy Caliper over a network. 

How do I start zoo client in one of my other Azure VMs? Install Zookeeper, but what should the config file look like before I run the bin/zkServer.sh start script? Do the clients need hyperledger caliper installed on their machines?

Modifiying the config-zookeeper.yaml do I change the server IP to localhost:2181, how does it know how to connect to the zookeeper clients on my other Azure VMs?

Thanks Attilla!
