### ISSUE TITLE
[consult]Is "ca" attribute not needed if cryptogen tool is used instead of CA

### ISSUE THREAD

**Issue by CoreyLin** [hyperledger/caliper#305]
## Context
Hello Caliper team:
My network has 2 orgs, and each org has 2 peers. And I didn't use CA server to create and publish certificates. Instead, I use the official script cryptogen to generate certificates.
So I want to confirm with you that in network configuration file, whether "ca" can be removed or not?
![10](https://user-images.githubusercontent.com/12689769/52839073-ccc1fd00-312f-11e9-88d1-98aea80858b2.png)
Thanks in advance.

**Comment by aklenik** [comment]
@CoreyLin You are absolutely right, you don't need a CA if you don't use its services. Please run a test without the CAs, and let me know the result :)

(The new Fabric adapter #296 allows you to dynamically register and enroll users, so the CA could play a role in your tests, but it's optional, of course.)

**Comment by aklenik** [comment]
Submitted #311 , so closing this related issue.
