### ISSUE TITLE
run the benchmark/simple/main.js demo and get an error,plz help me.

### ISSUE THREAD

**Issue by unknown7788** [hyperledger/caliper#307]
root@peer2:/opt/gopath/src/github.com/hyperledger/caliper# node ./benchmark/simple/main.js
info: [bench-flow.js]: ####### Caliper Test #######
info: [bench-flow.js]: Executing command: docker-compose -f network/fabric-v1.1/2org1peergoleveldb/docker-compose-tls.yaml up -d;sleep 3s
Creating network "2org1peergoleveldb_default" with the default driver
Creating ca.org2.example.com ... done
Creating ca.org1.example.com ... done
Creating orderer.example.com ... done
Creating peer0.org2.example.com ... done
Creating peer0.org1.example.com ... done
info: [create-channel.js]: Creating mychannel...
2019-02-15T07:15:18.341Z - error: [Remote.js]: Error: Failed to connect before the deadline URL:grpcs://localhost:7050
2019-02-15T07:15:18.342Z - error: [Orderer.js]: Orderer grpcs://localhost:7050 has an error Error: Failed to connect before the deadline URL:grpcs://localhost:7050
error: [create-channel.js]: Failed to create channels: Error: Failed to connect before the deadline URL:grpcs://localhost:7050
    at checkState (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:720:16)
error: [fabric.js]: Fabric initialization failed: Error: Failed to connect before the deadline URL:grpcs://localhost:7050
    at checkState (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:720:16)
error: [bench-flow.js]: Error: Error: Failed to connect before the deadline URL:grpcs://localhost:7050
    at checkState (/opt/gopath/src/github.com/hyperledger/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:720:16)
info: [demo.js]: [Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
info: [bench-flow.js]: Executing command: docker-compose -f network/fabric-v1.1/2org1peergoleveldb/docker-compose-tls.yaml down;docker rm $(docker ps -aq);docker rmi $(docker images dev* -q)
Stopping peer0.org1.example.com ... done

this is myenvironment

root@peer2:/opt/gopath/src/github.com/hyperledger/caliper# npm list grpc
caliper@0.1.0 /opt/gopath/src/github.com/hyperledger/caliper
├─┬ fabric-ca-client@1.4.0
│ └── grpc@1.14.2
├─┬ fabric-client@1.4.0
│ └── grpc@1.14.2
└── grpc@1.18.0

root@peer2:/opt/gopath/src/github.com/hyperledger/caliper#

**Comment by aklenik** [comment]
@unknown7788 
1. I'm not sure, whether Caliper seamlessly supports Fabric 1.4 right now (multiple PRs are on the way to address it). Plus you're using 1.4 SDK with a 1.1 network, bad idea. To install the 1.1 SDK, run `npm run fabric-v1.1-deps` in the root directory of Caliper.
2. The error indicates that you can't connect to the Fabric nodes. Since it's a local network, address/port/firewall stuff shouldn't be an issue. Check whether the containers started successfully with `docker logs <container name>`.

**Comment by feihujiang** [comment]
@unknown7788 Did you resolve your error?

**Comment by hppranaav** [comment]
I am having the same issue except i'm using fabric v1.3.0

**Comment by aklenik** [comment]
@hppranaav What are the exact issues? This thread is not relevant anymore, the method of running Caliper changed since then. Please refer to the updated docs (Getting Started, and Fabric-CCP configuration), and if you still run into issues, please open a new issue with the detailed error logs.
