### ISSUE TITLE
Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by CoreyLin** [hyperledger/caliper#308]
## Context
Env:
2 orgs, each org has 2 peers

Steps:
Execute command "node benchmark/simple/main.js -n /home/yzapps/hyperledger/yingzi/caliper/network/fabric-v1.4-yingzi/2org2peercouchdb/fabric-node.json"
note:1.omit "-c" parameter, which means using the default "config-linear-rate.yaml" as the benchmark config file
2.The content of used fabric-node.json is as following:
[fabric-node.zip](https://github.com/hyperledger/caliper/files/2868354/fabric-node.zip)

## Expected Behavior
The benchmark test(running "marbles" chaincode) ran successfully and report was generated normally.

## Actual Behavior
Three errors happened:
1.error: [monitor-docker.js]: monitor-docker: could not find active local container
2.Cannot read property 'url' of undefined
3.Cannot read property 'unshift' of undefined
The entire detailed log is below:
![555f179c176376ce66a76d33a7bd158](https://user-images.githubusercontent.com/12689769/52843467-2da40200-313d-11e9-8920-209b42ace177.png)
![437ba993c54272855a4fe26911fd8c8](https://user-images.githubusercontent.com/12689769/52843472-309ef280-313d-11e9-8128-01da9a3372b5.png)
![9ee05c30aab106c8c66c62d7e12e0af](https://user-images.githubusercontent.com/12689769/52843476-33014c80-313d-11e9-9882-acdf3d7a6117.png)
![6338bd5db2fb706a15c92e6fa58aed0](https://user-images.githubusercontent.com/12689769/52843480-35fc3d00-313d-11e9-8b1a-a9c818d21170.png)

Could you please help check this issue? Thanks in advance. @houqinghui

**Comment by CoreyLin** [comment]
It seemed that the chaincode was successfully installed and instantiated, but in later test, it failed...

**Comment by houqinghui** [comment]
@CoreyLin  Because the client and the fabric network is delopyed in different machine, so in the client machine, there is no local docker. Please refer to the below:
Q: How do I run caliper to test fabric which is deployed in another machine?
A:  Caliper is indepentent of the backend blockchain network. You can follow the below steps.
1.	Deploy the backend network. First you should choose the fabric version in the directory /network, and then choose the network topoloy you want to test, last you can deploy the network by the docker-compose.
2.	In the machine of caliper, you should modify the `localhost` to the ip of the host of fabric in the network configuration. 
3.	Run the caliper.
Some tips is that you should modify tht property `deployed` of the `channel` from `false` to `true` in the network config file. You had better use the go version’s network configuration file.

**Comment by houqinghui** [comment]
@CoreyLin  How can i monitor the remote docker?  
A : If you need to access the Docker daemon remotely, you need to enable the `tcp` Socket. Beware that the default setup provides un-encrypted and un-anthenticated direct access to the Docker daemon.You can listen on port `2375` on all network interfaces with `-H tcp://0.0.0.0:2375`, or on a particular networ interface using its IP address: `-H tcp://192.169.59.103:2375`. The belows are what you would concern about.

a. You can add `-H tcp://0.0.0.0:2375` to the `ExecStart` in the `/lib/systemd/systemd/docker.service` file, for example `ExecStart=/usr/bin/dockerd -H tcp：//0.0.0.0:2357 -H unix:///var/run/docker.sock`. 
b. Restart the daemon with `systemctl daemon-reload`.
c. Restart the service `sudo service docker restart`.
d. Check if the port is open. You can run `netstat -nptl`, if not, you can run `sudo ufw allow port` to open it.

**Comment by CoreyLin** [comment]
Thanks, qinghui. So is there a Q&A link?

**Comment by CoreyLin** [comment]
Thanks qinghui, your instruction is very helpful. I did the following two things:
1.Enable docker remote port 2375 on fabric network servers. Instead of changing /lib/systemd/system/docker.service directly, I think the better way is: https://success.docker.com/article/how-do-i-enable-the-remote-api-for-dockerd
I tried it successfully.
2.In the benchmark config file, specify "monitor" like this:
![7ab415984bf4ede31a28e421b67d81a](https://user-images.githubusercontent.com/12689769/52853599-0a864c00-3157-11e9-8c0c-c01130cdcb13.png)

After that, I execute "node benchmark/simple/main.js -c /home/yzapps/hyperledger/yingzi/caliper/network/fabric-v1.4-yingzi/2org2peercouchdb/config-linear-rate.yaml -n /home/yzapps/hyperledger/yingzi/caliper/network/fabric-v1.4-yingzi/2org2peercouchdb/fabric-node.json" to run the test again.
This time, "error: [monitor-docker.js]: monitor-docker: could not find active local container" disappeared. It is fixed.

However, the other two "Cannot read property" errors still exist. The detailed log is below:
![a78bc1c15caebdb24887fdc3c009a17](https://user-images.githubusercontent.com/12689769/52853806-a31ccc00-3157-11e9-9338-435b97fbb235.png)
![1633ddf37dc9fd73709dde63ecbac80](https://user-images.githubusercontent.com/12689769/52853809-a57f2600-3157-11e9-8a3d-80d1fe6a883d.png)
![62221ca0987f5bb87ec094e5b51172d](https://user-images.githubusercontent.com/12689769/52853815-a87a1680-3157-11e9-9c66-5b101a30cdbb.png)

Could you please check this? Thank you!

**Comment by aklenik** [comment]
@CoreyLin You didn't specify CAs for the organizations. Guess this answers your question in #305

**Comment by CoreyLin** [comment]
@aklenik Thanks very much for your so quick reply. :blush: But in #305 , you mentioned that I can omit CA configuration. I didn't configure CA in my configuration file.
So how can this issue be solved?

**Comment by CoreyLin** [comment]
In current situation, is there any configuration which can solve this issue? I didn't setup CA. Instead, I used cryptogen. @aklenik

**Comment by aklenik** [comment]
@CoreyLin Well, it's a bug, that needs to be fixed in the adapter. 
In the meantime, you could comment out [these](https://github.com/hyperledger/caliper/blob/master/src/adapters/fabric/e2eUtils.js#L695-L700) lines of the adapter since it's causing the problem.

**Comment by CoreyLin** [comment]
@aklenik OK, thanks! :thumbsup: I will comment out the lines mentioned by you, and run the test again.

**Comment by CoreyLin** [comment]
@aklenik After commenting out the lines mentioned by you, the "Cannot read property" issue is fixed. I will close this issue. Thanks for your helpful instruction.
