### ISSUE TITLE
chaincode simple not found

### ISSUE THREAD

**Issue by CoreyLin** [hyperledger/caliper#312]
## Context
Env:
2 orgs, each org has 2 peers

Steps:
1.In my fabric-node.json, the chaincodes configuration is as following:
![0983fbfa5fc25f4b5142be289ae8e0c](https://user-images.githubusercontent.com/12689769/52856775-4a056600-3160-11e9-8f59-94e05f1a4de8.png)
That is, only "marbles" chaincode is there. And there is not "simple" chaincode.
2.In caliper root folder, execute "node benchmark/simple/main.js -c /home/yzapps/hyperledger/yingzi/caliper/network/fabric-v1.4-yingzi/2org2peercouchdb/config-linear-rate.yaml -n /home/yzapps/hyperledger/yingzi/caliper/network/fabric-v1.4-yingzi/2org2peercouchdb/fabric-node.json" command to run the main.js test.

## Expected Behavior
1.Test is successful
2.There is no error
3.Test report is generated

## Actual Behavior
1.Error "chaincode simple not found" keeps being displayed:
![5f0c12100b6f6836f1b6ef0f7c75697](https://user-images.githubusercontent.com/12689769/52857006-d44dca00-3160-11e9-8a0d-34f237cc5ed4.png)
In my understanding, the chaincode is defined by myself only in the network configuration file. I only defined "marbles" in it. Why "simple" chaincode is being looked up?
Based on the error, I can infer there is some relationship between benchmark/simple/main.js and "simple" chaincode. They are tightly bonded, right?

2.Even though "simple" chaincode is not found, the test report was still generated, but the test result is incomplete, e.g. Avg Latency and Throughput seems not correct.
![31e3d3fe707d885a6f65952ecc66198](https://user-images.githubusercontent.com/12689769/52857261-969d7100-3161-11e9-8caf-b46c95bd0917.png)
![220ed49787fc0cc0d992717f8f36e78](https://user-images.githubusercontent.com/12689769/52857297-b0d74f00-3161-11e9-9848-acb9a9f365d2.png)

@aklenik Could you please help on this issue? Thanks in advance.

**Comment by aklenik** [comment]
@CoreyLin The target chaincode is also referenced from the user callback module. Make sure you use a callback intended for the marbles, and not for the simple chaincode.

**Comment by CoreyLin** [comment]
@aklenik thanks. Can I understand like this:
If I want to use the chaincode developed by myself, I need to develop a callback js file accordingly?

**Comment by aklenik** [comment]
@CoreyLin Yes, the callback module makes the actual calls to the chaincode (through Caliper and the Fabric adapter), and part of the call are the arguments specifying the target chaincode, function and arguments.

So the callback module must be supplied by the user, since it's your business logic, depending on your own chaincode API.

**Comment by CoreyLin** [comment]
@aklenik Got it. Thanks very much.
