### ISSUE TITLE
Disk Read and Disk Write is 0 for marbles init round

### ISSUE THREAD

**Issue by CoreyLin** [hyperledger/caliper#314]
## Context
Env:
2 orgs, each org has 2 peers

Benchmark config file:
[config-marbles.zip](https://github.com/hyperledger/caliper/files/2871535/config-marbles.zip)
Network config file:
[fabric-node-marbles.zip](https://github.com/hyperledger/caliper/files/2871536/fabric-node-marbles.zip)

Steps:
Execute command "node benchmark/marbles/main.js -c /home/yzapps/hyperledger/yingzi/caliper/network/fabric-v1.4-yingzi/2org2peercouchdb/config-marbles.yaml -n /home/yzapps/hyperledger/yingzi/caliper/network/fabric-v1.4-yingzi/2org2peercouchdb/fabric-node-marbles.json"

## Expected Behavior
In my understanding, marbles init round would write some initial data to the ledger, which means that writing to disk. So in the testing report, the Disk Write should not be 0.

## Actual Behavior
In the testing report, the Disk Write is 0.
![a3c3d9d76729b65de06bdd2b834982e](https://user-images.githubusercontent.com/12689769/52893583-e2d7c800-31d8-11e9-9ab6-c76d3d9ae101.png)
![917feb1cc0894eb64cd70e6d15130f3](https://user-images.githubusercontent.com/12689769/52893587-e66b4f00-31d8-11e9-8a4e-21ee8497d7d9.png)

Could you please explain why Disk Write is 0? Thanks in advance.

**Comment by aklenik** [comment]
There is a pending PR, that resolves this. The disk usage support is already there, but it's not processed and reported yet.

**Comment by CoreyLin** [comment]
OK, so in near future, you will support disk usage reporting on UI?

**Comment by aklenik** [comment]
@CoreyLin Resolved by PR #293
