### ISSUE TITLE
The difference between "Fail" and "Unfinished" in test log

### ISSUE THREAD

**Issue by CoreyLin** [hyperledger/caliper#315]
## Context
Hello Caliper team, after I ran a test, I discovered that in test log, there are two fields: Fail, Unfinished.
![3d4b862699716ba33c42427a8121d72](https://user-images.githubusercontent.com/12689769/52894044-621bca80-31de-11e9-9a10-d90546bccd14.png)
And in the generated report, only Fail is presented, while Unfinished is not presented.
![0b5bb7328107a4518f5035bf97bd963](https://user-images.githubusercontent.com/12689769/52894059-9c856780-31de-11e9-9158-98c8e6e54e77.png)
I don't understand the difference between them. Could you please tell me? Thanks in advance.

**Comment by aklenik** [comment]
Unfinished: the transaction is submitted and going through the life cycle. We don't know the result yet
Fail: we got the notification that the transaction failed. 
Succ: we got the notification that the transaction was successful. 

Submitted = succ + fail + unfinished

**Comment by CoreyLin** [comment]
So can I understand it like this:
unfinished will becomes one of these:
1.fail or timeout
2.success
