### ISSUE TITLE
"Succ" count in the test report is 0

### ISSUE THREAD

**Issue by CoreyLin** [hyperledger/caliper#316]
## Context
The context and env is totally same as #314 
In the Testing "query" round log, actually the totally success transaction was 1500, but in the generated report, the "Succ" count is 0. I can't understand. Could you please tell me? Thanks.
![3f7123c7622810ce4442fda7664e42b](https://user-images.githubusercontent.com/12689769/52894189-bc1d8f80-31e0-11e9-8c5d-03190afb6b48.png)
![c2632f4485de42456f99436147bdc8f](https://user-images.githubusercontent.com/12689769/52894191-bf188000-31e0-11e9-8a75-0d57d9c7265e.png)
![574c4e2c7a3142bbea54fb8c0fe041d](https://user-images.githubusercontent.com/12689769/52894193-c17ada00-31e0-11e9-9f3b-e65010fe1002.png)

**Comment by CoreyLin** [comment]
By the way, the following fields surrounded by red rectangle seem not normal too:
![b09a8895cadb1bdec8ee38cd0a3c3bc](https://user-images.githubusercontent.com/12689769/52894345-df493e80-31e2-11e9-8552-0d896e90193c.png)

**Comment by aklenik** [comment]
We'll look into it, something is definitely shady

**Comment by CoreyLin** [comment]
@aklenik thanks for your reply. Just now I found that it is not a bug. Actually, the displaying is normal. Because I found that the "Succ: 1500" is an accumulated number which count from the beginning of the test. Before running "query" test, actually "init" test had already sent 1500 transactions. So here "Succ: 1500" means that "init" test is successful.
And "query" test totally sent 15 transactions, and all of them failed. So it is not a bug.

**Comment by aklenik** [comment]
Ah, okay, didn't see that it's not the only round

**Comment by CoreyLin** [comment]
The displaying has no problem. But another problem comes to my mind: why all 15 "query" transactions failed? Everytime when I run this case, "init" is totally successful and "query" is failed.
Just now I debugged the peer log and couchdb log, found that some logs seems not normal:
peer log:
![710f2f47e2d03a81502e390f6b997b7](https://user-images.githubusercontent.com/12689769/52897310-eb96c100-320d-11e9-8107-005864415488.png)
couchdb log:
![f9f049eae07a8d8cdf65079721239c6](https://user-images.githubusercontent.com/12689769/52897313-f4879280-320d-11e9-93d2-f50437dec5c8.png)
It seems that the document can't be found/queried by nodejs SDK.

But when I directly query the marbles data from CLI, it is successful:
![b603ef6ac905f2f2d88d05147d27675](https://user-images.githubusercontent.com/12689769/52897350-69f36300-320e-11e9-85bb-4c7fd77813ad.png)
![722f8d576a7977ecf8a54c444926197](https://user-images.githubusercontent.com/12689769/52897352-6e1f8080-320e-11e9-8b97-d2c23f115e1e.png)
So it is strange. I just doubt maybe there is something wrong with "query.js" or its dependency libraries. But I am not sure. Currently I don't have time to debug the code error.

**Comment by CoreyLin** [comment]
Anyway, I have to skip it, and select another sample chaincode to try. I can't get stuck here...
