### ISSUE TITLE
[consult]how to tuning parameters to prevent "timeout expired while executing transaction"

### ISSUE THREAD

**Issue by CoreyLin** [hyperledger/caliper#317]
## Context
The context and env is totally same as #314
In the test log, when the sending tps was increased to some extent, transaction failure happened due to error "timeout expired while executing transaction".
![bd7d451ead5d799dbc636dc92da7fe7](https://user-images.githubusercontent.com/12689769/52894258-c2603b80-31e1-11e9-87d0-2580b0374156.png)
I have two questions in my mind:
1.What does this error mean from fabric theoretical point of view?
2.Can we take any measure(e.g. tuning some parameters) to prevent such error, or reduce the error count to minimum count? Could you please share your experience?
Thank you very much!

**Comment by CoreyLin** [comment]
I noticed that in blockchain.js, there is a parameter timeout:
![6edf4e567c8f475341ceb678666477b](https://user-images.githubusercontent.com/12689769/52895696-c77cb500-31f8-11e9-8787-7958b70a9646.png)
Is this timeout related to the error timeout in test log?

**Comment by CoreyLin** [comment]
Just now I checked the code. The timeout passing flow is like:
query.js-->blockchain.js:invokeSmartContract-->fabric.js:invokeSmartContract-->e2eUtils.js:invokebycontext
And error "Endorsement denied:" comes from invokebycontext function:
![024a75bc976a65e137d17e7bd7862c5](https://user-images.githubusercontent.com/12689769/52896141-9c955f80-31fe-11e9-9cdb-a8e511955ec1.png)
![3837e2ec0583d4ac288989a4b470ac5](https://user-images.githubusercontent.com/12689769/52896143-a15a1380-31fe-11e9-9a21-d7a0be9f7ec4.png)
Could you please furthur check why did this timeout happen? The passed timeout from query.js is 120 seconds, but I observed that the transaction failed much earlier than timeout expired, that is, about 1s, very fast to fail. It seems that 120s doesn't take effect here.

**Comment by aklenik** [comment]
What you set in Caliper and the callback, that's a client side timeout, passed to the Fabric SDK. You also need to set the timeout on the peer side. I think you can do that with the `CORE_CHAINCODE_EXECUTETIMEOUT=120s` environment variable on the peer containers, but check the peer configs for the exact name

**Comment by CoreyLin** [comment]
@aklenik Thanks. After debugging, I found it is not a timeout problem. Timeout configuration has no problem. Instead, the rich query of marbles returns "404 not found" error. I will skip this problem, and use another chaincode firstly. Anyway, I will close this issue.
