### ISSUE TITLE
[consult]endorsement policy impact on throughput

### ISSUE THREAD

**Issue by CoreyLin** [hyperledger/caliper#321]
## Context
Env:
2 orgs, each org has 2 peers

Benchmark configuration file:
[config-marbles-only-init.zip](https://github.com/hyperledger/caliper/files/2874558/config-marbles-only-init.zip)
Network configuration file:
[fabric-node-marbles.zip](https://github.com/hyperledger/caliper/files/2874561/fabric-node-marbles.zip)

Testing steps:
1.Set endorsement-policy as 2-of:
![a32b5754b00ded2cdb4f3f0f8ebc687](https://user-images.githubusercontent.com/12689769/52937022-e7e37580-3398-11e9-865c-2b97e52598e4.png)
Then run test, the test report is as following:
![818cb9c7f21505b2258e5d06e516419](https://user-images.githubusercontent.com/12689769/52937076-16f9e700-3399-11e9-8e69-cad59185079b.png)
2.Set endorsement-policy as 1-of:
![8253a1af9cc99086f9a753db4267968](https://user-images.githubusercontent.com/12689769/52937115-342eb580-3399-11e9-8065-d6ad9ebff512.png)
Then run test, the test report is as following:
![1402b76ce4e3cb018ec57cf251ed3bb](https://user-images.githubusercontent.com/12689769/52937162-51fc1a80-3399-11e9-85b1-0db6f6235a19.png)

## Expected Behavior
I read some articles, and in my understanding, endorsement-policy should have significant impact on the throughput. So, the throughput of endorsement-policy "1-of" should be much higher than that of endorsement-policy "2-of".

## Actual Behavior
Based on the generated testing report, there is not much difference between them. Both are around 100 tps.
Here I just want to consult your professional advice and experience about this. Does endorsement-policy have significant impact on throughput or not? Do you have any idea to improve the throughput? Thank you.

**Comment by aklenik** [comment]
@CoreyLin You heard it right, endorsement policy can have an impact on performance. Consider the following two scenarios: 

1. 2-of-2 policy: each transaction must be executed on at least one peer of __two__ different orgs, so consuming the resources of two peers in total. 
1. 1-of-2 policy: a transaction must be executed on at least one peer of __either__ orgs. So a transaction consumes the resources of only one peer in total, allowing twice as many transactions with the same resources (at least in theory).

But the first policy is resilient against malicious organizations, whereas in the second case a single "hacked" org could influence transaction processing (allowing "bad" transactions into the ledger).

Summary: yes, the endorsement policy does affect the performance. No, it is not a performance tuning parameter, it is determined by the business (or fault/attack tolerance) requirements.

NB: it would be possible to implement automatic load balancing based on the minimal organization sets that can satisfy a policy, but it's not a high priority task right now. Currently, Caliper assumes an N-of-N policy and sends transactions accordingly.

**Comment by CoreyLin** [comment]
Thanks. @aklenik

**Comment by aklenik** [comment]
@CoreyLin The new Fabric adapter has been merged, so you can specify the targets explicitly from the user module if Caliper's N-of-N endorsement policy assumption is not good enough.
