### ISSUE TITLE
Caliper Composer Benchmark -- Transactions failure when asset/participant registry is updated

### ISSUE THREAD

**Issue by sidraamalik** [hyperledger/caliper#327]
I have a sample network running in composer. The transactions are successful and the assets are being updated accordingly. However when i test the same network using caliper, transactions fail. I have figured out that the problem appears whenever "await registry update" is executed in logic.js. 

## Context - TemperatureReading transaction from perishable network

Model: 
transaction TemperatureReading{
  o Double centigrade
  --> Commodity commodity
}

Logic.js

async function temperatureReading(temperatureReading) {  // eslint-disable-line no-unused-vars
    const shipmentRegistry = await getAssetRegistry('org.example.trading.Commodity');
    const comm = shipmentRegistry.get(temperatureReading.commodity);
   if (comm.temperatureReadings) {
        comm.temperatureReadings.push(temperatureReading);
    } else {
        comm.temperatureReadings = [temperatureReading];
    }

   //  if I comment this line, transactions are successful in caliper. This works fine in composer. i have no ACL rules which might restrict this. 
   **await shipmentRegistry.update(comm);**  

}

## Expected Behavior
The commodity should be updated as a result with a temperature reading transaction.

**Comment by aklenik** [comment]
@sidraamalik Could you provide some error log for the behavior?
