### ISSUE TITLE
Allow to skip start and end scripts even when they are defined

### ISSUE THREAD

**Issue by aklenik** [hyperledger/caliper#331]
## Context
This issue is a rework of #329.

During the development of user callback or chaincodes, it would be nice to reuse an already started (through the start script) local network. Currently, we need to remove the `start` script from the network configuration file to achieve this.

Also, during the debugging of an error, it would be nice to keep the network running at the end of a benchmark to inspect the logs, for example. Currently, we need to remove the `end` script from the network configuration file to achieve this.

## Expected Behavior
Provide a mechanism to skip the start and/or end scripts even when they are present in the configuration. 

## Actual Behavior
Currently, we need to remove the `start`/`end` scripts from the network configuration file.

## Possible Fix
Caliper already provides a flexible configuration mechanism. Two options should be added to the general Caliper configuration file (`config/default.yaml`):

```yaml
core:
    skipStartScript: false
    skipEndScript: false
```
This way the settings can be easily overridden through environment variables or command line arguments. 

Finally, [this](https://github.com/hyperledger/caliper/blob/027528a5f5e142f17c694e6648baec51cb4c2139/src/comm/bench-flow.js#L336) and [this](https://github.com/hyperledger/caliper/blob/027528a5f5e142f17c694e6648baec51cb4c2139/src/comm/bench-flow.js#L382) line should be changed to take the settings into account.
 
## Existing issues
- #329

**Comment by feihujiang** [comment]
:+1:

**Comment by panyu4** [comment]
Since this issue had been resolved, it will be closed.
