### ISSUE TITLE
Improve the configuration support

### ISSUE THREAD

**Issue by aklenik** [hyperledger/caliper#339]
## Context
Caliper uses a hierarchical configuration mechanism provided by the [nconf](https://github.com/indexzero/nconf) package. The priority between the different configuration sources are the following:

Runtime > Environment variable > Command line > Configuration file 

The provided environment variables (conventionally written in uppercase with underscore separators) are made lowercase and the underscores are changed to dashes. For example, `CORE_SOMESETTING=10` can be queried through the `“core-somesetting”` configuration key. 

The configuration file allows nested objects, that are flattened to separate keys for each “leaf” attribute. For example, the value of `somesetting` in 
```yaml
core:
  someSetting: 10
```
can be queried through the `“core:someSetting”` configuration key. These two examples demonstrate the inconsistency of the configuration mechanism: `someSetting` cannot be overridden by environment variables since `CORE_SOMESETTING` will be mapped to `“core:somesetting”` (note the missing camel casing).

## Expected Behavior
The goal would be to use a common format for settings from every source. The proposed format is the following: **all lowercase letters** for the setting hierarchies, **separated by dashes**. So the previous examples both could be queried with the same configuration key, `“core-somesetting”`, and could be overridden by the environment variable `CORE_SOMESETTING=10`, or through the command line with `--core-somesetting=10`.

Moreover, to prevent name collisions with settings outside of Caliper (especially for environment variables), the `“caliper-”` prefix should be used for every settings key. 

It is also important to parse well-know string values (e.g., `‘false’`, `‘true’`, `‘3’`, `‘5.1’` or JSON values) as their corresponding type (e.g., boolean, number, or object), both for command line arguments and environment variables.

Corresponding documentation should also be provided that describes the configuration mechanism of Caliper.

## Possible Fix
Using the `“caliper-”` prefix requires the modification of the default configuration file. Everything should be enclosed in a top-level `“caliper”` attribute. This way nconf automatically will append the prefix, since it's part of the configuration hierarchy. For example:
```yaml
caliper:
  core:
    somesetting: 10
```
The environment variables are set by the users, so it's their responsibility to correctly override, for example, the `“caliper-core-somesetting”` value by setting the `CALIPER_CORE_SOMESETTING` environment variable. 

Consistent naming can be achieved by using all lowercase names in the configuration file, plus setting the appropriate nconf option (`options.logicalSeparator`), so it uses dashes as a separator when parsing a configuration file. 

Parsing well-known string values can be achieved by using the [appropriate settings](https://github.com/indexzero/nconf#argv) for nconf.

**Comment by nklincoln** [comment]
@aklenik - can this be closed now following from your latest PR?

**Comment by aklenik** [comment]
Yep, everything above and more is provided by the PR :)
