### ISSUE TITLE
can not find main.js

### ISSUE THREAD

**Issue by Arucald** [hyperledger/caliper#347]
**When I am running the benchmark, I type this :**  
node main.js -c config.yaml -n ../../network/fabric-v1.4/2org1peergoleveldb/fabric-go.json

**Then it shows:**
Error: Cannot find module '/Users/dada/caliper/benchmark/simple/main.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Hope to solve this problem.**

**Comment by aklenik** [comment]
@Arucald The main.js files have been removed. The current way of running a benchmark is the following (from the root Caliper dir):
```
npm run bench -- -c benchmark/simple/config.yaml -n network/fabric-v1.4/2org1peergoleveldb/fabric-go.json
```

This is a new change and the documentation hasn't been updated yet, but it will be soon!

**Comment by Arucald** [comment]
Ok.  This works well. THX

**Comment by aklenik** [comment]
PR #349 updated the documentation accordingly.
