### ISSUE TITLE
npm run test with sawtooth got docker rm errors

### ISSUE THREAD

**Issue by Arucald** [hyperledger/caliper#352]
when I type : `npm run test -- -- -c benchmark/simple/config-sawtooth.yaml -n network/sawtooth/simplenetwork/sawtooth.json`

it shows 
![image](https://user-images.githubusercontent.com/31911640/54012291-9ae10b00-41b0-11e9-985f-bd737d67b4cf.png)

this may caused by the container which is empty, so once we remove the container , it needs at least 1 argument.  This results in the output error of the CI test.

**Comment by nklincoln** [comment]
@panyu4 - can this now be closed?
