### ISSUE TITLE
Iroha version is outdated

### ISSUE THREAD

**Issue by stinger112** [hyperledger/caliper#36]
Current Iroha version used by Caliper is totally outdated and works over old manually generated connector library. 

I think Iroha and connector library should be updated, so I created this PR #35

**Comment by haojun** [comment]
Great, thannks @stinger112 . I'll review it later (we are moving to new cloud environment and unable to test any PR recently)

**Comment by stinger112** [comment]
Finally, PR has been merged. :+1: 
Thanks!

**Comment by stinger112** [comment]
@
