### ISSUE TITLE
Support common connection profile feature of the new fabric node SDK

### ISSUE THREAD

**Issue by haojun** [hyperledger/caliper#37]
From the discussion of [#caliper-contributors](https://chat.hyperledger.org/channel/caliper-contributors)
-------------------------
klenik:
So as the first topic of the channel (hopefully others will also join soon), I would suggest to use the Common Connection Profile feature of the Fabric Node SDK (1.1.0).
This would replace a LOT of code that currently assembles the object graphs needed to submit transactions, join channel, etc.

**Comment by haojun** [comment]
@aklenik Do you mind if i assign this to you, so other people know you are working on this?

**Comment by aklenik** [comment]
PR #296 resolves this issue, finally :)
