### ISSUE TITLE
When I tested the example chaincode:chaincode_example02, the parameters received by the chaincode were incorrect

### ISSUE THREAD

**Issue by Dingxining** [hyperledger/caliper#371]
When I tested the example chaincode:chaincode_example02, the parameters received by the chaincode were incorrect

I use the command  `peer chaincode invoke -o orderer:7050 -C mychannel -n chaincode_example02 -c '{"Args":["invoke","A","B","1"]}'`   in  cli.The chaincode is ok.

I am sure there is no problem with my environment, the caliper example works fine.
But there is a problem with running the chaincode, maybe there is a problem with my inovke.js. 
I modified the chain code to print out the received args
The chaincode accepts only one args:A,B,1.
So,The query.js is ok.

I need help,thanks.

invoke.js:
```
module.exports.info  = 'Invoke chaincode_example02.';

let bc, contx;
let setting=[{"function":"invoke","args":["A","B","1"]}];

module.exports.init = function(blockchain, context, args) {
    bc = blockchain;
    contx = context;
    return Promise.resolve();
};

module.exports.run = function() {
    // TODO: until Fabric query is implemented, use invoke
    return bc.invokeSmartContract(contx, 'chaincode_example02', 'v0',setting, 120);
};
```
query.js:
```
'use strict';

module.exports.info  = 'Querying chaincode_example02.';

let txIndex = 0;
let bc, contx;
module.exports.init = function(blockchain, context, args) {
    bc = blockchain;
    contx = context;
    return Promise.resolve();
};

module.exports.run = function() {
    txIndex++;
    // TODO: until Fabric query is implemented, use invoke
    return bc.invokeSmartContract(contx, 'chaincode_example02', 'v0',
        {
            chaincodeFunction: 'query',
            chaincodeArguments: ["B"]
        }, 120);
};

module.exports.end = function() {
    return Promise.resolve();
};

```

logs:
```
root@ubuntu:/opt/gopath/src/github.com/hyperledger/caliper# npm run bench -- -c benchmark/chaincode_example02/config.yaml -n network/fabric-v1.4/dev/fabric-go.json

> caliper@0.1.0 bench /opt/gopath/src/github.com/hyperledger/caliper
> node ./scripts/main.js "-c" "benchmark/chaincode_example02/config.yaml" "-n" "network/fabric-v1.4/dev/fabric-go.json"

info: [bench-flow.js]: ####### Caliper Test #######
info: [bench-flow.js]: Executing command: docker-compose -f network/fabric-v1.4/dev/docker-compose.yaml up -d;sleep 3s
Creating ca.org1.example.com ... done
Creating orderer.example.com ... done
Creating cli                 ... done
Creating peer0.org1.example.com ... done
info: [create-channel.js]: Creating mychannel...
info: [create-channel.js]: Created mychannel successfully
info: [create-channel.js]: Sleeping 5s...
info: [join-channel.js]: Joining channels...
info: [join-channel.js]: Joining organization org1 to channel mychannel...
info: [join-channel.js]: Successfully joined peerOrg1's peers to mychannel
info: [join-channel.js]: Successfully joined mychannel
info: [install-chaincode.js]: installing all chaincodes......
info: [install-chaincode.js]: Installing chaincode chaincode_example02...
info: [install-chaincode.js]: Installed chaincode chaincode_example02 successfully in all peers
info: [install-chaincode.js]: Installing chaincode fabcar...
info: [install-chaincode.js]: Installed chaincode fabcar successfully in all peers
info: [instantiate-chaincode.js]: Instantiating chaincodes...
info: [e2eUtils.js]: instantiate proposal was good
info: [e2eUtils.js]: Successfully sent Proposal and received ProposalResponse
info: [e2eUtils.js]: The chaincode instantiate transaction has been committed on peer localhost:7051
info: [e2eUtils.js]: The chaincode instantiate transaction was valid.
info: [e2eUtils.js]: Successfully sent instantiatetransaction to the orderer.
info: [instantiate-chaincode.js]: Instantiated chaincode chaincode_example02 successfully
info: [e2eUtils.js]: instantiate proposal was good
info: [e2eUtils.js]: Successfully sent Proposal and received ProposalResponse
info: [e2eUtils.js]: The chaincode instantiate transaction has been committed on peer localhost:7051
info: [e2eUtils.js]: The chaincode instantiate transaction was valid.
info: [e2eUtils.js]: Successfully sent instantiatetransaction to the orderer.
info: [instantiate-chaincode.js]: Instantiated chaincode fabcar successfully
info: [instantiate-chaincode.js]: Sleeping 5s...
info: [bench-flow.js]: Started monitor successfully
info: [bench-flow.js]: ####### Testing 'invoke' #######
info: [bench-flow.js]: ------ Test round 1 ------
info: [demo.js]: [Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
info: [demo.js]: [Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
info: [demo.js]: [Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
info: [demo.js]: [Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
info: [demo.js]: [Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
info: [demo.js]: [Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
error: [e2eUtils.js]: Failed to complete transaction [bd1af...]:Error: Endorsement denied: Error: args1:A,B,1args2:args3:
    at Object.invokebycontext (/opt/gopath/src/github.com/hyperledger/caliper/src/adapters/fabric/e2eUtils.js:1069:27)
    at <anonymous>
error: [e2eUtils.js]: Failed to complete transaction [08f15...]:Error: Endorsement denied: Error: args1:A,B,1args2:args3:
    at Object.invokebycontext (/opt/gopath/src/github.com/hyperledger/caliper/src/adapters/fabric/e2eUtils.js:1069:27)
    at <anonymous>
error: [e2eUtils.js]: Failed to complete transaction [0a2a2...]:Error: Endorsement denied: Error: args1:A,B,1args2:args3:
    at Object.invokebycontext (/opt/gopath/src/github.com/hyperledger/caliper/src/adapters/fabric/e2eUtils.js:1069:27)
    at <anonymous>
error: [e2eUtils.js]: Failed to complete transaction [40bd7...]:Error: Endorsement denied: Error: args1:A,B,1args2:args3:
    at Object.invokebycontext (/opt/gopath/src/github.com/hyperledger/caliper/src/adapters/fabric/e2eUtils.js:1069:27)
    at <anonymous>
error: [e2eUtils.js]: Failed to complete transaction [5c174...]:Error: Endorsement denied: Error: args1:A,B,1args2:args3:
    at Object.invokebycontext (/opt/gopath/src/github.com/hyperledger/caliper/src/adapters/fabric/e2eUtils.js:1069:27)
    at <anonymous>
error: [e2eUtils.js]: Failed to complete transaction [b291a...]:Error: Endorsement denied: Error: args1:A,B,1args2:args3:
    at Object.invokebycontext (/opt/gopath/src/github.com/hyperledger/caliper/src/adapters/fabric/e2eUtils.js:1069:27)
    at <anonymous>
error: [e2eUtils.js]: Failed to complete transaction [b5342...]:Error: Endorsement denied: Error: args1:A,B,1args2:args3:
    at Object.invokebycontext (/opt/gopath/src/github.com/hyperledger/caliper/src/adapters/fabric/e2eUtils.js:1069:27)
    at <anonymous>
```

**Comment by Dingxining** [comment]
I get the same error
```
{
            chaincodeFunction: 'invoke',
            chaincodeArguments: ["A","B","1"]
        }
```

**Comment by aklenik** [comment]
@Dingxining I think for the other adapter you need to pass named args, something like this:
```js
args: {
  param1: "A",
  param2: "B",
  param3: "1"
```

But check the other examples to confirm this.

**Comment by PADMAARUN** [comment]
tried to install hyperledger caliper and run sample benchmarks in ubuntu 16.04. I followed these steps:

    npm init -y
    npm install --only=prod @hyperledger/caliper-cli
    npx caliper bind --caliper-bind-sut fabric --caliper-bind-sdk 1.4.0

When I try to run the sample benchmark, I get this error.

Any help would be appreciated.

cse@system:~$ npx caliper --version

v0.2.0

cse@system:~$ docker --version

Docker version 1.10.3, build 20f81dd

cse@system:~$ docker-compose --version

docker-compose version 1.18.0, build 8dd22a9

cse@system:~$ npx caliper benchmark run --caliper-workspace ./ --caliper-benchconfig ~/caliper/packages/caliper-samples/benchmark/marbles/config.yaml --caliper-networkconfig ~/caliper/packages/caliper-samples/network/fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml


Benchmark for target Blockchain type fabric about to start
2019.11.25-15:46:19.180 info  [caliper] [caliper-flow]  ####### Caliper Test #######

2019.11.25-15:46:19.182 info  [caliper] [local-observer]    Observer interval set to 1 seconds

2019.11.25-15:46:19.183 info  [caliper] [caliper-utils]     Executing command: cd /home/cse;docker-compose -f caliper/packages/caliper-samples/network/fabriCreating orderer.example.com ... done


Creating network "2org1peergoleveldb_default" with the default driver

Creating peer0.org2.example.com ... done

Creating ca.org1.example.com ... 

Creating ca.org2.example.com ... 

Creating peer0.org2.example.com ... 

Creating peer0.org1.example.com ... 

2019.11.25-15:46:23.838 info  [caliper] [adapters/fabric]   Fabric SDK version: 1.4.0; TLS: none
2019.11.25-15:46:24.182 info  [caliper] [adapters/fabric]   Org1's registrar enrolled successfully
2019.11.25-15:46:24.359 info  [caliper] [adapters/fabric]   Org2's registrar enrolled successfully
2019.11.25-15:46:24.391 info  [caliper] [adapters/fabric]   Org1's admin's materials are successfully loaded

2019.11.25-15:46:24.399 info  [caliper] [adapters/fabric]   Org2's admin's materials are successfully loaded

2019.11.25-15:46:24.405 info  [caliper] [adapters/fabric]   client0.org1.example.com's materials are successfully loaded

2019.11.25-15:46:24.412 info  [caliper] [adapters/fabric]   client0.org2.example.com's materials are successfully loaded

2019.11.25-15:46:24.412 info  [caliper] [adapters/fabric]   Channel 'mychannel' definiton being retrieved from file

2019.11.25-15:46:24.452 info  [caliper] [adapters/fabric]   Channel 'mychannel' successfully created

2019.11.25-15:46:24.452 info  [caliper] [adapters/fabric]   Sleeping 5s...

2019.11.25-15:46:29.542 info  [caliper] [adapters/fabric]   Org1's peers successfully joined mychannel: peer0.org1.example.com
2019.11.25-15:46:29.633 info  [caliper] [adapters/fabric]   Org2's peers successfully joined mychannel: peer0.org2.example.com

2019.11.25-15:46:29.633 info  [caliper] [adapters/fabric]   Sleeping 5s...

2019.11.25-15:46:34.636 info  [caliper] [adapters/fabric]   Installing chaincodes for mychannel...



2019-11-25T10:16:34.666Z - error: [packager/Golang.js]: **error** while packaging /home/cse/src/contract/fabric/marbles/go

2019-11-25T10:16:34.666Z - error: [Client.js]: installChaincode **error** ENOENT: no such file or directory, lstat '/home/cse/src/contract/fabric/marbles/go'

2019.11.25-15:46:34.667 error [caliper] [caliper-flow]  **Error: Error**: Could not install marbles@v0 on peers peer0.org1.example.com: ENOENT: no such file or directory, lstat '/home/cse/src/contract/fabric/marbles/go'

    at Fabric._installChaincodes (/home/cse/node_modules/@hyperledger/caliper-fabric/lib/fabric.js:1221:31)

    at <anonymous>

    at process._tickCallback (internal/process/next_tick.js:189:7)

2019.11.25-15:46:35.669 info  [caliper] [local-observer]    [undefined Round undefined Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0

2019.11.25-15:46:35.670 info  [caliper] [caliper-utils]     Executing command: cd /home/cse;docker-compose -f caliper/packages/caliper-samples/network/fabric-v1.4.1/2org1peergoleveldb/docker-compose.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*
Stopping peer0.org2.example.com ... done
Stopping peer0.org1.example.com ... done

Stopping orderer.example.com    ... done

Stopping ca.org1.example.com    ... done

Stopping ca.org2.example.com    ... done

Removing peer0.org2.example.com ... done

Removing peer0.org1.example.com ... done

Removing orderer.example.com    ... done

Removing ca.org1.example.com    ... done

Removing ca.org2.example.com    ... done

Removing network 2org1peergoleveldb_default
docker: "rm" requires a minimum of 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
docker: "images" requires a maximum of 1 argument.
See 'docker images --help'.

Usage:  docker images [OPTIONS] [REPOSITORY[:TAG]]

List images
docker: "images" requires a maximum of 1 argument.
See 'docker images --help'.

Usage:  docker images [OPTIONS] [REPOSITORY[:TAG]]

List images
docker: "rmi" requires a minimum of 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
**Benchmark failure**
Error: Benchmark failure
    at Function.handler (/home/cse/node_modules/@hyperledger/caliper-cli/lib/benchmark/lib/runBenchmark.js:70:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
**Command failed**

**Comment by aklenik** [comment]
@PADMAARUN The reason for the error is in the logs: ENOENT: no such file or directory, lstat '/home/cse/src/contract/fabric/marbles/go'

Every relative path in your configurations will be resolved according to the workspace directory. Think of this as your project directory. 
The examples are designed to be self-contained, so they use relative paths everywhere. Set your workspace directory to the caliper-samples dir, and you should be fine

**Comment by PADMAARUN** [comment]
THANKS SIR..

WILL TRY AND LET YOU KNOW..

**Comment by PADMAARUN** [comment]
that error got corrected....

but i get this error when i run the sample benchmark

cse@system:~$ sudo npx caliper benchmark run --caliper-workspace ./
--caliper-benchconfig
~/caliper/packages/caliper-samples/benchmark/drm/config.yaml
--caliper-networkconfig
~/caliper/packages/caliper-samples/network/fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml
Benchmark for target Blockchain type fabric about to start
2019.11.27-22:17:38.440 info  [caliper] [caliper-flow]     ####### Caliper
Test #######
2019.11.27-22:17:38.442 info  [caliper] [local-observer]     Observer
interval set to 1 seconds
2019.11.27-22:17:38.443 info  [caliper] [caliper-utils]     Executing
command: cd /home/cse;docker-compose -f
caliper/packages/caliper-samples/network/fabric-v1.4.1/2org1peergoleveldb/docker-compose.yCreating
orderer.example.com ... done
Creating network "2org1peergoleveldb_default" with the default driver
Creating peer0.org2.example.com ... done
Creating ca.org1.example.com ...
Creating ca.org2.example.com ...
Creating peer0.org1.example.com ...
Creating peer0.org2.example.com ...
2019.11.27-22:17:43.036 info  [caliper] [adapters/fabric]     Fabric SDK
version: 1.4.0; TLS: none
2019.11.27-22:17:43.379 info  [caliper] [adapters/fabric]     Org1's
registrar enrolled successfully
2019.11.27-22:17:43.513 info  [caliper] [adapters/fabric]     Org2's
registrar enrolled successfully
2019.11.27-22:17:43.540 info  [caliper] [adapters/fabric]     Org1's
admin's materials are successfully loaded
2019.11.27-22:17:43.548 info  [caliper] [adapters/fabric]     Org2's
admin's materials are successfully loaded
2019.11.27-22:17:43.554 info  [caliper] [adapters/fabric]
client0.org1.example.com's materials are successfully loaded
2019.11.27-22:17:43.559 info  [caliper] [adapters/fabric]
client0.org2.example.com's materials are successfully loaded
2019.11.27-22:17:43.559 info  [caliper] [adapters/fabric]     Channel
'mychannel' definiton being retrieved from file
2019.11.27-22:17:43.592 info  [caliper] [adapters/fabric]     Channel
'mychannel' successfully created
2019.11.27-22:17:43.593 info  [caliper] [adapters/fabric]     Sleeping 5s...
2019.11.27-22:17:48.675 info  [caliper] [adapters/fabric]     Org1's peers
successfully joined mychannel: peer0.org1.example.com
2019.11.27-22:17:48.767 info  [caliper] [adapters/fabric]     Org2's peers
successfully joined mychannel: peer0.org2.example.com
2019.11.27-22:17:48.768 info  [caliper] [adapters/fabric]     Sleeping 5s...
2019.11.27-22:17:53.771 info  [caliper] [adapters/fabric]     Installing
chaincodes for mychannel...
2019.11.27-22:17:53.803 info  [caliper] [adapters/fabric]     marbles@v0
successfully installed on Org1's peers: peer0.org1.example.com
2019.11.27-22:17:53.812 info  [caliper] [adapters/fabric]     marbles@v0
successfully installed on Org2's peers: peer0.org2.example.com
2019.11.27-22:17:53.825 info  [caliper] [adapters/fabric]     drm@v0
successfully installed on Org1's peers: peer0.org1.example.com
2019.11.27-22:17:53.832 info  [caliper] [adapters/fabric]     drm@v0
successfully installed on Org2's peers: peer0.org2.example.com
2019.11.27-22:17:53.848 info  [caliper] [adapters/fabric]     simple@v0
successfully installed on Org1's peers: peer0.org1.example.com
2019.11.27-22:17:53.853 info  [caliper] [adapters/fabric]     simple@v0
successfully installed on Org2's peers: peer0.org2.example.com
2019.11.27-22:17:53.866 info  [caliper] [adapters/fabric]     smallbank@v0
successfully installed on Org1's peers: peer0.org1.example.com
2019.11.27-22:17:53.871 info  [caliper] [adapters/fabric]     smallbank@v0
successfully installed on Org2's peers: peer0.org2.example.com
2019.11.27-22:17:53.872 info  [caliper] [adapters/fabric]     Instantiating
marbles@v0 in mychannel. This might take some time...
2019.11.27-22:17:54.846 info  [caliper] [adapters/fabric]     Successfully
instantiated marbles@v0 in mychannel
2019.11.27-22:17:54.848 info  [caliper] [adapters/fabric]     Instantiating
drm@v0 in mychannel. This might take some time...
2019.11.27-22:17:55.725 info  [caliper] [adapters/fabric]     Successfully
instantiated drm@v0 in mychannel
2019.11.27-22:17:55.726 info  [caliper] [adapters/fabric]     Instantiating
simple@v0 in mychannel. This might take some time...
2019.11.27-22:17:56.564 info  [caliper] [adapters/fabric]     Successfully
instantiated simple@v0 in mychannel
2019.11.27-22:17:56.565 info  [caliper] [adapters/fabric]     Instantiating
smallbank@v0 in mychannel. This might take some time...
2019.11.27-22:17:57.579 info  [caliper] [adapters/fabric]     Successfully
instantiated smallbank@v0 in mychannel
2019.11.27-22:17:57.581 info  [caliper] [adapters/fabric]     Sleeping 5s...



2019.11.27-22:18:04.474 info  [caliper] [caliper-flow]     Started monitors
successfully
2019.11.27-22:18:04.476 info  [caliper] [defaultTest]     ####### Testing
'publish' #######
2019.11.27-22:18:04.477 info  [caliper] [defaultTest]     ####### Testing
'query' #######
2019.11.27-22:18:04.478 info  [caliper] [caliper-flow]     ----------
Finished Test ----------








*2019.11.27-22:18:04.478 info  [caliper] [report-builder]     ### All test
results ###2019.11.27-22:18:04.478 error [caliper] [caliper-flow]
Error: Error: Table must define at least one row.    at
exports.default.rows
(/home/cse/node_modules/table/dist/validateTableData.js:26:11)    at
Object.exports.default [as table]
(/home/cse/node_modules/table/dist/table.js:116:35)    at Report.printTable
(/home/cse/node_modules/@hyperledger/caliper-core/lib/report/report.js:133:23)
at Report.printResultsByRound
(/home/cse/node_modules/@hyperledger/caliper-core/lib/report/report.js:255:14)
at Object.module.exports.run
(/home/cse/node_modules/@hyperledger/caliper-core/lib/caliper-flow.js:119:20)
at <anonymous>*
    at process._tickCallback (internal/process/next_tick.js:189:7)
2019.11.27-22:18:05.480 info  [caliper] [local-observer]     [query Round
undefined Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
2019.11.27-22:18:05.481 info  [caliper] [caliper-utils]     Executing
command: cd /home/cse;docker-compose -f
caliper/packages/caliper-samples/network/fabric-v1.4.1/2org1peergoleveldb/docker-compose.yaml
down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z
\"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf
/tmp/hfc-*
