### ISSUE TITLE
Sample config files with Kafka orderer 

### ISSUE THREAD

**Issue by quangtdn** [hyperledger/caliper#375]
Hi there!

I already managed to run Caliper to benchmark a distributed Hyperledger Fabric Network. 
I really would like to now test Fabric under Kafka orderers. As I can see, the new Caliper with Fabric cpp now supports multiple orderers. Just for making sure, I want to ask if it is possible to benchmark a Fabric system using Kafka orderers. If so, is there any available sample config files with Kafka orderers in Caliper?

Thank you very much!

**Comment by aklenik** [comment]
@quangtdn You're right, multiple orderers (and thus Kafka-based ordering services) are now supported. However, there isn't a sample network for this. I think someone is working on a sample, but feel free to contribute your own fairly (but not too) complex network sample :)

**Comment by niket-yende** [comment]
@aklenik @quangtdn If some one can add a sample config file for benchmarking kafka it would be helpful for others.
