### ISSUE TITLE
add the Caliper running environment detection script  

### ISSUE THREAD

**Issue by houqinghui** [hyperledger/caliper#376]
When we run caliper to test our blockchain network, we should install many pre-requisity tools which is  fussy. So i want to write a static script to check whether they are installed, then install them if not. 
1. nodejs
2. nodegyp
3. docker
4. docker-compose
5. authority of linux user

**Comment by aklenik** [comment]
@houqinghui Can you elaborate on the pre-reqs? You mean docker and other dependencies, or blockchain platform dependencies?
