### ISSUE TITLE
zookeeper clients setup

### ISSUE THREAD

**Issue by quangtdn** [hyperledger/caliper#388]
Hi people!

I am going to use the Zookeeper service for benchmarking with distributed clients now. I have  some questions about the settings on Caliper. 

Firstly, do all the clients on distributed machines under Zookeeper service benchmark with the same exactly one channel specified in the master node? I want to make sure that distributed clients will not independently launch independent channels to test the same fabric network.

Secondly, if I run on nodes of a cluster, should time synchronization be inherent within the cluster?

Lastly, I just want to justify my understanding of the documentation. Please correct me if I am wrong. As far as I understand, the following steps are required for benchmarking distributed clients:

1) Run Zookeeper on 1 machine with some IP address, say 10.229.42.159.
2) On any machine that you want to launch Caliper client(s) for benchmarking, you run 'npm run startclient -- 10.229.42.159:2181' where 2181 is the port that Zookeeper uses to listen to client connection.
3) Add this to the config.json (or yaml) file of Caliper:
"clients": {
   "type": "zookeeper",
   "zoo" : {
     "server": "10.229.42.159:2181",
     "clientsPerHost": 5
   }
 }
And you don't have to specify anything about machines connected to Zookeeper server at 10.229.42.159 and the number of such machines. Caliper will automatically run benchmark on all of them.

Thank you very much for your time!

**Comment by quangtdn** [comment]
I managed to use distributed Zookeeper Clients to benchmark a distributed fabric network already. 

For my first question, I think it is probably correct.
For my 2nd concern, I indeed couldn't use distributed Zookeeper Clients of Caliper on my 2 machines. But it worked fine when I brought it onto the cluster. I am not sure if it's because of time sync, but it just works.

So I'm closing this now xD. 
Thanks!

**Comment by susheeldighade** [comment]
Hi quangtdn,
Can you please tell me how did you resolve the issue.
I created zookeeper cluster (on 1 machine using 3 docker containers) by referring to caliper documentation.
1. caliper zooservice start
All three containers were successfully launched
2. caliper zooclient start -w ~/myCaliperProject -a my_ip:my_port  -n my-sut-config.yaml
Output:
**Starting zookeeper client of type fabric
Command succeeded**

But when I checked on docker logs it showed following error:
**zoo1    | 2019-07-29 09:43:32,738 [myid:1] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@222] - Accepted socket connection f
rom /xx.xxx.xxx.xxx:35736
zoo1    | 2019-07-29 09:43:32,748 [myid:1] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@376] - Unable to read additional data from
 client sessionid 0x0, likely client has closed socket
zoo1    | 2019-07-29 09:43:32,749 [myid:1] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1056] - Closed socket connection for clien
t /xx.xxx.xxx.xxx8:35736 (no session established for client)**

3. while running benchmark it couldn't find any zookeeper clients.

**Comment by aklenik** [comment]
@susheeldighade Just a heads-up, the zookeeper feature will be deprecated/removed, because it's overly complex and the provided crash fault tolerance is not needed. It'll be replaced by a more lightweight and self-contained protocol (ie, no additional nodes will be needed beside the caliper nodes)

**Comment by susheeldighade** [comment]
@aklenik , Thanks for your quick response.
But how do you propose to perform a distributed testing by Caliper with the existing version. For us its a bit urgent, so can you please help us with some workaround. 
Do you know by when the lightweight version would be available for use?

**Comment by aklenik** [comment]
@susheeldighade How many TPS would you like to generate? With a few local clients, Caliper should be able to generate around 10k TPS. See PR #509 and Issue #505 
So you might not even need distributed clients.

**Comment by TopJohn** [comment]
> @aklenik , Thanks for your quick response.
> But how do you propose to perform a distributed testing by Caliper with the existing version. For us its a bit urgent, so can you please help us with some workaround.
> Do you know by when the lightweight version would be available for use?

do you solve the zookeeper problem ? I have met the same problem.but do not know how to solve.
