### ISSUE TITLE
If there is no result comming back after you commit the transactions

### ISSUE THREAD

**Issue by zcqzcg** [hyperledger/caliper#389]
It's like "**unfinished**" forever on command line.

And all transactions has been committed and sucess in peer.

Only the result was not comming back to my local machine.

So, here would be a little bug I have found in the Caliper fabric config file.

In the secter "info", as you can see below:
```json 
{
  "info": {
    "Version": "1.0.0",
    "Size": "4 Peers",
    "Orderer": "Solo",
    "Distribution": "Single Host",
    "details": "not provided"
  }
}
```

### You MUST get the "Version" right with your current fabric network.

For me, it writes "1.0.3" from nowhere, and it took me two days to find this bug, which is ignored in the [caliper site](https://hyperledger.github.io/caliper/docs/Fabric_Configuration.html).

Please add this note on your site. 
Thanks!

**Comment by aklenik** [comment]
@zcqzcg The `info` section of any platform's [network config](https://hyperledger.github.io/caliper/docs/Fabric_Ccp_Configuration.html#network-information) file does not affect the tests, those key-value pairs are meant to be included in the generated report, nothing more.

There could be a connection issue or lost message during a test that causes this seemingly infinite repeat. However, everything should reach the timeout eventually and terminate, hopefully.

**Comment by zcqzcg** [comment]
@aklenik Thanks for your advice and please check the fowlling codes in `caliper/src/adapters/fabric/e2eUtils.js` Line 46:
```js
/**
 * Initialize the Fabric client configuration.
 * @param {string} config_path The path of the Fabric network configuration file.
 */
function init(config_path) {
    const config = commUtils.parseYaml(config_path);
    ORGS = config.fabric.network;
    isLegacy = (config.info.Version.startsWith('1.0') || config.info.Version.startsWith('1.1'));
    if(!isLegacy){
        Gateway = require('fabric-network').Gateway;
        InMemoryWallet = require('fabric-network').InMemoryWallet;
        X509WalletMixin = require('fabric-network').X509WalletMixin;
    }
}
```

In that `init`, it's using the `info.Version` to decide which way to send transactions, the gateway or the basic context way( which I know nothing about the old way, I start with 1.2 ).

So in here, the `info.Version` matters.

Also, I am not so sure but I will ask anyway, hope you don't mind.
The `info.Version` also matters the `deps` which is used by caliper.

For example, if `info.Version` = 1.2, and we need to run `npm run fabric-v1.2-deps`.
Or, you will face error like this `Error: Cannot find module 'fabric-ca-client/lib/FabricCAClientImpl.js'`.

So I think, the `info.Version` should `=` the fabric version and also `=` the deps.

**Comment by aklenik** [comment]
@zcqzcg You're right, I wasn't aware of this change. However, this adapter will be deprecated soon, so maybe you should try the new Fabric CCP adapter: https://hyperledger.github.io/caliper/docs/Fabric_Ccp_Configuration.html
This detects the Fabric version based on the installed SDK version (from Fabric SDK 1.1), and based on whether peer event URLs are present in the config (which indicates Fabric 1.0).
