### ISSUE TITLE
errors running smallbank chaincode with fabric-ccp

### ISSUE THREAD

**Issue by quangtdn** [hyperledger/caliper#394]
Hi people,

I just run a simple bencmark:
npm run bench -- -c benchmark/smallbank/config.yaml -n network/fabric-v1.1/3org1peergoleveldb/fabric-ccp-go.yaml

But I got these errors. Other chaincodes are fine.

Thank you.

info: [bench-flow.js]: Started monitor successfully
info: [bench-flow.js]: ####### Testing 'smallOperations' #######
info: [bench-flow.js]: ------ Test round 1 ------
error: [adapters/fabric-ccp]: Transaction[5d8b589359] life-cycle errors:
	- "value" argument must not be a number
error: [adapters/fabric-ccp]: Transaction[c7a6e1e842] life-cycle errors:
	- "value" argument must not be a number
error: [adapters/fabric-ccp]: Transaction[a433e0365d] life-cycle errors:
	- "value" argument must not be a number
error: [adapters/fabric-ccp]: Transaction[89660ac33a] life-cycle errors:
	- "value" argument must not be a number
error: [adapters/fabric-ccp]: Transaction[a4bf36597c] life-cycle errors:
	- "value" argument must not be a number
info: [demo.js]: [Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
error: [adapters/fabric-ccp]: Transaction[512d6f9a38] life-cycle errors:
	- "value" argument must not be a number
error: [adapters/fabric-ccp]: Transaction[67263cf71a] life-cycle errors:
	- "value" argument must not be a number
error: [adapters/fabric-ccp]: Transaction[bcc827ecad] life-cycle errors:
	- "value" argument must not be a number
error: [adapters/fabric-ccp]: Transaction[0821a77478] life-cycle errors:
	- "value" argument must not be a number
error: [adapters/fabric-ccp]: Transaction[3bfa87d522] life-cycle errors:
	- "value" argument must not be a number
error: [adapters/fabric-ccp]: Transaction[8c5c0c3338] life-cycle errors:
	- "value" argument must not be a number
error: [adapters/fabric-ccp]: Transaction[915c070598] life-cycle errors:
	- "value" argument must not be a number
error: [adapters/fabric-ccp]: Transaction[97e5e7d01c] life-cycle errors:

**Comment by aklenik** [comment]
Resolved by #430
