### ISSUE TITLE
How to run caliper with distributed clients

### ISSUE THREAD

**Issue by robiharid** [hyperledger/caliper#403]
Hi guys

I am trying to run zookeeper to run the benchmark across multiple Azure VMs in the cloud. I want to send transactions across the network at scale so I can benchmark the performance.

With Zookeeper:
1. What do I specify in the conf/zoo.cfg file? (https://zookeeper.apache.org/doc/r3.1.2/zookeeperStarted.html)

With Launch clients on target machine seperately:
1. Does this mean I have to install npm, node, fabric-ca, etc on each machine?
2. Does this mean I pull caliper on each machine? 
3. Do I then run npm run startclient -- zookeeper-server for each machine?

Thank you, I am really new to this - just trying to do some basic things.

When I try to run `npm run startclient -- ip.azure.com:2181` I get this:

>caliper@0.1.0 startclient /home/user/caliper
>node ./src/comm/client/zoo-client.js "ip:2181"

and then the process just hangs and doesn't update

**Comment by houqinghui** [comment]
@robiharid  1. You should intall npm, node, fabric-ca,etc on each machine, then you can start the client. While we start to virtualize the module, so that users can install npm package or docker image to test their blockchain network. 2. Yes, you should pull caliepr on each machine, because the code of the client is located in the caliper repo. 3. Yes,

**Comment by robiharid** [comment]
> @robiharid 1. You should intall npm, node, fabric-ca,etc on each machine, then you can start the client. While we start to virtualize the module, so that users can install npm package or docker image to test their blockchain network.
> 2. Yes, you should pull caliepr on each machine, because the code of the client is located in the caliper repo.
> 3. Yes,

Thanks so much!

I have installed all dependencies on new VM.

**Main VM:**
`npm run startclient -- ip:2181`

> caliper@0.1.0 startclient /home/robiharid/caliper
> node ./src/comm/client/zoo-client.js "ip.com:2181"

**Slave VM:**
`npm run startclient -- zookeeper-server`

> caliper@0.1.0 startclient /home/robiharid/caliper
> node ./src/comm/client/zoo-client.js "zookeeper-server"

How do I specify what IP zookeeper should connect to on slave VM?

**Comment by houqinghui** [comment]
@robiharid  1. You should start the ZK service, the ip should be the local host's ip. 
2. You should run `npm run startclient -- your ip : port` in all VM.

**Comment by robiharid** [comment]
> @robiharid 1. You should start the ZK service, the ip should be the local host's ip.
> 2. You should run `npm run startclient -- your ip : port` in all VM.

Thank you - but I just get frozen screen?

I am running npm run startclient with the IP I use SSH into.

![image](https://user-images.githubusercontent.com/16907484/55751031-996b6280-5a3c-11e9-94e7-5d3e750e90fd.png)
It freezes and doesn't do anything?

**Comment by houqinghui** [comment]
@robiharid  I want to know whether you have started the zookeeper service. You can excute `jps` to check the ZK status, and you can refer to [the doc](https://blog.csdn.net/zhengxiangwen/article/details/50631696)

**Comment by robiharid** [comment]
> @robiharid I want to know whether you have started the zookeeper service. You can excute `jps` to check the ZK status, and you can refer to [the doc](https://blog.csdn.net/zhengxiangwen/article/details/50631696)

Thank you.

![image](https://user-images.githubusercontent.com/16907484/55800907-bcddee00-5acc-11e9-8275-6cf2b58c8b17.png)

I am not sure if ZK is running as I specify port 2181 but it shows port 6451.

![image](https://user-images.githubusercontent.com/16907484/55802445-2a3f4e00-5ad0-11e9-97d7-dbc21e964406.png)

when I connect using I get: Connection refused
![image](https://user-images.githubusercontent.com/16907484/55802488-3e834b00-5ad0-11e9-881f-2f447d8b96d5.png)]

this is my ZK conf/zoo.cfg file:
![image](https://user-images.githubusercontent.com/16907484/55802563-64a8eb00-5ad0-11e9-8be8-0989faadff75.png)

This does not change the caliper ```npm run startclient -- zookeeper-server``` freezing as I believe JPS shows there is no Quorum pid (Zookeeper)

**Comment by jutinguely** [comment]
@robiharid did you figure out how it worked?
