### ISSUE TITLE
Error: Failed to connect before deadline

### ISSUE THREAD

**Issue by hppranaav** [hyperledger/caliper#411]
I am running my custom chaincode on caliper. As such i have created extra peers for my test scenario and have created new crypto material for it. After creating them, i tried to run my benchmark test, however after all the containers are set up, the test unexpectedly stop showing the error

2019-04-18T13:46:07.351Z - error: [Remote.js]: Error: Failed to connect before the deadline URL:grpc://localhost:7050
2019-04-18T13:46:07.354Z - error: [Orderer.js]: Orderer grpc://localhost:7050 has an error Error: Failed to connect before the deadline URL:grpc://localhost:7050

I am running a standard test that comes with caliper for 2 Organisations and 1 peer. I have not changed any other files. I expected the test to run smoothly, as it has run before previously.

I am using the latest version of caliper.
fabric: v1.3.0
npm: v5.6.0
 I am not able to run any tests after i have generated crypto material for extra peers.

**Comment by hppranaav** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/home/pranaav/.nvm/versions/node/v8.9.4/bin/node',
1 verbose cli   '/home/pranaav/.nvm/versions/node/v8.9.4/bin/npm',
1 verbose cli   'run',
1 verbose cli   'bench',
1 verbose cli   '--',
1 verbose cli   '-c',
1 verbose cli   'benchmark/disaster/config.yaml',
1 verbose cli   '-n',
1 verbose cli   'network/fabric-v1.3/2org1peergoleveldb/fabric-go.json' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prebench', 'bench', 'postbench' ]
5 info lifecycle caliper@0.1.0~prebench: caliper@0.1.0
6 info lifecycle caliper@0.1.0~bench: caliper@0.1.0
7 verbose lifecycle caliper@0.1.0~bench: unsafe-perm in lifecycle true
8 verbose lifecycle caliper@0.1.0~bench: PATH: /home/pranaav/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pranaav/go/src/github.com/hppranaav/caliper/node_modules/.bin:/home/pranaav/.nvm/versions/node/v8.9.4/bin:/home/pranaav/bin:/home/pranaav/.local/bin:/home/pranaav/bin:/home/pranaav/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle caliper@0.1.0~bench: CWD: /home/pranaav/go/src/github.com/hppranaav/caliper
10 silly lifecycle caliper@0.1.0~bench: Args: [ '-c',
10 silly lifecycle   'node ./scripts/main.js "-c" "benchmark/disaster/config.yaml" "-n" "network/fabric-v1.3/2org1peergoleveldb/fabric-go.json"' ]
11 silly lifecycle caliper@0.1.0~bench: Returned: code: 1  signal: null
12 info lifecycle caliper@0.1.0~bench: Failed to exec bench script
13 verbose stack Error: caliper@0.1.0 bench: `node ./scripts/main.js "-c" "benchmark/disaster/config.yaml" "-n" "network/fabric-v1.3/2org1peergoleveldb/fabric-go.json"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/pranaav/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/pranaav/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid caliper@0.1.0
15 verbose cwd /home/pranaav/go/src/github.com/hppranaav/caliper
16 verbose Linux 4.15.0-47-generic
17 verbose argv "/home/pranaav/.nvm/versions/node/v8.9.4/bin/node" "/home/pranaav/.nvm/versions/node/v8.9.4/bin/npm" "run" "bench" "--" "-c" "benchmark/disaster/config.yaml" "-n" "network/fabric-v1.3/2org1peergoleveldb/fabric-go.json"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error caliper@0.1.0 bench: `node ./scripts/main.js "-c" "benchmark/disaster/config.yaml" "-n" "network/fabric-v1.3/2org1peergoleveldb/fabric-go.json"`
22 error Exit status 1
23 error Failed at the caliper@0.1.0 bench script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]



## This is the log file associated with the error

**Comment by aklenik** [comment]
@hppranaav Start the network manually, and check the orderer logs. Probably it had some errors and couldn't start, that's why Caliper can't connect to it
