### ISSUE TITLE
BAD_REQUEST when creating channel

### ISSUE THREAD

**Issue by rarae** [hyperledger/caliper#412]
info: [create-channel.js]: Creating mychannel...
error: [create-channel.js]: Failed to create channels: Error: Create status for mychannel is BAD_REQUEST with information error authorizing update: error validating ReadSet: existing config does not contain element for [Group]  /Channel/Application/Org4MSP but was in the read set
    at Object.run (/home/kafka/caliper/src/adapters/fabric/create-channel.js:125:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
error: [fabric.js]: Fabric initialization failed: Error: Create status for mychannel is BAD_REQUEST with information error authorizing update: error validating ReadSet: existing config does not contain element for [Group]  /Channel/Application/Org4MSP but was in the read set
    at Object.run (/home/kafka/caliper/src/adapters/fabric/create-channel.js:125:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
error: [bench-flow.js]: Error: Error: Create status for mychannel is BAD_REQUEST with information error authorizing update: error validating ReadSet: existing config does not contain element for [Group]  /Channel/Application/Org4MSP but was in the read set
    at Object.run (/home/kafka/caliper/src/adapters/fabric/create-channel.js:125:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
info: [demo.js]: [Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0

**Comment by aklenik** [comment]
@rarae Did you generate your own genesis block and channel configuration Tx, or you used an example from the repo? Since I see Org4MSP in the errors, I'm guessing you're running a custom network. Make sure your genesis block also contains this Org
