### ISSUE TITLE
npm run bench with fabric got docker rm errors 

### ISSUE THREAD

**Issue by nitrousracer** [hyperledger/caliper#413]
This seems similar to issue #352. when running 

npm run bench -- -c benchmark/simple/config.yaml -n network/fabric-v1.2/2org1peergoleveldb/fabric-go.json

(1.1, 1.2, 1.3, 1.4) All versions

it shows the following error:

error: [bench-flow.js]: Unsuccessful command execution. Error code: 1. Terminating signal: null                                                                              error: [scripts/main.js]: Error while executing the benchmark: Error: Command failed: docker-compose -f network/fabric-v1.2/2org1peergoleveldb/docker-compose.yaml down;dock er rm $(docker ps -aq);docker rmi $(docker images dev* -q)                                                                                                                   No such command: down;docker
--

npm ERR! code ELIFECYCLE                                                                                                                                                     npm ERR! errno 1                                                                                                                                                             npm ERR! caliper@0.1.0 bench: `node ./scripts/main.js "-c" "benchmark/simple/config.yaml" "-n" "network/fabric-v1.2/2org1peergoleveldb/fabric-go.json"`                      npm ERR! Exit status 1                                                                                                                                                       npm ERR!                                                                                                                                                                     npm ERR! Failed at the caliper@0.1.0 bench script.                                                                                                                           npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
--

Although I am following the steps precisely and tried to bring the network up and down multiple times, delete all containers and images and start again, use the recommended flags 
--no-recreate, 
--force-recreate

with no results.

**Comment by aklenik** [comment]
@nitrousracer Hmm, this is strange, the same start/end scripts are used everywhere with success for a long time now. Can you provide the versions for the following tools:
* docker
* docker-compose
* node
* your OS

**Comment by nitrousracer** [comment]
Thank you for your response @aklenik, 

I am running the following:

Docker version 18.09.2, build 6247962
docker-compose version 1.23.2, build 1110ad01 (also tried version 1.24.0)
node version: 8.11.0 (I know that version 10 doesn't work, so downgraded to 8)
windows 10 64-bit with hyper-visor enabled.

**Comment by aklenik** [comment]
@nitrousracer Can you try manually executing the start and end scripts without Caliper?

**Comment by nklincoln** [comment]
This command (npm run bench), and the main.js script it called, no longer exists in the Caliper project
