### ISSUE TITLE
Transaction Data Gathered by the fabric-ccp Adapter

### ISSUE THREAD

**Issue by ig0rsky** [hyperledger/caliper#414]
## Expected Behavior
When I'm running the fabric / fabric-ccp adapter, I expect to receive some transaction specific custom data per transaction, as described in the docs.
https://hyperledger.github.io/caliper/docs/Fabric_Ccp_Configuration.html

## Actual Behavior
There's no custom data about the transaction, when tested with Fabric v1.2 to v1.4. Enabling such custom data about transactions on the network is not described in the documentation.

## Possible Fix
Pointing to a documentation / setting in the Hyperledger Fabric docs for enabling said behaviour, or perhaps adding more detail on the corresponding section of Caliper documentation.

@aklenik

**Comment by aklenik** [comment]
@ig0rsky As detailed by [the CCP docs](https://hyperledger.github.io/caliper/docs/Fabric_Ccp_Configuration.html#transaction-data-gathered-by-the-adapter), the return value of the `invoke*` functions is an array of `TxStatus` instances, that provide some functions to retrieve Tx data. You call the `invoke*` functions from your user callback modules, so you can inspect the gathered data there. Automatic export of gathered data is not provided yet.

Something like this should work in your user callback module please verify it:
```js
let results = bc.invokeSmartContract(...);
for (let result of results) {
  console.log(result.GetID());
  console.log(result.GetStatus());
  console.log(result.GetTimeCreate());
  console.log(result.GetTimeFinal());

  for (let customEntry of result.GetCustomData()) {
    console.log(`${customEntry[0]}: ${customEntry[1]}`);
  } 
}
```

**Comment by ig0rsky** [comment]
Thank you, I was turning the object directly into JSON using JSON.stringify and wondering why some of the data is not there. If I'm not mistaken, the old(fabric) query API still won't return any custom data, correct? @aklenik

**Comment by aklenik** [comment]
@ig0rsky IIRC only the basics. We plan to deprecate that adapter, so it's better to stick with the Fabric-CCP adapter

**Comment by hoannguyen26196** [comment]
Sorry sir, i can not find Fabric cpp adapter. Would you give me some suggest? Thank you

**Comment by aklenik** [comment]
@hoannguyen26196 The CCP adapter has been renamed simple to the Fabric adapter (and the old one was removed). You can refer to this doc section for the gathered data: https://hyperledger.github.io/caliper/vLatest/fabric-config/#gathered-tx-data
