### ISSUE TITLE
Fabric Network Files need updating

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#418]
During the refactor to the new project structure, not all of the Fabric network files were updated to the required format.

There are multiple decisions to be made here based on:
 - we are holding *many* network configurations, which is resulting in a large amount of debt when updating items ... is there a smarter way we could be doing this?
 - We are holding static crypto material that will expire. It may be beneficial to add a step that generates the required crypto material using a cryptogen tools (this is now done in the fabric-sdk-node integration tests for that very reason)

Suggestions:
- dynamically generate cryptomaterial for networks
- only provide a limited number of networks for each version:
  - 2org1peer levelDB/couchDB, solo ordering service
  - 2org1peer levelDB/couchDB, kafka/raft ordering service

**Comment by aklenik** [comment]
@nklincoln 👍 for these remarks. I think the different topologies all had their reasons to exist:

#orgs: 
* 1: dev mode
* 2: production-like setup
* 3: possible to test N-of-M endorsement policies

#peers:
* 1: minimum needed, results in the smallest network for every org scenario above 
* 2+: test load balancing mechanisms

#stateDB:
* goleveldb: fast, lightweight
* couchdb: rich query tests

Proposed solutions: 
1. Agree with the dynamically generated crypto artifacts, plus fewer files to pull/push
1. Why not do the same with network configs? They're highly regular in their structure. A script with some high-level parameters could generate all crypto/config/network artifacts (and in a consistent way!!!!). As long as we're sticking to template-like systematic namings (peer0org1, client0.org1, etc.), it should be easy to implement.

**Comment by nklincoln** [comment]
Point 2 in the above: *yes*

**Comment by nklincoln** [comment]
I'm closing this issue because the main content has been delivered - I will raise a separate issue to deal with automatically generating the crypto config
