### ISSUE TITLE
New Docs for refactored package structure need enhancing

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#421]
The new documentation for the refactor project structure require some enhancing, and include (not limited to):
 - More details on bootstrap/repoclean
 - Writing own applications
 - Creating own benchmarks
    - Writing config file
    - Writing test files

**Comment by aklenik** [comment]
@nklincoln I'd leave the first point to you. I've already volunteered for the tutorial-like docs tasks in a previous call :)

**Comment by nklincoln** [comment]
closing due to existing docs and tutorial(s)
