### ISSUE TITLE
Investigate the use of worker threads for client processes

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#423]
At the moment, each Caliper test client is a spawned Node process.

Since node v10, there is the concept of worker threads, which is a far more (memory) efficient (and achieves the same thing) as spawning multiple node processes.

We should investigate upgrading the node version used by Caliper and the ability to use worker threads

**Comment by aklenik** [comment]
Not to mention that debugging is easier in a single process :)
Plus when we do the Caliper master/worker separation, then it would be weird if the worker process would spawn other worker processes :)

**Comment by nklincoln** [comment]
unfortunately this is not possible due to the implementation of gRPC :(

The most sensible line of approach is to either:
- Use clustering to spread across CPUs
- Concentrate efforts on "dockerising" the clients

My vote is on the latter

**Comment by aklenik** [comment]
👍 for the latter, let's focus on building self-contained and easy-to-scale-out clients, and provide deployment templates for popular platforms.
