### ISSUE TITLE
change MaxMessageCount and re-generate config, run simple test with fabric-v1.4  failed

### ISSUE THREAD

**Issue by loganwu** [hyperledger/caliper#431]
I wanna change MaxMessageCount in configtx.yam within fabric-v1.4.
So I re-generate mychannel.tx and orgs.genesis.block file, and re-run simple test failed:

commond: node run-benchmark.js -c ../benchmark/simple/config.yaml  -t fabric -n ../network/fabric-v1.4/3org2peergoleveldb/fabric-go.json

log:  info: [create-channel.js]: Creating mychannel...
2019-04-29T10:34:47.645Z - error: [Remote.js]: Error: Failed to connect before the deadline URL:grpc://localhost:7050
2019-04-29T10:34:47.646Z - error: [Orderer.js]: Orderer grpc://localhost:7050 has an error Error: Failed to connect before the deadline URL:grpc://localhost:7050 
error: [create-channel.js]: Failed to create channels: Error: Failed to connect before the deadline URL:grpc://localhost:7050
    at checkState (/home/loganwu/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:833:16)
error: [fabric.js]: Fabric initialization failed: Error: Failed to connect before the deadline URL:grpc://localhost:7050
    at checkState (/home/loganwu/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:833:16)
error: [caliper-flow]: Error: Error: Failed to connect before the deadline URL:grpc://localhost:7050
    at checkState (/home/loganwu/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:833:16)

**Comment by aklenik** [comment]
@loganwu See Issue #415, maybe it is related. If not, look at the logs of the orderer node and post the relevant parts here.

**Comment by loganwu** [comment]
The following is orderer log:

2019-04-30 06:58:27.593 UTC [localconfig] completeInitialization -> INFO 001 Kafka.Version unset, setting to 0.10.2.0
2019-04-30 06:58:27.604 UTC [orderer.common.server] prettyPrintStruct -> INFO 002 Orderer config values:
	General.LedgerType = "file"
	General.ListenAddress = "0.0.0.0"
	General.ListenPort = 7050
	General.TLS.Enabled = false
	General.TLS.PrivateKey = "/etc/hyperledger/fabric/tls/server.key"
	General.TLS.Certificate = "/etc/hyperledger/fabric/tls/server.crt"
	General.TLS.RootCAs = [/etc/hyperledger/fabric/tls/ca.crt]
	General.TLS.ClientAuthRequired = false
	General.TLS.ClientRootCAs = []
	General.Cluster.RootCAs = [/etc/hyperledger/fabric/tls/ca.crt]
	General.Cluster.ClientCertificate = ""
	General.Cluster.ClientPrivateKey = ""
	General.Cluster.DialTimeout = 5s
	General.Cluster.RPCTimeout = 7s
	General.Cluster.ReplicationBufferSize = 20971520
	General.Cluster.ReplicationPullTimeout = 5s
	General.Cluster.ReplicationRetryTimeout = 5s
	General.Keepalive.ServerMinInterval = 1m0s
	General.Keepalive.ServerInterval = 2h0m0s
	General.Keepalive.ServerTimeout = 20s
	General.GenesisMethod = "file"
	General.GenesisProfile = "SampleInsecureSolo"
	General.SystemChannel = "test-system-channel-name"
	General.GenesisFile = "/etc/hyperledger/configtx/orgs.genesis.block"
	General.Profile.Enabled = false
	General.Profile.Address = "0.0.0.0:6060"
	General.LocalMSPDir = "/etc/hyperledger/msp/orderer/msp"
	General.LocalMSPID = "OrdererMSP"
	General.BCCSP.ProviderName = "SW"
	General.BCCSP.SwOpts.SecLevel = 256
	General.BCCSP.SwOpts.HashFamily = "SHA2"
	General.BCCSP.SwOpts.Ephemeral = false
	General.BCCSP.SwOpts.FileKeystore.KeyStorePath = "/etc/hyperledger/msp/orderer/msp/keystore"
	General.BCCSP.SwOpts.DummyKeystore =
	General.BCCSP.SwOpts.InmemKeystore =
	General.BCCSP.PluginOpts =
	General.Authentication.TimeWindow = 15m0s
	FileLedger.Location = "/var/hyperledger/production/orderer"
	FileLedger.Prefix = "hyperledger-fabric-ordererledger"
	RAMLedger.HistorySize = 1000
	Kafka.Retry.ShortInterval = 5s
	Kafka.Retry.ShortTotal = 10m0s
	Kafka.Retry.LongInterval = 5m0s
	Kafka.Retry.LongTotal = 12h0m0s
	Kafka.Retry.NetworkTimeouts.DialTimeout = 10s
	Kafka.Retry.NetworkTimeouts.ReadTimeout = 10s
	Kafka.Retry.NetworkTimeouts.WriteTimeout = 10s
	Kafka.Retry.Metadata.RetryMax = 3
	Kafka.Retry.Metadata.RetryBackoff = 250ms
	Kafka.Retry.Producer.RetryMax = 3
	Kafka.Retry.Producer.RetryBackoff = 100ms
	Kafka.Retry.Consumer.RetryBackoff = 2s
	Kafka.Verbose = false
	Kafka.Version = 0.10.2.0
	Kafka.TLS.Enabled = false
	Kafka.TLS.PrivateKey = ""
	Kafka.TLS.Certificate = ""
	Kafka.TLS.RootCAs = []
	Kafka.TLS.ClientAuthRequired = false
	Kafka.TLS.ClientRootCAs = []
	Kafka.SASLPlain.Enabled = false
	Kafka.SASLPlain.User = ""
	Kafka.SASLPlain.Password = ""
	Kafka.Topic.ReplicationFactor = 3
	Debug.BroadcastTraceDir = ""
	Debug.DeliverTraceDir = ""
	Consensus = map[SnapDir:/var/hyperledger/production/orderer/etcdraft/snapshot WALDir:/var/hyperledger/production/orderer/etcdraft/wal]
	Operations.ListenAddress = "127.0.0.1:8443"
	Operations.TLS.Enabled = false
	Operations.TLS.PrivateKey = ""
	Operations.TLS.Certificate = ""
	Operations.TLS.RootCAs = []
	Operations.TLS.ClientAuthRequired = false
	Operations.TLS.ClientRootCAs = []
	Metrics.Provider = "disabled"
	Metrics.Statsd.Network = "udp"
	Metrics.Statsd.Address = "127.0.0.1:8125"
	Metrics.Statsd.WriteInterval = 30s
	Metrics.Statsd.Prefix = ""
2019-04-30 06:58:27.647 UTC [fsblkstorage] newBlockfileMgr -> INFO 003 Getting block information from block storage
2019-04-30 06:58:27.679 UTC [orderer.commmon.multichannel] newLedgerResources -> PANI 004 Error creating channelconfig bundle: initializing channelconfig failed: could not create channel Consortiums sub-group config: setting up the MSP manager failed: the supplied identity is not valid: x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "ca.org2.example.com")
panic: Error creating channelconfig bundle: initializing channelconfig failed: could not create channel Consortiums sub-group config: setting up the MSP manager failed: the supplied identity is not valid: x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "ca.org2.example.com")

goroutine 1 [running]:
github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000197810, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:229 +0x515
github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).log(0xc00013c320, 0x4, 0xf73523, 0x27, 0xc0004d5808, 0x1, 0x1, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0xf6
github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).Panicf(0xc00013c320, 0xf73523, 0x27, 0xc0004d5808, 0x1, 0x1)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159 +0x79
github.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panicf(0xc00013c328, 0xf73523, 0x27, 0xc0004d5808, 0x1, 0x1)
	/opt/gopath/src/github.com/hyperledger/fabric/common/flogging/zap.go:74 +0x60
github.com/hyperledger/fabric/orderer/common/multichannel.(*Registrar).newLedgerResources(0xc00021a630, 0xc0000bf0e0, 0xc0000bf0e0)
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/common/multichannel/registrar.go:260 +0x2d7
github.com/hyperledger/fabric/orderer/common/multichannel.(*Registrar).Initialize(0xc00021a630, 0xc0004b6060)
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/common/multichannel/registrar.go:147 +0x242
github.com/hyperledger/fabric/orderer/common/server.initializeMultichannelRegistrar(0xc000149180, 0xc0002f81d0, 0x0, 0xc00021a3f0, 0x19ba420, 0xc0002f82d0, 0x2, 0x2, 0xc0002f82e0, 0x2, ...)
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/common/server/main.go:414 +0x2ec
github.com/hyperledger/fabric/orderer/common/server.Start(0xf519e0, 0x5, 0xc000214c00)
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/common/server/main.go:142 +0x52d
github.com/hyperledger/fabric/orderer/common/server.Main()
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/common/server/main.go:87 +0x1ce
main.main()
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/main.go:15 +0x

**Comment by aklenik** [comment]
@loganwu Make sure you use the same crypto materials for both the orderer and for regenerating the genesis block and channel tx. Probably you don't use the same CA certs in the genesis block and the orderer's trusted CA list. 

(It's usually cleaner to also regenerate the crypto materials during testing, so you have consistent configs and certs, without any leftover cert to mess with your setup.)

**Comment by loganwu** [comment]
I use the 'generate.sh' script in dir (/caliper-application/network/fabric-v1.4/config) to generate the genesis.block and crypto certs and mychannel.tx

**Comment by loganwu** [comment]
Yes, the same problem as Issue #415. Maybe we can modify the generate.sh to avoid the same problem.
