### ISSUE TITLE
Running benchmark for fabric v1.4 giving endorsement error

### ISSUE THREAD

**Issue by ayushiagg** [hyperledger/caliper#443]
I'm using caliper for hyperledger fabric v1.4 performance benchmark framework.

System specifications: 
- Ubuntu 18.04.2 LTS 
- fabric version 1.4 , 
- node version: v8.11.1

While running the following command :
```
node run-benchmark.js -c ../../../config.yaml -n ../../../sample-config.json
```
These files are specified here: https://github.com/ayushiagg/caliper

I get the following errors : 

**error: [e2eUtils.js]: Failed to complete transaction [56da0...]:Error: Endorsement denied: Error: Invalid invoke function name. Expecting "invoke" "delete" "query"
    at Object.invokebycontext (/home/ayushi/go/src/github.com/hyperledger/caliper/packages/caliper-fabric/lib/e2eUtils.js:1073:27)
    at <anonymous>**

**error: [e2eUtils.js]: Failed to complete transaction [0e4b2...]:Error: Timeout
    at Timeout.setTimeout [as _onTimeout] (/home/ayushi/go/src/github.com/hyperledger/caliper/packages/caliper-fabric/lib/e2eUtils.js:873:54)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)**

The output of the command ends with 
**/home/ayushi/go/src/github.com/hyperledger/caliper/packages/caliper-application
info: [caliper-flow]: 

#######################################
# Test summary: 3 succeeded, 2 failed #
#######################################

info: [scripts/run.js]: Benchmark run successfully**

**Comment by aklenik** [comment]
@ayushiagg The first error is returned by the chaincode, probably you passed a wrong function name in your user callback. 
As for the timeout issue: it can happen if your network is overloaded, or for a variety of other reasons :)
