### ISSUE TITLE
Cannot read property 'clients' of undefined

### ISSUE THREAD

**Issue by hg2013211626** [hyperledger/caliper#444]
error: [scripts/main.js]: Error while executing the benchmark: TypeError: Cannot read property 'clients' of undefined
    at new Client (/home/hg/go/src/github.com/hyperledger/caliper/src/comm/client/client.js:92:33)
    at Object.module.exports.run (/home/hg/go/src/github.com/hyperledger/caliper/src/comm/bench-flow.js:331:15)
    at main (/home/hg/go/src/github.com/hyperledger/caliper/scripts/main.js:53:25)
    at Object.<anonymous> (/home/hg/go/src/github.com/hyperledger/caliper/scripts/main.js:62:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

I use fabric 1.2 ,and I want to know why has this problem? And how to deal with it ?

**Comment by aklenik** [comment]
@hg2013211626 We are aware of this, but it only occurs when there's some serious error during the init phase of Caliper or its client processes. This error is not propagated/handled correctly in the main Caliper process I guess. But this shouldn't interfere with an otherwise correct benchmark run.

**Comment by hg2013211626** [comment]
> @hg2013211626 We are aware of this, but it only occurs when there's some serious error during the init phase of Caliper or its client processes. This error is not propagated/handled correctly in the main Caliper process I guess. But this shouldn't interfere with an otherwise correct benchmark run.

But now my code can't run , I want to know how to deal with this issue?

**Comment by houqinghui** [comment]
@hg2013211626 Do you modify the configuration file? This error shows that there isn't the property `clients` in the configuration file https://github.com/hyperledger/caliper/blob/343321a2378e96f00dad05a2a27dd24a0f99424e/packages/caliper-application/benchmark/simple/config.yaml#L6

**Comment by aklenik** [comment]
@hg2013211626 Sorry, I misinterpreted the error message, @houqinghui is right, you're probably missing an attribute in the config.

**Comment by aklenik** [comment]
@hg2013211626 Did you resolve the issue of the missing `clients` section?

**Comment by Momin10** [comment]
H i I am facingthe issue related to this. I am getting the following error 
**Error: Property 'clients' of network is missing, undefined or null**

**Comment by Momin10** [comment]
Can you please mention what does that client type specify in config.yaml file?

**Comment by aklenik** [comment]
@Momin10 This issue corresponds to a really old version of Caliper, so I'm closing it. Please open another issue, with detailed error information. But these doc pages should help you answer your questions:
1. Clients in network config: https://hyperledger.github.io/caliper/docs/Fabric_Configuration.html#clients
2. Clients in benchmark config: https://hyperledger.github.io/caliper/docs/2_Architecture.html#configuration-file
