### ISSUE TITLE
Caliper fixed API

### ISSUE THREAD

**Issue by houqinghui** [hyperledger/caliper#449]
An stable release of Caliper is on the way, so, some APIs should be fixed.  Now i think blockchain adapter,  tx status, monitor data and performance data should have fixed API. 
1. adapter APIs are used to implentment the blockchain adapter which can interact with the backend blockchain system. 
2. tx status APIs are used to record the status of tx which has been processed and the blockchain adapter  return the status of tx to Caliper client. So tx status APIS should be fixed and used by diferent adapter.
3. monitor data and performance data should be persisted.  File system and sqlite database can be used to do it. The two way are light-weight, and user don't need to install database server.

If you have some suggesstions ,  please tell me, so that we can improve this work.

**Comment by nklincoln** [comment]
closing as outdated following the most recent delivery for monitors/observers
