### ISSUE TITLE
Where are the parameters in the fabric?

### ISSUE THREAD

**Issue by siatzhuliang** [hyperledger/caliper#454]
Caliper launches fabric by docker for performance testing, so where is the configuration file for some parameters of the fabric? For example, where is the configuration file in [fabric/sampleconfig/core.yaml](https://github.com/hyperledger/fabric/blob/release-1.4/sampleconfig/core.yaml) in caliper? Is it in the docker container?Thanks Reply.

**Comment by houqinghui** [comment]
@siatzhuliang You can find the network configuration files and docker-compose files in the folder https://github.com/hyperledger/caliper/tree/master/packages/caliper-application/network/fabric-v1.4/2org2peergoleveldb.  You can refer to the doc https://hyperledger.github.io/caliper/ .
If you still have questions, you ask Caliper maintainers/contributors by [rocker chat](https://chat.hyperledger.org/channel/caliper)

**Comment by aklenik** [comment]
@siatzhuliang The settings in `core.yaml` are overridden using environment variables in the Docker Compose file. See one of the Docker Compose files in the directory linked by @houqinghui

**Comment by siatzhuliang** [comment]
> @siatzhuliang The settings in `core.yaml` are overridden using environment variables in the Docker Compose file. See one of the Docker Compose files in the directory linked by @houqinghui

Thank you very much, I found these configuration files in the docker container. But now I have a problem. When I run the caliper test, does the fabric genesis block configuration file use [caliper/packages/caliper-samples/network/fabric-v1.4/config/configtx.yaml](https://github.com/hyperledger/caliper/blob/master/packages/caliper-samples/network/fabric-v1.4/config/configtx.yaml) or configtx.yaml（this file in docker container）? I need to modify these configuration parameters to observe the impact on fabric performance, so this issue is critical.

**Comment by siatzhuliang** [comment]
> @siatzhuliang The settings in `core.yaml` are overridden using environment variables in the Docker Compose file. See one of the Docker Compose files in the directory linked by @houqinghui

I mean that caliper folder and the fabric container both have configperx.yaml file, so which one is used for initialization?

**Comment by aklenik** [comment]
@siatzhuliang The configuration transaction binaries are pre-generated with the `configtxgen` tool. If you modify parameters that influence these transactions (for example, orderer batching parameters), then you need to regenerate these artifacts (the generate.sh scripts are also next to the network examples).

These generated artifacts (the genesis block, for example) are mounted in the containers, you don't need to modify anything there (I think). 

So the basic workflow is the following:
1. Change the settings in the configtx.yaml and crypto-config.yaml files as you need.
1. Re-run the `cryptogen` and `configtxgen` tools.
1. Change any Fabric-related settings in the docker-compose files
1. Start Caliper, it will launch the configured _local network_

NB: performance testing local networks is not recommended, there's a lot of resource interference among the docker containers. Local networks are useful to experiment with the different setups and topology assembling (plus to test your user callback module and/or smart contract). But you need to distribute your network on multiple nodes to get meaningful performance results. This distributed deploy is out of Caliper's scope (but it can connect to an already deployed/running network).
