### ISSUE TITLE
automatically generate crypto config

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#463]
Taken from #418 

It would be more efficient for us to automatically generate the crypto config as a configuration step inside Caliper for the fabric networks.

This would save the maintenance of files, and prevent any issues with certificate expiry.

**Comment by aklenik** [comment]
The updated `generate.sh` files could be added to the `start` commands, and the `crypto-config` directory to `.gitignore`

**Comment by nklincoln** [comment]
True, I added a similar functionality into the Fabric-sdk-node, which would make the travis build more feasible - https://github.com/hyperledger/fabric-sdk-node/blob/master/build/tasks/certs.js

Would could do similar within a package script and run the same commands at the start of the travis build when running a fabric adaptor test

**Comment by aceetheridge** [comment]
You could also add the --output=./crypto-config flag to the generate command. This would automatically put all the files in the correct place whenever the generate script is run.

**Comment by aklenik** [comment]
This repo already generates the crypto materials on-the-fly for CI tests. The samples dir will be removed soon, so the issue is closed.
(A similar issue should be created for the benchmark repo.)
