### ISSUE TITLE
Clean up the Fabric CCP adapter

### ISSUE THREAD

**Issue by aklenik** [hyperledger/caliper#467]
## Context
The adapter currently relies on the `FabricNetwork` module for network information which is intended for the user modules and breaks the code flow (and code completion support) in the adapter.

## Possible Fix
The adapter should process the network configuration file directly, treating the sections as self-contained objects.

## Progress of the refactoring
- [ ] Extract the network validation into a separate util module
- [ ] Separate the user/admin/registrar initialization from the `FabricNetwork` module
- [ ] Separate the channel creation from the `FabricNetwork` module
- [ ] Separate the channel joining from the `FabricNetwork` module
- [ ] Separate the chaincode installation from the `FabricNetwork` module
- [ ] Separate the chaincode instantiation from the `FabricNetwork` module

**Comment by nklincoln** [comment]
Superseded by #940
