### ISSUE TITLE
Add a license check process to build

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#471]
All source files should have the same license header, and we should enforce this as part of the build process for all Caliper packages.

We can use `npm` modules for just this - there are several license checker packages available ... and we should!!

**Comment by houqinghui** [comment]
Can the `npm` packages that can check licenses modify the license header automaticly? or it can give us some hints, then we change them?

**Comment by nklincoln** [comment]
yes - if we use `license-check-and-add` we can specify a `-fix` that will add any missing/incorrect headers

**Comment by aklenik** [comment]
@nklincoln And how would that work in a CI scenario? Adds an additional commit with the fix? Or is it just intended for local use before raising the PR?

**Comment by nklincoln** [comment]
In a CI scenario, the lic checker will be enabled, and run as part of the `npm test` phase - any files being added that do not have the correct license header will fail the build. It will then be the responsibility of the person submitting the PR to add the missing license headers to their files, either manually, or using an npm script that we could add into the package files

**Comment by nklincoln** [comment]
delivered in #531
