### ISSUE TITLE
How to test burrow by using caliper?

### ISSUE THREAD

**Issue by JamesChenmx** [hyperledger/caliper#479]
Hi, every one !
    i do not know how to test burrow. i want to know how to test burrow.

                                                                            Thanks！

**Comment by nklincoln** [comment]
caliper benchmark run -w <workspace path> -c benchmark/simple/config.yaml -n network/burrow/simple/burrow.json

**Comment by aklenik** [comment]
@JamesChenmx Since the readme has been updated, I'm closing this thread.
