### ISSUE TITLE
Fulfill linting requirements

### ISSUE THREAD

**Issue by haojun** [hyperledger/caliper#48]
The code should be modified to follow linting rules

**Comment by aklenik** [comment]
I can help in the refactoring if you want to split the work.

**Comment by haojun** [comment]
That would be very helpful. 
I'm working on comm folder now, can you help with the fabric adapter?

**Comment by aklenik** [comment]
Of course, I'll start working on it

**Comment by nklincoln** [comment]
Happy to assist with any further linting changes - just let me know which items you would like tackled 👍

**Comment by subhodi** [comment]
Also use of `const` and `let` is encouraged over `var` in strict mode.

**Comment by subhodi** [comment]
@haojun i can help with you with liniting bechmark/simple directory files.

**Comment by haojun** [comment]
@subhodi OK, that's great

**Comment by subhodi** [comment]
i think arrow functions should be preferred over normal functions. If then eslint rule `"prefer-arrow-callback":"warn"`  should be updated

**Comment by aklenik** [comment]
@haojun Fabric lint fixes in #62
