### ISSUE TITLE
Modularise Caliper Resource Monitoring

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#483]
At the moment Caliper uses `Docker stats` as a resource monitor. This is useful for local monitoring, but restrictive when scaling up. 

There are also numerous open source monitoring tools available. Caliper should be able to use any tool that has the appropriate adaptor coded for it and it should be possible for a user to select a desired monitoring tool with a flag in their configuration file

This will require:
 - Formalize the API that Caliper uses for configuring and retrieving monitoring stats
 - Create a monitoring Interface that adaptors must be coded to
 - Convert the Docker stats default monitor to respect the interface
 - Ensure the Reporting can work with the returned information from the Interface

**Comment by aklenik** [comment]
👍 
I'd even go one step further, and formalize the dataflow/data model of such inputs/outputs.
We're talking about mainly two types of data that Caliper works with:

1. **Event-oriented data**
    The collected data correspond to certain events in the system. The transaction data gathered by the adapters fall in this category. For every transaction, the adapters attach timestamps, results, etc. Global time series data can be derived from such observations (such as load rate, throughput, pending TXs), but otherwise, it's hard to correlate TX-based observations through time (since the life-cycle of a TX can span multiple seconds).
1. **Time series data**
    Data from resource metric monitoring falls under this category. A certain metric (or more) is continuously observed through time. In this case, the challenge is handling the sheer number of metrics (>100 per node). Selecting relevant metrics automatically is a hard problem, and is usually done in a guided manner with some expert's help. 

Fortunately, it's not the responsibility of Caliper to automatically analyze such data. We only need to handle/process/export/store it in a consistent manner, preferably with some metadata.

Once we have such a data model for the input/source side, different exporters/reporters could be implemented in a source-independent way.

**Comment by nklincoln** [comment]
closing as #525 has made this redundant 👍
