### ISSUE TITLE
publish caliper to npm

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#488]
Following the conversion of Caliper into a monorepo, with the Caliper components split into their logical component packages, we should publish Caliper to npm so that it may be made available.

We have the following dependancy tree:

caliper-CLI
 - caliper core
 - caliper-adapter-A
    - caliper-core
    - adapter-A-sdk
 - caliper-adapter-B
    - caliper-core 
    - adapter-B-sdk
 - caliper-adapter-C
    - caliper-core
    - adapter-C-sdk

caliper-core
  - no (internal) deps

Based on the above:
1. When caliper-core is updated with breaking changes, all modules require dependancy changes
2. When a new major sdk occurs for an adapter, the adapter and CLI require updating
3. When an adapter is updated to the next major release, the Caliper-CLI requires updating

The following is proposed: 
- To prevent confusion in platform version compatibility, adapters are published at the same version level as the technology they target. For instance: caliper-fabric@1.1.x may be used with Fabric version 1.1; caliper-fabric@1.4.x may be used with Fabric 1.4. The adaptor dependancies are set to consume up to the next major version of the target SDK, and the "x" is used by Caliper to provide flexibility in our own publishing for updates/fixes. We can follow a similar pattern with other adaptors.
- An alternative to the above would be to publish adapters at 0.xy.z levels, where x-y are the major-minor version of the target platform and the z relates to the caliper patch version number. eg caliper-fabric@0.14.z would target fabric 1.4. This would retain a release a 0 release for caliper, and the ability to retain patch versions.
- caliper-core and caliper-cli remain at 0.x.y levels

We will need to be explicit in release notes regarding the supported target platform(s) that the CLI is capable of interacting with, since there will be a disconnect in the 0.x.y versioning with versioning that mirrors the target platform.

Item for consideration:
- Caliper-core dependancies in adaptors *and* the CLI are set to '~' so they will automatically pull in the next minor (patch) release that is compatible. 
- This risk in doing the same for a consumed client-sdk within the adapters is that we lose the ability of fixing tests at the client level. This may expose us to breaking changes if the underlying semantic versioning rules are not strictly adhered to.
- The need to update caliper-cli version for each individual adapter release leads to a tricky versioning system, or at the very least the need to maintain a compatibility table. We could circumvent this through further subdivision of the project into packages such as `caliper-cli-sawtooth` or investigate the ability to dynamically pull a versioned dependancy within the cli itself. This item needs more discussion.

**Comment by 54ZBD** [comment]
hi , Do u succeed install Cli (1.4), i met an erro when install cli ?Any help would be greatly appreciated!

**Comment by aklenik** [comment]
@nklincoln So, I played around with the versioning and publishing stuff a bit. By building on PR #502, this [branch](https://github.com/aklenik/caliper/tree/multiversion-packages) restructures the dependencies a little bit.

# Reasoning and modifications

The modifications took into account the following assumptions/thoughts:
1. The CLI package in its own is really lightweight, its only job is to nicely call the common entry points of the adapter packages (through the core, technically), irrespectively of the actual platform and version of the package.
1. When a user creates a Caliper project, the only thing that should be needed is to install a single package corresponding to the SUT. I think this one-liner setup is crucial for usability until we publish Docker images.
1. It's a best practice to keep projects as self-contained as possible. We saw that global installs can cause hard-to-debug problems, plus different projects could require different Caliper package versions.

To this end, I inverted the dependencies between the CLI and adapter packages. The dependency tree became simpler, just like the installation of packages. Example for the `caliper-fabric-ccp` packages:

```
caliper-fabric-ccp@1.1.0
├── caliper-cli@0.1.0
├── caliper-core@0.1.0
└── Fabric-SDK@1.1.0

caliper-fabric-ccp@1.4.1
├── caliper-cli@0.1.0
├── caliper-core@0.1.0
└── Fabric-SDK@1.4.1
```

# Result

Once the packages are published (more on that later), creating a Caliper project that targets Fabric 1.4.1 is straightforward:
```
mkdir secret-project && cd secret-project

# assemble your artifacts, e.g., suppose the contents of packages/caliper-samples are here

# do the usual npm project setup
npm init 

# use the local registry for now
npm i --registry http://localhost:4873 --save caliper-fabric-ccp@1.4.1

# use npx for locally installed CLI binary
npx caliper benchmark run -w . -c benchmark/simple/config-linear-rate.yaml -n network/fabric-v1.4.1/raft/fabric-ccp-node-tls.yaml
```

And that's it. Installing Caliper and the SUT-compatible package took one command, and the extra `npx` command is not a big price to pay for a self-contained project.

# Technicalities

The "specification" of packages to publish is in the [npm_publish](https://github.com/aklenik/caliper/tree/multiversion-packages/packages/caliper-tests-integration/npm_publish) directory. The [publishing script](https://github.com/aklenik/caliper/blob/multiversion-packages/packages/caliper-tests-integration/scripts/npm_publish.js) reads the file list and performs a backup-replace-restore workflow on the `package.json` file of the given package (e.g., `packages/caliper-fabric-ccp/package.json` ) and publishes it with the given version and corresponding dependencies. So this list is a one-to-one mapping to the published adapter packages (or even Docker images later on). 

# Up for discussion
Currently, the adapter versions match the backend SDK versions exactly. I'd support the idea of matching only the major and minor versions (publishing the package with the latest SDK patch version), thus leaving the package patch version for adapter-related semantic versioning. 
E.g.: `caliper-fabric-ccp@1.4.X` uses the latest Fabric SDK (1.4.3) which is (hopefully) compatible with any Fabric 1.4.Y version.

**Comment by aklenik** [comment]
Finally resolved this 👍
