### ISSUE TITLE
NodeJS Chaincode

### ISSUE THREAD

**Issue by michielmulders** [hyperledger/caliper#49]
Is it possible to add a NodeJS chaincode example as well for Fabric?
Thanks!

**Comment by haojun** [comment]
We could do that, but it's not high priority.

**Comment by aklenik** [comment]
@michielmulders in the meantime you can deploy nodejs CCs from the official fabric-samples repo. Note, that currently you have to provide absolute path to the cc dir. The fabric sdk should take care of the rest. (haven't tested it yet)

**Comment by aklenik** [comment]
@michielmulders @haojun PR #116 fixes this problem, so the issue can be closed

**Comment by aklenik** [comment]
@panyu4 This issue has been resolved for some time now

**Comment by panyu4** [comment]
@aklenik  OK，it can be closed.
