### ISSUE TITLE
Explain config.yaml

### ISSUE THREAD

**Issue by ederquesado** [hyperledger/caliper#491]
--- 
test:
  name: Composer Performance test
  description: This is an example Composer perf test
  clients:
    type: local
    number: 1
  rounds:
  - label: basic-sample-network
    txNumber:
    - 10000
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 50
    arguments:
      testAssets: 1000
    callback: benchmark/composer/composer-samples/basic-sample-network.js
  - label: basic-sample-network
    txNumber:
    - 10000
    trim: 0
    rateControl:
    - type: fixed-rate
      opts:
        tps: 50
    arguments:
      testAssets: 1000
    callback: benchmark/composer/composer-samples/basic-sample-network.js

## I want to know what it is and how it works
1.txNumber
2.testAssets
3.tps

**Comment by aklenik** [comment]
@ederquesado Please refer to the following doc pages:
1. https://hyperledger.github.io/caliper/docs/2_Architecture.html#configuration-file
1. An arbitrary key-value pair passed to the `init` function of the user callback module
1. https://hyperledger.github.io/caliper/docs/Rate_Controllers.html#fixed-rate
