### ISSUE TITLE
Caliper can not have multiple orderer definitions in a network configuration file

### ISSUE THREAD

**Issue by Jamesxu182** [hyperledger/caliper#492]
## Context

Caliper can not have multiplemultiple orderer definitions in a network configuration file, or it will report a issue that **the hosturl of the orderer is not defined** when it is trying to create a channel.  The issue only is found on Caliper Composer but did not test on other adapters yet.

**In the channels section of _composer.json_**
``` javascript
{
  ...
  "channels": {
    "mychannel": {
      "config": "/etc/hyperledger/configtx/mychannel.tx",
      "mspconfig": "/etc/hyperledger/msp/users/Admin@org1.example.com/msp",
      "orderers": [
        "orderer0.example.com",
        "orderer1.example.com",
        "orderer2.example.com"
      ],
      "peers": [
        "peer0.org1.example.com",
        "peer0.org2.example.com"
      ]
    }
  }
  ...
}
```

The orderers in channels section is a JSON array but only can have one single orderer defined there. it is confused to who want to apply Caplier to a network with a cluster of orderers.

## Expected Behavior

Successfully create a channel across all peers and orderers as that is defined in network configure file (composer.json).

## Actual Behavior

Failed when it try to create a channel and mention that **hosturl** of orderer is not defined, which is actually defined in **orderers** section

## Possible Fix

With a quick investigation of the issue by myself, I refer the problem file below. 

https://github.com/hyperledger/caliper/blob/27ec5f94e70a4cb3856f2b1dfd26b3e2f95b087f/packages/caliper-composer/lib/composer_utils.js#L68-L102

**Take a look at line 85 above**, it might include potential problems somehow. This is the direct place which causes the issue.

## Steps to Reproduce

1. Add one more orderer record in the channel definition in the network configuration file (composer.json)
2. Re-run the benchmark, it will show the node.js issue

## Your Environment

* Version used:  Caliper with the commits on Jun 22, 2019 (the latest version when the issue is found)
* Environment name and version: node.js (8.16.0)
* Operating System and version (desktop or mobile): Linux 5.1.14-arch1-1-ARCH

**Comment by aklenik** [comment]
@Jamesxu182 Does it work if you change the line to this:
```
let orderer = config.composer.network.orderers[channel.orderers[0]].hosturl;
```

Note, that Composer support is currently limited, and improving it is not a high priority right now. But every fix and enhancement is welcome of course!
