### ISSUE TITLE
Procedure to benchmark HyperLedger Fabric 1.4.1 + Error Installing CLI

### ISSUE THREAD

**Issue by ComeTiss** [hyperledger/caliper#493]
Hello guys, 

As part of my thesis project, I have developed a single node network with HyperLedger 1.4.1 (Raft consensus) and I am currently running the application using Docker ToolBox on Windows 10. I have written my own chaincodes using Node (version 10.15).

I would like now to use Caliper to benchmark this application, however, I am a bit lost regarding the procedure to follow. 

* If I understand well, I need to change my connection.json file so it matches the requirements from [https://hyperledger.github.io/caliper/docs/Fabric_Configuration.html] ?

* The docs also mention a config file for the benchmark test - should I create it and where should it be placed?

* So far my application directories structure is the following:

-- caliper
-- project
--- network
--- client
--- chaincode
--- bin
-- config

Should I keep it as above, or do I need to move the chaincode within caliper?

Finally, to run the benchmark test, should I first deploy my network and the chaincodes, then run the benchmark?

Finally, I have tried to install the CLI to run at least a sample benchmark, however the install fails. I did as follow: 
* npm install -g node-gyp
* git clone https://github.com/hyperledger/caliper
* cd caliper
* npm install
* I tried to run "npm repo clean", but it would just do nothing so i had to kill it. Although, if it just removes node_modules in packages, It doesn't really matter right?
* npm run bootstrap --force
 (without force it doesn't work)
* export BENCHMARK=fabric-ccp
* ./packages/caliper-tests-integration/scripts/run-integration-tests.sh

And it fails at that stage... (see log screenshot)
![image](https://user-images.githubusercontent.com/25883168/60352379-a0609c00-99bf-11e9-8bac-7f2413ea06eb.png)

Apologies, I am still new to this and a bit lost by the complexity of the framework.
Any help would be greatly appreciated!

Thanks

**Comment by 54ZBD** [comment]
hi,i met the same erro when istalling Cli. Do u have address this question ? Any help would be greatly appreciated!

**Comment by aklenik** [comment]
@ComeTiss Windows support is not confirmed for Caliper. Take a look at `run-integration-tests.sh`, maybe it uses some paths that are not Windows compatible. As for the general procedure for benchmarking (assuming you have installed the CLI successfully):
1. Create a benchmark test configuration file describing your test rounds and business logic to use: https://hyperledger.github.io/caliper/docs/2_Architecture.html#configuration-file
1. Create a network configuration file, and I'd suggest using the new Fabric-CCP adapter: https://hyperledger.github.io/caliper/docs/Fabric_Ccp_Configuration.html
1. Run the CLI by specifying the above files plus a workspace directory. Every relative path in your configs will be resolved from the workspace directory.

A Raft-based example is available here: https://github.com/hyperledger/caliper/tree/master/packages/caliper-samples/network/fabric-v1.4.1/raft

@54ZBD For CLI install errors, refer to this issue: https://github.com/hyperledger/caliper/issues/478 

For further general benchmarking questions, please use the [#caliper Rocket chat channel](https://chat.hyperledger.org/channel/caliper) or the [mailing list](https://lists.hyperledger.org/g/caliper/topics).

**Comment by PADMAARUN** [comment]
hi
when i run sample benchmark i get the following error

cse@system:~$ sudo npx caliper benchmark run --caliper-workspace ./ --caliper-benchconfig ~/caliper/packages/caliper-samples/benchmark/drm/config.yaml --caliper-networkconfig ~/caliper/packages/caliper-samples/network/fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml
Benchmark for target Blockchain type fabric about to start
2019.11.27-22:17:38.440 info  [caliper] [caliper-flow]     ####### Caliper Test #######
2019.11.27-22:17:38.442 info  [caliper] [local-observer]     Observer interval set to 1 seconds
2019.11.27-22:17:38.443 info  [caliper] [caliper-utils]     Executing command: cd /home/cse;docker-compose -f caliper/packages/caliper-samples/network/fabric-v1.4.1/2org1peergoleveldb/docker-compose.yCreating orderer.example.com ... done
Creating network "2org1peergoleveldb_default" with the default driver
Creating peer0.org2.example.com ... done
Creating ca.org1.example.com ...
Creating ca.org2.example.com ...
Creating peer0.org1.example.com ...
Creating peer0.org2.example.com ...
2019.11.27-22:17:43.036 info  [caliper] [adapters/fabric]     Fabric SDK version: 1.4.0; TLS: none
2019.11.27-22:17:43.379 info  [caliper] [adapters/fabric]     Org1's registrar enrolled successfully
2019.11.27-22:17:43.513 info  [caliper] [adapters/fabric]     Org2's registrar enrolled successfully
2019.11.27-22:17:43.540 info  [caliper] [adapters/fabric]     Org1's admin's materials are successfully loaded
2019.11.27-22:17:43.548 info  [caliper] [adapters/fabric]     Org2's admin's materials are successfully loaded
2019.11.27-22:17:43.554 info  [caliper] [adapters/fabric]     client0.org1.example.com's materials are successfully loaded
2019.11.27-22:17:43.559 info  [caliper] [adapters/fabric]     client0.org2.example.com's materials are successfully loaded
2019.11.27-22:17:43.559 info  [caliper] [adapters/fabric]     Channel 'mychannel' definiton being retrieved from file
2019.11.27-22:17:43.592 info  [caliper] [adapters/fabric]     Channel 'mychannel' successfully created
2019.11.27-22:17:43.593 info  [caliper] [adapters/fabric]     Sleeping 5s...
2019.11.27-22:17:48.675 info  [caliper] [adapters/fabric]     Org1's peers successfully joined mychannel: peer0.org1.example.com
2019.11.27-22:17:48.767 info  [caliper] [adapters/fabric]     Org2's peers successfully joined mychannel: peer0.org2.example.com
2019.11.27-22:17:48.768 info  [caliper] [adapters/fabric]     Sleeping 5s...
2019.11.27-22:17:53.771 info  [caliper] [adapters/fabric]     Installing chaincodes for mychannel...
2019.11.27-22:17:53.803 info  [caliper] [adapters/fabric]     marbles@v0 successfully installed on Org1's peers: peer0.org1.example.com
2019.11.27-22:17:53.812 info  [caliper] [adapters/fabric]     marbles@v0 successfully installed on Org2's peers: peer0.org2.example.com
2019.11.27-22:17:53.825 info  [caliper] [adapters/fabric]     drm@v0 successfully installed on Org1's peers: peer0.org1.example.com
2019.11.27-22:17:53.832 info  [caliper] [adapters/fabric]     drm@v0 successfully installed on Org2's peers: peer0.org2.example.com
2019.11.27-22:17:53.848 info  [caliper] [adapters/fabric]     simple@v0 successfully installed on Org1's peers: peer0.org1.example.com
2019.11.27-22:17:53.853 info  [caliper] [adapters/fabric]     simple@v0 successfully installed on Org2's peers: peer0.org2.example.com
2019.11.27-22:17:53.866 info  [caliper] [adapters/fabric]     smallbank@v0 successfully installed on Org1's peers: peer0.org1.example.com
2019.11.27-22:17:53.871 info  [caliper] [adapters/fabric]     smallbank@v0 successfully installed on Org2's peers: peer0.org2.example.com
2019.11.27-22:17:53.872 info  [caliper] [adapters/fabric]     Instantiating marbles@v0 in mychannel. This might take some time...
2019.11.27-22:17:54.846 info  [caliper] [adapters/fabric]     Successfully instantiated marbles@v0 in mychannel
2019.11.27-22:17:54.848 info  [caliper] [adapters/fabric]     Instantiating drm@v0 in mychannel. This might take some time...
2019.11.27-22:17:55.725 info  [caliper] [adapters/fabric]     Successfully instantiated drm@v0 in mychannel
2019.11.27-22:17:55.726 info  [caliper] [adapters/fabric]     Instantiating simple@v0 in mychannel. This might take some time...
2019.11.27-22:17:56.564 info  [caliper] [adapters/fabric]     Successfully instantiated simple@v0 in mychannel
2019.11.27-22:17:56.565 info  [caliper] [adapters/fabric]     Instantiating smallbank@v0 in mychannel. This might take some time...
2019.11.27-22:17:57.579 info  [caliper] [adapters/fabric]     Successfully instantiated smallbank@v0 in mychannel
2019.11.27-22:17:57.581 info  [caliper] [adapters/fabric]     Sleeping 5s...



2019.11.27-22:18:04.474 info  [caliper] [caliper-flow]     Started monitors successfully
2019.11.27-22:18:04.476 info  [caliper] [defaultTest]     ####### Testing 'publish' #######
2019.11.27-22:18:04.477 info  [caliper] [defaultTest]     ####### Testing 'query' #######
2019.11.27-22:18:04.478 info  [caliper] [caliper-flow]     ---------- Finished Test ----------

2019.11.27-22:18:04.478 info  [caliper] [report-builder]     ### All test results ###
**2019.11.27-22:18:04.478 error [caliper] [caliper-flow]     Error: Error: Table must define at least one row.
    at exports.default.rows (/home/cse/node_modules/table/dist/validateTableData.js:26:11)
    at Object.exports.default [as table] (/home/cse/node_modules/table/dist/table.js:116:35)
    at Report.printTable (/home/cse/node_modules/@hyperledger/caliper-core/lib/report/report.js:133:23)
    at Report.printResultsByRound (/home/cse/node_modules/@hyperledger/caliper-core/lib/report/report.js:255:14)
    at Object.module.exports.run (/home/cse/node_modules/@hyperledger/caliper-core/lib/caliper-flow.js:119:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
2019.11.27-22:18:05.480 info  [caliper] [local-observer]     [query Round undefined Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
2019.11.27-22:18:05.481 info  [caliper] [caliper-utils]     Executing command: cd /home/cse;docker-compose -f caliper/packages/caliper-samples/network/fabric-v1.4.1/2org1peergoleveldb/docker-compose.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker** images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*
