### ISSUE TITLE
How to debug the User Defined Test Module (and possibly everything else)?

### ISSUE THREAD

**Issue by netanyahuyasser** [hyperledger/caliper#498]
## Context
I already try the Hyperledger Caliper and run several benchmarks in the `packages/caliper-samples` on my local server without encountering any issues. 

Currently, I want to debug the **User Defined Test Module** specified in the `packages/caliper-samples`. For example, I already set a breakpoint in the `packages/caliper-samples/benchmark/simple/query.js`.

```javascript
module.exports.run = function() {
    /** -> set a breakpoint at this line */ const acc  = account_array[Math.floor(Math.random()*(account_array.length))];

    if (bc.bcType === 'fabric-ccp') {
        let args = {
            chaincodeFunction: 'query',
            chaincodeArguments: [acc],
        };

        return bc.bcObj.querySmartContract(contx, 'simple', 'v0', args, 10);
    } else {
        // NOTE: the query API is not consistent with the invoke API
        return bc.queryState(contx, 'simple', 'v0', acc);
    }
};
```
However, when I start the debugging session, it produces the following error:
```shell
Program path uses differently cased character as file on disk; this might result in breakpoints not being hit.
/home/netanyahu/.nvm/versions/node/v8.16.0/bin/node --inspect-brk=48673 packages/caliper-cli/caliper.js benchmark run -w ./packages/caliper-samples -c benchmark/simple/config.yaml -n network/fabric-v1.4/2org1peercouchdb/fabric-ccp-node.yaml 
Debugger listening on ws://127.0.0.1:48673/57afac6b-e640-40c6-bfc7-d0922f0c4ec2
Debugger attached.
Benchmark for target Blockchain type fabric-ccp about to start
cmdutils.js:32
Benchmark failure
cmdutils.js:32
Error: Benchmark failure
Command failed
```
I want to perform debugging for any **User Defined Test Module**. How to do it properly within Hyperledger Caliper? The vscode `launch.json` configuration file needed to launch the debugging session can be seen at **Your Environment** section.
 
## Expected Behavior
When debugging session is launched, process supposes to be stopped at the defined breakpoints. 
```javascript
module.exports.run = function() {
    /** -> set a breakpoint at this line */ const acc  = account_array[Math.floor(Math.random()*(account_array.length))];

    if (bc.bcType === 'fabric-ccp') {
        let args = {
            chaincodeFunction: 'query',
            chaincodeArguments: [acc],
        };

        return bc.bcObj.querySmartContract(contx, 'simple', 'v0', args, 10);
    } else {
        // NOTE: the query API is not consistent with the invoke API
        return bc.queryState(contx, 'simple', 'v0', acc);
    }
};
```
## Actual Behavior
It produces the following error, with no further clue on how to resolve it:
```shell
Program path uses differently cased character as file on disk; this might result in breakpoints not being hit.
/home/netanyahu/.nvm/versions/node/v8.16.0/bin/node --inspect-brk=48673 packages/caliper-cli/caliper.js benchmark run -w ./packages/caliper-samples -c benchmark/simple/config.yaml -n network/fabric-v1.4/2org1peercouchdb/fabric-ccp-node.yaml 
Debugger listening on ws://127.0.0.1:48673/57afac6b-e640-40c6-bfc7-d0922f0c4ec2
Debugger attached.
Benchmark for target Blockchain type fabric-ccp about to start
cmdutils.js:32
Benchmark failure
cmdutils.js:32
Error: Benchmark failure
Command failed
```

## Possible Fix
Document the proper way on how to debug the **User Defined Test Module**.

## Steps to Reproduce
1. Make sure there is not exists any running docker process i.e. `$ docker ps -aq` must be evaluated to empty.
2. Create `./.vscode/launch.json` config file to set debugging session
3. Set breakpoints in any of the **User Defined Test Modules** that you want to debug and inspect.
4. Launch the debugging configuration file.
5. Inspect the debug console and it will show the error as seen in the **Actual Behavior** instead of the **Expected Behavior** section.

## Existing issues
To my best knowledge. No one has raised this issue yet. Feel free to reference the issue if you found any of them.

## Context
Without knowing how to debug the **User Defined Test Module** properly, we can now only relying on the Logger module of Hyperledger Caliper defined in the `CaliperUtils` class (`./packages/caliper-core/lib/utils/caliper-utils.js`).

## Your Environment
* Version used: latest
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node.js v8.6.1 installed through nvm v0.33.2
* Operating System and version (desktop or mobile): Ubuntu Desktop LTS 16.04
* `./.vscode/launch.json` config files:
```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Caliper Benchmark",
      "program": "${workspaceFolder}/packages/caliper-cli/caliper.js",
      "args": [
        "benchmark", "run", "-w", "./packages/caliper-samples", "-c", "benchmark/simple/config.yaml", "-n", "network/fabric-v1.4/2org1peercouchdb/fabric-ccp-node.yaml"
      ]
    }
  ]
}
```

**Comment by netanyahuyasser** [comment]
After setting breakpoints in `./packages/caliper-cli/lib/benchmark/lib/runBenchmark.js` at this particular line of [code](https://github.com/hyperledger/caliper/blob/27ec5f94e70a4cb3856f2b1dfd26b3e2f95b087f/packages/caliper-cli/lib/benchmark/lib/runBenchmark.js#L64):
```javascript
const response = await CaliperFlow.run(benchConfigFile, blockchainConfigFile, adminClient, clientFactory, workspace);
```

I found that the error message was like this one bellow at `./packages/caliper-fabric-ccp/lib/fabric.js`, specifically at this line of [code](https://github.com/hyperledger/caliper/blob/27ec5f94e70a4cb3856f2b1dfd26b3e2f95b087f/packages/caliper-fabric-ccp/lib/fabric.js#L1983):
```shell
message: "Couldn't create Channel 'mychannel': Orderer response indicated unsuccessful Channel 'mychannel' creation: BAD_REQUEST"
stack: 
"Error: Couldn't create Channel 'mychannel': Orderer response indicated unsuccessful Channel 'mychannel' creation: BAD_REQUEST
    at Fabric._createChannels (/home/netanyahu/Projects/Go/go1.11.6/src/github.com/hyperledger/caliper/packages/caliper-fabric-ccp/lib/fabric.js:321:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)"
```

This error is raised due to error raised at this particular line of [code](https://github.com/hyperledger/caliper/blob/27ec5f94e70a4cb3856f2b1dfd26b3e2f95b087f/packages/caliper-fabric-ccp/lib/fabric.js#L312), in which the error message are:
```shell
message: "Failed to connect before the deadline URL:grpc://localhost:7050"
stack: "Error: Failed to connect before the deadline URL:grpc://localhost:7050
    at checkState (/home/netanyahu/Projects/Go/go1.11.6/src/github.com/hyperledger/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:833:16)"
```

But still no clues on how to resolve this one.

**Comment by netanyahuyasser** [comment]
Duplicate of #39

**Comment by aklenik** [comment]
@netanyahuyasser For now, you must rely on logging inside the user modules. The inspection ports must be shifted when spawning clients to avoid port collisions, as discussed in #39 
Although I'd still prefer the log-mining approach. Unless you test with a single client and fix number of transactions, debugging will mess up the scheduling/timing of Caliper. Logs are easier to analyze and reflect the intended timing/scheduling of the benchmark
