### ISSUE TITLE
Spelling mistake in Rate Controller document

### ISSUE THREAD

**Issue by vita-dounai** [hyperledger/caliper#506]
## Context

![image](https://user-images.githubusercontent.com/44284897/61101088-1e7e7180-a49b-11e9-999a-0c3b6609fc31.png)

## Expected Behavior

The fixed ***backlog*** rate ...
## Actual Behavior

The fixed ***bacjklog*** rate ...

## Possible Fix

fix spelling mistake

## Steps to Reproduce

1.visit [Rate_Controllers](https://hyperledger.github.io/caliper/docs/Rate_Controllers.html)

**Comment by aklenik** [comment]
@vita-dounai Well, there're probably a lot more spelling mistakes in the documentation :) Before Caliper is (soon) published to npm, the documentation will also get a facelift (regarding structure, content, and typos of course).

So I'll open a general issue for this, closing (and referencing) this one 👍
