### ISSUE TITLE
Caliper Multi-Host Timeout error

### ISSUE THREAD

**Issue by nimaafraz** [hyperledger/caliper#510]
I'm trying to run a simple benchmark with 2org1peergoleveldb network with the peers of the second Org on a separate VM. However, I get a timeout Error when initializing the simple benchmark.
I only change the IPs of the peers in the fabric-ccp-go.yaml to the external IP. I made sure that the ports are open in the second VM. I wonder if there are more steps to take for the multi-host caliper.

## Actual Behavior# 
> node ./scripts/main.js "-c" "benchmark/simple/config-feedback-rate.yaml" "-n" "network/fabric-v1.1/2org1peergoleveldb/fabric-ccp-go.yaml"

info: [bench-flow.js]: ####### Caliper Test #######
Creating orderer.example.com ... done
Creating network "2org1peergoleveldb_default" with the default driver
Creating peer0.org1.example.com ... done
Creating ca.org1.example.com ...
Creating orderer.example.com ...
Creating peer0.org2.example.com ...
Creating peer0.org1.example.com ...
info: [adapters/fabric-ccp]: Fabric SDK version: 1.1.0; TLS: none; Fabric v1.0 compatibility mode
info: [adapters/fabric-ccp]: Org1's registrar enrolled successfully
info: [adapters/fabric-ccp]: Org2's registrar enrolled successfully
info: [adapters/fabric-ccp]: Org1's admin's materials are successfully loaded
info: [adapters/fabric-ccp]: Org2's admin's materials are successfully loaded
info: [adapters/fabric-ccp]: client0.org1.example.com's materials are successfully loaded
info: [adapters/fabric-ccp]: client0.org2.example.com's materials are successfully loaded
info: [adapters/fabric-ccp]: mychannel successfully created
info: [adapters/fabric-ccp]: Sleeping 5s...
info: [adapters/fabric-ccp]: Org1's peers successfully joined mychannel: peer0.org1.example.com
info: [adapters/fabric-ccp]: peer0.org2.example.com has already joined mychannel
info: [adapters/fabric-ccp]: Sleeping 5s...
info: [adapters/fabric-ccp]: Installing chaincodes for mychannel...
info: [adapters/fabric-ccp]: simple@v0 is already installed on peer0.org2.example.com
info: [packager/Golang.js]: packaging GOLANG from contract/fabric/simple/go
info: [adapters/fabric-ccp]: simple@v0 successfully installed on Org1's peers: peer0.org1.example.com
info: [adapters/fabric-ccp]: Instantiating simple@v0 in mychannel. This might take some time...
error: [adapters/fabric-ccp]: The following errors occured while instantiating simple@v0 in mychannel:
	- Commit timeout for simple@v0 in mychannel from peer0.org2.example.com
error: [bench-flow.js]: Error: Error: Commit timeout for simple@v0 in mychannel from peer0.org2.example.com
    at Timeout.setTimeout [as _onTimeout] (/home/nima/caliper/src/adapters/fabric-ccp/fabric.js:1117:41)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
info: [demo.js]: [Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0
info: [bench-flow.js]: Executing command: docker-compose -f network/fabric-v1.0/2org1peergoleveldb/docker-compose.yaml down;docker rm $(docker ps -aq);docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*
Stopping peer0.org1.example.com ... done
Stopping peer0.org2.example.com ... done
Stopping orderer.example.com    ... done
Stopping ca.org1.example.com    ... done
Stopping ca.org2.example.com    ... done
Removing peer0.org1.example.com ... done
Removing peer0.org2.example.com ... done
Removing orderer.example.com    ... done
Removing ca.org1.example.com    ... done
Removing ca.org2.example.com    ... done
Removing network 2org1peergoleveldb_default
27e87504ecef
Untagged: dev-peer0.org1.example.com-simple-v0:latest
Deleted: sha256:d6ce02cc92c1cfa50780fcb2c2e2940009ae29db05fa7f2099ffd3ea7ce08395
Deleted: sha256:eb082d58e267d50bcdba129b40ed03448032eafd7c421f211ca17b48932be614
Deleted: sha256:3c3d4d84e3c162927c2ed4070ecfc06182e47e886d9379f5983dc86eff189a42
Deleted: sha256:d77b9012bb16c6b048f91277186600a8cc844d3386fd1c1950fefc8c6d498f32
info: [bench-flow.js]:

#######################################
# Test summary: 0 succeeded, 0 failed #
#######################################

info: [scripts/main.js]: Benchmark run successfully

**## Possible Fix**
I tried to increase the timeout values in /caliper-nima/src/adapters/fabric-ccp/fabric.js as follow but it did not make any difference. Still the same timeout error.

        this.configChaincodeInstantiateTimeout = config.get('fabricCcp:timeout:chaincodeInstantiate', 30000000);
        this.configChaincodeInstantiateEventTimeout = config.get('fabricCcp:timeout:chaincodeInstantiateEvent', 30000000);
        this.configDefaultTimeout = config.get('fabricCcp:timeout:invokeOrQuery', 6000000);

## Steps to Reproduce

1. Change the IPs in the fabric-ccp-go.yaml (the link for the file https://justpaste.it/2bn4f)
2. npm run bench -- -c benchmark/simple/config-feedback-rate.yaml -n network/fabric-v1.1/2org1peergoleveldb/fabric-ccp-go.yaml 

## Your Environment
Google cloud VMs Ubuntu 19.04 custom (1 vCPU, 7.5 GB memory)
Caliper "git checkout 4156c4da7105fd1c2b848573a9943bfc9900becb"

**Comment by aklenik** [comment]
@nimaafraz Please use an up2date version of Caliper. Moreover, the peers also have a setting for increasing the chaincode instantiation timeout. For the client-side timeout configs, see this docs: https://hyperledger.github.io/caliper/docs/Runtime_Configuration.html

**Comment by nimaafraz** [comment]
> @nimaafraz Please use an up2date version of Caliper. Moreover, the peers also have a setting for increasing the chaincode instantiation timeout. For the client-side timeout configs, see this docs: https://hyperledger.github.io/caliper/docs/Runtime_Configuration.html

@aklenik Thanks. I upgraded to the latest version. Also I increased the client-side timeout values. Now it does not give me a timeout error but it gets stuck in the following line for hours (depending on the timeout value):
`info: [adapters/fabric-ccp]: Instantiating simple@v0 in mychannel. This might take some time...`

However, when looking at the second VM's Docker status, I can see that when I run the benchmark in the first VM, a new 'dev-peer0.org2.example.com-simple-v0' container is created in the second machine. I think the problem could be that the first VM cannot access the peer0 on the second VM.

**Comment by aklenik** [comment]
@nimaafraz How is your network distributed? Every Fabric component (peer and orderer) endpoint should be exposed to Caliper (and each other). Also, take a look at the peer logs, might have some instantiation errors.

**Comment by nimaafraz** [comment]
@aklenik I have two VMs where I run the Org1's peer and CA and the single orderer in VM1, and Org2's peer and CA on VM2. Here is the network config file:  https://justpaste.it/2bn4f
I first make sure that the local version of the benchmark runs on both of the VMs. Then on VM2 I run: "docker-compose -f network/fabric-v1.4/2org1peergoleveldb/docker-compose.yaml up -d;sleep 3s" so the containers would start. Then on the first machine, I run the benchmark and get the timeout error.
I checked the peer0.0rg1 logs and here is what I see:
2019-07-17 11:16:05.806 UTC [lscc] executeInstall -> INFO 030 Installed Chaincode [simple] Version [v0] to peer
2019-07-17 11:16:06.677 UTC [blocksProvider] DeliverBlocks -> WARN 031 [mychannel] Got error &{NOT_FOUND}
2019-07-17 11:16:06.778 UTC [ConnProducer] DisableEndpoint -> WARN 032 Only 1 endpoint remained, will not black-list it
2019-07-17 11:16:06.781 UTC [blocksProvider] DeliverBlocks -> WARN 033 [mychannel] Got error &{NOT_FOUND}

**Comment by nimaafraz** [comment]
I'm still struggling with this. What I did further was to make sure the contents of "caliper/network/fabric-v1.x/config/crypto-config" is the same in the two VMs. I'm not sure if this is necessary or not but anyway, I get another error now:


Removing network 2org1peergoleveldb_default
f016f9dc219b
Untagged: dev-peer0.org1.example.com-marbles-v1-a6cb10d46568463c6a5d95462ec8ed19eaa3145c0b63a2d905224fec13ad90ce:latest
Deleted: sha256:abb1125a8d200187602d7369f0e75503c859a7c14bb97d318dada9757d012cfe
Deleted: sha256:a3d43f00a19fc33c592682d0933484a4aa7f720f0aa18f81d85240cdc0967bd4
Deleted: sha256:9fe5ff84164e51834843853e9300eed6f8c08663916563c5303a3ccc1e35c00d
Deleted: sha256:62c0eb59cb6e9deaf03e545eb0f6b8b4182d4c97dbe7accbd0a9a3a2d6942f82
info: [bench-flow.js]:

#######################################
 Test summary: 0 succeeded, 0 failed #
#######################################

info: [scripts/main.js]: Benchmark run successfully

**Comment by aklenik** [comment]
@nimaafraz the fabric adapter you use has been officially deprecated a few minutes ago. Try the Fabric-ccp adapter in the docs. Caliper can connect to any distributed fabric network, you just need to set the correct endpoints. If this is not the case, then probably it's a configuration issue on the fabric side

**Comment by nimaafraz** [comment]
Thanks, @aklenik. I finally managed to get it working and published a short guide for it here: https://medium.com/@nima.afraz/hyperledger-caliper-on-multiple-hosts-6bcd07492e07
