### ISSUE TITLE
While sending high-throughput transactions, caliper throws Failed to connect before the deadline grpcs://<orderer>

### ISSUE THREAD

**Issue by manojpramesh** [hyperledger/caliper#512]
## Context

While sending transactions to the network using Hyperledger Caliper, It works fine for a lower number of Transactions per second. However, When I increase the TPS to above 60, it throws the error `Error: Failed to connect before the deadline URL:grpcs://orderer` for a random number of transactions (20% - 50% of the transactions).

## Expected Behavior
The orderer should process the transactions without any error for any number of TPS.

## Actual Behavior
For a higher number of TPS, caliper throws the following error for some transactions. I could get only up to 80 TPS. Anything around or above that range throws the error.

```
2019-07-10T08:20:58.651Z - error: [Remote.js]: Error: Failed to connect before the deadline URL:grpcs://orderer2-hlf:7050
2019-07-10T08:20:58.652Z - error: [Orderer.js]: Orderer grpcs://orderer2-hlf:7050 has an error Error: Failed to connect before the deadline URL:grpcs://orderer2-hlf:7050 
(node:585) UnhandledPromiseRejectionWarning: Error: Failed to connect before the deadline URL:grpcs://orderer2-hlf:7050
    at checkState (/opt/caliper/node_modules/fabric-client/node_modules/grpc/src/client.js:833:16)
(node:585) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 42)
```

## Steps to Reproduce & Environment

I am using Kubernetes for Hyperledger Fabric and each pod has at least 3GB RAM and 1 CPU allocated. The network has **1 Org (2 peers), 5 Orderers (RAFT Cluster) and a CA**.

Caliper is also running in a Kubernetes pod in the same cluster to avoid any network latency. The config used for caliper are:

```
clients:
     type: local
     number: 7
rounds:
  - label: test
    txNumber:
    - 500
    rateControl:
    - type: fixed-rate
      opts:
        tps: 80
```

**Comment by aklenik** [comment]
@manojpramesh Your expected behavior doesn't hold, sent tps influences the orderer network. This error is because of connection drops or timeouts, originating from the backend network, not from Caliper.
Take a look at the utilization of the pod resources, I think your resources are not sufficient for this load (1 CPU is not that much).
Also make sure that all of your orderers started successfully.

**Comment by manojpramesh** [comment]
@aklenik All the orderers are running successfully and I could not see any errors or warnings in their logs. I tried up to 4 CPUs and couldn't seem to make a difference.

**Comment by aklenik** [comment]
@manojpramesh Can you check the utilization of your pod resources (network, memory, CPU)? Connection drops due to scarce resources might not show up in the server-side logs.

**Comment by manojpramesh** [comment]
Sure. I will update you.

**Comment by mukulverm4** [comment]
Hey @manojpramesh , I'm facing the same issue. Even after allocating more resources to the machine, I got the same timeout error. 
Did this get resolved for you?

**Comment by manojpramesh** [comment]
@mukulverm4 Just did a basic scaling and no luck. The Max I could achieve was 100 TPS. Currently running it with 3 Raft orderer (4 vcpu, 8 gb each). Wondering if you were able to find anything?
