### ISSUE TITLE
Convert Caliper monitor to be Prometheus/Grafana

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#525]
The existing monitor for Caliper is somewhat lightweight and hand cranked; there are existing open source monitors that are designed exactly for monitoring the same thing that Caliper is monitoring... we should be using one of those!!

This issue is for the replacement of the current monitor with Prometheus/Grafana.

The following is desired:

- [ ] Use prometheus with cAdvisor and node_exporter to visualise resource consumption by linking Prometheus with Grafana
- [ ] Use the Prometheus push gateway so that clients can send TPS information to Prometheus, that can then be visualised within Grafana
- [ ] Use the Prometheus HTTP query service to extract and generate a report by pulling the monitored resource consumption and TPS stats for each benchmark
- [ ] Enable the use of a "user defined" Prometheus store (ie pass details of the prometheus server to the clients and monitor generator)

With the above completed, the samples should be modified to also stand up the required Docker images for:
- prometheus
- prometheus push gateway
- grafana
With the corresponding edits within the caliper benchmark files included

**Comment by nklincoln** [comment]
Initial prototype is working for the pushing of Caliper metrics to a Prometheus push gateway that is being scraped by Prometheus and visualized through Grafana. At the moment I am pushing within the `txUpdate()` client function. 

Push is going to `/metrics/job/caliper/instance/${testLabel}/round/${testRound.toString()}/client/${clientId.toString()}`

And the following are being pushed:

- caliper_tps (for the current txDuration)
- caliper_latency (for the current txDuration)
- caliper_total_delay (sum of all latencies)
- caliper_total_tx_count (sum of all transactions)

We might be interested in persisting:
- max_latency
- txn_pass
- txn_fail

I'm looking into a reasonable way to persist (or at least obtain) the start and end times for each test round. We can then use the Prometheus hhtp range query to grab details of each test round in order to create a report. More importantly, we can move the "trim" notion into the query, which is a *much* more suitable place for it

**Comment by aklenik** [comment]
@nklincoln I think your PR addressed everything described in this issue. If yes, then feel free to close it 👍
