### ISSUE TITLE
Reserved word being used in resultArray

### ISSUE THREAD

**Issue by Lynn14m** [hyperledger/caliper#538]
## Context
Modifying test for rate controller, came across txStats function using the same word as a built in JavaScript function.

## Expected Behavior
Able to interact with object values without using reserved word (length).

**Comment by aklenik** [comment]
@Lynn14m Could you point to a code location, please?

**Comment by Lynn14m** [comment]
Line 219 in caliper/packages/caliper-core/lib/blockchain.js 

> @Lynn14m Could you point to a code location, please?

**Comment by nklincoln** [comment]
closing as txStats have been replaced
