### ISSUE TITLE
Travis CI got stuck in "npm ERR! code E404"

### ISSUE THREAD

**Issue by vita-dounai** [hyperledger/caliper#542]
I put forward a pull request but it seems that it's very hard to pass the test of Travis CI. >_<

My PR's link is https://github.com/hyperledger/caliper/pull/515. The Travis CI always tell me when installing some NPM packages such like `secp256k1`, the npm got a 404 error and the test failed immediately. But all tests run well on my own computer, so I wonder that what happend in Travis CI?

**Comment by aklenik** [comment]
@vita-dounai 
@nklincoln is looking into this issue, which is also affecting the other PRs. Current guess is, that it's a resource limitation from the Travis side.

**Comment by aklenik** [comment]
@vita-dounai PR #543 circumvents this problem. So rebase your PR to the current caliper/master, and force-push it again

**Comment by vita-dounai** [comment]
I push again and the problem solved 👍 :)
