### ISSUE TITLE
Getting error while Publishing the packages

### ISSUE THREAD

**Issue by sara-rouhani** [hyperledger/caliper#552]
I have a problem when I want to install caliper cli
I follow these steps:
npm install
npm repoclean
npm run bootstrap
cd ./packages/caliper-tests-integration
npm run start_verdaccio

Everything goes fine so far but when I run npm run publish_packages I get the following error
npm ERR!
 code EPUBLISHCONFLICT

npm ERR!
 publish fail Cannot publish over existing version.
npm ERR!
 publish fail Update the 'version' field in package.json and try again.
npm 
ERR! publish fail 
.
.
.
Aborting, could not publish package caliper-core to local npm server
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! caliper-tests-integration@0.1.0 publish_packages: `./scripts/publish-packages.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the caliper-tests-integration@0.1.0 publish_packages script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
I tried npm run cleanup but still the same error. I am trying on fresh system no previous version of caliper is installed on this one.  

Here is my system info:

OS- Ubuntu 18.04 LTS
NPM version 6.4.1
Node version 8.16.1
node-gyp version 5.0.3
docker version 18.09.7
docker-compose version 1.24.0

**Comment by zsgilber** [comment]
I am getting the same error. It looks like it might be happening because `caliper-core` version `0.1.0` was published to npm yesterday: https://www.npmjs.com/package/caliper-core.

**Comment by maheshshastri** [comment]
Will this affect installation process ? I am new to caliper was also facing this issue. What would be the new installation steps for caliper now?

**Comment by TopJohn** [comment]
I have the same problem too! A few days ago,I success,but recently i met this problem

**Comment by duoduolr** [comment]
I got the same error.

**Comment by maheshshastri** [comment]
All, I could manage to publish locally and install caliper after updating "version:0.1.0" to "version:0.1.1" in all package.json. I updated the version and followed the steps in the document for installing caliper. It worked for me.

**Comment by TopJohn** [comment]
> All, I could manage to publish locally and install caliper after updating "version:0.1.0" to "version:0.1.1" in all package.json. I updated the version and followed the steps in the document for installing caliper. It worked for me.

Yeah, i use the same aproach to deal with it.

**Comment by sara-rouhani** [comment]
Although the package hasn't been published by caliper guys, you can install the package -->  npm install -g caliper-cli. I tried and it works fine.

**Comment by aklenik** [comment]
@sara-rouhani @zsgilber @maheshshastri @TopJohn @duoduolr 
Unfortunately, someone published these "unofficial" Caliper packages. We're working on this. But the naming won't cause problems for the official packages since they'll be published under the Hyperledger organization, which requires proper authentication & authorization. So the official packages will be named `@hyperledger/caliper-...`

**Comment by TopJohn** [comment]
> @sara-rouhani @zsgilber @maheshshastri @TopJohn @duoduolr
> Unfortunately, someone published these "unofficial" Caliper packages. We're working on this. But the naming won't cause problems for the official packages since they'll be published under the Hyperledger organization, which requires proper authentication & authorization. So the official packages will be named `@hyperledger/caliper-...`

when will it finish? why the npm server's package affect the local npm server? can you explain it ,thanks.

**Comment by aklenik** [comment]
@TopJohn 
1) Finalizing the NPM package and Docker image publishing will be one of the agenda items of this week's Caliper call. 
2) I guess (really just guessing here) Verdaccio first looks in the NPM registry for a package, and if not found, it'll look in the local registry. I don't know whether this is configurable or not.

**Comment by maheshshastri** [comment]
@aklenik 
Unfortunately I had to reinstall caliper and now I facing following issue for chalk
lerna WARN EHOIST_PKG_VERSION "caliper-cli" package depends on chalk@1.1.3, which differs from the hoisted chalk@^1.1.3
Even if I ignore and try to install by following instructions to install caliper , I am getting following error 
ERR! 404 Not Found: chalk@1.1.3

When I looked at the logs same error appeared for yargs

1013 http fetch GET 404 http://localhost:4873/chalk 89ms
1014 http fetch GET 404 http://localhost:4873/yargs 89ms
1015 silly fetchPackageMetaData error for chalk@1.1.3 404 Not Found: chalk@1.1.3
1016 silly fetchPackageMetaData error for yargs@10.0.3 404 Not Found: yargs@10.0.3
1017 http fetch GET 304 http://localhost:4873/caliper-core 155ms (from cache)


I tried to reinstall by cloning into a new project but I am stuck on this now.

Any help is appreciated thanks in advance.

**Comment by TopJohn** [comment]
> @TopJohn
> 
> 1. Finalizing the NPM package and Docker image publishing will be one of the agenda items of this week's Caliper call.
> 2. I guess (really just guessing here) Verdaccio first looks in the NPM registry for a package, and if not found, it'll look in the local registry. I don't know whether this is configurable or not.

I saw the code, you are right.

**Comment by yuyan110nan** [comment]
> All, I could manage to publish locally and install caliper after updating "version:0.1.0" to "version:0.1.1" in all package.json. I updated the version and followed the steps in the document for installing caliper. It worked for me.

i met the same error , but how to update the caliper version

**Comment by aklenik** [comment]
@yuyan110nan change the version attributes in the package.json files in the package directories.

**Comment by aklenik** [comment]
Caliper is officially published, with detailed docs on install and development. So I'm closing this issue.
