### ISSUE TITLE
Error when instantiating my contract

### ISSUE THREAD

**Issue by sara-rouhani** [hyperledger/caliper#564]
Hi, I have written my contract based on 'fabric-contract-api' package and I can successfully install, instantiate, invoke and query my smart contract using basic fabric network.
Now I want to analyze my contract using caliper. I have put the contract in the src folder. in the benchmark folder, I put my init and query files to test the contract and simply I use default config.yaml file of caliper (I just changed the callback lines). Also, in the network directory under the fabric-v1.4 / 2org1peercouchdb/ I changed the fabric-node.yaml file and I added my contract under chaincodes. I can run caliper samples for simple and marble but I get an error while instantiating my contract. 
SendProposal - timeout after 300000, 
I looked into docker logs and this was the error. "error": "context finished before block retrieved: context canceled", "grpc.code": "Unknown", "grpc.call_duration": "676.055798ms"}
2019-08-28 18:59:05.185 UTC [endorser] callChaincode -> INFO 050 [mychannel][56f24d8d] Entry chaincode: name:"lscc" .

I am wondering how caliper instantiate contracts. because I couldn't find "peer chaincode instantiate .."  command in caliper directory. I checked other contract samples they start with 
  async Init(stub) {
        let ret = stub.getFunctionAndParameters();
        console.info(ret);
        console.info('=========== Instantiated Marbles Chaincode ===========');
        return shim.success();
    }
which my contract doesn't have a such method for instatiaation.

**Comment by nklincoln** [comment]
By default caliper will call the `init` function in chaincode during instantiate, as this was a legacy requirement for Fabric. You can either:
- just add an empty init function to your smart contract
- override the function being called on startup within the network config file, under chaincodes -> add a null `function` entry at the same level as version|language|path
