### ISSUE TITLE
Monitors are a required item in the bench config file

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#573]
At the moment monitors are a required item in the bench config file.

It is perfectly reasonable to assume that someone might run a benchmark without the specification of a monitor, because they are only interested in the TPS/latency results.

I suggest that this requirement is relaxed.

**Comment by nklincoln** [comment]
My bad ... you can have 'type: none, as an option. Maybe we should add this to the docs 😂

**Comment by aklenik** [comment]
It's been added to the docs.
