### ISSUE TITLE
Logging of tx status to console

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#587]
Currently the console logging from observers spams the console, with repeated outputs. 

It would be really nice if we could modify the way in which this happens such that (from a user perspective) the value is simply updated.

This is done for such things as the `docker stats` command

**Comment by aklenik** [comment]
Hmm, I'm not sure what you're proposing. Could you give an example expected behavior?

**Comment by nklincoln** [comment]
The thought here is that either:
- dynamically update the values (i think chalk can do this?) instead of repeatedly adding a new line
- do what the `docker stats` command does - add a load of newlines so that the new print out is at the top of the console but the user only ever sees the top line

Of course it is better to "just use grafana" once the Prometheus metrics PR goes in ...

**Comment by aklenik** [comment]
My concern is that the logging mechanism doesn't know about its actual target. So those newlines will be added to the log files as well. A viable workaround would be to use the lot-of-newlines approach, but directly through the `console` (and chalk). So the console would serve as a basic "UI", while the logs remain clean and separate. And the console observer should provide an `enable` option of course :)

**Comment by nklincoln** [comment]
this is indirectly (partially) solved by the pending updates for prometheus ... the observers have a "none" option

**Comment by aklenik** [comment]
@nklincoln 
I think we can close this issue. The Prometheus monitor can calculate the previously reported metrics at the end (if configured).

**Comment by nklincoln** [comment]
closing issue as this has been addressed by the new observer behaviour
