### ISSUE TITLE
Hyperledger Besu Support

### ISSUE THREAD

**Issue by fengkiej** [hyperledger/caliper#610]
## Context
Hyperledger Besu (formerly PegaSys' Pantheon) just got added into Hyperledger family last month. A support to benchmark Besu is needed to complete all Hyperledger's blockchain support on Caliper.

## Expected Behavior
There should be a script to run Caliper on Hyperledger Besu.

## Actual Behavior
N/A

## Possible Fix
Add new script to run Caliper on Besu. I may be able to do this later, but if there's someone who are more familiar with Caliper, I expect they can do this much quicker.

## Steps to Reproduce
N/A

## Existing issues
N/A

## Context
N/A

## Your Environment
N/A

**Comment by aklenik** [comment]
@fengkiej If I understand correctly, Besu is an Ethereum client, so it should support the Ethereum RPC, thus web3.js. An experimental Ethereum adapter has been merged recently, which will be included in the 0.2.0 release. Before implementing a separate adapter for Besu, we should investigate whether the general Ethereum adapter suffices or not. (But correct me if I'm wrong about the Besu API.)

**Comment by fengkiej** [comment]
@aklenik I see, so after the adapter has been released on 0.2.0 Caliper. We can see further customization (if it is needed) later.

**Comment by aklenik** [comment]
Closed by #616
