### ISSUE TITLE
Fabric-client and fabric-ca-client are not correctly installed!

### ISSUE THREAD

**Issue by Vegard-Bear** [hyperledger/caliper#628]
## Context

when i git clone the caliper and cd caliper, then i 

<img width="1664" alt="Screen Shot 2019-11-03 at 8 54 36 PM" src="https://user-images.githubusercontent.com/40748014/68095146-ed123180-fee1-11e9-8770-6348fb7962c5.png">

When i try to show my fabric-client and fabric-ca-client, i see this

<img width="1038" alt="Screen Shot 2019-11-04 at 9 19 25 AM" src="https://user-images.githubusercontent.com/40748014/68095502-0c5e8e00-fee5-11e9-9c48-d2f3ee970440.png">

I know that there must be something wrong with my fabric-client and fabric-ca-client, but i don't know how to fix it. Is there anyone who has some ideas, thanks in advance!

## Expected Behavior

Fabric-client and fabric-ca-client are correctly installed and i can run the example by node main.js

## Actual Behavior

fabric-client and fabric-ca-client are  not correctly installed and i cannot run the example by node main.js

## Possible Fix

Maybe reinstalling the fabric-client and fabric-ca-client helps

## Existing issues

- [GitHub Issues](https://github.com/hyperledger/caliper/issues/302)

**Comment by Vegard-Bear** [comment]
@aklenik

**Comment by aklenik** [comment]
The `node main.js ...` approach has been gone a long time ago. Now Caliper offers a CLI to start your tests, either when installed through npm/docker or using the source code directly.
Check out the docs for the various ways to install/bootstrap Caliper: https://hyperledger.github.io/caliper/vLatest/installing-caliper/

**Comment by Vegard-Bear** [comment]
Ok and thanks a lot! @

**Comment by Vegard-Bear** [comment]
Ok and thanks a lot!
