### ISSUE TITLE
Failed to load connector module "composer-connector-undefined"

### ISSUE THREAD

**Issue by Akash76** [hyperledger/caliper#64]
![screenshot from 2018-05-08 15-16-31](https://user-images.githubusercontent.com/29705984/39750469-f4ac6206-52d2-11e8-8ed0-0400d905613a.png)

I have made all the necessary changes in my config files but it has raised this error...Failed to load connector module "composer-connector-undefined"...
The expected output is it have to show the performance results of my application...

**Comment by feihujiang** [comment]
Could you please list the version of your fabric and composer. @Akash76 
Prior to running performance tests, it is important to note that the current framework has been written to support:
Hyperledger Composer v0.19.0 and higher
Hyperledger Fabric v1.1.0

The framework has been verified with the following dependencies:
    "composer-admin": "0.19.0",
    "composer-client": "0.19.0",
    "composer-common": "0.19.0",
    "fabric-ca-client": "1.1.0",
    "fabric-client": "1.1.0",

**Comment by houqinghui** [comment]
@Akash76  @ @sidraamalik   have you solve the problem ?    are you sure to install the composer correctly?

**Comment by sidraamalik** [comment]
I havent been able to install it. Can you tell me the and steps of
installing each component on ubuntu ?

**Comment by houqinghui** [comment]
@sidraamalik   i suggest   you should  run benchmark test of fabric first ,  if successful, than  you run the test of composer that is based on fabric.  after a time , i will list the steps of running the composer test.

**Comment by houqinghui** [comment]
![image](https://user-images.githubusercontent.com/13465812/47762653-82d81700-dcf8-11e8-8a02-cb8dd7bb25dd.png)
follow these steps to run fabric test. [https://github.com/hyperledger/caliper]

**Comment by aklenik** [comment]
@nklincoln @Akash76 @sidraamalik The exact steps to run the sample Composer-based benchmark:
```
git clone https://github.com/hyperledger/caliper.git
cd caliper
npm install
npm install grpc@1.10.1 fabric-ca-client@1.1.0 fabric-client@1.1.0 composer-admin@0.19.0 composer-client@0.19.0 composer-common@0.19.0
cd benchmark/composer
node main.js
```

If the error still persists, please provide some information about your environment: 
* `npm ls grpc fabric-ca-client fabric-client composer-admin composer-client composer-common`
* `node --version`
* OS version
* the exact steps/modifications performed to reproduce the error starting from `git clone`

**Comment by panyu4** [comment]
Since there are no more activities, it will be closed.
