### ISSUE TITLE
implement conflux chain adaptor for benchmark performance

### ISSUE THREAD

**Issue by xiaods** [hyperledger/caliper#643]
## Context

because the conflux chain have no benchmark tool for public review the chain's performance.  

## Expected Behavior

support conflux chain adaptor

## Steps to Reproduce

1. add conflux chain adaptor
2. 
3.
4.

## Existing issues

- [ ] [Conflux bounty](https://bounty.conflux-chain.org/view-bounty?bountyId=5dc26c3b6ae498233fd9b9c7&language=zh-CN)

**Comment by aklenik** [comment]
@xiaods contributions are welcome :)

**Comment by xiaods** [comment]
@aklenik Thanks, i will do it.

**Comment by xiaods** [comment]
come back. i will working on it asap.

**Comment by davidkel** [comment]
Closing as this is over 4 years old so don't expect a connector to be submitted
