### ISSUE TITLE
"Table must define at least one row" error while running sample

### ISSUE THREAD

**Issue by PADMAARUN** [hyperledger/caliper#670]
i get the follwing error

cse@system:~$ **sudo npx caliper benchmark run --caliper-workspace ./ --caliper-benchconfig ~/caliper/packages/caliper-samples/benchmark/drm/config.yaml --caliper-networkconfig ~/caliper/packages/caliper-samples/network/fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml
Benchmark for target Blockchain type fabric about to start**
2019.11.27-22:17:38.440 info  [caliper] [caliper-flow]     ####### Caliper Test #######
2019.11.27-22:17:38.442 info  [caliper] [local-observer]     Observer interval set to 1 seconds
2019.11.27-22:17:38.443 info  [caliper] [caliper-utils]     Executing command: cd /home/cse;docker-compose -f caliper/packages/caliper-samples/network/fabric-v1.4.1/2org1peergoleveldb/docker-compose.yCreating orderer.example.com ... done
Creating network "2org1peergoleveldb_default" with the default driver
Creating peer0.org2.example.com ... done
Creating ca.org1.example.com ...
Creating ca.org2.example.com ...
Creating peer0.org1.example.com ...
Creating peer0.org2.example.com ...
2019.11.27-22:17:43.036 info  [caliper] [adapters/fabric]     Fabric SDK version: 1.4.0; TLS: none
2019.11.27-22:17:43.379 info  [caliper] [adapters/fabric]     Org1's registrar enrolled successfully
2019.11.27-22:17:43.513 info  [caliper] [adapters/fabric]     Org2's registrar enrolled successfully
2019.11.27-22:17:43.540 info  [caliper] [adapters/fabric]     Org1's admin's materials are successfully loaded
2019.11.27-22:17:43.548 info  [caliper] [adapters/fabric]     Org2's admin's materials are successfully loaded
2019.11.27-22:17:43.554 info  [caliper] [adapters/fabric]     client0.org1.example.com's materials are successfully loaded
2019.11.27-22:17:43.559 info  [caliper] [adapters/fabric]     client0.org2.example.com's materials are successfully loaded
2019.11.27-22:17:43.559 info  [caliper] [adapters/fabric]     Channel 'mychannel' definiton being retrieved from file
2019.11.27-22:17:43.592 info  [caliper] [adapters/fabric]     Channel 'mychannel' successfully created
2019.11.27-22:17:43.593 info  [caliper] [adapters/fabric]     Sleeping 5s...
2019.11.27-22:17:48.675 info  [caliper] [adapters/fabric]     Org1's peers successfully joined mychannel: peer0.org1.example.com
2019.11.27-22:17:48.767 info  [caliper] [adapters/fabric]     Org2's peers successfully joined mychannel: peer0.org2.example.com
2019.11.27-22:17:48.768 info  [caliper] [adapters/fabric]     Sleeping 5s...
2019.11.27-22:17:53.771 info  [caliper] [adapters/fabric]     Installing chaincodes for mychannel...
2019.11.27-22:17:53.803 info  [caliper] [adapters/fabric]     marbles@v0 successfully installed on Org1's peers: peer0.org1.example.com
2019.11.27-22:17:53.812 info  [caliper] [adapters/fabric]     marbles@v0 successfully installed on Org2's peers: peer0.org2.example.com
2019.11.27-22:17:53.825 info  [caliper] [adapters/fabric]     drm@v0 successfully installed on Org1's peers: peer0.org1.example.com
2019.11.27-22:17:53.832 info  [caliper] [adapters/fabric]     drm@v0 successfully installed on Org2's peers: peer0.org2.example.com
2019.11.27-22:17:53.848 info  [caliper] [adapters/fabric]     simple@v0 successfully installed on Org1's peers: peer0.org1.example.com
2019.11.27-22:17:53.853 info  [caliper] [adapters/fabric]     simple@v0 successfully installed on Org2's peers: peer0.org2.example.com
2019.11.27-22:17:53.866 info  [caliper] [adapters/fabric]     smallbank@v0 successfully installed on Org1's peers: peer0.org1.example.com
2019.11.27-22:17:53.871 info  [caliper] [adapters/fabric]     smallbank@v0 successfully installed on Org2's peers: peer0.org2.example.com
2019.11.27-22:17:53.872 info  [caliper] [adapters/fabric]     Instantiating marbles@v0 in mychannel. This might take some time...
2019.11.27-22:17:54.846 info  [caliper] [adapters/fabric]     Successfully instantiated marbles@v0 in mychannel
2019.11.27-22:17:54.848 info  [caliper] [adapters/fabric]     Instantiating drm@v0 in mychannel. This might take some time...
2019.11.27-22:17:55.725 info  [caliper] [adapters/fabric]     Successfully instantiated drm@v0 in mychannel
2019.11.27-22:17:55.726 info  [caliper] [adapters/fabric]     Instantiating simple@v0 in mychannel. This might take some time...
2019.11.27-22:17:56.564 info  [caliper] [adapters/fabric]     Successfully instantiated simple@v0 in mychannel
2019.11.27-22:17:56.565 info  [caliper] [adapters/fabric]     Instantiating smallbank@v0 in mychannel. This might take some time...
2019.11.27-22:17:57.579 info  [caliper] [adapters/fabric]     Successfully instantiated smallbank@v0 in mychannel
2019.11.27-22:17:57.581 info  [caliper] [adapters/fabric]     Sleeping 5s...

2019.11.27-22:18:04.474 info  [caliper] [caliper-flow]     Started monitors successfully
2019.11.27-22:18:04.476 info  [caliper] [defaultTest]     ####### Testing 'publish' #######
2019.11.27-22:18:04.477 info  [caliper] [defaultTest]     ####### Testing 'query' #######
2019.11.27-22:18:04.478 info  [caliper] [caliper-flow]     ---------- Finished Test ----------

2019.11.27-22:18:04.478 info  [caliper] [report-builder]     ### All test results ###
**2019.11.27-22:18:04.478 error [caliper] [caliper-flow]     Error: Error: Table must define at least one row.
    at exports.default.rows (/home/cse/node_modules/table/dist/validateTableData.js:26:11)
    at Object.exports.default [as table] (/home/cse/node_modules/table/dist/table.js:116:35)
    at Report.printTable (/home/cse/node_modules/@hyperledger/caliper-core/lib/report/report.js:133:23)
    at Report.printResultsByRound (/home/cse/node_modules/@hyperledger/caliper-core/lib/report/report.js:255:14)
    at Object.module.exports.run (/home/cse/node_modules/@hyperledger/caliper-core/lib/caliper-flow.js:119:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
2019.11.27-22:18:05.480 info  [caliper] [local-observer]     [query Round undefined Transaction Info] - Submitted: 0 Succ: 0 Fail:0 Unfinished:0**
2019.11.27-22:18:05.481 info  [caliper] [caliper-utils]     Executing command: cd /home/cse;docker-compose -f caliper/packages/caliper-samples/network/fabric-v1.4.1/2org1peergoleveldb/docker-compose.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*

**Comment by aklenik** [comment]
@PADMAARUN We'll look into the issue. 

But I'd kindly like to ask you not to duplicate questions across different issues, as it makes them hard to track for the community and for the maintainers. The maintainers are doing everything they can to answer/resolve questions in a timely manner. Posting the question multiple times won't help this process, but rather complicates the housekeeping tasks for us. Thank you.

**Comment by PADMAARUN** [comment]
On installing and ruuning Hyperledger Explorer, i got this log. kindly help


False 'ssl-certs' '/home/cse/blockchain-explorer/ssl-certs'
******* Initialization started for hyperledger fabric platform ******, { fabcar: { name: 'fabcar', profile: './connection-profile/fabcar.json' } }
 client_configs.name  fabcar  client_configs.profile  ./connection-profile/fabcar.json
FabricUtils.createFabricClient 
config.client.tlsEnable  false
FabricConfig, this.config.channels  mychannel
2019-12-17T13:45:11.589Z - [31merror[39m: [FabricCAClientService.js]: Failed to enroll admin, error:%o message=Calling enrollment endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:7054], stack=Error: Calling enrollment endpoint failed with error [Error: connect ECONNREFUSED 127.0.0.1:7054]
    at ClientRequest.request.on (/home/cse/blockchain-explorer/node_modules/fabric-ca-client/lib/FabricCAClient.js:487:12)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:73:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
'Error instantiating FabricCAServices '
2019-12-17T13:45:11.596Z - [31merror[39m: [BaseWallet]: setUserContext: identity 'admin' isn't enrolled, or loaded
Error: identity 'admin' isn't enrolled, or loaded
    at FileSystemWallet.setUserContext (/home/cse/blockchain-explorer/node_modules/fabric-network/lib/impl/wallet/basewallet.js:56:10)
    at <anonymous>

 ********* call to initializeDetachClient **********
initializeDetachClient --> client_config  { name: 'fabcar', profile: './connection-profile/fabcar.json' }  name  fabcar
initializeDetachClient, network config)  { name: 'fabcar-network',
  version: '1.0.0',
  license: 'Apache-2.0',
  client: 
   { tlsEnable: false,
     adminUser: 'admin',
     adminPassword: 'adminpw',
     enableAuthentication: false,
     organization: 'Org1',
     connection: { timeout: [Object] } },
  channels: { mychannel: { orderers: [Array], peers: [Object] } },
  organizations: 
   { Org1: 
      { mspid: 'Org1MSP',
        peers: [Array],
        certificateAuthorities: [Array] } },
  peers: { 'peer0.org1.example.com': { url: 'grpc://localhost:7051' } },
  certificateAuthorities: 
   { 'ca.example.com': { url: 'http://localhost:7054', caName: 'ca.example.com' } } }

************************************* initializeDetachClient *************************************************
Error : Failed to connect client peer, please check the configuration and peer status
Info :  Explorer will continue working with only DB data
************************************** initializeDetachClient ************************************************

FabricUtils.createDetachClient 
initializeListener, client_name, client  fabcar { name: 'fabcar', profile: './connection-profile/fabcar.json' }


Please open web browser to access ：http://localhost:8080/


pid is 5771


FabricConfig, this.config.channels  mychannel
<<<<<<<<<<<<<<<<<<<<<<<<<< Explorer Error >>>>>>>>>>>>>>>>>>>>>
Error :  [ 'Default client peer is down and no channel details available database' ]

**Comment by aklenik** [comment]
@PADMAARUN This error is related to Hyperledger Explorer, so please ask for help in the related forums.

**Comment by ruixk** [comment]
I meet the same problem when I run  ‘npx caliper benchmark run --caliper-workspace ./caliper-benchmarks/ --caliper-benchconfig benchmarks/scenario/simple/config.yaml --caliper-networkconfig networks/fabric/fabric-v1.4.1/2org1peercouchdb/fabric-go.yaml’,   when I modify config.yaml just change  `  txNumber: 100 `
to  
`txNumber: ` 
` - 100`
All test can run complete， but `Send Rate (TPS)` is only 1.1
```
+----------+------+------+-----------------+-----------------+-----------------+-----------------+------------------+
| Name     | Succ | Fail | Send Rate (TPS) | Max Latency (s) | Min Latency (s) | Avg Latency (s) | Throughput (TPS) |
|----------|------|------|-----------------|-----------------|-----------------|-----------------|------------------|
| open     | 100  | 0    | 1.1             | 0.45            | 0.26            | 0.35            | 1.0              |
|----------|------|------|-----------------|-----------------|-----------------|-----------------|------------------|
| query    | 100  | 0    | 1.1             | 0.04            | 0.01            | 0.02            | 1.1              |
|----------|------|------|-----------------|-----------------|-----------------|-----------------|------------------|
| transfer | 100  | 0    | 1.1             | 0.40            | 0.36            | 0.38            | 1.0              |
+----------+------+------+-----------------+-----------------+-----------------+-----------------+------------------+

```

**Comment by woshizuibangde** [comment]
> @PADMAARUN We'll look into the issue.
> 
> But I'd kindly like to ask you not to duplicate questions across different issues, as it makes them hard to track for the community and for the maintainers. The maintainers are doing everything they can to answer/resolve questions in a timely manner. Posting the question multiple times won't help this process, but rather complicates the housekeeping tasks for us. Thank you.

HI,sir. i met this same problem today. Did it has solved? Thank you!

**Comment by root5533** [comment]
Running into the same issue. Followed steps exactly available [here](https://hyperledger.github.io/caliper/vLatest/installing-caliper/#the-caliper-cli). Please look into it.

**Comment by tzortzispanagiotis** [comment]
The same issue is also happening to me. Is an answer available yet?

**Comment by adityainterwork** [comment]
I am also getting the same error  **Error: Table must define at least one row.**

**Comment by tk1993** [comment]
This has resolved the issue for me 
File: config.yaml
Location: caliper-benchmarks/benchmarks/scenario/simple/
Change :     txNumber: 100
To :             txNumber:
                   - 100

**Comment by adityainterwork** [comment]
yeah, I have done that. And it was working after it.

**Comment by kpratihast** [comment]
> This has resolved the issue for me
> File: config.yaml
> Location: caliper-benchmarks/benchmarks/scenario/simple/
> Change : txNumber: 100
> To : txNumber:
> - 100

The test completed after making this change, however, all 100 transactions failed.

**Comment by adityainterwork** [comment]
My test was passed but couldn't understand the TPS.
![1579850608313](https://user-images.githubusercontent.com/46881822/73151258-663fb000-40f0-11ea-8330-df58b960cc25.png)

**Comment by naonishijima** [comment]
I suppose it needs more change like this
```
txNumber: 100
rateControl:
type: fixed-rate 
```
to
```
txNumber:
- 100
rateControl:
- type: fixed-rate
```

**Comment by csd3458** [comment]
any luck with that error guys?

**Comment by aklenik** [comment]
The core problem is that the master branch of the benchmarks repo is no longer compatible with Caliper v0.2.0. I'll tag the benchmark repo at the correct commits soon but until then checkout the last compatible commit after cloning the benchmark repo.
Full example:
```
git clone https://github.com/hyperledger/caliper-benchmarks.git
cd caliper-benchmarks
git checkout 68fd45900edfabbadc0f2c6215a08ee31e49a596
npm init -y
npm install --only=prod @hyperledger/caliper-cli@0.2.0
npx caliper bind --caliper-bind-sut fabric --caliper-bind-sdk 1.4.0
npx caliper benchmark run --caliper-workspace . --caliper-benchconfig benchmarks/scenario/simple/config_long.yaml --caliper-networkconfig networks/fabric/fabric-v1.4.0/2org1peergoleveldb/fabric-go-tls.yaml
```
