### ISSUE TITLE
There are bugs in caliper-fisco-bcos package on npm

### ISSUE THREAD

**Issue by vita-dounai** [hyperledger/caliper#675]
After I fix the bugs in FISCO BCOS adapter([https://github.com/hyperledger/caliper/pull/647](https://github.com/hyperledger/caliper/pull/647)), the @hyperledger/caliper-fisco-bcos npm package([https://www.npmjs.com/package/@hyperledger/caliper-fisco-bcos](https://www.npmjs.com/package/@hyperledger/caliper-fisco-bcos)) still not working, could you update it too?

**Comment by aklenik** [comment]
The fix will be included in the next published release, which will either be a rolling `0.3.0-unstable` (made possible by PR #626) or the stable `0.3.0`. 

Since we're in the pre-major release phase, we don't plan to backport fixes to the previous versions (0.1.0 and 0.2.0).
