### ISSUE TITLE
Error undefined symbol: SSL_library_init while running simple test with hyperledger caliper

### ISSUE THREAD

**Issue by cleverence** [hyperledger/caliper#70]
$sudo node main.js 
TAP version 13
#######Caliper Test######
docker-compose -f network/fabric/simplenetwork/docker-compose.yaml up -d
Creating network "simplenetwork_default" with the default driver
Creating ca_peerOrg2 ... ``
Creating ca_peerOrg1 ... 
Creating couchdb ... 
Creating orderer.example.com ... 
Creating orderer.example.com
Creating couchdb
Creating ca_peerOrg2
Creating orderer.example.com ... done
Creating peer0.org2.example.com ... 
Creating peer1.org2.example.com ... 
Creating peer0.org1.example.com ... 
Creating peer1.org2.example.com
Creating peer0.org2.example.com
Creating peer0.org1.example.com ... done
Creating peer1.org1.example.com ... 
Creating peer1.org1.example.com ... done
#create mychannel......
node: symbol lookup error: /home/clever/caliper/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node: undefined symbol: SSL_library_init

**Comment by haojun** [comment]
I've no idea about it...... but I found a similar issue here:
https://github.com/grpc/grpc-node/issues/341

Not sure if it can solve your problem.

**Comment by nicolasnoble** [comment]
gRPC author here - if anyone can provide a reproducible environment where this happens, please do so.

**Comment by reehamRaed** [comment]
@nicolasnoble  it's in linux-x64
 
grpc_node.node: undefined symbol: SSL_library_init

**Comment by Titogelo** [comment]
I've got the same error while creating a channel as well. I am running the balance-transfer tutorial from Fabric. While invoking the API call that creates a channel I get this error back

```
node: symbol lookup error: /home/****/hyperledger/fabric-samples/balance-transfer/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node: undefined symbol: SSL_library_init
```

**Comment by aklenik** [comment]
@Titogelo This behavior isn't related to Caliper as it turned out in the above-mentioned issue. Have you tried the proposed fixes starting from [this comment](https://github.com/grpc/grpc-node/issues/341#issuecomment-401504537)?

**Comment by nicolasnoble** [comment]
Note that this should've been fixed by Ubuntu.
