### ISSUE TITLE
Silent failure in CLI 

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#700]
When running a benchmark using the CLI, if there is a missing benchmark or network configuration path, there is a silent failure.

This is because `benchmarkConfigPath = CaliperUtils.resolvePath(benchmarkConfigPath, workspacePath)` will throw if the first passed parameter is undefined ... but it is never caught and there are no output error messages to help assist diagnosis of the command that doesn't actually run.

We should either have an outer catch to deal with any uncaught errors, or at least condition for undefined parameters.

**Comment by aklenik** [comment]
@nklincoln The launch commands now rigorously check the main required settings:
https://github.com/hyperledger/caliper/blob/fc3e4589c529caaf3e099d7c6563cb846a1a1b24/packages/caliper-core/lib/common/utils/caliper-utils.js#L41

So I think that closes this issue.
