### ISSUE TITLE
Long-running test fails with RangeError: Too many elements passed to Promise.all

### ISSUE THREAD

**Issue by scottoaks17** [hyperledger/caliper#729]
Running a test with a very long duration resulted in a failure when the test concluded.

## Context
Full text of error:
2020.02.08-00:34:21.400^[[32m info ^[[39m [caliper] [local-observer]    [smallOperations Round 0 Transaction Info] - Submitted: 2255213 Succ: 2255095 Fail:101 Unfinished:17
2020.02.08-00:34:21.617^[[32m info ^[[39m [caliper] [local-client.js]   Client[12340] encountered an error: RangeError: Too many elements passed to Promise.all
    at Function.all (<anonymous>)
    at CaliperLocalClient.runDuration (/home/opc/caliper_new/node_modules/@hyperledger/caliper-core/lib/client/caliper-local-client.js:282:23)
2020.02.08-00:34:21.618^[[31m error^[[39m [caliper] [defaultTest]       ------ Failed 'smallOperations' testing with the following error ------
    Error: Client encountered error:RangeError: Too many elements passed to Promise.all
    at ChildProcess.<anonymous> (/home/opc/caliper_new/node_modules/@hyperledger/caliper-core/lib/client/client-orchestrator.js:267:45)
    at ChildProcess.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2020.02.08-00:34:21.619^[[32m info ^[[39m [caliper] [caliper-flow]      ---------- Finished Test ----------

## Expected Behavior
Results should be processed

## Actual Behavior
Above error emitted

## Possible Fix
Process the promises in batches. The limit on Promise.all appears to be 2097151, so something like this should work in caliper-local-client.js:

    let chunkSize = 2000000;
    for (var i=0, len=promises.length; i < len; i += chunkSize) {
        await Promise.all(promises.slice(i,chunkSize));
    }

## Steps to Reproduce

1. Run a long test, In my case, I had 2255213 transactions over a 4 hour period.
2.
3.
4.

## Existing issues
None found

## Your Environment
Version used: caliper-cli 0.2.0, fabric 1.4.0, grpc 1.14.2
Environment name and version (e.g. Chrome 39, node.js 5.4): node 10.18.1
Operating System and version (desktop or mobile): OEL 7.7

**Comment by nklincoln** [comment]
@scottoaks17 - thanks for raising this issue, this is something that we have been wanting to address for a while now 👍

**Comment by aklenik** [comment]
@scottoaks17 This also raises the question of the limit of the `promises` array. A quick-fix would be to gather the promises in an array of arrays (using the above chunk size for example). Although we're working on a solution to circumvent the `Promise.all` entirely, but that's only for the 0.4.0 release.

If you can put together a PR with the mentioned quick-fix, it might land in 0.3.0 as a temporary workaround.
