### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by JulienGuo** [hyperledger/caliper#73]
My node version is 8.9.4 ; npm install is completed.
There is error : 

guolidong:~/Documents/GitHub/caliper$ node benchmark/simple/main.js -c config-fabric.json -n fabric.json
TAP version 13
# #######Caliper Test######
not ok 1 SyntaxError: Unexpected token function
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [SyntaxError: Unexpected token function]
    at: Test.onetime [as end] (/Users/guolidong/Documents/GitHub/caliper/node_modules/tape-promise/node_modules/onetime/index.js:22:12)
    stack: |-
      /Users/guolidong/Documents/GitHub/caliper/src/fabric/e2eUtils.js:546
      async function invokebycontext(context, id, version, args, timeout){
            ^^^^^^^^
      SyntaxError: Unexpected token function
          at Object.exports.runInThisContext (vm.js:76:16)
          at Module._compile (module.js:542:28)
          at Object.Module._extensions..js (module.js:579:10)
          at Module.load (module.js:487:32)
          at tryModuleLoad (module.js:446:12)
          at Function.Module._load (module.js:438:3)
          at Module.require (module.js:497:17)
          at require (internal/module.js:20:19)
          at Object.<anonymous> (/Users/guolidong/Documents/GitHub/caliper/src/fabric/fabric.js:12:18)
          at Module._compile (module.js:570:32)
  ...

1..1
# tests 1
# pass  0
# fail  1

**Comment by haojun** [comment]
Hi, could you try with node v8.10?

**Comment by aklenik** [comment]
It should work with any 8.x version. Are you sure you are using the right runtime? What is the output of the following command(s)?
`node -v` or `nvm ls`

**Comment by JulienGuo** [comment]
Problem solved
THKS @aklenik 
It's strange .  I run “nvm use v8.9.4”in a terminal，and run “node -v”in another terminal , it will be show v6.9.5.

guolidong:~$ node -v
v6.9.5
guolidong:~$ nvm ls
->       v6.9.5
         v8.9.4
         system
default -> v6.9 (-> v6.9.5)
node -> stable (-> v8.9.4) (default)
stable -> 8.9 (-> v8.9.4) (default)
iojs -> N/A (default)
lts/* -> lts/carbon (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.14.1 (-> N/A)
lts/carbon -> v8.11.1 (-> N/A)
guolidong:~$

**Comment by Alessthana** [comment]
Try to use nodev10.xx
