### ISSUE TITLE
Smallbank sample code will not run: TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by scottoaks17** [hyperledger/caliper#730]
#51  Context
Transactions in the smallbank sample code fail here:

    let functionArgs = [tempArgs[0].toString(), tempArgs[1].toString(), tempArgs[2].toString(), tempArgs[3].toString()];

tempArgs here is a specific request (the op_payload) from generateWorkload; here is a what it looks like in the case of 'transact_savings':

       case 'transact_savings': {
            op_payload = {
                'amount': amount,
                'customer_id': random_acc,
                'transaction_type':random_op
            };
            break;
        }

For most payloads, there are only 3 and not 4 items in the array and so tempArgs[3] is undefined.

## Expected Behavior
Code should run

## Actual Behavior
Code throws TypeError

## Possible Fix

    let functionArgs = tempArgs.slice(0, tempArgs.length - 1).map(function(v) { return v.toString(); });

## Steps to Reproduce
1. Fails on all runs
2.
3.
4.

## Existing issues

None found

## Your Environment
Version used: caliper-cli 0.2.0, fabric 1.4.0, grpc 1.14.2
Environment name and version (e.g. Chrome 39, node.js 5.4): node 10.18.1
Operating System and version (desktop or mobile): OEL 7.7

**Comment by aklenik** [comment]
@scottoaks17 Nice catch!
The also simplified fix should also suffice:
```js
let functionArgs = Object.values(arg).map(v => v.toString());
```

Would you like to submit the fix for the benchmark repo? :)

**Comment by aklenik** [comment]
Opened a new issue for this in the benchmark repo:
https://github.com/hyperledger/caliper-benchmarks/issues/55
