### ISSUE TITLE
How to use benchmarks to test sample network first-network

### ISSUE THREAD

**Issue by littlexy** [hyperledger/caliper#759]
Hello, now I want to use benchmarks to test a sample network provided by Hyperledger Fabric, its name is first-network, but its structure of network config file is different from the structure provided by   benchmarks, so, should I change configtx.yaml in first-network to fit in benchmark? Or should I do some other thing? Please give me some steps to handle it. Any help would be appreciated!

**Comment by nklincoln** [comment]
you can use caliper to target an existing network, this does require knowledge of the network configuration etc that is bespoke to the network you created - see https://developer.ibm.com/technologies/blockchain/tutorials/blockchain-performance-testing-smart-contracts-vscode-caliper for more information
