### ISSUE TITLE
TypeError: Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by littlexy** [hyperledger/caliper#760]
Has somebody encountered the problem in title? How to resolve it? Please give me some advice. Thanks in advance!

**Comment by aklenik** [comment]
@littlexy Could you provide more details, please? Like the example you used, commands you executed, etc.

**Comment by aklenik** [comment]
@littlexy I've run into probably the same issue. The benchmark configuration file should include `test.workers` and not `test.clients`. The documentation is incorrect, and the benchmark repo examples haven't been updated to the v0.3.0 release. 
Does this solve your problem?

**Comment by littlexy** [comment]
@aklenik Thanks for your reply.

1.  I use fabric-v1.4.0/2org1peergoleveldb as example. My executed command is "npx caliper launch master --caliper-workspace . --caliper-benchconfig benchmarks/scenario/simple/config.yaml --caliper-networkconfig networks/fabric/fabric-v1.4.0/2org1peergoleveldb/fabric-go.yaml" 
2. I want to konw where to find test.workers.
3.when I executed  "npx caliper --version", it appeared "v0.3.0", does that mean the benchmark repo examples have been updated to the v0.3.0? If not, how should I do?

**Comment by aklenik** [comment]
@littlexy This file contains that attribute: benchmarks/scenario/simple/config.yaml
The latest Caliper release is 0.3.0, but the benchmark repo examples are not updated yet (they are completely separate artifacts from Caliper). We're working on updating the benchmark repo

**Comment by littlexy** [comment]
@aklenik So, if I use the older Caliper release that would be okay?

**Comment by aklenik** [comment]
@littlexy Yes, that should be fine. I'll close this issue since this is a benchmark repo problem.

**Comment by ramoncordeiro** [comment]
My caliper is 0.3.0 and the benchmark configuration is set test.workers. But it not works. I have the same problem.

error: [caliper-flow]: Error: TypeError: Cannot read property 'hasOwnProperty' of undefined
    at ClientOrchestrator.init (/usr/local/lib/node_modules/@hyperledger/caliper-cli/node_modules/@hyperledger/caliper-core/lib/client/client-orchestrator.js:108:24)
    at Object.module.exports.run (/usr/local/lib/node_modules/@hyperledger/caliper-cli/node_modules/@hyperledger/caliper-core/lib/caliper-flow.js:101:60)
    at async Function.handler (/usr/local/lib/node_modules/@hyperledger/caliper-cli/lib/benchmark/lib/runBenchmark.js:64:30)
info: [caliper-utils]: Executing command: cd /home/ramon/Documentos/workspace/caliper/caliper-benchmarks;docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb/docker-compose.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*

**Comment by aklenik** [comment]
@ramoncordeiro Please re-check your Caliper version. The file paths in the error logs indicate that you're using v0.2.0. That version still uses the `test.clients` attributes, so v0.3.0 benchmark files won't work.

**Comment by ramoncordeiro** [comment]
I've already change to test.clients. But it not works.

**Comment by aklenik** [comment]
@ramoncordeiro Could you please list all the details of your test? Since you're using a bench repo example, please start with the commands for cloning the repository and installing Caliper.

**Comment by CozyDoughnut600** [comment]
I got the error 'TypeError: Cannot read property 'hasOwnProperty' of undefined', It happens when my ticket thingy wants to parent the channel. It goes wrong, and he's not in the correct category, how can I fix this? Does anyone have the same problem?
