### ISSUE TITLE
Fabric binding is missing the ca package

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#765]
Default binding config for 1.4.5 onwards is missing the fabric-ca packages ... we should have those in place

**Comment by gzuhlwang** [comment]
@nklincoln I use caliper image v0.3.0 for benchmarking fabric 2.0.0 with node sdk 1.4.7 binded. The caliper contianer throw the following error:

2020.03.16-08:55:56.197 +0000 error [cli-launch-master] Unexpected error during benchmark execution: Error: Cannot find module 'fabric-ca-client/package'

is it the same thing?

**Comment by nklincoln** [comment]
@gzuhlwang - yes, this is the same error

**Comment by gzuhlwang** [comment]
@nklincoln thanks your replies. Now  if i want to benchmark fabric 2.0.0 with caliper, is there any available caliper image? I switch caliper image from v0.3.0 to caliper:0.3.1-unstable-20200312092854. I got another error:
2020.03.16-09:14:29.353 +0000 error [bind] Failed to execute "npm" with return code 1.

**Comment by nklincoln** [comment]
fabric 2 is compatible with 1.4.x fabric sdk's, so there is no barrier there (i am running benchmarks on fabric 2.0)

**Comment by gzuhlwang** [comment]
so, you mean i can use node sdk 1.4.5 downwards for my purpose.

**Comment by gzuhlwang** [comment]
of course, 1.4.x ~ 1.4.5 (inclusive?)

**Comment by nklincoln** [comment]
yes that is correct

**Comment by gzuhlwang** [comment]
yeah. I will do it. thanks for u help man.

**Comment by gzuhlwang** [comment]
@nklincoln sorry to bother u. But when I fall back node sdk to 1.4.3 or 1.4.4, and  everything else keeps the same, I met the following error:

make: Leaving directory '/home/node/.npm-global/lib/node_modules/fabric-network/node_modules/pkcs11js/build'
> grpc@1.24.2 install /home/node/.npm-global/lib/node_modules/fabric-network/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! Completion callback never invoked!
node-pre-gyp ERR! System Linux 5.3.0-40-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/node/.npm-global/lib/node_modules/fabric-network/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/node/.npm-global/lib/node_modules/fabric-network/node_modules/grpc
node-pre-gyp ERR! node -v v10.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the grpc@1.24.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-03-17T17_35_24_572Z-debug.log
2020.03.17-17:35:25.550 +0000 error [bind] Failed to execute "npm" with return code 6.

At the start of caliper  container, I enter the container, and check the node version(v10.16.3), npm version(6.9.0). After a while, the above error will be thrown.

The following env may be helpful.

-  CALIPER_BIND_SUT=fabric:1.4.3
-  CALIPER_BIND_SDK=1.4.3 

any tips will be thankful.

**Comment by nklincoln** [comment]
that's a grpc error - the fix is in for the original error and you can get the new image with `docker pull hyperledger/caliper:0.3.0-unstable-20200303163238`

Closing this issue under #767
