### ISSUE TITLE
caliper bind command is failing

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#768]
When running bind command, the command is failing on additional bind args with `Not enough arguments following: caliper-bind-args`

This is an issue within the current version of yargs being used

**Comment by ShruthieS** [comment]
Hi, 
I am facing the following issue.
Not enough arguments following: caliper-bind-args
I have updated the yargs version to 15.3.1, still am facing this issue. Can you suggest how to resolve this?

**Comment by aklenik** [comment]
@ShruthieS What is the exact command you're executing? With the caliper-bind-args parameter, you have to use = to set it: https://hyperledger.github.io/caliper/v0.3/installing-caliper/#the-bind-command
(Otherwise, the value will be picked up as another parameter, leaving the bind-args unset.)

**Comment by ShruthieS** [comment]
@aklenik Thanks for the response! This is the command I am executing.
caliper bind --caliper-bind-sut fabric:1.4.1 --caliper-bind-sdk 1.4.0 --caliper-bind-args=-g
Like you mentioned I have used = only to set it. Is this correct? or should I do any changes? to resolve this issue.

**Comment by aklenik** [comment]
@ShruthieS Can you try `--caliper-bind-args="-g"` (so also using quotes around -g)?

**Comment by ShruthieS** [comment]
@aklenik I have tried that too.
![Screenshot from 2020-04-30 12-30-01](https://user-images.githubusercontent.com/60088388/80681536-852e5380-8ade-11ea-9857-b0de715981d7.png)

**Comment by aklenik** [comment]
@ShruthieS Which Caliper version are you using?

**Comment by ShruthieS** [comment]
@aklenik  0.3.0

**Comment by aklenik** [comment]
@ShruthieS Then maybe some global dependencies cause this error. Caliper depends on yargs for the CLI. Can you find out what yargs version is installed globally? It should be 15.3.1. If any other version is present globally, remove it (or install Caliper locally).

**Comment by nageshcaparthy** [comment]
I have the same issue. I have installed Caliper 0.3.0 and yargs of 15.3.2. But still, I end up with same issue. 

caliper bind --caliper-bind-sut fabric --caliper-bind-sdk 1.4.7 --caliper-bind-args="-g"
Usage:
  caliper bind --caliper-bind-sut fabric:1.4.1 --caliper-bind-cwd ./ --caliper-bind-args="-g"

Options:
  --help, -h           Show usage information  [boolean]
  --version            Show version information  [boolean]
  --caliper-bind-sut   The name and version of the platform and its SDK to bind to  [string]
  --caliper-bind-cwd   The working directory for performing the SDK install  [string]
  --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
  --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]

Not enough arguments following: caliper-bind-args

**Comment by nklincoln** [comment]
The fix is only available in the versions:
- 0.3.1
- unstable

You will not see the fix in 0.3.0 as it pre-dates the fix merge
