### ISSUE TITLE
Execute chaincode timeout. error: [Peer.js]: sendProposal - timed out after:30000

### ISSUE THREAD

**Issue by LiQi1997-Simba** [hyperledger/caliper#775]
Hello!I used caliper to test my chaincode, and all the tests failed because REQUEST_TIMEOUT.I have modified Peer - CORE_CHAINCODE_EXECUTETIMEOUT=120s in docker-compose.yaml, which does not solve the problem.What else do I need to change? Please give me some steps to handle it. Any help would be appreciated!

My caliper version is v0.2.0 and fabric version v1.4.4.

## Context

2020-03-21T14:51:32.448Z - error: [Peer.js]: sendProposal - timed out after:29999
2020-03-21T14:51:32.472Z - error: [Peer.js]: sendProposal - timed out after:30000
2020-03-21T14:51:32.484Z - error: [Peer.js]: sendProposal - timed out after:30000
2020-03-21T14:51:32.484Z - error: [Peer.js]: sendProposal - timed out after:30000
2020.03.21-07:51:32.485 error [caliper] [adapters/fabric] 	Transaction[71dcc89281] life-cycle errors:
	- Proposal response error by peer0.org1.example.com: REQUEST_TIMEOUT
	- Proposal response error by peer0.org2.example.com: REQUEST_TIMEOUT
2020-03-21T14:51:32.486Z - error: [Peer.js]: sendProposal - timed out after:30000
2020-03-21T14:51:32.489Z - error: [Peer.js]: sendProposal - timed out after:30000
2020-03-21T14:51:32.489Z - error: [Peer.js]: sendProposal - timed out after:30000
2020.03.21-07:51:32.489 error [caliper] [adapters/fabric] 	Transaction[2521de31d6] life-cycle errors:
	- Proposal response error by peer0.org1.example.com: REQUEST_TIMEOUT
	- Proposal response error by peer0.org2.example.com: REQUEST_TIMEOUT
2020.03.21-07:51:32.489 error [caliper] [adapters/fabric] 	Transaction[b10b4194e4] life-cycle errors:
	- Proposal response error by peer0.org1.example.com: REQUEST_TIMEOUT
	- Proposal response error by peer0.org2.example.com: REQUEST_TIMEOUT

| Name             | Succ | Fail | Send Rate (TPS) | Max Latency (s) | Min Latency (s) | Avg Latency (s) | Throughput (TPS) |
|------------------|------|------|-----------------|-----------------|-----------------|-----------------|------------------|
| Register a user. | 0    | 1149 | 38.2            | 0.00            | 100000.00       | NaN             | 0.0              |

**Comment by aklenik** [comment]
@LiQi1997-Simba The mentioned setting is only for server-side (Fabric) timeout. When you submit your TX from your worker module (calling `invokeSmartContract`), you can set the client-side (Caliper) timeout as the last argument, in seconds: https://hyperledger.github.io/caliper/vLatest/fabric-config/#the-run-callback

(Note, that the timeout is for complete TX life-cycle, i.e., endorsing, ordering and validating & committing.)
