### ISSUE TITLE
Error:  [caliper] [caliper-engine]: 	Error while performing "test" step: TypeError: Cannot read property 'length' of undefined - While running predefined caliper benchmark tests

### ISSUE THREAD

**Issue by swathidhamo** [hyperledger/caliper#781]
Ran the caliper benchmark test using the following command in the fabcar benchmark setup in Fabric samples. 

`npx caliper launch master     --caliper-workspace .     --caliper-benchconfig benchmarks/samples/fabric/fabcar/config.yaml     --caliper-networkconfig networks/fabric/fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml`

![Screenshot from 2020-04-01 19-18-04](https://user-images.githubusercontent.com/22546722/78144753-a4898080-744d-11ea-8ddd-02722f17ba9a.png)
![Screenshot from 2020-04-01 19-18-09](https://user-images.githubusercontent.com/22546722/78144764-a7847100-744d-11ea-84d3-8d50f910c19e.png)

Couldn't find any instance of the field length in the relevant directories and these are standard benchmark tests

Commands to replicate
```
 sudo npx caliper bind --caliper-bind-sut fabric --caliper-bind-sdk 1.4.4 

sudo npx caliper launch master     --caliper-workspace .     --caliper-benchconfig benchmarks/scenario/simple/config.yaml     --caliper-networkconfig networks/fabric/fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml


```

* Version used: 0.3.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Nodejs v10.19, npm v5.6.0
* Operating System and version (desktop or mobile): Ubuntu `18.04`

I need to run benchmarks on smart contracts written on top of the Fabcar setup, so an understanding of caliper would be quite critical
Thank you in advance

**Comment by AnushaUpadhyaya** [comment]
I am getting a similar error. Details included below:

TypeError: Cannot read property 'hasOwnProperty' of undefined - While running predefined caliper benchmark tests

caliper-benchmarks$ npx caliper bind --caliper-bind-sut fabric --caliper-bind-sdk 1.4.1

caliper-benchmarks $ npx caliper benchmark run --caliper-workspace . --caliper-benchconfig benchmarks/scenario/simple/config.yaml --caliper-networkconfig networks/fabric/
fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml

Benchmark for target Blockchain type fabric about to start
2020.03.26-16:51:52.354 info  [caliper] [benchmark-validator]   No observer specified, will default to `none`
2020.03.26-16:51:52.355 info  [caliper] [caliper-flow]  ####### Caliper Test #######
2020.03.26-16:51:52.359 info  [caliper] [null-observer]         Configured observer
2020.03.26-16:51:52.363 info  [caliper] [caliper-utils]         Executing command: cd /apps/opt/user/src/caliper-benchmarks;export FABRIC_VERSION=1.4.1;docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb/docker-compose.yaml up -d;sleep 3s
Creating network "2org1peergoleveldb_default" with the default driver
Creating orderer.example.com ... done
Creating ca.org2.example.com ... done
Creating ca.org1.example.com ... done
Creating peer0.org1.example.com ... done
Creating peer0.org2.example.com ... done
2020.03.26-16:51:58.050 info  [caliper] [adapters/fabric]       Fabric SDK version: 1.4.1; TLS: none
2020.03.26-16:51:58.668 info  [caliper] [adapters/fabric]       Org1's registrar enrolled successfully
2020.03.26-16:51:58.863 info  [caliper] [adapters/fabric]       Org2's registrar enrolled successfully
2020.03.26-16:51:58.884 info  [caliper] [adapters/fabric]       Org1's admin's materials are successfully loaded
2020.03.26-16:51:58.893 info  [caliper] [adapters/fabric]       Org2's admin's materials are successfully loaded
2020.03.26-16:51:58.902 info  [caliper] [adapters/fabric]       client0.org1.example.com's materials are successfully loaded
2020.03.26-16:51:58.910 info  [caliper] [adapters/fabric]       client0.org2.example.com's materials are successfully loaded
2020.03.26-16:51:58.911 info  [caliper] [adapters/fabric]       Channel 'mychannel' definiton being retrieved from file
2020.03.26-16:51:58.971 info  [caliper] [adapters/fabric]       Channel 'mychannel' successfully created
2020.03.26-16:51:58.971 info  [caliper] [adapters/fabric]       Sleeping 5s...
2020.03.26-16:52:04.061 info  [caliper] [adapters/fabric]       Org1's peers successfully joined mychannel: peer0.org1.example.com
2020.03.26-16:52:04.118 info  [caliper] [adapters/fabric]       Org2's peers successfully joined mychannel: peer0.org2.example.com
2020.03.26-16:52:04.119 info  [caliper] [adapters/fabric]       Sleeping 5s...
2020.03.26-16:52:09.120 info  [caliper] [adapters/fabric]       Installing chaincodes for mychannel...
2020.03.26-16:52:09.175 info  [caliper] [adapters/fabric]       marbles@v0 successfully installed on Org1's peers: peer0.org1.example.com
2020.03.26-16:52:09.202 info  [caliper] [adapters/fabric]       marbles@v0 successfully installed on Org2's peers: peer0.org2.example.com
2020.03.26-16:52:09.241 info  [caliper] [adapters/fabric]       drm@v0 successfully installed on Org1's peers: peer0.org1.example.com
2020.03.26-16:52:09.257 info  [caliper] [adapters/fabric]       drm@v0 successfully installed on Org2's peers: peer0.org2.example.com
2020.03.26-16:52:09.290 info  [caliper] [adapters/fabric]       simple@v0 successfully installed on Org1's peers: peer0.org1.example.com
2020.03.26-16:52:09.316 info  [caliper] [adapters/fabric]       simple@v0 successfully installed on Org2's peers: peer0.org2.example.com
2020.03.26-16:52:09.366 info  [caliper] [adapters/fabric]       smallbank@v0 successfully installed on Org1's peers: peer0.org1.example.com
2020.03.26-16:52:09.385 info  [caliper] [adapters/fabric]       smallbank@v0 successfully installed on Org2's peers: peer0.org2.example.com
2020.03.26-16:52:09.386 info  [caliper] [adapters/fabric]       Instantiating marbles@v0 in mychannel. This might take some time...
2020.03.26-16:52:50.509 info  [caliper] [adapters/fabric]       Successfully instantiated marbles@v0 in mychannel
2020.03.26-16:52:50.510 info  [caliper] [adapters/fabric]       Instantiating drm@v0 in mychannel. This might take some time...
2020.03.26-16:53:31.681 info  [caliper] [adapters/fabric]       Successfully instantiated drm@v0 in mychannel
2020.03.26-16:53:31.682 info  [caliper] [adapters/fabric]       Instantiating simple@v0 in mychannel. This might take some time...
2020.03.26-16:54:12.143 info  [caliper] [adapters/fabric]       Successfully instantiated simple@v0 in mychannel
2020.03.26-16:54:12.143 info  [caliper] [adapters/fabric]       Instantiating smallbank@v0 in mychannel. This might take some time...
2020.03.26-16:54:52.760 info  [caliper] [adapters/fabric]       Successfully instantiated smallbank@v0 in mychannel
2020.03.26-16:54:52.761 info  [caliper] [adapters/fabric]       Sleeping 5s...
2020.03.26-16:54:59.594 info  [caliper] [caliper-flow]  Started monitors successfully
2020.03.26-16:54:59.598 error [caliper] [caliper-flow]  Error: TypeError: Cannot read property 'hasOwnProperty' of undefined
    at ClientOrchestrator.init (/apps/opt/user/caliper-benchmarks/node_modules/@hyperledger/caliper-core/lib/client/client-orchestrator.js:41:24)
    at Object.module.exports.run (/apps/opt/user/caliper-benchmarks/node_modules/@hyperledger/caliper-core/lib/caliper-flow.js:106:60)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020.03.26-16:54:59.599 info  [caliper] [caliper-utils]         Executing command: cd /apps/opt/user/src/caliper-benchmarks;docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb/docker-compose.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*
The FABRIC_VERSION variable is not set. Defaulting to a blank string.
Stopping peer0.org2.example.com ... done
Stopping peer0.org1.example.com ... done
Stopping ca.org2.example.com    ... done
Stopping orderer.example.com    ... done
Stopping ca.org1.example.com    ... done
Removing peer0.org2.example.com ... done
Removing peer0.org1.example.com ... done
Removing ca.org2.example.com    ...
Removing ca.org2.example.com    ... done
Removing orderer.example.com    ... done
2020.03.26-16:55:10.715 error [caliper] [monitor-docker]        Error reading monitor statistics: TypeError: Cannot read property 'total_usage' of undefined
Removing network 2org1peergoleveldb_default
/bin/sh: line 0: test: too many arguments
33cf0ce35730
1600290eab6b
5a96ae3d5db1
7976934839cf
9415198ad745
33e9cc25a725
dda7839c1bb8
3ec7be72c3fc
/bin/sh: line 0: test: too many arguments
Untagged: dev-peer0.org2.example.com-smallbank-v0-f8b95020f1a3b8371f7c58e1af1ff3d9fe0d4b26389373fa678955579a772c8f:latest
Deleted: sha256:2361af75dabee0ad0a43b25f0b6a5b58e7cb6c3231d282a2d2dc7bb824e49909
Deleted: sha256:3032f8259512d9f6dc25f80db38f08b02e95c7cd05b068edd75c1ba76ab8d7b5
Deleted: sha256:b27856fa2491bb9d1c2f3fc17ead3f5f4dd62ae617cd24d65abc3860146e1537
Deleted: sha256:49b2091c128bbcccaca075a1656de3acb472c126e64eac0e71befbffef846f95
Untagged: dev-peer0.org1.example.com-smallbank-v0-b1f07dc4b6d8079c04183f3e9c828770349d6c0fd5ce55d82a7782925b2ce03a:latest
Deleted: sha256:8abb7da7b75fec30574f4e6ccfaf679c430f2232f73a7e0d21b85b907974eb2b
Deleted: sha256:38db82de6737213aeda2b282682ef217e5fd2685132fe7a4ae662329607995c6
Deleted: sha256:ea3ada938da9f6d83795ccaf7995dd4cd61bbe5d5ca19434b6699f3ea8608b71
Deleted: sha256:1ad62e7826dbd0b207c0baf79781cf9d955ab55b54c072e2015cfcd4bbb68fc4
Untagged: dev-peer0.org2.example.com-simple-v0-7ebccf7a7fd05d8ac0a55ea61f1f0397ca89de629cef5f537c0950ecf302d423:latest
Deleted: sha256:a37f993496fe72fbab9e4e0bbb6a9c940ce561047a45d32bebba3eca740f28c4
Deleted: sha256:52e8857ad12777fb40be3650bee3619cd1433829d469ed959c1d434767ebe11d
Untagged: dev-peer0.org1.example.com-simple-v0-b845a7f88df0bd3a47a573b80bd5cfab0986278f024e8667a3c90fb0eb1f4d6d:latest
Deleted: sha256:52518c51172c1fa481eed34989924652ddda7cf5c5f0c7edc5bf3c53c0c99ce7
Deleted: sha256:a419810d92cc086faeae2749173ce6c1af98af221ea90a67f4534525b1e29b57
Deleted: sha256:ccd7719ba8b9a991f3ba425d76b03ca015cf3068d4e5ce0ec033534fff9b06ce
Deleted: sha256:34a46359fe30700837500dc077427c662b060fe9fcacc62429918187c539ff23
Untagged: dev-peer0.org1.example.com-drm-v0-08a16fdaf3af53efb6b99e3c2ec4de9aa78e4d592b4582fc4aa4709c1f3b13cb:latest
Deleted: sha256:b581aa3ed140fba6d5640d84e267bc7af1a58290cfb74b6d147da1c9325a6ca6
Deleted: sha256:9b1cfa7581aa5ff68c9ea1a4dbe9f64cf75c4029bfc7f54b0c6ece726d1fa5d8
Deleted: sha256:c4a51bd4e552a3636d92e5bd09d079713e7aa83187acfd2f1a3d44cc0dbc8b70
Deleted: sha256:091900b0e658637a5e2c5bcbda4d642e4486f1734d36b3d8d53118d32322efb0
Untagged: dev-peer0.org2.example.com-drm-v0-c25cb5f64ec9f30764df0f6b930f1f3bc7b96f88da333c49c4c6779ac65a4552:latest
Deleted: sha256:560ed692f73a96dd11ea6d5a4a835ee69564915093df57136c0519211d76cde2
Deleted: sha256:9b0a12f3f0b3bbe74ecc3e129bfd6ad3bca14c768ec46ecee6e3bfae639a020a
Deleted: sha256:4fe24fb745e16244c921ad4d323a05efb15ccdd764cbd7c0a30c60477874b808
Deleted: sha256:be2c9ba63fadb7c39db5f4a753dbea11ad1dca52d3d2ce16d95cd57fb8b422a0
Untagged: dev-peer0.org1.example.com-marbles-v0-d970bb5377683adf108a269e3670f7f9cbb849f3eff58fe19595ea3374a52ea0:latest
Deleted: sha256:9b6e2ae3eabe8379762082d7cc886a9ee546cae130c739a0e4a552f81999c130
Deleted: sha256:45b85e75113b806841184686a1ba415e8ca5d858b319e43e9b7add3ee2b5f72c
Deleted: sha256:7353e9d287b05930f1b0428912ebebe8407ca6167529014ba1ee87b166f3f14e
Deleted: sha256:265e6740b94a30ccb0d7b32b3965ed8b4615f0b2f01e1a486bd06f65cb3669f0
Untagged: dev-peer0.org2.example.com-marbles-v0-82ec74ea3ac84a8926b1d7d3d256a2e2f41b74928c28cf4bcdbb5a7774a90f87:latest
Deleted: sha256:43a9e4cedeba3e0c8e73139dde187de54365bb67f4fb727acdbf415654b8d6b2
Deleted: sha256:d382b9bb6cf9babcb8a1a33e521c98eb92b3e5d7be028da386ed896a2119b7aa
Deleted: sha256:ad9212cfb8eb6f67331fb727616783504db3c1ee44447c3cf8293e645b2f1e8d
Deleted: sha256:621921b86a80c1145c39a25bc15d6866c5dfca33ef8ad4b3587904bb954a840a
Benchmark failure
Error: Benchmark failure
    at Function.handler (/apps/opt/user/caliper-benchmarks/node_modules/@hyperledger/caliper-cli/lib/benchmark/lib/runBenchmark.js:70:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Command failed



Version used : 0.2.0
node version : 10.19   npm version : 6.13.4
Operating System: CentOS 7

**Comment by gzuhlwang** [comment]
I got a similar error.
`error [caliper-engine] Error while performing "test" step: TypeError: Cannot read property 'length' of undefined
2020.03.30-07:33:09.662 +0000 info [caliper-engine] Skipping end command due to benchmark flow conditioning
2020.03.30-07:33:09.678 +0000 error [cli-launch-master] Benchmark failed with error code 6.`

are you fixed it?

**Comment by RookieLinLucy666** [comment]
I got a similar error too...
 this problem has happened when I use caliper0.2.0 and caliper0.3.0 to test fabric, the same as the fiscobcos.
`error [caliper] [caliper-flow] 	Error: TypeError: Cannot read property 'hasOwnProperty' of undefined`

version:
benchmark:  latest
system: macos

Commands to replicate
`npx caliper benchmark run \
    --caliper-workspace . \
    --caliper-benchconfig benchmarks/scenario/simple/config.yaml \
    --caliper-networkconfig networks/fabric/fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml`

**Comment by tzortzispanagiotis** [comment]
On config.yaml:
Modify this:
`monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: fabricClientWorker.js
    multiOutput: avg
  interval: 1
`
To this:
`monitor:
  type:
  - docker
  docker:
    name:
    - all
  interval: 1
`
There is some kind of issue with the process monitor. By removing the monitor i guess you lose some functionality, but the benchmark runs fine.

Also, looking at your logs I noticed that the fabcar smart contract is not installed during the initialisation of your network. This happens because in fabric-go.yaml you probably havent modified it to include this chaincode (you can comment out the other 5 options, drm marbles simple etc, since it only causes extra delay on initialisation.). Fabcar chaincode is located in src/fabric/samples/fabcar if you are using caliper-benchmarks repository as your workspace.

**Comment by RookieLinLucy666** [comment]
> I got a similar error too...
> this problem has happened when I use caliper0.2.0 and caliper0.3.0 to test fabric, the same as the fiscobcos.
> `error [caliper] [caliper-flow] Error: TypeError: Cannot read property 'hasOwnProperty' of undefined`
> 
> version:
> benchmark: latest
> system: macos
> 
> Commands to replicate
> `npx caliper benchmark run \ --caliper-workspace . \ --caliper-benchconfig benchmarks/scenario/simple/config.yaml \ --caliper-networkconfig networks/fabric/fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml`

================================================================

I found that it's a bug about benchmarks in a closed issue. The reviewer suggested us to use the older version.
`git checkout v0.2.0`
Then benchmark runs successfully.

**Comment by swathidhamo** [comment]
![Screenshot from 2020-04-04 18-33-34](https://user-images.githubusercontent.com/22546722/78451370-df382680-76a2-11ea-857f-f0fc9c7c21c2.png)
I had made the mentioned changes suggested by @tzortzispanagiotis  on the config.yaml file. 
They now lead to an error because the "Initialization ongoing" log from the caliper-local-client.js file runs in an infinite loop. This seems to be a core caliper engine so I don't know how to diagnose it. 

Looking at the file I realize the error comes from line 345/346 of the caliper-local-client.js file, it seems to be because the context is not set. 
I have attached the config and fabric go files with a couple of other syntax changes. 

**This is the snapshot of the caliper-local-client file**
![Screenshot from 2020-04-04 18-31-42](https://user-images.githubusercontent.com/22546722/78451331-a7c97a00-76a2-11ea-80c6-5ce1a782992d.png)

**The command line logs**
![Screenshot from 2020-04-04 18-33-30](https://user-images.githubusercontent.com/22546722/78451365-dc3d3600-76a2-11ea-941c-2f8ee7ccf656.png)
![Screenshot from 2020-04-04 18-33-39](https://user-images.githubusercontent.com/22546722/78451372-e0695380-76a2-11ea-9df0-cfbdcba6dba0.png)
![Screenshot from 2020-04-04 18-33-43](https://user-images.githubusercontent.com/22546722/78451373-e19a8080-76a2-11ea-8304-e56c314b7ec7.png)


Help here would be much appreciated! I have tried to modify that file and trace errors but I am unable to do so. And a switch to version 0.2.0 also yields a similar error.

**Comment by RookieLinLucy666** [comment]
Maybe you can have a try the older version, including changing the caliper version.


`npm install --only=prod @hyperledger/caliper-cli@0.2.0`
`git clonehttps://github.com/hyperledger/caliper-benchmarks.git`  and then `git checkout v0.2.0`


After that, the running command becomes like that
`npx caliper benchmark run \
    --caliper-workspace . \
    --caliper-benchconfig benchmarks/scenario/simple/config.yaml \
    --caliper-networkconfig networks/fabric/fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml`


Conclusion:
Using older versions including caliper and benchmarks, then using the command v0.2.0 then it will work.




On 04/4/2020 21:06，Swathi Dhamodaran<notifications@github.com> wrote：


I had made the mentioned changes suggested by @tzortzispanagiotis on the config.yaml file.
They now lead to an error because the "Initialization ongoing" log from the caliper-local-client.js file runs in an infinite loop. This seems to be a core caliper engine so I don't know how to diagnose it.

Looking at the file I realize the error comes from line 345/346 of the caliper-local-client.js file, it seems to be because the context is not set.
I have attached the config and fabric go files with a couple of other syntax changes.

This is the snapshot of the caliper-local-client file


The command line logs




Help here would be much appreciated! I have tried to modify that file and trace errors but I am unable to do so. And a switch to version 0.2.0 also yields a similar error.

**Comment by swathidhamo** [comment]
I was able to run the fabcar tests successfully with version 0.3.0. 
Turns out all it took was some modification of the assets field and then a few basic changes. 
I have attached the final config files for anyone's reference. 
Thank you all for your help




[fabric-go.txt](https://github.com/hyperledger/caliper/files/4451491/fabric-go.txt)
[config.txt](https://github.com/hyperledger/caliper/files/4451489/config.txt)

**Comment by ManjuVenkatachalam** [comment]
I have setup hyperledger fabric v1.4.2 with 1 org 2 peer 1 orderer running natively in three different VMs. In that I am trying to implement caliper v0.3.0. 
I am facing this issue while instantiating and invoking the chaincode.
error: [Orderer.js]: sendBroadcast - on error: "Error: 14 UNAVAILABLE: failed to connect to all addresses\n    at Object.exports.createStatusError (/home/loan/caliper-benchmarks/node_modules/grpc/src/common.js:91:15)\n    at ClientDuplexStream._emitStatusIfDone (/home/loan/caliper-benchmarks/node_modules/grpc/src/client.js:233:26)\n    at ClientDuplexStream._receiveStatus (/home/loan/caliper-benchmarks/node_modules/grpc/src/client.js:211:8)\n    at Object.onReceiveStatus (/home/loan/caliper-benchmarks/node_modules/grpc/src/client_interceptors.js:1306:15)\n    at InterceptingListener._callNext (/home/loan/caliper-benchmarks/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/home/loan/caliper-benchmarks/node_modules/grpc/src/client_interceptors.js:618:8)\n    at /home/loan/caliper-benchmarks/node_modules/grpc/src/client_interceptors.js:1123:18"
2020.04.29-12:22:12.094 error [caliper] [caliper-engine] 	Error while performing "install" step: Error: Orderer error for instantiating WarehouseCreatepool1CC@v0 in composerchannelrest: SERVICE_UNAVAILABLE
2020.04.29-12:22:12.094 info  [caliper] [caliper-engine] 	Executed "install" step in 0.473 seconds
2020.04.29-12:22:12.094 info  [caliper] [caliper-engine] 	Skipping end command due to benchmark flow conditioning
2020.04.29-12:22:12.094 error [caliper] [cli-launch-master] 	Benchmark failed with error code 5


Any one can you please suggest how to resolve this?

**Comment by aklenik** [comment]
@ManjuVenkatachalam This error comes from the Fabric SDK, and tells you that it can't reach certain endpoints of your Fabric nodes (or they reject the connection). So I suggest checking your networking settings since you have a distributed setup.

**Comment by gzuhlwang** [comment]
@aklenik  I met the same error. some background:
```
caliper image:hyperledger/caliper:0.3.1-unstable-20200507121257
cmd for caliper: launch master --caliper-flow-only-test --caliper-fabric-gateway-usegateway
env var: CALIPER_BIND_SUT: fabric:2.1.0
SUT: fabric 2.0.0
```

with channel and cc ready,  everything is ok. cli is ok for generating tx. But the caliper always didnot work as expected. please help me out, many thanks.
