### ISSUE TITLE
Error while performing "install" step

### ISSUE THREAD

**Issue by 609127400** [hyperledger/caliper#796]
Error while performing "install" step: Error: Invalid endorsement for simple@v0 in mychannel from peer0.org1.example.com: 2 UNKNOWN: Stream removed

I follow the chapter **Installing and Running Caliper** on document of caliper to run cmd [npx caliper launch master  --caliper-bind-sut fabric:1.4.0 ... ]，but got an error：Error while performing "install" step: Error: Invalid endorsement for simple@v0 in mychannel from peer0.org1.example.com: 2 UNKNOWN: Stream removed

when caliper's [adapters/fabric] Instantiating chaincode[simple@v0], there will be two ccenv containers，and peer0.org1,peer0.org2 is Exit with an error :

[gossip.service] func1 -\u003e INFO 056\u001b[0m Elected as a leader, starting delivery service for channel mychannel
fatal error: unexpected signal during runtime execution
signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7fbad42c2259

**Comment by 609127400** [comment]
Why there are two ccenv container when Instantiating  chaincode on channel? it's unreasonable，I think maybe just two ccenv to compile chaincode cause the connect error between peer and ccenv

**Comment by aklenik** [comment]
@609127400 Could be different versions of the same image. Try removing every ccenv image and related chaincode images, then run Caliper again.
