### ISSUE TITLE
Sleep time between phases of a round

### ISSUE THREAD

**Issue by aklenik** [hyperledger/caliper#8]
My terminology is the following: a Caliper config file can define multiple _rounds_, each round consists of (possibly) multiple _phases_, each phase associated with its own rate-controller.

Currently, the implementation [contains](https://github.com/hyperledger/caliper/blob/d8ed8ee4c6c931eb488697be8f58ec64c268adaa/src/comm/bench-flow.js#L268) a `sleep` call between each _phase_ inside the round, so a sudden increase in transaction rate cannot be modeled because of this cooldown period.

Is this behavior intentional? If not, a possible solution would be to call `sleep` after the whole round has [finished](https://github.com/hyperledger/caliper/blob/d8ed8ee4c6c931eb488697be8f58ec64c268adaa/src/comm/bench-flow.js#L129).

**Comment by haojun** [comment]
The design of 'phase' is only to reduce duplicate definitions, so each phase will be treated as an independent test round. 

If you want to define a continuous test with changing tx rate, you should implement a new type of 'rate-control' . 

In fact this is the reason why the modularized rate-control was introduced.

**Comment by aklenik** [comment]
Ah, thank you for the clarification!
