### ISSUE TITLE
npm ERR! Failed at the grpc@1.10.1 install script.

### ISSUE THREAD

**Issue by JulienGuo** [hyperledger/caliper#80]
root@vm10-210-0-10:/opt/gopath/src/github.com/hyperledger/caliper# npm install

> grpc@1.10.1 install /opt/gopath/src/github.com/hyperledger/caliper/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

/usr/bin/env: ‘node’: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! grpc@1.10.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the grpc@1.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-29T02_56_33_212Z-debug.log

**Comment by JulienGuo** [comment]
solved :
1、do not use root user
2、install node-gyp in global way . Such as install in ubuntu : sudo apt-get install node-gyp

**Comment by mabatak1** [comment]
npm install react-native  firebase@4.6.2 --save

**Comment by biletron** [comment]
> 
> 
> npm install react-native firebase@4.6.2 --save

it definitely saved hours of mine. could you please explain the reason behind? (for me just to understand)

**Comment by samthomson** [comment]
Changing firebase from 4.6.0 to 4.6.2 worked for me too, thanks.

**Comment by RevanthSivalingam** [comment]
> npm install react-native firebase@4.6.2 --save

Thanks, it's working !!

**Comment by adimunteanu** [comment]
> npm install react-native firebase@4.6.2 --save
This saved my day, it's working!

**Comment by rjcallahan** [comment]
It worked for me as well. THANKS!

**Comment by andypapmedialight** [comment]
> 

> npm install react-native firebase@4.6.2 --save

BINGO!
Cheers.

**Comment by komalbarge45** [comment]
It works for me. Thanks!

**Comment by Rober19** [comment]
for me works this:
package.json ->
"dependencies": {
    "firebase": "^5.0.2"
  },
 "resolutions": {
    "grpc": "^1.12.0"
  }

https://github.com/grpc/grpc/issues/15403#issuecomment-390122298

**Comment by ishandutta2007** [comment]
I needed to downgrade node from 10.12 to 8.11

    node -v

v10.12.0

    npm install -g n
    n 8.11.1
    mode -v

v8.11.1

**Comment by Hdezhkam** [comment]
npm install firebase --force

**Comment by Jchinonso** [comment]
> ```json
> "resolutions": {
>     "grpc": "^1.12.0"
>   }
> ```

Then use yarn  to install
