### ISSUE TITLE
Error while running benshmark on an existing network "version" must be one of [1.0]]

### ISSUE THREAD

**Issue by HelmiTrabelsi** [hyperledger/caliper#809]
I followed this tutoriel  but when I run the benshmark  on Fabric 2.0 I get this error: 
[caliper] [cli-launch-master] 	Unexpected error during benchmark execution: ValidationError: child "version" fails because ["version" must be one of [1.0]]. "client" is not allowed

**Comment by aklenik** [comment]
@HelmiTrabelsi The schema of your network configuration file is incorrect. See this doc page for the valid attributes and their values: https://hyperledger.github.io/caliper/v0.3/fabric-config/#network-configuration-file-reference

**Comment by nklincoln** [comment]
further to the above, the Fabric docs state that "Currently only version 1.0 is supported, and it is not envisioned that this schema will change frequently."

https://hyperledger-fabric.readthedocs.io/en/release-2.0/developapps/connectionprofile.html
