### ISSUE TITLE
Error with with installing hyperledger caliber: problem reading the PEM file

### ISSUE THREAD

**Issue by mohamedbaza** [hyperledger/caliper#816]
I am installing hyperledger caliber using the local NPM found at https://hyperledger.github.io/caliper/v0.3/installing-caliper/. Once I invoke the local CLI binary (step 4) using the command,

>omar@Baza:~/caliper-benchmarks$ npx caliper launch master \
>     --caliper-workspace . \
>     --caliper-benchconfig benchmarks/scenario/simple/config.yaml \
>     --caliper-networkconfig networks/fabric/fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml

I got the following log error:

2020.04.23-17:22:54.452 info  [caliper] [cli-launch-master] 	Set workspace path: /home/omar/caliper-benchmarks
2020.04.23-17:22:54.453 info  [caliper] [cli-launch-master] 	Set benchmark configuration path: /home/omar/caliper-benchmarks/benchmarks/scenario/simple/config.yaml
2020.04.23-17:22:54.453 info  [caliper] [cli-launch-master] 	Set network configuration path: /home/omar/caliper-benchmarks/networks/fabric/fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml
2020.04.23-17:22:54.453 info  [caliper] [cli-launch-master] 	Set SUT type: fabric
2020.04.23-17:22:54.456 info  [caliper] [benchmark-validator] 	No observer specified, will default to `none`
2020.04.23-17:22:54.456 info  [caliper] [caliper-engine] 	Starting benchmark flow
2020.04.23-17:22:54.460 info  [caliper] [adapters/fabric] 	Initializing standard adaptor compatible with installed SDK: 1.4.0
2020.04.23-17:22:54.871 info  [caliper] [caliper-utils] 	Executing command: cd .; export FABRIC_VERSION=1.4.1;export FABRIC_CA_VERSION=1.4.1;docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb/docker-compose.yaml up -d;sleep 3s
Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
2020.04.23-17:22:58.195 info  [caliper] [caliper-engine] 	Executed start command in 3.324 seconds
2020.04.23-17:22:58.197 info  [caliper] [adapters/fabric] 	Fabric SDK version: 1.4.0; TLS: none
2020-04-23T22:22:58.211Z - error: [NetworkConfig101.js]: NetworkConfig101 - problem reading the PEM file :: Error: ENOENT: no such file or directory, open '/home/omar/caliper-benchmarks/networks/fabric/config_solo/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/key.pem'
2020.04.23-17:22:58.212 error [caliper] [caliper-engine] 	Error while performing "init" step: Error: ENOENT: no such file or directory, open '/home/omar/caliper-benchmarks/networks/fabric/config_solo/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/key.pem'
2020.04.23-17:22:58.212 info  [caliper] [caliper-engine] 	Executed "init" step in 0.016 seconds
2020.04.23-17:22:58.212 info  [caliper] [caliper-utils] 	Executing command: cd .; docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb/docker-compose.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*
The FABRIC_VERSION variable is not set. Defaulting to a blank string.
The FABRIC_CA_VERSION variable is not set. Defaulting to a blank string.
Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/json?all=1: dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/json?all=1: dial unix /var/run/docker.sock: connect: permission denied
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/json?filters=%7B%22reference%22%3A%7B%22dev%2A%22%3Atrue%7D%7D: dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/json?filters=%7B%22reference%22%3A%7B%22dev%2A%22%3Atrue%7D%7D: dial unix /var/run/docker.sock: connect: permission denied
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
2020.04.23-17:22:58.764 info  [caliper] [caliper-engine] 	Executed end command in 0.552 seconds
2020.04.23-17:22:58.765 error [caliper] [cli-launch-master] 	Benchmark failed with error code 4
Usage:
 caliper launch master --caliper-bind-sut fabric:1.4.1 [other options]

Options:
  --help, -h           Show usage information  [boolean]
  --version            Show version information  [boolean]
  --caliper-bind-sut   The name and version of the platform to bind to  [string]
  --caliper-bind-cwd   The working directory for performing the SDK install  [string]
  --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
  --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]

Error: Benchmark failed with error code 4
    at Function.handler (/home/omar/caliper-benchmarks/node_modules/@hyperledger/caliper-cli/lib/launch/lib/launchMaster.js:70:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Luciferjason** [comment]
I have the same pem problem with you. 

2020.04.24-15:24:19.250 info  [caliper] [cli-launch-master] 	Set workspace path: /root/go/src/github.com/hyperledger/caliper/caliper-benchmarks
2020.04.24-15:24:19.253 info  [caliper] [cli-launch-master] 	Set benchmark configuration path: /root/go/src/github.com/hyperledger/caliper/caliper-benchmarks/benchmarks/scenario/simple/config.yaml
2020.04.24-15:24:19.253 info  [caliper] [cli-launch-master] 	Set network configuration path: /root/go/src/github.com/hyperledger/caliper/caliper-benchmarks/networks/fabric/fabric-v1.4.1/2org1peergoleveldb/fabric-go-tls.yaml
2020.04.24-15:24:19.253 info  [caliper] [cli-launch-master] 	Set SUT type: fabric
2020.04.24-15:24:19.270 info  [caliper] [benchmark-validator] 	No observer specified, will default to `none`
2020.04.24-15:24:19.276 info  [caliper] [caliper-engine] 	Starting benchmark flow
2020.04.24-15:24:20.562 info  [caliper] [adapters/fabric] 	Initializing standard adaptor compatible with installed SDK: 1.4.8
2020.04.24-15:24:20.981 info  [caliper] [caliper-utils] 	Executing command: cd caliper-benchmarks; export FABRIC_VERSION=1.4.1;export FABRIC_CA_VERSION=1.4.1;docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb/docker-compose-tls.yaml up -d;sleep 3s
Creating network "2org1peergoleveldb_default" with the default driver
Creating ca.org1.example.com    ... done
Creating orderer.example.com ... done
Creating ca.org2.example.com ... done
Creating peer0.org1.example.com ... done
Creating peer0.org2.example.com ... done
2020.04.24-15:24:31.463 info  [caliper] [caliper-engine] 	Executed start command in 10.483 seconds
2020.04.24-15:24:31.464 info  [caliper] [adapters/fabric] 	Fabric SDK version: 1.4.8; TLS: server
2020-04-24T07:24:31.492Z - error: [NetworkConfig101.js]: NetworkConfig101 - problem reading the PEM file :: Error: ENOENT: no such file or directory, open '/root/go/src/github.com/hyperledger/caliper/caliper-benchmarks/networks/fabric/config_solo/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem'
2020.04.24-15:24:31.494 error [caliper] [caliper-engine] 	Error while performing "init" step: Error: ENOENT: no such file or directory, open '/root/go/src/github.com/hyperledger/caliper/caliper-benchmarks/networks/fabric/config_solo/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem'
2020.04.24-15:24:31.495 info  [caliper] [caliper-engine] 	Executed "init" step in 0.031 seconds
2020.04.24-15:24:31.495 info  [caliper] [caliper-utils] 	Executing command: cd caliper-benchmarks; docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb/docker-compose-tls.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*
The FABRIC_CA_VERSION variable is not set. Defaulting to a blank string.
The FABRIC_VERSION variable is not set. Defaulting to a blank string.
Removing peer0.org2.example.com ... done
Removing peer0.org1.example.com ... done
Removing ca.org1.example.com    ... done
Removing ca.org2.example.com    ... done
Removing orderer.example.com    ... done
Removing network 2org1peergoleveldb_default
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
2020.04.24-15:24:33.217 info  [caliper] [caliper-engine] 	Executed end command in 1.721 seconds
2020.04.24-15:24:33.217 error [caliper] [cli-launch-master] 	Benchmark failed with error code 4
Usage:
 caliper launch master --caliper-bind-sut fabric:1.4.1 [other options]

Options:
  --help, -h           Show usage information  [布尔]
  --version            Show version information  [布尔]
  --caliper-bind-sut   The name and version of the platform to bind to  [字符串]
  --caliper-bind-cwd   The working directory for performing the SDK install  [字符串]
  --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [字符串]
  --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [字符串]

**Comment by chinmay241** [comment]
From: https://github.com/hyperledger/caliper-benchmarks/blob/master/README.md#running-a-benchmark
Ensure that the crypto configuration files have been generated. Do this by navigating to the relevant /networks/fabric/config_x directory and running the command: 
_The x in the case is solo_
`./generate.sh`

But after which the Crypto file generation might fail, But some possible solution in this issue here https://github.com/hyperledger/caliper-benchmarks/issues/40

**Comment by mohamedbaza** [comment]
I run the command ./generate.sh as follows but I getting the following error. Did I make something wrong?

omar@Baza:~/caliper-benchmarks$ cd networks/fabric/config_solo
omar@Baza:~/caliper-benchmarks/networks/fabric/config_solo$ ./generate.sh

Pull Hyperledger Fabric binaries

===> Downloading version x86_64–1.0.0 platform specific fabric binaries
===> Downloading: https://github.com/hyperledger/fabric/releases/download/v1.0.0/hyperledger-fabric-linux-amd64-1.0.0.tar.gz
 % Total % Received % Xferd Average Speed Time Time Time Current
 Dload Upload Total Spent Left Speed
100 9 100 9 0 0 29 0 — : — : — — : — : — — : — : — 29

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
==> There was an error downloading the binary file.

— — → x86_64–1.0.0 platform specific fabric binary is not available to download ← —

./generate.sh: line 13: ./bin/cryptogen: No such file or directory
./generate.sh: line 14: ./bin/configtxgen: No such file or directory
./generate.sh: line 15: ./bin/configtxgen: No such file or directory
find: ‘crypto-config’: No such file or directory
