### ISSUE TITLE
While Instantiation, invoking chaincode error: [Orderer.js]: sendBroadcast - on error: "Error: 14 UNAVAILABLE: failed to connect to all addresses\n at Object.exports.createStatusError 

### ISSUE THREAD

**Issue by ManjuVenkatachalam** [hyperledger/caliper#822]
I have setup hyperledger fabric v1.4.2 with 1 org 2 peer 1 orderer running natively in three different VMs. In that I am trying to implement caliper v0.3.0.
I am facing this issue while instantiating and invoking the chaincode.
error: [Orderer.js]: sendBroadcast - on error: "Error: 14 UNAVAILABLE: failed to connect to all addresses\n at Object.exports.createStatusError (/home/loan/caliper-benchmarks/node_modules/grpc/src/common.js:91:15)\n at ClientDuplexStream._emitStatusIfDone (/home/loan/caliper-benchmarks/node_modules/grpc/src/client.js:233:26)\n at ClientDuplexStream._receiveStatus (/home/loan/caliper-benchmarks/node_modules/grpc/src/client.js:211:8)\n at Object.onReceiveStatus (/home/loan/caliper-benchmarks/node_modules/grpc/src/client_interceptors.js:1306:15)\n at InterceptingListener._callNext (/home/loan/caliper-benchmarks/node_modules/grpc/src/client_interceptors.js:568:42)\n at InterceptingListener.onReceiveStatus (/home/loan/caliper-benchmarks/node_modules/grpc/src/client_interceptors.js:618:8)\n at /home/loan/caliper-benchmarks/node_modules/grpc/src/client_interceptors.js:1123:18"
2020.04.29-12:22:12.094 error [caliper] [caliper-engine] Error while performing "install" step: Error: Orderer error for instantiating WarehouseCreatepool1CC@v0 in composerchannelrest: SERVICE_UNAVAILABLE
2020.04.29-12:22:12.094 info [caliper] [caliper-engine] Executed "install" step in 0.473 seconds
2020.04.29-12:22:12.094 info [caliper] [caliper-engine] Skipping end command due to benchmark flow conditioning
2020.04.29-12:22:12.094 error [caliper] [cli-launch-master] Benchmark failed with error code 5

Any one can you please suggest how to resolve this?

**Comment by nklincoln** [comment]
That's an error being reported by the fabric sdk, indicating that the peer addresses are incorrect, or something is blocking/preventing connection.

I would start by looking at the network configuration file (which is essentially a common connection profile). The Fabric docs might be able to assist further with distributed networks. 

Alternatively, you may find it easier to manually install/instantiate the chaincode, and use the fabric-gateway mode of operation that permits discovery

**Comment by ManjuVenkatachalam** [comment]
[Azure_fabric-go.txt](https://github.com/hyperledger/caliper/files/4552358/Azure_fabric-go.txt)

**Comment by aklenik** [comment]
@ManjuVenkatachalam 
1. I would double-check whether networking is set up correctly between the nodes. For example, the right ports are open in the VMs (like 7050 for the ordered VM).
2. I would check whether the network correctly starts up before using Caliper. For example, the Fabric node logs indicate successful communication between the nodes.
3. Your network configuration file seems to be correct. The `SERVICE_UNAVAILABLE` error usually means a networking problem, or explicit rejection by the target service (in which case check the Fabric side logs).

**Comment by csquan** [comment]
I have face this same problem .
It is not network problem,I have checkout fabric network and it is right,eg:port ,images.
so ,how solve it?

**Comment by aklenik** [comment]
@csquan `UNAVAILABLE` errors can mean multiple types of connection errors: wrong endpoint set, service is not ready to serve requests yet, etc. We'll need more info about your deployment (where are the nodes, how does the network look like, etc).

**Comment by ManjuVenkatachalam** [comment]
Hi @csquan,
 In the network config file, in orderer section, i have added the maximum send msg length in grpc options,
"grpc-max-send-message-length: -1"

Now its working.

**Comment by csquan** [comment]
Hi,
I had try edit net config as you said,after edit my net config is:


orderers:
&nbsp; orderer.example.com:
&nbsp;&nbsp;&nbsp; url: grpcs://localhost:7050
&nbsp;&nbsp;&nbsp; # these are standard properties defined by the gRPC library
&nbsp;&nbsp;&nbsp; # they will be passed in as-is to gRPC client constructor
&nbsp;&nbsp;&nbsp; grpcOptions:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ssl-target-name-override: orderer.example.com
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; grpc-max-send-message-length: -1
&nbsp;&nbsp;&nbsp; tlsCACerts:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; path: artifacts/channel/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt


but it still not work,errors:


2020-07-29 08:39:13.999] [ERROR] Create-Channel - Error: SERVICE_UNAVAILABLE
&nbsp;&nbsp;&nbsp; at ClientDuplexStream.<anonymous&gt; (/home/csquan/work/fabric-samples/balance-transfer/node_modules/fabric-client/lib/Orderer.js:185:21)
&nbsp;&nbsp;&nbsp; at ClientDuplexStream.emit (events.js:315:20)
&nbsp;&nbsp;&nbsp; at ClientDuplexStream._emitStatusIfDone (/home/csquan/work/fabric-samples/balance-transfer/node_modules/grpc/src/client.js:234:12)
&nbsp;&nbsp;&nbsp; at ClientDuplexStream._receiveStatus (/home/csquan/work/fabric-samples/balance-transfer/node_modules/grpc/src/client.js:211:8)
&nbsp;&nbsp;&nbsp; at Object.onReceiveStatus (/home/csquan/work/fabric-samples/balance-transfer/node_modules/grpc/src/client_interceptors.js:1311:15)
&nbsp;&nbsp;&nbsp; at InterceptingListener._callNext (/home/csquan/work/fabric-samples/balance-transfer/node_modules/grpc/src/client_interceptors.js:568:42)
&nbsp;&nbsp;&nbsp; at InterceptingListener.onReceiveStatus (/home/csquan/work/fabric-samples/balance-transfer/node_modules/grpc/src/client_interceptors.js:618:8)









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hyperledger/caliper"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月28日(星期二) 晚上8:10
收件人:&nbsp;"hyperledger/caliper"<caliper@noreply.github.com&gt;;
抄送:&nbsp;"mars"<314588595@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [hyperledger/caliper] While Instantiation, invoking chaincode error: [Orderer.js]: sendBroadcast - on error: "Error: 14 UNAVAILABLE: failed to connect to all addresses\n at Object.exports.createStatusError  (#822)





 
Hi @csquan,
 In the network config file, in orderer section, i have added the maximum send msg length in grpc options,
 "grpc-max-send-message-length: -1"
 
Now its working.

**Comment by csquan** [comment]
Hi,
I had follow&nbsp;fabric-samples/balance-transfer,just run run*.sh to start network and test*.sh to run test,
then test errors when create channel:


2020-07-29 08:39:13.999] [ERROR] Create-Channel - Error: SERVICE_UNAVAILABLE
&nbsp;&nbsp;&nbsp; at ClientDuplexStream.<anonymous&gt; (/home/csquan/work/fabric-samples/balance-transfer/node_modules/fabric-client/lib/Orderer.js:185:21)
&nbsp;&nbsp;&nbsp; at ClientDuplexStream.emit (events.js:315:20)
&nbsp;&nbsp;&nbsp; at ClientDuplexStream._emitStatusIfDone (/home/csquan/work/fabric-samples/balance-transfer/node_modules/grpc/src/client.js:234:12)
&nbsp;&nbsp;&nbsp; at ClientDuplexStream._receiveStatus (/home/csquan/work/fabric-samples/balance-transfer/node_modules/grpc/src/client.js:211:8)
&nbsp;&nbsp;&nbsp; at Object.onReceiveStatus (/home/csquan/work/fabric-samples/balance-transfer/node_modules/grpc/src/client_interceptors.js:1311:15)
&nbsp;&nbsp;&nbsp; at InterceptingListener._callNext (/home/csquan/work/fabric-samples/balance-transfer/node_modules/grpc/src/client_interceptors.js:568:42)
&nbsp;&nbsp;&nbsp; at InterceptingListener.onReceiveStatus (/home/csquan/work/fabric-samples/balance-transfer/node_modules/grpc/src/client_interceptors.js:618:8)







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hyperledger/caliper"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月28日(星期二) 晚上7:58
收件人:&nbsp;"hyperledger/caliper"<caliper@noreply.github.com&gt;;
抄送:&nbsp;"mars"<314588595@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [hyperledger/caliper] While Instantiation, invoking chaincode error: [Orderer.js]: sendBroadcast - on error: "Error: 14 UNAVAILABLE: failed to connect to all addresses\n at Object.exports.createStatusError  (#822)





 
@csquan UNAVAILABLE errors can mean multiple types of connection errors: wrong endpoint set, service is not ready to serve requests yet, etc. We'll need more info about your deployment (where are the nodes, how does the network look like, etc).

**Comment by csquan** [comment]
Hi,
&nbsp;I had solve it but not modify net config.
&nbsp;first,make sure node version is 8.15.0 which I found some said in google.
I had install node version&nbsp;Node.js v8.4.0 or higher as&nbsp;https://github.com/hyperledger/fabric-samples/tree/v1.4.1/balance-transfer said ,but it does not work ,and errors was confuse me a lot.fabric official does not test it well .
secondly,instaintaly cc in testApp.sh at first time always failed.Try it again in manually will success.
last,modify 3000 to 6000 in app/invoke*.js where eventHub timeout set.
or it always failed when invoke.
so fabric samples confuse me a lot.
does people in IBM not test well?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hyperledger/caliper"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月28日(星期二) 晚上8:10
收件人:&nbsp;"hyperledger/caliper"<caliper@noreply.github.com&gt;;
抄送:&nbsp;"mars"<314588595@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [hyperledger/caliper] While Instantiation, invoking chaincode error: [Orderer.js]: sendBroadcast - on error: "Error: 14 UNAVAILABLE: failed to connect to all addresses\n at Object.exports.createStatusError  (#822)





 
Hi @csquan,
 In the network config file, in orderer section, i have added the maximum send msg length in grpc options,
 "grpc-max-send-message-length: -1"
 
Now its working.

**Comment by csquan** [comment]
Hi,
&nbsp;I had solve it but not modify net config.
&nbsp;first,make sure node version is 8.15.0 which I found some said in google.
I had install node version&nbsp;Node.js v8.4.0 or higher as&nbsp;https://github.com/hyperledger/fabric-samples/tree/v1.4.1/balance-transfer said ,but it does not work ,and errors was confuse me a lot.fabric official does not test it well .
secondly,instaintaly cc in testApp.sh at first time always failed.Try it again in manually will success.
last,modify 3000 to 6000 in app/invoke*.js where eventHub timeout set.
or it always failed when invoke.
so fabric samples confuse me a lot.
does people in IBM not test well?







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hyperledger/caliper"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月28日(星期二) 晚上7:58
收件人:&nbsp;"hyperledger/caliper"<caliper@noreply.github.com&gt;;
抄送:&nbsp;"mars"<314588595@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [hyperledger/caliper] While Instantiation, invoking chaincode error: [Orderer.js]: sendBroadcast - on error: "Error: 14 UNAVAILABLE: failed to connect to all addresses\n at Object.exports.createStatusError  (#822)





 
@csquan UNAVAILABLE errors can mean multiple types of connection errors: wrong endpoint set, service is not ready to serve requests yet, etc. We'll need more info about your deployment (where are the nodes, how does the network look like, etc).

**Comment by aklenik** [comment]
@csquan Seems like ran into errors with an example from the `fabric-samples` repo, but we're glad to read you solved your problem. 
(On a side note, Fabric is an enterprise-grade distributed system, which usually means it's not trivial to setup. Which also means it's not trivial to provide simple examples for it. The Caliper team also struggles with providing simple and easy-to-use examples. That's why community feedback is important, because the developers see the project differently than a first-time user.)
