### ISSUE TITLE
life-cycle errors

### ISSUE THREAD

**Issue by Tallminsome** [hyperledger/caliper#824]
## Context

I was using caliper to test my consensus,but some how some transactions always report life-cycle error.Following are the parts of errors:
2020.05.03-12:46:17.007 error [caliper] [adapters/fabric] 	Transaction[fdb2bee38e] life-cycle errors:
	- orderer1.trj.com response error with status NOT_FOUND
2020.05.03-12:46:17.207 error [caliper] [adapters/fabric] 	Transaction[46bf00997d] life-cycle errors:
	- orderer2.trj.com response error with status NOT_FOUND
2020.05.03-12:46:17.406 error [caliper] [adapters/fabric] 	Transaction[4404cfa5ac] life-cycle errors:
	- orderer3.trj.com response error with status NOT_FOUND
2020.05.03-12:46:19.405 error [caliper] [adapters/fabric] 	Transaction[5f450dc94f] life-cycle errors:
	- orderer0.trj.com response error with status NOT_FOUND
2020.05.03-12:46:19.607 error [caliper] [adapters/fabric] 	Transaction[187c26e806] life-cycle errors:
	- orderer1.trj.com response error with status NOT_FOUND
2020.05.03-12:46:19.807 error [caliper] [adapters/fabric] 	Transaction[9ab92674a9] life-cycle errors:
	- orderer2.trj.com response error with status NOT_FOUND
2020.05.03-12:46:20.006 error [caliper] [adapters/fabric] 	Transaction[fcbdbadcc9] life-cycle errors:
	- orderer3.trj.com response error with status NOT_FOUND
2020.05.03-12:46:22.007 error [caliper] [adapters/fabric] 	Transaction[5f35d48ed8] life-cycle errors:
	- orderer0.trj.com response error with status NOT_FOUND
2020.05.03-12:46:22.206 error [caliper] [adapters/fabric] 	Transaction[45a53d73a2] life-cycle errors:
	- orderer1.trj.com response error with status NOT_FOUND
2020.05.03-12:46:22.405 error [caliper] [adapters/fabric] 	Transaction[841ee464ea] life-cycle errors:
	- orderer2.trj.com response error with status NOT_FOUND
2020.05.03-12:46:22.608 error [caliper] [adapters/fabric] 	Transaction[f55521d5c9] life-cycle errors:
	- orderer3.trj.com response error with status NOT_FOUND

## Expected Behavior

Run correctly
## Actual Behavior

Still can run, but some transaction failed
## Possible Fix

Maybe it's my consensus that is going wrong. But I checked the docker logs,my orderer peers runs correctly but in the end it can not receive the requests. I was wondering maybe my orderer peers just finished all the requests and there were no more requests.

## Your Environment
Ubuntu 16.0.4
fabric 1.4.4
caliper 0.3
go 1.14.2

**Comment by nklincoln** [comment]
Hi @Tallminsome, to clarify: 
- Some transactions work
- Some transactions fail
- Those that fail have errors emanating from fabric-sdk code, or within peers themselves?

**Comment by Tallminsome** [comment]
@nklincoln Thanks, actually I don't know exactly what question it is.Cuz I successfully tested my project after I tried couple of times.

**Comment by nklincoln** [comment]
OK, based on the above, I will close this issue - thanks for getting back to us 👌
