### ISSUE TITLE
Caliper work with hurley

### ISSUE THREAD

**Issue by levanthanh3005** [hyperledger/caliper#833]
Hello,
I am using hurley:
https://github.com/worldsibu/hurley
And convector:
https://github.com/hyperledger-labs/convector
After solving the problem of version in #812
To build a test network with a smart contract, my fabric config is here:
[fabric.yaml.zip](https://github.com/hyperledger/caliper/files/4603576/fabric.yaml.zip)

I have an error with the default channel of hurley: ch1

2020.05.09-13:04:58.187 info  [caliper] [adapters/fabric] 	Channel 'ch1' is configured as created, skipping creation
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: access denied: channel [] creator org [org1MSP]
    at new createStatusError (/hyperledger/caliper/node_modules/grpc/src/client.js:64:15)
    at /hyperledger/caliper/node_modules/grpc/src/client.js:583:15
error: [Client.js]: Failed Channels Query. Error: Error: 2 UNKNOWN: access denied: channel [] creator org [org1MSP]
    at new createStatusError (/hyperledger/caliper/node_modules/grpc/src/client.js:64:15)
    at /hyperledger/caliper/node_modules/grpc/src/client.js:583:15
2020.05.09-13:04:58.215 error [caliper] [adapters/fabric] 	The following errors occurred while querying ch1 information from org1MSP's peers:
	- Couldn't query ch1 information from peer0.org1.hurley.lab: 2 UNKNOWN: access denied: channel [] creator org [org1MSP]
2020.05.09-13:04:58.215 error [caliper] [caliper-flow] 	Error: Error: Couldn't query ch1 information from org1MSP's peers
    at Fabric._joinChannels (/hyperledger/caliper/node_modules/@hyperledger/caliper-fabric/lib/fabric.js:1495:27)
    at <anonymous>

**Comment by nklincoln** [comment]
Never used the convector/Hurley framework, it may require a new adaptor. If it "just" creates a standard Fabric network, then it would appear that the wrong certificates are being used and so access is rightfully being denied. As mentioned, Hurley itself is an unknown framework to us, so we cannot advise which certificates that it creates you should be providing - best suggestion would be to inspect the fabric container logs to help guide you on the errors, and iterate over what is available to you as provided by Hurley

**Comment by davidkel** [comment]
I believe Hurley and Convector are end of life. Hurley is used to stand up a fabric network (like so many other tools, eg minifabric) it should be possible to configure a network config to work with that fabric network.

**Comment by davidkel** [comment]
Closing as no further action necessary
