### ISSUE TITLE
Orderer object passed within invokeSettings: must reference target orderer by name

### ISSUE THREAD

**Issue by gzuhlwang** [hyperledger/caliper#834]
## Context

With a fabric 2.0.0 network up, channel created, chaincode worked well, it can be invoked with cli.
Now my intention is using caliper v0.3.0 benchmarking the network. 

related run callback code:
```
module.exports.run = async function() {
    txIndex++;
    let newAcc = generateAccount();
    let args = {
        chaincodeFunction: 'set',
        chaincodeArguments: [newAcc, '100']
    };

    return bc.invokeSmartContract(contx, targetCC, '1.0', args, 120);
};
```
even I added the orderer filed, same error will be thrown.

```
module.exports.run = async function() {
    txIndex++;
    let newAcc = generateAccount();
    let args = {
        chaincodeFunction: 'set',
        chaincodeArguments: [newAcc, '100'],
        orderer: 'orderer.example.com'
    };

    return bc.invokeSmartContract(contx, targetCC, '1.0', args, 120);
};

```

## Expected Behavior

generating tx load.
## Actual Behavior

caliper thrown the following err info.
```
2020.05.11-16:42:16.099 info  [caliper] [caliper-local-client.js] 	txUpdateTime: 5000
2020.05.11-16:42:16.099 info  [caliper] [caliper-local-client.js] 	Info: client 2 start test runDuration():Invoking set sacc.
2020.05.11-16:42:16.099 info  [caliper] [caliper-local-client.js] 	txUpdateTime: 5000
2020.05.11-16:42:16.099 info  [caliper] [caliper-local-client.js] 	Info: client 1 start test runDuration():Invoking set sacc.
2020.05.11-16:42:16.100 info  [caliper] [caliper-local-client.js] 	Info: client 3 start test runDuration():Invoking set sacc.
2020.05.11-16:42:16.100 info  [caliper] [caliper-local-client.js] 	Info: client 4 start test runDuration():Invoking set sacc.
2020.05.11-16:42:16.117 error [caliper] [adapters/fabric] 	Transaction[913c287394] unexpected error: Error: Orderer object passed within invokeSettings: must reference target orderer by name
    at Fabric._submitSingleTransaction (/root/benchmarkfabric2.0/fabric-samples/first-network/caliper-benchmarks/node_modules/@hyperledger/caliper-fabric/lib/adaptor-versions/v2/fabric-v2.js:1812:23)
2020.05.11-16:42:16.120 error [caliper] [adapters/fabric] 	Transaction[feec2ad499] unexpected error: Error: Orderer object passed within invokeSettings: must reference target orderer by name
    at Fabric._submitSingleTransaction (/root/benchmarkfabric2.0/fabric-samples/first-network/caliper-benchmarks/node_modules/@hyperledger/caliper-fabric/lib/adaptor-versions/v2/fabric-v2.js:1812:23)
2020.05.11-16:42:16.120 error [caliper] [adapters/fabric] 	Transaction[c2bf28ad2a] unexpected error: Error: Orderer object passed within invokeSettings: must reference target orderer by name
```
## Existing issues

Not found

## Your Environment

* caliper version used:0.3.0
* node version:v10.20.1
* nom version: 6.14.4

if need more, I will detail more. Please help me out. many thanks.
@nklincoln

**Comment by nklincoln** [comment]
Hi @gzuhlwang - did the transaction complete successfully before you added the orderer name to the payload?

**Comment by gzuhlwang** [comment]
@nklincoln  thanks your replies. probably no. I checked orderer log. no block generated.

**Comment by gzuhlwang** [comment]
at the end of day, caliper prints the following logs.
```
2020.05.11-18:39:54.620 info  [caliper] [message-handler] 	Handled "test" message for worker 0
2020.05.11-18:39:54.620 info  [caliper] [message-handler] 	Handled "test" message for worker 3
2020.05.11-18:39:54.621 info  [caliper] [message-handler] 	Handled "test" message for worker 2
2020.05.11-18:39:54.623 info  [caliper] [message-handler] 	Handled "test" message for worker 1
2020.05.11-18:39:54.624 info  [caliper] [message-handler] 	Handled "test" message for worker 4
2020.05.11-18:39:54.627 info  [caliper] [report-builder] 	### Test result ###
2020.05.11-18:39:54.639 info  [caliper] [report-builder]
+------+------+------+-----------------+-----------------+-----------------+-----------------+------------------+
| Name | Succ | Fail | Send Rate (TPS) | Max Latency (s) | Min Latency (s) | Avg Latency (s) | Throughput (TPS) |
|------|------|------|-----------------|-----------------|-----------------|-----------------|------------------|
| set  | 0    | 75   | 5.4             | 0.00            | 100000.00       | NaN             | 0.0              |
+------+------+------+-----------------+-----------------+-----------------+-----------------+------------------+

2020.05.11-18:39:54.645 info  [caliper] [round-orchestrator] 	Finished round 1 (set) in 14.996 seconds
2020.05.11-18:39:54.645 info  [caliper] [report-builder] 	### All test results ###
2020.05.11-18:39:54.647 info  [caliper] [report-builder]
+------+------+------+-----------------+-----------------+-----------------+-----------------+------------------+
| Name | Succ | Fail | Send Rate (TPS) | Max Latency (s) | Min Latency (s) | Avg Latency (s) | Throughput (TPS) |
|------|------|------|-----------------|-----------------|-----------------|-----------------|------------------|
| set  | 0    | 75   | 5.4             | 0.00            | 100000.00       | NaN             | 0.0              |
+------+------+------+-----------------+-----------------+-----------------+-----------------+------------------+

2020.05.11-18:39:54.664 info  [caliper] [caliper-flow] 	Generated report with path /root/benchmarkfabric2.0/fabric-samples/first-network/caliper-benchmarks/report.html
2020.05.11-18:39:54.766 info  [caliper] [message-handler] 	Handling "exit" message
2020.05.11-18:39:54.767 info  [caliper] [message-handler] 	Handling "exit" message
2020.05.11-18:39:54.767 info  [caliper] [message-handler] 	Handling "exit" message
2020.05.11-18:39:54.767 info  [caliper] [message-handler] 	Handled "exit" message for worker 0
2020.05.11-18:39:54.767 info  [caliper] [round-orchestrator] 	Benchmark finished in 26.437 seconds. Total rounds: 1. Successful rounds: 1. Failed rounds: 0.
2020.05.11-18:39:54.768 info  [caliper] [caliper-engine] 	Skipping end command due to benchmark flow conditioning
2020.05.11-18:39:54.768 info  [caliper] [cli-launch-master] 	Benchmark successfully finished

```

**Comment by gzuhlwang** [comment]
correction. added orderer, the logs are different.

`2020.05.11-18:48:08.844 error [caliper] [message-handler] 	Handled unsuccessful "prepare" message for worker 0 and test round 0 with error SyntaxError: Unexpected identifier
2020.05.11-18:48:08.844 error [caliper] [message-handler] 	Handled unsuccessful "prepare" message for worker 1 and test round 0 with error SyntaxError: Unexpected identifier
2020.05.11-18:48:08.844 info  [caliper] [message-handler] 	Handling "prepare" message
2020.05.11-18:48:08.845 error [caliper] [round-orchestrator] 	Failed round 1 (set): Error: SyntaxError: Unexpected identifier
    at WorkerOrchestrator.updateWorkerPhase (/root/benchmarkfabric2.0/fabric-samples/first-network/caliper-benchmarks/node_modules/@hyperledger/caliper-core/lib/master/orchestrators/worker-orchestrator.js:211:61)
    at WorkerOrchestrator.processWorkerUpdate (/root/benchmarkfabric2.0/fabric-samples/first-network/caliper-benchmarks/node_modules/@hyperledger/caliper-core/lib/master/orchestrators/worker-orchestrator.js:124:18)
    at ChildProcess.<anonymous> (/root/benchmarkfabric2.0/fabric-samples/first-network/caliper-benchmarks/node_modules/@hyperledger/caliper-core/lib/common/messaging/process-master.js:51:30)
    at ChildProcess.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2020.05.11-18:48:08.846 error [caliper] [message-handler] 	Handled unsuccessful "prepare" message for worker 3 and test round 0 with error SyntaxError: Unexpected identifier
2020.05.11-18:48:08.846 info  [caliper] [report-builder] 	### All test results ###
2020.05.11-18:48:08.846 error [caliper] [message-handler] 	Handled unsuccessful "prepare" message for worker 2 and test round 0 with error SyntaxError: Unexpected identifier
2020.05.11-18:48:08.846 error [caliper] [message-handler] 	Handled unsuccessful "prepare" message for worker 4 and test round 0 with error SyntaxError: Unexpected identifier
2020.05.11-18:48:08.846 error [caliper] [round-orchestrator] 	Error while finalizing the report: Error: Table must define at least one row.`

**Comment by nklincoln** [comment]
> at the end of day, caliper prints the following logs.
> 
> ```
> 2020.05.11-18:39:54.620 info  [caliper] [message-handler] 	Handled "test" message for worker 0
> 2020.05.11-18:39:54.620 info  [caliper] [message-handler] 	Handled "test" message for worker 3
> 2020.05.11-18:39:54.621 info  [caliper] [message-handler] 	Handled "test" message for worker 2
> 2020.05.11-18:39:54.623 info  [caliper] [message-handler] 	Handled "test" message for worker 1
> 2020.05.11-18:39:54.624 info  [caliper] [message-handler] 	Handled "test" message for worker 4
> 2020.05.11-18:39:54.627 info  [caliper] [report-builder] 	### Test result ###
> 2020.05.11-18:39:54.639 info  [caliper] [report-builder]
> +------+------+------+-----------------+-----------------+-----------------+-----------------+------------------+
> | Name | Succ | Fail | Send Rate (TPS) | Max Latency (s) | Min Latency (s) | Avg Latency (s) | Throughput (TPS) |
> |------|------|------|-----------------|-----------------|-----------------|-----------------|------------------|
> | set  | 0    | 75   | 5.4             | 0.00            | 100000.00       | NaN             | 0.0              |
> +------+------+------+-----------------+-----------------+-----------------+-----------------+------------------+
> 
> 2020.05.11-18:39:54.645 info  [caliper] [round-orchestrator] 	Finished round 1 (set) in 14.996 seconds
> 2020.05.11-18:39:54.645 info  [caliper] [report-builder] 	### All test results ###
> 2020.05.11-18:39:54.647 info  [caliper] [report-builder]
> +------+------+------+-----------------+-----------------+-----------------+-----------------+------------------+
> | Name | Succ | Fail | Send Rate (TPS) | Max Latency (s) | Min Latency (s) | Avg Latency (s) | Throughput (TPS) |
> |------|------|------|-----------------|-----------------|-----------------|-----------------|------------------|
> | set  | 0    | 75   | 5.4             | 0.00            | 100000.00       | NaN             | 0.0              |
> +------+------+------+-----------------+-----------------+-----------------+-----------------+------------------+
> 
> 2020.05.11-18:39:54.664 info  [caliper] [caliper-flow] 	Generated report with path /root/benchmarkfabric2.0/fabric-samples/first-network/caliper-benchmarks/report.html
> 2020.05.11-18:39:54.766 info  [caliper] [message-handler] 	Handling "exit" message
> 2020.05.11-18:39:54.767 info  [caliper] [message-handler] 	Handling "exit" message
> 2020.05.11-18:39:54.767 info  [caliper] [message-handler] 	Handling "exit" message
> 2020.05.11-18:39:54.767 info  [caliper] [message-handler] 	Handled "exit" message for worker 0
> 2020.05.11-18:39:54.767 info  [caliper] [round-orchestrator] 	Benchmark finished in 26.437 seconds. Total rounds: 1. Successful rounds: 1. Failed rounds: 0.
> 2020.05.11-18:39:54.768 info  [caliper] [caliper-engine] 	Skipping end command due to benchmark flow conditioning
> 2020.05.11-18:39:54.768 info  [caliper] [cli-launch-master] 	Benchmark successfully finished
> ```

So in that one, all transactions are failing, - do you have any logs for that instance, since it would be nice to investigate that aspect before moving onto a target orderer.

Also, what command are you using to run the benchmark?

**Comment by gzuhlwang** [comment]
@nklincoln this is the cmd used. 

` npx caliper launch master --caliper-benchconfig benchmarks/samples/fabric/sacc/config.yaml  --caliper-networkconfig networks/fabric-go-tls.yaml --caliper-workspace /root/benchmarkfabric2.0/fabric-samples/first-network/caliper-benchmarks/ --caliper-flow-only-test`

**Comment by gzuhlwang** [comment]
the code  thrown the err info。

https://github.com/hyperledger/caliper/blob/fa2fb054a2343b9114774e4fb387a374dbc14e89/packages/caliper-fabric/lib/adaptor-versions/v2/fabric-v2.js#L1812

**Comment by gzuhlwang** [comment]
@nklincoln  I add binding setting --caliper-bind-sut fabric:1.4.3. now caliper works.
