### ISSUE TITLE
Not enough arguments following: caliper-bind-args

### ISSUE THREAD

**Issue by nageshcaparthy** [hyperledger/caliper#837]
I am trying to understand the caliper tool for first time and have been having issues in setting it up and running it. 

I have the following versions installed:

I am trying multiple options to run the bind command, however, it all ends up with an error. 

caliper bind --caliper-bind-sut fabric:1.4.4 --caliper-bind-cwd ./ --caliper-bind-args="-g"
Usage:
  caliper bind --caliper-bind-sut fabric:1.4.1 --caliper-bind-cwd ./ --caliper-bind-args="-g"

Options:
  --help, -h           Show usage information  [boolean]
  --version            Show version information  [boolean]
  --caliper-bind-sut   The name and version of the platform and its SDK to bind to  [string]
  --caliper-bind-cwd   The working directory for performing the SDK install  [string]
  --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
  --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]

Not enough arguments following: caliper-bind-args

## Steps to Reproduce

1.
2.
3.
4.

## Existing issues
Similar issue, reported here but no possible fix for the error. 

https://github.com/hyperledger/caliper/issues/768

## Context
I am trying to use caliper for my project and this is impacting my overall planning due to the delay in understanding the framework with fabric. Once the local setup is working, I would like to demonstrate it to my company and understand the pro- and cons- to use with our cloud offering.  

## Your EnvironmentVS Code: 1.39.2
Node: v10.20.1
npm: 6.14.4
IBM Blockchain Platform: v1.0.28
Go: 0.14.0
Ubuntu 16.4

Regards,
Nagesh

**Comment by nageshcaparthy** [comment]
I have also run, npm uninstall yargs -g to check the yargs conflict but that has not helped.

**Comment by nklincoln** [comment]
Can you confirm the version that you are using of Caliper please?

The fix for the above went in on 16th March, which means the fix is only available in the following releases of caliper:
- 0.3.1
- unstable

**Comment by nageshcaparthy** [comment]
I am using caliper 0.3.0. Let me try to upgrade it to 0.3.1 and test it again.

**Comment by nageshcaparthy** [comment]
@nklincoln Thank you. The binding did work after the upgrade to 0.3.1.
