### ISSUE TITLE
Configuration file page for Benchmark Generator cannot be visited.

### ISSUE THREAD

**Issue by zhangjingwen2008** [hyperledger/caliper#839]
https://hyperledger.github.io/caliper/vNext/benchmark-generator/Architecture#ConfigurationFile
When I clicked the line above only got information like "404 The requested page could not be found. Click here to return to our Getting Started page". 
So where can I find it ?

**Comment by nklincoln** [comment]
that's a broken link - should be directing here: https://hyperledger.github.io/caliper/v0.3/bench-config/

(but versioned)

**Comment by zhangjingwen2008** [comment]
> that's a broken link - should be directing here: https://hyperledger.github.io/caliper/v0.3/bench-config/
> 
> (but versioned)

Thanks~
