### ISSUE TITLE
Caliper will permit the use of gateway with SDKs that do not contain code

### ISSUE THREAD

**Issue by Lynn14m** [hyperledger/caliper#847]
When using the `caliper launch master` command with the `caliper-fabric-gateway-usegateway` option and an SDK version without gateway code, we expect the command to not run and fail straight away as the code path doesn't exist in the SDK.

Instead the command is still able to be run and errors with `Unexpected error during benchmark execution: TypeError: Cannot read property 'MSPID_SCOPE_SINGLE' of undefined`

**Comment by nklincoln** [comment]
The fix for this one is to perform more rigorous checking at the point where the adaptor is selected in fabric.js
