### ISSUE TITLE
Error: Benchmark configuration file path is not set

### ISSUE THREAD

**Issue by dretrtg** [hyperledger/caliper#849]
when execute   :    caliper launch master \
> >     --caliper-workspace ~/caliper-benchmarks \
> >     --caliper-benchconfig benchmarks/scenario/simple/config.yaml \
> >     --caliper-networkconfig networks/fabric/fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml
then wrong as title

**Comment by nklincoln** [comment]
@dretrtg 
Can we have more information please?
- version of caliper used
- platform run on
- actual error returned

**Comment by rabebbenothmen** [comment]
hi, 
i have the same  issue how can i resolve it?

**Comment by timamz** [comment]
am facing the same issue, using caliper 0.3.2 on ubuntu 22.04
has anyone solved it yet?
