### ISSUE TITLE
MaxTPS rate controller

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#870]
There are already quite a few rate controllers, however a missing controller is that which seeks to find the maximum possible TPS that may be driven.

We currently have rate limiting controllers that seek to maintain a stead backlog of transactions such that the SUT is not overwhelmed by the transactions, however it is not necessarily going to tune itself to output the maximum achievable TPS; just the TPS that satisfies the backlog.

During the rate control cycle, we have access to the current TPS as witnessed by the worker. Meaning that is would be possible to step up (ramp) the TPS until the achieved rate drops below the send rate, backoff again and increase with a smaller ramp gradient.

This could in theory enable the maximum TPS to be investigated, since once all sending clients achieve an equilibrium, the workers are at their maximum driving rate.

**Comment by aklenik** [comment]
Yes, a max-rate controller would be useful. However, finding a meaningful metric for the step up/down decisions will be hard.

For example, even if the txs still finish within a given latency threshold (one possible metric), the SUT could still be in an overloaded state (whatever that means). So I'm not sure that the limited information of the workers will be enough. But we can experiment with basic metrics.

(Btw, an unconditional max-rate/no-sleep controller is a perfect combination with a dummy test adapter to profile/stresstest the worker processes)

**Comment by nklincoln** [comment]
closed by above PRs
