### ISSUE TITLE
Two Network Directories for Fabric

### ISSUE THREAD

**Issue by ynamiki** [hyperledger/caliper#88]
There are two directories for Fabric: `network/fabric` and `network/fabric-v11`.

I would like to know intentions of each directory.
`fabric` is for Fabric v1.0 only? (but I can use `fabric/simplenetwork` with Fabric v1.1)

**Comment by haojun** [comment]
The original caliper as well as simplenetwork only support fabric v1.0 at the beginning, and then composer team added a new folder to include files they needed and named as fabric-v11 to distinguish with the old folder. But now caliper have been updated to support fabric v1.1, the names of those two folders may be confusing.

**Comment by ynamiki** [comment]
Thanks, I understand the background.
