### ISSUE TITLE
Error: Benchmark failed with error code 6

### ISSUE THREAD

**Issue by jaideep2709** [hyperledger/caliper#906]
reating ethereum ... done
2020.07.06-02:29:46.188 info  [caliper] [caliper-engine]        Executed start command in 512.417 seconds
2020.07.06-02:29:52.450 info  [caliper] [caliper-engine]        Executed "init" step in 6.105 seconds
2020.07.06-02:29:52.451 info  [caliper] [ethereum.js]   Creating contracts...
2020.07.06-02:34:04.839 info  [caliper] [ethereum.js]   Deployed contract simple at 0x91496eafe3C54C48D1Add5c1Fb30655d6b76e56b
2020.07.06-02:34:04.948 info  [caliper] [caliper-engine]        Executed "install" step in 252.498 seconds
2020.07.06-02:34:05.024 info  [caliper] [messenger.js]  Creating messenger of type "process-master" 
2020.07.06-02:34:05.578 info  [caliper] [null-observer]         Configured "null" observer
2020.07.06-02:34:05.580 error [caliper] [round-orchestrator]    Round 1 configuration validation error: Missing "callback" attribute
2020.07.06-02:34:05.596 error [caliper] [caliper-engine]        Error while performing "test" step: Error: Round 1 configuration validation error: Missing "callback" attribute
2020.07.06-02:34:05.596 info  [caliper] [caliper-utils]         Executing command: cd .; docker-compose -f networks/ethereum/1node/docker-compose.yml down
Stopping ethereum ... done
Removing ethereum ... done
Removing network 1node_default
2020.07.06-02:34:27.670 info  [caliper] [caliper-engine]        Executed end command in 22.074 seconds
2020.07.06-02:34:27.671 error [caliper] [cli-launch-master]     Benchmark failed with error code 6
Usage:
 caliper launch master --caliper-bind-sut fabric:1.4.1 [other options]

Options:
  --help, -h           Show usage information  [boolean]
  --version            Show version information  [boolean]
  --caliper-bind-sut   The name and version of the platform to bind to  [string]
  --caliper-bind-cwd   The working directory for performing the SDK install  [string]
  --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
  --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]

Error: Benchmark failed with error code 6
    at Function.handler (/home/gaganq/Documents/caliperPractice/caliper-benchmarks/node_modules/@hyperledger/caliper-cli/lib/launch/lib/launchMaster.js:70:23)
## Your Environment

* Version used:
Environment name and version (e.g. Chrome 39, node.js 5.4):npm 5.6.0 node js 8.10.0 docker 19.03.8 docker compose 1.25.5
Operating System and version (desktop or mobile): ubuntu 18.04
* Link to your project:

**Comment by nklincoln** [comment]
The error trace include:
`Error while performing "test" step: Error: Round 1 configuration validation error: Missing "callback" attribute`

**Comment by nklincoln** [comment]
This would appear to be a configuration error and not an error within Caliper - feel free to reach out on the community Rocket Chat for assistance in configuration matters https://chat.hyperledger.org/channel/caliper
