### ISSUE TITLE
Caliper throws error for fabric 1.4.1

### ISSUE THREAD

**Issue by mamunbond07** [hyperledger/caliper#915]
## Context

Dear good people, I tried to benchmark with fabric 1.4.1 with following link: https://hyperledger.github.io/caliper/v0.3.2/installing-caliper/#pre-requisites. I issued the following command:
>npm init -y
>npm install --only=prod \
    @hyperledger/caliper-cli@0.3.2
>npx caliper bind \
    --caliper-bind-sut fabric:1.4.1

>sudo npx caliper launch master \
   --caliper-bind-sut fabric:1.4.1 \
    --caliper-workspace . \
    --caliper-benchconfig benchmarks/scenario/simple/config.yaml \
    --caliper-networkconfig networks/fabric/v1/v1.4.1/2org1peergoleveldb/fabric-go.yaml

## Output
2020.07.07-15:00:31.284 info  [caliper] [cli-launch-master] 	Binding specification is present, performing binding for "fabric:1.4.1"
2020.07.07-15:00:31.291 warn  [caliper] [bind] 	Working directory not specified. Using "/home/bc/caliper/caliper-benchmarks"
2020.07.07-15:00:31.291 info  [caliper] [bind] 	Binding for fabric@1.4.1. This might take some time...
2020.07.07-15:00:31.291 info  [caliper] [bind] 	Using working directory: /home/bc/caliper/caliper-benchmarks
2020.07.07-15:00:31.292 info  [caliper] [bind] 	Calling npm with: install grpc@1.14.2 fabric-ca-client@1.4.1 fabric-client@1.4.1 fabric-protos@2.0.0-snapshot.1 fabric-network@1.4.1
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

> grpc@1.14.2 install /home/bc/caliper/caliper-benchmarks/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download 
[grpc] Success: "/home/bc/caliper/caliper-benchmarks/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" is installed via remote
npm WARN notsup Unsupported engine for fabric-protos@2.0.0-snapshot.1: wanted: {"node":"^8.9.0","npm":"^5.5.1"} (current: {"node":"10.21.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: fabric-protos@2.0.0-snapshot.1
npm WARN notsup Unsupported engine for fabric-ca-client@1.4.1: wanted: {"node":"^8.9.0","npm":"^5.5.1"} (current: {"node":"10.21.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: fabric-ca-client@1.4.1
npm WARN notsup Unsupported engine for fabric-client@1.4.1: wanted: {"node":"^8.9.0","npm":"^5.5.1"} (current: {"node":"10.21.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: fabric-client@1.4.1

+ grpc@1.14.2
+ fabric-protos@2.0.0-snapshot.1
+ fabric-network@1.4.1
+ fabric-ca-client@1.4.1
+ fabric-client@1.4.1
updated 5 packages and audited 730 packages in 29.052s

5 packages are looking for funding
  run `npm fund` for details

found 37 vulnerabilities (33 low, 2 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
2020.07.07-15:01:01.700 info  [caliper] [cli-launch-master] 	Set workspace path: /home/bc/caliper/caliper-benchmarks
2020.07.07-15:01:01.700 info  [caliper] [cli-launch-master] 	Set benchmark configuration path: /home/bc/caliper/caliper-benchmarks/benchmarks/scenario/simple/config.yaml
2020.07.07-15:01:01.701 info  [caliper] [cli-launch-master] 	Set network configuration path: /home/bc/caliper/caliper-benchmarks/networks/fabric/v1/v1.4.1/2org1peergoleveldb/fabric-go.yaml
2020.07.07-15:01:01.701 info  [caliper] [cli-launch-master] 	Set SUT type: fabric:1.4.1
2020.07.07-15:01:01.709 info  [caliper] [benchmark-validator] 	No observer specified, will default to `none`
2020.07.07-15:01:01.710 info  [caliper] [caliper-engine] 	Starting benchmark flow
2020.07.07-15:01:02.750 info  [caliper] [adapters/fabric] 	Initializing standard adaptor compatible with installed SDK: 1.4.1
2020.07.07-15:01:03.742 info  [caliper] [caliper-utils] 	Executing command: cd .; export FABRIC_VERSION=1.4.1;export FABRIC_CA_VERSION=1.4.1;docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb/docker-compoCreating orderer.example.com ... done
Creating network "2org1peergoleveldb_default" with the default driver
Creating peer0.org2.example.com ... done
Creating ca.org1.example.com ... 
Creating orderer.example.com ... 
Creating peer0.org2.example.com ... 
Creating peer0.org1.example.com ... 
2020.07.07-15:01:14.876 info  [caliper] [caliper-engine] 	Executed start command in 11.135 seconds
2020.07.07-15:01:14.877 info  [caliper] [adapters/fabric] 	Fabric SDK version: 1.4.1; TLS: none
2020.07.07-15:01:16.020 info  [caliper] [adapters/fabric] 	Org1's registrar enrolled successfully
2020.07.07-15:01:16.346 info  [caliper] [adapters/fabric] 	Org2's registrar enrolled successfully
2020.07.07-15:01:16.433 info  [caliper] [adapters/fabric] 	Org1's admin's materials are successfully loaded
2020.07.07-15:01:16.466 info  [caliper] [adapters/fabric] 	Org2's admin's materials are successfully loaded
2020.07.07-15:01:16.490 info  [caliper] [adapters/fabric] 	client0.org1.example.com's materials are successfully loaded
2020.07.07-15:01:16.531 info  [caliper] [adapters/fabric] 	client0.org2.example.com's materials are successfully loaded
2020.07.07-15:01:16.533 info  [caliper] [adapters/fabric] 	Channel 'mychannel' definiton being retrieved from file
2020.07.07-15:01:16.536 error [caliper] [caliper-engine] 	Error while performing "init" step: Error: Couldn't read configuration binary for mychannel: EISDIR: illegal operation on a directory, read
2020.07.07-15:01:16.540 info  [caliper] [caliper-engine] 	Executed "init" step in 1.664 seconds
2020.07.07-15:01:16.541 info  [caliper] [caliper-utils] 	Executing command: cd .; docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb/docker-compose.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*
The FABRIC_VERSION variable is not set. Defaulting to a blank string.
The FABRIC_CA_VERSION variable is not set. Defaulting to a blank string.
Stopping peer0.org1.example.com ... done
Stopping peer0.org2.example.com ... done
Stopping orderer.example.com    ... done
Stopping ca.org1.example.com    ... done
Stopping ca.org2.example.com    ... done
Removing peer0.org1.example.com ... done
Removing peer0.org2.example.com ... done
Removing orderer.example.com    ... done
Removing ca.org1.example.com    ... done
Removing ca.org2.example.com    ... done
Removing network 2org1peergoleveldb_default
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
2020.07.07-15:01:29.290 info  [caliper] [caliper-engine] 	Executed end command in 12.749 seconds
2020.07.07-15:01:29.291 error [caliper] [cli-launch-master] 	Benchmark failed with error code 4
Usage:
 caliper launch master --caliper-bind-sut fabric:1.4.1 [other options]

Options:
  --help, -h           Show usage information  [boolean]
  --version            Show version information  [boolean]
  --caliper-bind-sut   The name and version of the platform to bind to  [string]
  --caliper-bind-cwd   The working directory for performing the SDK install  [string]
  --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
  --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]

Error: Benchmark failed with error code 4
    at Function.handler (/home/bc/caliper/caliper-benchmarks/node_modules/@hyperledger/caliper-cli/lib/launch/lib/launchMaster.js:70:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)

## My Environment

* Version used: Fabric 1.4.1, Caliper 0.3.2
* Environment name and version: NodeJS 10.21.0, npm 6.14.4
* Operating System and version (desktop): Ubuntu 16.04

Please kindly help me to resolve this.

**Comment by nklincoln** [comment]
Looks like there are a few errors there:

`Unsupported engine for fabric-ca-client@1.4.1: wanted: {"node":"^8.9.0","npm":"^5.5.1"} (current: {"node":"10.21.0","npm":"6.14.4"})` you are attempting to bind to packages that explicitly do not support the version of node you have installed

I would start with the above, as it probably causes a cascade of issues

**Comment by nklincoln** [comment]
closing due to solution being provided and no response from author
