### ISSUE TITLE
Caliper throws error for Sawtooth.json config

### ISSUE THREAD

**Issue by mamunbond07** [hyperledger/caliper#918]
## Context

Dear good people, I am trying to benchmark with sawtooth and issued the following command and getting error.
>sudo npx caliper launch master \
    --caliper-bind-sut sawtooth:1.0.0 \
    --caliper-workspace . \
    --caliper-benchconfig benchmarks/scenario/smallbank/config.yaml \
    --caliper-networkconfig networks/sawtooth/smallbank/sawtooth.json

##Output
```
2020.07.07-21:49:31.929 info  [caliper] [cli-launch-master] 	Binding specification is present, performing binding for "sawtooth:1.0.0"
2020.07.07-21:49:31.938 warn  [caliper] [bind] 	Working directory not specified. Using "/home/bc/caliper/caliper-benchmarks"
2020.07.07-21:49:31.939 info  [caliper] [bind] 	Binding for sawtooth@1.0.0. This might take some time...
2020.07.07-21:49:31.939 info  [caliper] [bind] 	Using working directory: /home/bc/caliper/caliper-benchmarks
2020.07.07-21:49:31.939 info  [caliper] [bind] 	Calling npm with: install sawtooth-sdk@1.0.0
+ sawtooth-sdk@1.0.0
updated 1 package and audited 851 packages in 12.323s

5 packages are looking for funding
  run `npm fund` for details

found 40 vulnerabilities (36 low, 2 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
2020.07.07-21:49:46.173 info  [caliper] [cli-launch-master] 	Set workspace path: /home/bc/caliper/caliper-benchmarks
2020.07.07-21:49:46.174 info  [caliper] [cli-launch-master] 	Set benchmark configuration path: /home/bc/caliper/caliper-benchmarks/benchmarks/scenario/smallbank/config.yaml
2020.07.07-21:49:46.174 info  [caliper] [cli-launch-master] 	Set network configuration path: /home/bc/caliper/caliper-benchmarks/networks/sawtooth/smallbank/sawtooth.json
2020.07.07-21:49:46.174 info  [caliper] [cli-launch-master] 	Set SUT type: sawtooth:1.0.0
2020.07.07-21:49:46.616 info  [caliper] [benchmark-validator] 	No observer specified, will default to `none`
Creating sawtooth-validator-default ... done
2020.07.07-21:49:46.617 info  [caliper] [caliper-utils] 	Executing command: cd .; docker-compose -f networks/sawtooth/smallbank/sawtooth-smallbank-go.yaml up -d
Creating network "smallbank_default" with the default driver
Creating sawtooth-settings-tp-default ... done
Creating sawtooth-rest-api-default ... 
Creating sawtooth-smallbank-tp-go-default ... 
Creating sawtooth-settings-tp-default ... 
2020.07.07-21:49:55.829 info  [caliper] [caliper-engine] 	Executed start command in 9.212 seconds
2020.07.07-21:49:55.830 info  [caliper] [caliper-engine] 	Executed "init" step in 0 seconds
2020.07.07-21:49:55.837 info  [caliper] [caliper-engine] 	Executed "install" step in 0 seconds
2020.07.07-21:49:55.838 info  [caliper] [messenger.js] 	Creating messenger of type "process-master" 
2020.07.07-21:49:55.854 info  [caliper] [null-observer] 	Configured "null" observer
2020.07.07-21:49:55.868 error [caliper] [round-orchestrator] 	Round 1 configuration validation error: Missing "callback" attribute
2020.07.07-21:49:55.879 error [caliper] [caliper-engine] 	Error while performing "test" step: Error: Round 1 configuration validation error: Missing "callback" attribute
2020.07.07-21:49:55.883 info  [caliper] [caliper-utils] 	Executing command: cd .; docker-compose -f networks/sawtooth/smallbank/sawtooth-smallbank-go.yaml down;(test -z "$(docker ps -aq)") || docker rm $(docker ps -aq)
Stopping sawtooth-settings-tp-default     ... done
Stopping sawtooth-smallbank-tp-go-default ... done
Stopping sawtooth-rest-api-default        ... done
Stopping sawtooth-validator-default       ... done
Removing sawtooth-settings-tp-default     ... done
Removing sawtooth-smallbank-tp-go-default ... done
Removing sawtooth-rest-api-default        ... done
Removing sawtooth-validator-default       ... done
Removing network smallbank_default
2020.07.07-21:50:19.469 info  [caliper] [caliper-engine] 	Executed end command in 23.585 seconds
2020.07.07-21:50:19.469 error [caliper] [cli-launch-master] 	Benchmark failed with error code 6
Usage:
 caliper launch master --caliper-bind-sut fabric:1.4.1 [other options]

Options:
  --help, -h           Show usage information  [boolean]
  --version            Show version information  [boolean]
  --caliper-bind-sut   The name and version of the platform to bind to  [string]
  --caliper-bind-cwd   The working directory for performing the SDK install  [string]
  --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
  --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]

Error: Benchmark failed with error code 6
    at Function.handler (/home/bc/caliper/caliper-benchmarks/node_modules/@hyperledger/caliper-cli/lib/launch/lib/launchMaster.js:70:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## My Environment

* Version used: Caliper 0.3.2, Sawtooth 1.0.0
* Environment name and version: NodeJS 10.21.0, npm 6.14.4
* Operating System and version (desktop): Ubuntu 16.04

Please kindly help me to resolve this.

**Comment by aklenik** [comment]
@mamunbond07 Please see this issue for the answer: 
https://github.com/hyperledger/caliper-benchmarks/issues/95

**Comment by mamunbond07** [comment]
Thanks a lot for your response. However, I now change the version of caliper to 0.4.0-unstable-20200707113434 and I used NPM to install caliper. Though the code is running , but I am getting the following error:

## Output
2020.07.08-09:13:23.238 error [caliper] [sawtooth-connector] 	invokeSmartContract failed, Error: Unable to load batch builder for smallbank[1.0] at src/sawtooth/scenario/smallbank/SmallBankBatchBuilder.js::Cannot find module 'caliper-core'

## Previous related issue
I saw a previous issue might be related to my problem: https://github.com/hyperledger/caliper/issues/524

## Expected behavior:
As I used **NPM** to install caliper, and as the NPM by-default should have installed all the dependencies in **node_modules** folder in my working directory, I should not get this. Am I right?

## My script
For your reference, I include here the script I have used:
>npm init -y
npm install --only=prod \
     @hyperledger/caliper-cli@0.4.0-unstable-20200707113434

>sudo npx caliper launch master \
    --caliper-bind-sut sawtooth:1.0.0 \
    --caliper-workspace . \
    --caliper-benchconfig benchmarks/scenario/smallbank/config.yaml \
    --caliper-networkconfig networks/sawtooth/smallbank/sawtooth.json

Please kindly help me to resolve this.

**Comment by aklenik** [comment]
Please use the stable versions of caliper and the bench repo, as the unstable version and the bench master haven't been synchronized yet. If the issue still persists, please open an issue on the bench repo and we'll look into it

**Comment by mamunbond07** [comment]
Thanks again. I rolled-back to the caliper: 0.3.2 again and the problem that I have mentioned at the beginning of the thread occurs again. 

## My script:
>npm init -y
npm install --only=prod \
     @hyperledger/caliper-cli@0.3.2

>sudo npx caliper launch master \
    --caliper-bind-sut sawtooth:1.0.0 \
    --caliper-workspace . \
    --caliper-benchconfig benchmarks/scenario/smallbank/config.yaml \
    --caliper-networkconfig networks/sawtooth/smallbank/sawtooth.json

**Comment by mamunbond07** [comment]
Hi,
After I go back to the stable version caliper 0.3.2, the problem still persists. I opened a new issue: https://github.com/hyperledger/caliper-benchmarks/issues/101.
Please kindly help me on this.
