### ISSUE TITLE
fisco-bcos problem when using caliper 

### ISSUE THREAD

**Issue by Xubin-source** [hyperledger/caliper#935]
Typererror:secp256.sign is not a function
![图片](https://user-images.githubusercontent.com/56347756/88473856-2436e000-cf54-11ea-9b83-293499d45c81.png)

**Comment by nklincoln** [comment]
@vita-dounai, are you aware of any changes that might have caused this?

**Comment by nklincoln** [comment]
closed by #936 - turns out a dependancy of a dependancy had breaking changes 😞

**Comment by aklenik** [comment]
@nklincoln Maybe we should commit `package-lock.json`, as suggested by npm 😅
