### ISSUE TITLE
meet wrong when run blockchain-explorer

### ISSUE THREAD

**Issue by csquan** [hyperledger/caliper#941]
HI,
I have follow link:https://github.com/hyperledger/blockchain-explorer,
before run docker-compose up -d,I had done all what web said should do,
but run  docker-compose up meet some wrongs:
explorer.mynetwork.com      | [2020-07-31T06:19:41.546] [INFO] FabricConfig - config.client.tlsEnable  true
explorer.mynetwork.com      | [2020-07-31T06:19:41.547] [INFO] FabricConfig - FabricConfig, this.config.channels  mychannel
explorer.mynetwork.com      | [2020-07-31T06:19:41.574] [INFO] FabricGateway - enrollUserIdentity: userName : exploreradmin
explorer.mynetwork.com      | 2020-07-31T06:19:45.013Z - error: [ServiceEndpoint]: Error: Failed to connect before the deadline on Endorser- name: peer0.org1.example.com, url:grpcs://localhost:7051, connected:false, connectAttempted:true
explorer.mynetwork.com      | 2020-07-31T06:19:45.015Z - error: [ServiceEndpoint]: waitForReady - Failed to connect to remote gRPC server peer0.org1.example.com url:grpcs://localhost:7051 timeout:3000
explorer.mynetwork.com      | 2020-07-31T06:19:45.017Z - error: [NetworkConfig]: buildPeer - Unable to connect to the endorser peer0.org1.example.com due to Error: Failed to connect before the deadline on Endorser- name: peer0.org1.example.com, url:grpcs://localhost:7051, connected:false, connectAttempted:true
explorer.mynetwork.com      | [2020-07-31T06:19:45.029] [ERROR] FabricGateway - Error: Endorser must be connected
explorer.mynetwork.com      | [2020-07-31T06:19:45.034] [ERROR] FabricClient - { ExplorerError: [ 'Failed to create wallet, please check the configuration, and valid file paths' ]
explorer.mynetwork.com      |     at FabricGateway.initialize (/opt/explorer/app/platform/fabric/gateway/FabricGateway.js:135:10)
explorer.mynetwork.com      |     at process._tickCallback (internal/process/next_tick.js:68:7)
explorer.mynetwork.com      |   name: 'ExplorerError',
explorer.mynetwork.com      |   message:
explorer.mynetwork.com      |    '[ \'Failed to create wallet, please check the configuration, and valid file paths\' ]' }
explorer.mynetwork.com      | [2020-07-31T06:19:45.036] [ERROR] main - <<<<<<<<<<<<<<<<<<<<<<<<<< Explorer Error >>>>>>>>>>>>>>>>>>>>>
explorer.mynetwork.com      | [2020-07-31T06:19:45.037] [ERROR] main - Error :  [ 'Invalid platform configuration, Please check the log' ]
,any help should be appreciate.

**Comment by aklenik** [comment]
This is not a Caliper-related problem, please raise the issue in the related repository.

**Comment by csquan** [comment]
can you tell me where to raise problem. 
in explorer repository,there is no place to issue.

**Comment by csquan** [comment]
errors show:Failed to connect before the deadline on Endorser- name: peer0.org1.example.com, url:grpcs://localhost:7051, connected:false, connectAttempted:true.
is the common problem run fabric and I do not know where to put this issue.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hyperledger/caliper"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 下午2:32
收件人:&nbsp;"hyperledger/caliper"<caliper@noreply.github.com&gt;;
抄送:&nbsp;"mars"<314588595@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hyperledger/caliper] meet wrong when run blockchain-explorer (#941)





 
This is not a Caliper-related problem, please raise the issue in the related repository.

**Comment by aklenik** [comment]
@csquan This is the JIRA page for Blockchain Explorer, where they manage issues: https://jira.hyperledger.org/projects/BE/issues/BE-694?filter=allopenissues

**Comment by armughanahmed** [comment]
@csquan did you find solution for this? i am currently facing the same issue.
