### ISSUE TITLE
invalid block 18: unknown ancestor

### ISSUE THREAD

**Issue by LuffySmile** [hyperledger/caliper#942]
INFO [08-03|08:50:51.121] Maximum peer count                       ETH=50 LES=0 total=50
INFO [08-03|08:50:51.122] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [08-03|08:50:51.122] Set global gas cap                       cap=25000000
INFO [08-03|08:50:51.122] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=16.00MiB handles=16
INFO [08-03|08:50:51.130] Writing custom genesis block 
INFO [08-03|08:50:51.130] Persisted trie from memory database      nodes=1 size=171.00B time="37.649µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [08-03|08:50:51.130] Successfully wrote genesis state         database=chaindata                      hash="cbc198…847427"
INFO [08-03|08:50:51.131] Allocated cache and file handles         database=/root/.ethereum/geth/lightchaindata cache=16.00MiB handles=16
INFO [08-03|08:50:51.137] Writing custom genesis block 
INFO [08-03|08:50:51.138] Persisted trie from memory database      nodes=1 size=171.00B time="29.478µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [08-03|08:50:51.138] Successfully wrote genesis state         database=lightchaindata                      hash="cbc198…847427"
INFO [08-03|08:50:51.174] Maximum peer count                       ETH=50 LES=0 total=50
INFO [08-03|08:50:51.174] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [08-03|08:50:51.174] Set global gas cap                       cap=25000000
INFO [08-03|08:50:51.174] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=512.00MiB handles=524288
INFO [08-03|08:50:51.213] Opened ancient database                  database=/root/.ethereum/geth/chaindata/ancient
INFO [08-03|08:50:51.214] Disk storage enabled for ethash caches   dir=/root/.ethereum/geth/ethash count=3
INFO [08-03|08:50:51.214] Disk storage enabled for ethash DAGs     dir=/root/.ethash               count=2
INFO [08-03|08:50:51.214] Loaded most recent local header          number=0 hash="cbc198…847427" td=524288 age=1y3mo4d
INFO [08-03|08:50:51.214] Loaded most recent local full block      number=0 hash="cbc198…847427" td=524288 age=1y3mo4d
INFO [08-03|08:50:51.214] Loaded most recent local fast block      number=0 hash="cbc198…847427" td=524288 age=1y3mo4d
INFO [08-03|08:50:51.214] Importing blockchain                     file=/root/Eth_test/bc.dat
ERROR[08-03|08:50:51.215] 
BAD BLOCK 
Chain config: {ChainID: 21194 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: <nil>, YOLO v1: <nil>, Engine: ethash}

Number: 1
Hash: 0x0f34a5d81e4a0c7a8cd84b5a96ed026086cad450b51eb425cdc0cde28e087b7d

Error: unknown ancestor
ERROR[08-03|08:50:51.215] Import error                             err="invalid block 18: unknown ancestor"
INFO [08-03|08:50:51.215] Blockchain stopped 

Import done in 1.223544ms.

Compactions
 Level |   Tables   |    Size(MB)   |    Time(sec)  |    Read(MB)   |   Write(MB)
-------+------------+---------------+---------------+---------------+---------------
   0   |          1 |       0.00077 |       0.00000 |       0.00000 |       0.00000
-------+------------+---------------+---------------+---------------+---------------
 Total |          1 |       0.00077 |       0.00000 |       0.00000 |       0.00000

Read(MB):0.00247 Write(MB):0.00098
Object memory: 130.066 MB current, 129.947 MB peak
System memory: 334.836 MB current, 334.836 MB peak
Allocations:   0.018 million
GC pause:      227.828µs

Compacting entire database...
Compaction done in 57.14436ms.

Compactions
 Level |   Tables   |    Size(MB)   |    Time(sec)  |    Read(MB)   |   Write(MB)
-------+------------+---------------+---------------+---------------+---------------
   1   |          1 |       0.00077 |       0.01339 |       0.00077 |       0.00077
-------+------------+---------------+---------------+---------------+---------------
 Total |          1 |       0.00077 |       0.01339 |       0.00077 |       0.00077

Read(MB):0.00247 Write(MB):0.00189
invalid block 18: unknown ancestor
Service 'node' failed to build: The command '/bin/sh -c geth --nousb init /root/Eth_test/genesis.json && geth --nousb import /root/Eth_test/bc.dat && geth --nousb makedag 0 /root/Eth_test/.ethash && geth --nousb makedag 30000 /root/Eth_test/.ethash' returned a non-zero code: 1
2020.08.03-16:50:51.626 error [caliper] [caliper-utils] 	Unsuccessful command execution. Error code: 1. Terminating signal: null
2020.08.03-16:50:51.627 error [caliper] [caliper-engine] 	An error occurred while executing the start command: Error: Command failed: cd .; docker-compose -f networks/ethereum/1node/docker-compose.yml up -d && sleep 3
Creating network "1node_default" with the default driver
Building node
Service 'node' failed to build: The command '/bin/sh -c geth --nousb init /root/Eth_test/genesis.json && geth --nousb import /root/Eth_test/bc.dat && geth --nousb makedag 0 /root/Eth_test/.ethash && geth --nousb makedag 30000 /root/Eth_test/.ethash' returned a non-zero code: 1

2020.08.03-16:50:51.627 info  [caliper] [caliper-engine] 	Executed start command in 1.654 seconds
2020.08.03-16:50:51.627 info  [caliper] [caliper-utils] 	Executing command: cd .; docker-compose -f networks/ethereum/1node/docker-compose.yml down
Removing network 1node_default
2020.08.03-16:50:52.145 info  [caliper] [caliper-engine] 	Executed end command in 0.518 seconds
2020.08.03-16:50:52.146 error [caliper] [cli-launch-master] 	Benchmark failed with error code 3

## My Environment
* Version used:caliper 0.3.2；ethereum latest
* nodejs 8.10； docker  19.03.6；docker-compose  1.17.1
* Operating System and version (desktop or mobile): Ubuntu Server 18.04

**Comment by chenqping** [comment]
I've met the same issue, any progress with this?

**Comment by 47759476** [comment]
I met the same problem, is there any solution

**Comment by aklenik** [comment]
This is probably an issue with the example network, so I transferred a related issue to the benchmark repo, which you can follow here: https://github.com/hyperledger/caliper-benchmarks/issues/119
I'm closing this one.
