### ISSUE TITLE
error [caliper] [cli-launch-master]

### ISSUE THREAD

**Issue by casm3** [hyperledger/caliper#947]
Unexpected error during benchmark execution: Error: Invalid "mychannel" channel configuration: child "chaincodes" fails because ["chaincodes" is required]. "contracts" is not allowed

## Context

When I try to start the Benchmark by running

npx caliper launch master     --caliper-bind-sut fabric:1.4.1     --caliper-workspace .     --caliper-benchconfig benchmarks/scenario/simple/config.yaml     --caliper-networkconfig networks/fabric/v1/v1.4.1/2org1peergoleveldb/fabric-go.yaml

## Your Environment

* Version used:
 0.3.1/0.3.0
* Environment name and version (e.g. Chrome 39, node.js 5.4):
Nodejs 10.19, NPM 6.14
* Operating System and version (desktop or mobile): 
Ubuntu 20.04
* Link to your project:

**Comment by aklenik** [comment]
@casm3 The `contracts` terminology is introduced by the upcoming v0.4.0 release, please checkout the v0.3.2 tag of the repository to match the Caliper version you're using. If the issue still persists, let us know.
