### ISSUE TITLE
Don't assume relative paths in config-files

### ISSUE THREAD

**Issue by RobertDiebels** [hyperledger/caliper#95]
The fabric blockchain configuration file expects "relative-to-project-root" paths for certificates. Users should be able to pass absolute paths.

`path.join(__dirname, '../..', somepathvalue)`

I encountered this when creating a Docker container out of caliper.I mounted my configuration files into a different directory and was faced with a file not found exception even though I provided an absolute path to the files.

**Comment by panyu4** [comment]
Since PR #133 had resolved this issue, I'm closing it.
