### ISSUE TITLE
Error while performing "install"

### ISSUE THREAD

**Issue by mszychiewicz** [hyperledger/caliper#955]
## Context

Hi
I tried to run a benchmark with command specified under the "Installing and Running Caliper" but it fails on chaincode install,(https://hyperledger.github.io/caliper/v0.3.2/installing-caliper/)
I've run both for 0.3.2 and 0.4 Caliper versions and Go and Node chaincode.
First I thought it was caused by wrong GOPATH or GOROOT but I've checked it was set up correctly.
Then I checked if the 'shim' and 'peer' modules were present in the go directory and downloaded them but the error was still there.
Is the error referring to not being able to find go packages locally or on peer containers?
Should I provide them myself? How is it done? 
As for the node error I confirmed that npm is present locally.
Any help would be much appreciated. Thanks!

Commands:
npx caliper launch master \
                                              --caliper-workspace . \
                                              ---caliper-benchconfig benchmarks/samples/fabric/marbles/config.yaml \
                                              --caliper-networkconfig networks/fabric/v1/v1.4.1/2org1peergoleveldb/fabric-go.yaml

npx caliper launch master \
                                              --caliper-workspace . \
                                              --caliper-benchconfig benchmarks/samples/fabric/marbles/config.yaml \
                                              --caliper-networkconfig networks/fabric/v1/v1.4.1/2org1peergoleveldb/fabric-node.yaml
## Output

GO error:
Error while performing "install" step: Error: Invalid endorsement for marbles@v0 in mychannel from peer0.org1.example.com: error starting container: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 
"/chaincode/input/src/fabric/samples/marbles/go/marbles.go:110:2: cannot find package 
"github.com/hyperledger/fabric/core/chaincode/shim" in any of:
	/usr/local/go/src/github.com/hyperledger/fabric/core/chaincode/shim (from $GOROOT)
	/chaincode/input/src/github.com/hyperledger/fabric/core/chaincode/shim (from $GOPATH)
	/go/src/github.com/hyperledger/fabric/core/chaincode/shim
/chaincode/input/src/fabric/samples/marbles/go/marbles.go:111:2: cannot find package "github.com/hyperledger/fabric/protos/peer" in any of:
	/usr/local/go/src/github.com/hyperledger/fabric/protos/peer (from $GOROOT)
	/chaincode/input/src/github.com/hyperledger/fabric/protos/peer (from $GOPATH)
	/go/src/github.com/hyperledger/fabric/protos/peer"

Node error:
Error while performing "install" step: Error: Invalid endorsement for marbles@v0 in mychannel from peer0.org1.example.com: error starting container: error starting container: Failed to generate platform-specific docker build: Error returned from build: 127 "/bin/sh: npm: not found"
## Your Environment

* Version used: 0.3.2 (0.4-unstable also)
* Environment name and version: node v10.19.0, npm 6.14.4, go 1.13.8 linux/amd64
* Operating System and version: Ubuntu 20.04.1-LTS

**Comment by nklincoln** [comment]
looks like you are not correctly passing in the contract ID within the callback? Which equally could be an issue with the sample benchmarks themselves as there have been many changes in the configuration. First point of call would be to make sure the caliper version you are using matches the tag of the caliper benchmarks repo samples
