### ISSUE TITLE
Installing localy from source fails

### ISSUE THREAD

**Issue by serkixenos** [hyperledger/caliper#958]
Installing localy from source fails when following instructions at https://hyperledger.github.io/caliper/v0.3.2/installing-caliper/

## Context
Following instructions from "Installing locally from source" section, installation fail at npm

## Expected Behavior
Bootstraping executes with no problem

## Actual Behavior
gprc package compilation fails

## Possible Fix
Update the documentation and suggest a list of prerequisistes for successfull bootstrap

## Steps to Reproduce
1. git clone https://github.com/hyperledger/caliper.git
2. cd caliper
3. npm i && npm run repoclean -- --yes && npm run bootstrap

## Context
Trying to experiment with new connectors/adapters

## Your Environment
Ubuntu 18.04
[CaliperIssue.log](https://github.com/hyperledger/caliper/files/5119135/CaliperIssue.log)

**Comment by chenqping** [comment]
I also met this issue when installing from source, please help

**Comment by aklenik** [comment]
@serkixenos Please list the version of `node` you're using. Also please embed the relevant error logs in the issue, so others can also find it easily.

**Comment by serkixenos** [comment]
Node version is v12.18.3, and log is attached to the issue, there is a link to it under Your Environment section

**Comment by nklincoln** [comment]
`gprc package compilation fails` this could be a result of grpc not playing nicely with the version of node you have?

**Comment by serkixenos** [comment]
OK, can you let me know what is your environment where installation from source works? Can you send me the output of:
```
sudo dpkg -l '*' | grep 'ii '
```
This command will list all installed packages with their versions on your computer.

**Comment by nklincoln** [comment]
It fails for me when trying to compile with v12 node too, as a result of no pre-built binaries for grpc ... and then the internal build of grpc failing. Node V10 works (shudder) i suspect this is a result of grpc moving to native modules now and no longer caring about pre built binaries 🤷

**Comment by nklincoln** [comment]
@serkixenos - i managed to build on node v12 by changing the fabric-connector dev dependancies to 1.4.11
