### ISSUE TITLE
Cannot deploy non-sample Composer networks

### ISSUE THREAD

**Issue by ATMarcks** [hyperledger/caliper#96]
Steps to reproduce:

1. I create an empty business network via the Hyperledger Composer playground and name it `my-test-network`. I leave everything default, but I add one participant type to my model. I download the `.bna` file, extract it, and put the resulting files in `caliper/src/contract/composer/my-test-network`
2. I add the following to the caliper `package.json`:

```
    "composer-admin": "0.19.0",
    "composer-client": "0.19.0",
    "composer-common": "0.19.0",
    "fabric-ca-client": "1.1.0",
    "fabric-client": "1.1.0"
```
and run `npm install`.

3. I add a modified test file to `caliper/benchmark/composer/my-test-network/testing.js`
3. Inside of `caliper/benchmark/composer/config-composer.json` I modify `rounds` and update the `label` fields to the name of my network, `my-test-network`. I update the `callback` fields to be `benchmark/composer/my-test-network/testing.js`
4. Inside of `caliper/network/fabric-v11/2-org-1-peer/composer.json` I modify `composer.chaincodes` and change `id` to be `my-test-network`. I leave the version to be `0.1.0`, the same version that is in my network's `package.json`
5. I change my working directory to be `caliper/benchmark/composer` and I run `node main.js`:

```
✓ Creating channels mychannel
✓ Attempting to join peer peer0.org1.example.com to channel mychannel (attempt 1/5)
✓ Attempting to join peer peer0.org2.example.com to channel mychannel (attempt 1/5)
Deploying Composer
✓ Performing Composer runtime install for network my-test-network with card PerfPeerAdmin@Org1
✓ Performing Composer runtime install for network my-test-network with card PerfPeerAdmin@Org2
Starting business network my-test-network. This involves building chaincode containers and may take several minutes to complete...
```
The application gets stuck at this stage until it times out.

```
Starting business network my-test-network. This involves building chaincode containers and may take several minutes to complete...
composer.installSmartContract() failed,  Error: Error trying to start business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 2 UNKNOWN: timeout expired while starting chaincode my-test-network:0.1.0(networkid:dev,peerid:peer0.org1.example.com,tx:cf9a6b55e448683d7e0ce89fd7834b704c2f72a2959bc1bc03552dcb92b84854)
Response from attempted peer comms was an error: Error: 2 UNKNOWN: timeout expired while starting chaincode my-test-network:0.1.0(networkid:dev,peerid:peer0.org2.example.com,tx:cf9a6b55e448683d7e0ce89fd7834b704c2f72a2959bc1bc03552dcb92b84854)
```

The peer logs are not much more enlightening, displays only the same errors. I can test `basic-sample-network` with seemingly no problems.

This could be a problem with composer or my configs, but `composer-cli` seems to have no problem with `composer network install`/`composer network start`

**Comment by haojun** [comment]
@nklincoln It has not been answered for a long time. I'm not sure if it is a problem of composer or configuration? What do we need to do?

**Comment by nklincoln** [comment]
@ATMarcks - can you confirm if you were deploying the network to the 'Composer Dev Servers' successfully, or the Fabric network created by Caliper please

**Comment by ATMarcks** [comment]
@nklincoln IIRC the network failed to deploy on the Fabric instance created by caliper, but would deploy fine on the composer dev servers that I downloaded with composer separately. With that being said I don't have my configs or any of the logs saved any longer, so feel free to close if you cannot repro

**Comment by nklincoln** [comment]
@ATMarcks thanks - iirc the Composer Dev servers have a larger timeout value set within the configuration to permit the time necessary for the node modules to be pulled when building and deploying the chaincode container. If your business network was quite large, it is possible that the timeout was exceeded in this case.

**Comment by houqinghui** [comment]
@ATMarcks  you can modify CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE = 2-org-1-peer_default in the docker-composer.yaml at /network/fabric/2-org-1-peer.  someone has the same problime, he resolve s it.

**Comment by hehui0316** [comment]
how to modify testing.js
