### ISSUE TITLE
Upgrade Caliper to NodeJS v14 (LTS)

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#965]
engines.node is currently set at 10 ... we should bump this to the LTS version of node, which in now v14

Consequences:

This impacts on Fabric SDK binding (only able to bind to latest), consequently we would have to:
- only bind to 1.4 and 2.2 latest (that uses grpc-js)
- provide guidance (or an alternative image?) for those wishing/restricted to lower versions of the SDKs

Alterations:
- All packages
- Travis build
- Caliper image
- Documentation for building own image and/or specifying custom bindings (enhanced binding stage/page)
- Breaking change, version bump required

**Comment by naonishijima** [comment]
Would it be possible to give me an update on this issue? Is there something I can help with?

**Comment by aklenik** [comment]
@naonishijima Feel free to join the caliper-contributors Rocket.Chat channel, where we can discuss the details and steps of the version bump: https://chat.hyperledger.org/channel/caliper-contributors

**Comment by fraVlaca** [comment]
picking up this issue and updating dependencies to run caliper on node 14 LTS (v14.19.0 (npm v6.14.16))

**Comment by fraVlaca** [comment]
- [ ] move as many npm dependencies to the latest versions available.(Fabric dependencies need to stick to 1.4 rather than 2.2) 
- [ ] remove the "^" symbols (because of the colors npm module being sabotaged) and using explicit versions
- [ ] ship package-lock.json files

**Comment by davidkel** [comment]
@naonishijima @aklenik 
Current status
- caliper 0.4.2 can be used with node 14, the only issue is that the fabric 1.4 SUT can't be used
- The caliper repo itself now works with node 14 (although it's not optimised as yet) with a couple more updates to come to complete (ie 2 integration test builds to move to node 14, creation of the docker image to use node14)

**Comment by davidkel** [comment]
I think this issue is now done, there are some follow-ons as described in these issues
#1222 
#1217 
#1125
