### ISSUE TITLE
Unable to run integration tests for newly implemented connector

### ISSUE THREAD

**Issue by serkixenos** [hyperledger/caliper#972]
Unable to run integration tests for newly implemented connector

## Context
We installed caliper from source and bootstrapped the repo. We merged our changes, and now we want to run integration tests. In order to run integration tests, npm wants to install package containing our new connector from npm repo. This package does not exists in npm repo, because it is not released, and it wont be released until we do it properly.
```
2020.08.31-17:55:07.834 info  [caliper] [cli-launch-manager]	Set SUT type: newconnector
2020.08.31-17:55:07.835 error [caliper] [cli-launch-manager]	Unexpected error during benchmark execution: Error: Module "@hyperledger/caliper-newconnector" could not be loaded: Error: Cannot find module '@hyperledger/caliper-newconnector'
Searched paths: ...
```
Package source code is in CALIPER/packages/caliper-newconnector

## Expected Behavior
We are able to run integration tests without publishing unfinished product.

## Actual Behavior
Integration tests fails on installing npm package caliper-newconnector, which contains our 

## Possible Fix
Enable running integration tests from unpublished package source code.

## Steps to Reproduce
Implement very basic new connector and try to run integration tests for it. E.g. you can copy Ethereum connector, rename it, add required changes in config.yaml and caliper-utils.js and try to run integration tests.

## Context
Blocker - we are unable to continue.

## Your Environment
* Ubuntu 20.04
* node v10.19.0, npm v6.14.4
* Caliper - master branch, commit d9f2cc8cf9419d9b7c06c4c91077514d27d3b546

**Comment by aklenik** [comment]
@serkixenos How did you set the connector in your network config file, under `caliper.blockchain`? Setting it to the JS file containing the factory function should work.
