### ISSUE TITLE
Unexpected error during benchmark execution: Error: Invalid "mychannel" channel configuration: child "chaincodes" fails because

### ISSUE THREAD

**Issue by hhp2020** [hyperledger/caliper#978]
Hi,

I was trying to run the caliper-benchmark and just immediately i have this error:

Unexpected error during benchmark execution: Error: Invalid "mychannel" channel configuration: child "chaincodes" fails because ["chaincodes" is required]. "contracts" is not allowed.

the command was:

caliper launch master \

--caliper-workspace ~/caliper-benchmarks \
--caliper-benchconfig benchmarks/samples/fabric/fabcar/config.yaml \
--caliper-networkconfig networks/fabric/v1/v1.4.1/2org1peergoleveldb/fabric-go.yaml
I couldnt find any solution.
The environmnet:
Node 8.15
npm 6.4
go 1.11
Ubuntu 18.04

any suggestions please ?

**Comment by aklenik** [comment]
@hhp2020 Please checkout the 0.3.2 tag of the benchmark repo, which is compatible with Caliper v.0.3.2
