### ISSUE TITLE
Hard-coded MSPID

### ISSUE THREAD

**Issue by RobertDiebels** [hyperledger/caliper#98]
The file [src/fabric/util.js ](https://github.com/hyperledger/caliper/blob/master/src/fabric/util.js#L291)contains a hardcoded MSPID: `OrdererMSP`. Even-though all the files with network options give the illusion the mspid is configurable for an orderer.

It took me over 2 hours to locate this mistake because I thought something was wrong with my own configuration. Please don't ever hard-code something like that again.

**Comment by haojun** [comment]
closed by #126

**Comment by RobertDiebels** [comment]
@aklenik I looked at the fix and I implemented the same one in my fork. I can confirm it works. Excuse the late reply btw. I didn't see a notification for this issue for some reason.
