### ISSUE TITLE
how invokeSmartContract is called on multiple channel.

### ISSUE THREAD

**Issue by Shweta-hlf** [hyperledger/caliper#983]
I am Intergrating Hyperledger Caliper(v0.3.2) with Fabric(1.4.7).How invokeSmartContract is called on multiple channel? I tried to invoke chaincode function on multiple channel,but data added into last channel only.
Kindly help.
--

**Comment by nklincoln** [comment]
if you use the standard fabric connector (non gateway) you disambiguate between contracts on different channels using the unique `contractID` property. Note contractID is unique across channels, but multiple channels may have the same name contract captured in the `id` property

https://hyperledger.github.io/caliper/v0.3.2/fabric-config/#network-configuration-file-reference

**Comment by nklincoln** [comment]
closing as question is answered
