### ISSUE TITLE
Unable to run caliper-benchmark 

### ISSUE THREAD

**Issue by hhp2020** [hyperledger/caliper#986]
Hi,

I was trying to run the caliper-benchmark and just immediately i have this error:

Unexpected error during benchmark execution: Error: Invalid "mychannel" channel configuration: child "chaincodes" fails because ["chaincodes" is required]. "contracts" is not allowed.

the command was:

caliper launch master \

--caliper-workspace ~/caliper-benchmarks \
--caliper-benchconfig benchmarks/samples/fabric/fabcar/config.yaml \
--caliper-networkconfig networks/fabric/v1/v1.4.1/2org1peergoleveldb/fabric-go.yaml
I couldnt find any solution.
The environmnet:
Node 8.15
npm 6.4
go 1.11
Ubuntu 18.04

any suggestions please ?

**Comment by nklincoln** [comment]
looks like you are using mis-matching versions of caliper and configuration files, ensure that the version of caliper you are using matches the tagged repo of caliper-benchmarks
