### ISSUE TITLE
unused dependancies present in packages

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/caliper#999]
Following some refactor there are some unused dependancies through the project. These can be found by running depcheck https://github.com/depcheck/depcheck

The unused dependancies should be removed prior to consideration of a release

**Comment by aklenik** [comment]
That's a cool tool, can we add it to the first CI job? 🥇

**Comment by nklincoln** [comment]
should be possible, though there are some false positives coming from it such as internal links, if we can ignore certain items using a config file, then certainly 👍

**Comment by nklincoln** [comment]
closing due to PR and opening of build issue in #1003
